# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'MechEngHome.ui'
##
## Created by: Qt User Interface Compiler version 6.8.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QGridLayout, QLabel,
    QMainWindow, QMenu, QMenuBar, QPushButton,
    QSizePolicy, QStatusBar, QTabWidget, QToolBox,
    QVBoxLayout, QWidget)

class Ui_MElist(object):
    def setupUi(self, MElist):
        if not MElist.objectName():
            MElist.setObjectName(u"MElist")
        MElist.resize(530, 780)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MElist.sizePolicy().hasHeightForWidth())
        MElist.setSizePolicy(sizePolicy)
        MElist.setMinimumSize(QSize(270, 610))
        MElist.setMaximumSize(QSize(16777215, 16777215))
        font = QFont()
        font.setFamilies([u"Consolas"])
        font.setPointSize(12)
        MElist.setFont(font)
        MElist.setTabShape(QTabWidget.TabShape.Rounded)
        MElist.setDockNestingEnabled(False)
        MElist.setUnifiedTitleAndToolBarOnMac(False)
        self.actionUnit_Converter = QAction(MElist)
        self.actionUnit_Converter.setObjectName(u"actionUnit_Converter")
        self.actionMoments_of_Inertia = QAction(MElist)
        self.actionMoments_of_Inertia.setObjectName(u"actionMoments_of_Inertia")
        self.actionVectors = QAction(MElist)
        self.actionVectors.setObjectName(u"actionVectors")
        self.actionFriction_and_Force = QAction(MElist)
        self.actionFriction_and_Force.setObjectName(u"actionFriction_and_Force")
        self.actionFasteners = QAction(MElist)
        self.actionFasteners.setObjectName(u"actionFasteners")
        self.actionMaterial_Properties = QAction(MElist)
        self.actionMaterial_Properties.setObjectName(u"actionMaterial_Properties")
        self.actionCM_and_CG = QAction(MElist)
        self.actionCM_and_CG.setObjectName(u"actionCM_and_CG")
        self.actionTrusses = QAction(MElist)
        self.actionTrusses.setObjectName(u"actionTrusses")
        self.actionBeamsMoments_of_Inertia = QAction(MElist)
        self.actionBeamsMoments_of_Inertia.setObjectName(u"actionBeamsMoments_of_Inertia")
        self.actionShear_and_Moment = QAction(MElist)
        self.actionShear_and_Moment.setObjectName(u"actionShear_and_Moment")
        self.actionIndeterminate_Axial_Structures = QAction(MElist)
        self.actionIndeterminate_Axial_Structures.setObjectName(u"actionIndeterminate_Axial_Structures")
        self.actionFlexure = QAction(MElist)
        self.actionFlexure.setObjectName(u"actionFlexure")
        self.actionBeam_Deformation = QAction(MElist)
        self.actionBeam_Deformation.setObjectName(u"actionBeam_Deformation")
        self.actionAxial_Beam_Deformation = QAction(MElist)
        self.actionAxial_Beam_Deformation.setObjectName(u"actionAxial_Beam_Deformation")
        self.actionTorsional_Beam_Deformation = QAction(MElist)
        self.actionTorsional_Beam_Deformation.setObjectName(u"actionTorsional_Beam_Deformation")
        self.actionSupported_Beams = QAction(MElist)
        self.actionSupported_Beams.setObjectName(u"actionSupported_Beams")
        self.actionMohr_s_Circle = QAction(MElist)
        self.actionMohr_s_Circle.setObjectName(u"actionMohr_s_Circle")
        self.actionC_Clamp = QAction(MElist)
        self.actionC_Clamp.setObjectName(u"actionC_Clamp")
        self.actionCompression_Link = QAction(MElist)
        self.actionCompression_Link.setObjectName(u"actionCompression_Link")
        self.actionTension_Link = QAction(MElist)
        self.actionTension_Link.setObjectName(u"actionTension_Link")
        self.actionPost = QAction(MElist)
        self.actionPost.setObjectName(u"actionPost")
        self.actionPost_and_Beam = QAction(MElist)
        self.actionPost_and_Beam.setObjectName(u"actionPost_and_Beam")
        self.actionKinematic_Diagraming = QAction(MElist)
        self.actionKinematic_Diagraming.setObjectName(u"actionKinematic_Diagraming")
        self.actionVector_Analysis = QAction(MElist)
        self.actionVector_Analysis.setObjectName(u"actionVector_Analysis")
        self.actionGDT_Checker = QAction(MElist)
        self.actionGDT_Checker.setObjectName(u"actionGDT_Checker")
        self.actionVirtual_Condition_Calculator = QAction(MElist)
        self.actionVirtual_Condition_Calculator.setObjectName(u"actionVirtual_Condition_Calculator")
        self.actionLimits_and_Fits = QAction(MElist)
        self.actionLimits_and_Fits.setObjectName(u"actionLimits_and_Fits")
        self.actionGDTFasteners = QAction(MElist)
        self.actionGDTFasteners.setObjectName(u"actionGDTFasteners")
        self.actionPaper_Gauging = QAction(MElist)
        self.actionPaper_Gauging.setObjectName(u"actionPaper_Gauging")
        self.actionTolerance_Finder = QAction(MElist)
        self.actionTolerance_Finder.setObjectName(u"actionTolerance_Finder")
        self.actionDiameter_Deviation = QAction(MElist)
        self.actionDiameter_Deviation.setObjectName(u"actionDiameter_Deviation")
        self.actionTorsion = QAction(MElist)
        self.actionTorsion.setObjectName(u"actionTorsion")
        self.actionPressure = QAction(MElist)
        self.actionPressure.setObjectName(u"actionPressure")
        self.actionAddMohr_s_Circle = QAction(MElist)
        self.actionAddMohr_s_Circle.setObjectName(u"actionAddMohr_s_Circle")
        self.actionModule_List = QAction(MElist)
        self.actionModule_List.setObjectName(u"actionModule_List")
        self.actionQuit = QAction(MElist)
        self.actionQuit.setObjectName(u"actionQuit")
        self.actionNotepad = QAction(MElist)
        self.actionNotepad.setObjectName(u"actionNotepad")
        font1 = QFont()
        font1.setFamilies([u"Consolas"])
        self.actionNotepad.setFont(font1)
        self.actionCalculator = QAction(MElist)
        self.actionCalculator.setObjectName(u"actionCalculator")
        self.actionScreenshot = QAction(MElist)
        self.actionScreenshot.setObjectName(u"actionScreenshot")
        self.actionPerfer_SI_units = QAction(MElist)
        self.actionPerfer_SI_units.setObjectName(u"actionPerfer_SI_units")
        self.actionPerfer_Metric_Units = QAction(MElist)
        self.actionPerfer_Metric_Units.setObjectName(u"actionPerfer_Metric_Units")
        self.actionMaterials_list = QAction(MElist)
        self.actionMaterials_list.setObjectName(u"actionMaterials_list")
        self.actionCross_Sectional_Beams_and_Shapes_Lists = QAction(MElist)
        self.actionCross_Sectional_Beams_and_Shapes_Lists.setObjectName(u"actionCross_Sectional_Beams_and_Shapes_Lists")
        self.actionAbout = QAction(MElist)
        self.actionAbout.setObjectName(u"actionAbout")
        self.actionUnit_Converter_help = QAction(MElist)
        self.actionUnit_Converter_help.setObjectName(u"actionUnit_Converter_help")
        self.actionMoments_of_Inertia_help = QAction(MElist)
        self.actionMoments_of_Inertia_help.setObjectName(u"actionMoments_of_Inertia_help")
        self.actionVectors_help = QAction(MElist)
        self.actionVectors_help.setObjectName(u"actionVectors_help")
        self.actionFriction_and_Force_help = QAction(MElist)
        self.actionFriction_and_Force_help.setObjectName(u"actionFriction_and_Force_help")
        self.actionFasteners_help = QAction(MElist)
        self.actionFasteners_help.setObjectName(u"actionFasteners_help")
        self.actionMaterial_Properties_help = QAction(MElist)
        self.actionMaterial_Properties_help.setObjectName(u"actionMaterial_Properties_help")
        self.actionCM_and_CG_help = QAction(MElist)
        self.actionCM_and_CG_help.setObjectName(u"actionCM_and_CG_help")
        self.actionTrusses_help = QAction(MElist)
        self.actionTrusses_help.setObjectName(u"actionTrusses_help")
        self.actionBeamsMoments_of_Inertia_help = QAction(MElist)
        self.actionBeamsMoments_of_Inertia_help.setObjectName(u"actionBeamsMoments_of_Inertia_help")
        self.actionShear_and_Moment_help = QAction(MElist)
        self.actionShear_and_Moment_help.setObjectName(u"actionShear_and_Moment_help")
        self.actionIndeterminate_Axial_Structures_help = QAction(MElist)
        self.actionIndeterminate_Axial_Structures_help.setObjectName(u"actionIndeterminate_Axial_Structures_help")
        self.actionFlexure_help = QAction(MElist)
        self.actionFlexure_help.setObjectName(u"actionFlexure_help")
        self.actionBeam_Deformation_help = QAction(MElist)
        self.actionBeam_Deformation_help.setObjectName(u"actionBeam_Deformation_help")
        self.actionAxial_Beam_Deformation_help = QAction(MElist)
        self.actionAxial_Beam_Deformation_help.setObjectName(u"actionAxial_Beam_Deformation_help")
        self.actionTorsional_Beam_Deformation_help = QAction(MElist)
        self.actionTorsional_Beam_Deformation_help.setObjectName(u"actionTorsional_Beam_Deformation_help")
        self.actionSupported_Beams_help = QAction(MElist)
        self.actionSupported_Beams_help.setObjectName(u"actionSupported_Beams_help")
        self.actionMohr_s_Circle_help = QAction(MElist)
        self.actionMohr_s_Circle_help.setObjectName(u"actionMohr_s_Circle_help")
        self.actionC_Clamp_help = QAction(MElist)
        self.actionC_Clamp_help.setObjectName(u"actionC_Clamp_help")
        self.actionCompression_Link_help = QAction(MElist)
        self.actionCompression_Link_help.setObjectName(u"actionCompression_Link_help")
        self.actionTension_Link_help = QAction(MElist)
        self.actionTension_Link_help.setObjectName(u"actionTension_Link_help")
        self.actionPost_help = QAction(MElist)
        self.actionPost_help.setObjectName(u"actionPost_help")
        self.actionPost_and_Beam_help = QAction(MElist)
        self.actionPost_and_Beam_help.setObjectName(u"actionPost_and_Beam_help")
        self.actionSolid_shaft_and_Pipe_help = QAction(MElist)
        self.actionSolid_shaft_and_Pipe_help.setObjectName(u"actionSolid_shaft_and_Pipe_help")
        self.actionKinematic_Diagraming_help = QAction(MElist)
        self.actionKinematic_Diagraming_help.setObjectName(u"actionKinematic_Diagraming_help")
        self.actionVector_and_Motion_Analysis_help = QAction(MElist)
        self.actionVector_and_Motion_Analysis_help.setObjectName(u"actionVector_and_Motion_Analysis_help")
        self.actionGDT_Checker_help = QAction(MElist)
        self.actionGDT_Checker_help.setObjectName(u"actionGDT_Checker_help")
        self.actionVirtual_Condition_Calculator_help = QAction(MElist)
        self.actionVirtual_Condition_Calculator_help.setObjectName(u"actionVirtual_Condition_Calculator_help")
        self.actionLimits_and_Fits_help = QAction(MElist)
        self.actionLimits_and_Fits_help.setObjectName(u"actionLimits_and_Fits_help")
        self.actionGDTFasteners_help = QAction(MElist)
        self.actionGDTFasteners_help.setObjectName(u"actionGDTFasteners_help")
        self.actionPaper_Gauging_help = QAction(MElist)
        self.actionPaper_Gauging_help.setObjectName(u"actionPaper_Gauging_help")
        self.actionTolerance_Finder_help = QAction(MElist)
        self.actionTolerance_Finder_help.setObjectName(u"actionTolerance_Finder_help")
        self.actionDiameter_Deviation_help = QAction(MElist)
        self.actionDiameter_Deviation_help.setObjectName(u"actionDiameter_Deviation_help")
        self.actionTorsion_help = QAction(MElist)
        self.actionTorsion_help.setObjectName(u"actionTorsion_help")
        self.actionPressure_help = QAction(MElist)
        self.actionPressure_help.setObjectName(u"actionPressure_help")
        self.actionTheme = QAction(MElist)
        self.actionTheme.setObjectName(u"actionTheme")
        self.actionSaftey_Factors = QAction(MElist)
        self.actionSaftey_Factors.setObjectName(u"actionSaftey_Factors")
        self.actionSolid_Shaft_and_Pipe = QAction(MElist)
        self.actionSolid_Shaft_and_Pipe.setObjectName(u"actionSolid_Shaft_and_Pipe")
        self.actionMohr_s_Circle_2 = QAction(MElist)
        self.actionMohr_s_Circle_2.setObjectName(u"actionMohr_s_Circle_2")
        self.actionFit_Classes = QAction(MElist)
        self.actionFit_Classes.setObjectName(u"actionFit_Classes")
        self.actionUnit_Settings = QAction(MElist)
        self.actionUnit_Settings.setObjectName(u"actionUnit_Settings")
        self.actionUnit_Converter_2 = QAction(MElist)
        self.actionUnit_Converter_2.setObjectName(u"actionUnit_Converter_2")
        self.centralwidget = QWidget(MElist)
        self.centralwidget.setObjectName(u"centralwidget")
        self.gridLayout = QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.ModuleList = QToolBox(self.centralwidget)
        self.ModuleList.setObjectName(u"ModuleList")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.ModuleList.sizePolicy().hasHeightForWidth())
        self.ModuleList.setSizePolicy(sizePolicy1)
        font2 = QFont()
        font2.setFamilies([u"Consolas"])
        font2.setPointSize(14)
        self.ModuleList.setFont(font2)
        self.ModuleList.setContextMenuPolicy(Qt.ContextMenuPolicy.NoContextMenu)
        self.ModuleList.setFrameShape(QFrame.Shape.WinPanel)
        self.ModuleList.setFrameShadow(QFrame.Shadow.Sunken)
        self.ModuleList.setLineWidth(2)
        self.ModuleList.setMidLineWidth(0)
        self.generalanalysis = QWidget()
        self.generalanalysis.setObjectName(u"generalanalysis")
        self.generalanalysis.setGeometry(QRect(0, 0, 508, 485))
        self.gridLayout_4 = QGridLayout(self.generalanalysis)
        self.gridLayout_4.setObjectName(u"gridLayout_4")
        self.vectors = QPushButton(self.generalanalysis)
        self.vectors.setObjectName(u"vectors")
        sizePolicy1.setHeightForWidth(self.vectors.sizePolicy().hasHeightForWidth())
        self.vectors.setSizePolicy(sizePolicy1)
        self.vectors.setMinimumSize(QSize(230, 25))

        self.gridLayout_4.addWidget(self.vectors, 3, 0, 1, 1)

        self.cmandcg = QPushButton(self.generalanalysis)
        self.cmandcg.setObjectName(u"cmandcg")
        sizePolicy1.setHeightForWidth(self.cmandcg.sizePolicy().hasHeightForWidth())
        self.cmandcg.setSizePolicy(sizePolicy1)
        self.cmandcg.setMinimumSize(QSize(230, 25))

        self.gridLayout_4.addWidget(self.cmandcg, 5, 1, 1, 1)

        self.moi = QPushButton(self.generalanalysis)
        self.moi.setObjectName(u"moi")
        sizePolicy1.setHeightForWidth(self.moi.sizePolicy().hasHeightForWidth())
        self.moi.setSizePolicy(sizePolicy1)
        self.moi.setMinimumSize(QSize(230, 25))

        self.gridLayout_4.addWidget(self.moi, 1, 1, 1, 1)

        self.fasteners = QPushButton(self.generalanalysis)
        self.fasteners.setObjectName(u"fasteners")
        sizePolicy1.setHeightForWidth(self.fasteners.sizePolicy().hasHeightForWidth())
        self.fasteners.setSizePolicy(sizePolicy1)
        self.fasteners.setMinimumSize(QSize(230, 25))

        self.gridLayout_4.addWidget(self.fasteners, 3, 1, 1, 1)

        self.unitconvert = QPushButton(self.generalanalysis)
        self.unitconvert.setObjectName(u"unitconvert")
        sizePolicy1.setHeightForWidth(self.unitconvert.sizePolicy().hasHeightForWidth())
        self.unitconvert.setSizePolicy(sizePolicy1)
        self.unitconvert.setMinimumSize(QSize(230, 25))

        self.gridLayout_4.addWidget(self.unitconvert, 1, 0, 1, 1)

        self.matlprop = QPushButton(self.generalanalysis)
        self.matlprop.setObjectName(u"matlprop")
        sizePolicy1.setHeightForWidth(self.matlprop.sizePolicy().hasHeightForWidth())
        self.matlprop.setSizePolicy(sizePolicy1)
        self.matlprop.setMinimumSize(QSize(230, 25))

        self.gridLayout_4.addWidget(self.matlprop, 5, 0, 1, 1)

        self.ModuleList.addItem(self.generalanalysis, u"General Analysis")
        self.beamsandloads = QWidget()
        self.beamsandloads.setObjectName(u"beamsandloads")
        self.beamsandloads.setGeometry(QRect(0, 0, 508, 485))
        self.verticalLayout_2 = QVBoxLayout(self.beamsandloads)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.beamsandloadssub = QToolBox(self.beamsandloads)
        self.beamsandloadssub.setObjectName(u"beamsandloadssub")
        self.beamsandloadssub.setFrameShape(QFrame.Shape.WinPanel)
        self.beamsandloadssub.setFrameShadow(QFrame.Shadow.Sunken)
        self.beamsandloadssub.setLineWidth(2)
        self.stdbeams = QWidget()
        self.stdbeams.setObjectName(u"stdbeams")
        self.stdbeams.setGeometry(QRect(0, 0, 486, 391))
        self.gridLayout_2 = QGridLayout(self.stdbeams)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.indtrmaxialstructs = QPushButton(self.stdbeams)
        self.indtrmaxialstructs.setObjectName(u"indtrmaxialstructs")
        sizePolicy1.setHeightForWidth(self.indtrmaxialstructs.sizePolicy().hasHeightForWidth())
        self.indtrmaxialstructs.setSizePolicy(sizePolicy1)
        self.indtrmaxialstructs.setMinimumSize(QSize(210, 25))

        self.gridLayout_2.addWidget(self.indtrmaxialstructs, 2, 1, 1, 1)

        self.axialbeam = QPushButton(self.stdbeams)
        self.axialbeam.setObjectName(u"axialbeam")
        sizePolicy1.setHeightForWidth(self.axialbeam.sizePolicy().hasHeightForWidth())
        self.axialbeam.setSizePolicy(sizePolicy1)
        self.axialbeam.setMinimumSize(QSize(210, 25))

        self.gridLayout_2.addWidget(self.axialbeam, 3, 1, 1, 1)

        self.mohrs = QPushButton(self.stdbeams)
        self.mohrs.setObjectName(u"mohrs")
        sizePolicy1.setHeightForWidth(self.mohrs.sizePolicy().hasHeightForWidth())
        self.mohrs.setSizePolicy(sizePolicy1)
        self.mohrs.setMinimumSize(QSize(210, 25))

        self.gridLayout_2.addWidget(self.mohrs, 10, 1, 1, 1)

        self.flex = QPushButton(self.stdbeams)
        self.flex.setObjectName(u"flex")
        sizePolicy1.setHeightForWidth(self.flex.sizePolicy().hasHeightForWidth())
        self.flex.setSizePolicy(sizePolicy1)
        self.flex.setMinimumSize(QSize(210, 25))

        self.gridLayout_2.addWidget(self.flex, 2, 0, 1, 1)

        self.beamdeform = QPushButton(self.stdbeams)
        self.beamdeform.setObjectName(u"beamdeform")
        sizePolicy1.setHeightForWidth(self.beamdeform.sizePolicy().hasHeightForWidth())
        self.beamdeform.setSizePolicy(sizePolicy1)
        self.beamdeform.setMinimumSize(QSize(210, 25))

        self.gridLayout_2.addWidget(self.beamdeform, 3, 0, 1, 1)

        self.moi_beamssub = QPushButton(self.stdbeams)
        self.moi_beamssub.setObjectName(u"moi_beamssub")
        sizePolicy1.setHeightForWidth(self.moi_beamssub.sizePolicy().hasHeightForWidth())
        self.moi_beamssub.setSizePolicy(sizePolicy1)
        self.moi_beamssub.setMinimumSize(QSize(210, 25))

        self.gridLayout_2.addWidget(self.moi_beamssub, 0, 1, 1, 1)

        self.trusses = QPushButton(self.stdbeams)
        self.trusses.setObjectName(u"trusses")
        sizePolicy1.setHeightForWidth(self.trusses.sizePolicy().hasHeightForWidth())
        self.trusses.setSizePolicy(sizePolicy1)
        self.trusses.setMinimumSize(QSize(210, 25))

        self.gridLayout_2.addWidget(self.trusses, 0, 0, 1, 1)

        self.shearandmoment = QPushButton(self.stdbeams)
        self.shearandmoment.setObjectName(u"shearandmoment")
        sizePolicy1.setHeightForWidth(self.shearandmoment.sizePolicy().hasHeightForWidth())
        self.shearandmoment.setSizePolicy(sizePolicy1)
        self.shearandmoment.setMinimumSize(QSize(210, 25))

        self.gridLayout_2.addWidget(self.shearandmoment, 1, 0, 1, 1)

        self.supportedbeams = QPushButton(self.stdbeams)
        self.supportedbeams.setObjectName(u"supportedbeams")
        sizePolicy1.setHeightForWidth(self.supportedbeams.sizePolicy().hasHeightForWidth())
        self.supportedbeams.setSizePolicy(sizePolicy1)
        self.supportedbeams.setMinimumSize(QSize(210, 25))

        self.gridLayout_2.addWidget(self.supportedbeams, 1, 1, 1, 1)

        self.torsionbeam = QPushButton(self.stdbeams)
        self.torsionbeam.setObjectName(u"torsionbeam")
        sizePolicy1.setHeightForWidth(self.torsionbeam.sizePolicy().hasHeightForWidth())
        self.torsionbeam.setSizePolicy(sizePolicy1)
        self.torsionbeam.setMinimumSize(QSize(210, 25))

        self.gridLayout_2.addWidget(self.torsionbeam, 10, 0, 1, 1)

        self.beamsandloadssub.addItem(self.stdbeams, u"General Beam Analysis")
        self.combloading = QWidget()
        self.combloading.setObjectName(u"combloading")
        self.combloading.setGeometry(QRect(0, 0, 486, 391))
        self.verticalLayout_3 = QVBoxLayout(self.combloading)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.Shearforceandbendingmoment_3 = QLabel(self.combloading)
        self.Shearforceandbendingmoment_3.setObjectName(u"Shearforceandbendingmoment_3")
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Fixed)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(28)
        sizePolicy2.setHeightForWidth(self.Shearforceandbendingmoment_3.sizePolicy().hasHeightForWidth())
        self.Shearforceandbendingmoment_3.setSizePolicy(sizePolicy2)
        self.Shearforceandbendingmoment_3.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.verticalLayout_3.addWidget(self.Shearforceandbendingmoment_3)

        self.gridLayout_3 = QGridLayout()
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.complink = QPushButton(self.combloading)
        self.complink.setObjectName(u"complink")
        sizePolicy1.setHeightForWidth(self.complink.sizePolicy().hasHeightForWidth())
        self.complink.setSizePolicy(sizePolicy1)
        self.complink.setMinimumSize(QSize(210, 25))

        self.gridLayout_3.addWidget(self.complink, 0, 0, 1, 1)

        self.tensionlink = QPushButton(self.combloading)
        self.tensionlink.setObjectName(u"tensionlink")
        sizePolicy1.setHeightForWidth(self.tensionlink.sizePolicy().hasHeightForWidth())
        self.tensionlink.setSizePolicy(sizePolicy1)
        self.tensionlink.setMinimumSize(QSize(210, 25))

        self.gridLayout_3.addWidget(self.tensionlink, 2, 0, 1, 1)

        self.cclamp = QPushButton(self.combloading)
        self.cclamp.setObjectName(u"cclamp")
        sizePolicy1.setHeightForWidth(self.cclamp.sizePolicy().hasHeightForWidth())
        self.cclamp.setSizePolicy(sizePolicy1)
        self.cclamp.setMinimumSize(QSize(210, 25))

        self.gridLayout_3.addWidget(self.cclamp, 0, 1, 1, 1)

        self.post = QPushButton(self.combloading)
        self.post.setObjectName(u"post")
        sizePolicy1.setHeightForWidth(self.post.sizePolicy().hasHeightForWidth())
        self.post.setSizePolicy(sizePolicy1)
        self.post.setMinimumSize(QSize(210, 25))

        self.gridLayout_3.addWidget(self.post, 2, 1, 1, 1)


        self.verticalLayout_3.addLayout(self.gridLayout_3)

        self.line = QFrame(self.combloading)
        self.line.setObjectName(u"line")
        sizePolicy3 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Fixed)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy3)
        self.line.setFrameShape(QFrame.Shape.HLine)
        self.line.setFrameShadow(QFrame.Shadow.Sunken)

        self.verticalLayout_3.addWidget(self.line)

        self.Shearforceandbendingmoment = QLabel(self.combloading)
        self.Shearforceandbendingmoment.setObjectName(u"Shearforceandbendingmoment")
        sizePolicy3.setHeightForWidth(self.Shearforceandbendingmoment.sizePolicy().hasHeightForWidth())
        self.Shearforceandbendingmoment.setSizePolicy(sizePolicy3)
        self.Shearforceandbendingmoment.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.verticalLayout_3.addWidget(self.Shearforceandbendingmoment)

        self.postandbeam = QPushButton(self.combloading)
        self.postandbeam.setObjectName(u"postandbeam")
        sizePolicy1.setHeightForWidth(self.postandbeam.sizePolicy().hasHeightForWidth())
        self.postandbeam.setSizePolicy(sizePolicy1)
        self.postandbeam.setMinimumSize(QSize(210, 25))

        self.verticalLayout_3.addWidget(self.postandbeam)

        self.line_2 = QFrame(self.combloading)
        self.line_2.setObjectName(u"line_2")
        sizePolicy3.setHeightForWidth(self.line_2.sizePolicy().hasHeightForWidth())
        self.line_2.setSizePolicy(sizePolicy3)
        self.line_2.setFrameShape(QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QFrame.Shadow.Sunken)

        self.verticalLayout_3.addWidget(self.line_2)

        self.Shearforceandbendingmoment_2 = QLabel(self.combloading)
        self.Shearforceandbendingmoment_2.setObjectName(u"Shearforceandbendingmoment_2")
        sizePolicy3.setHeightForWidth(self.Shearforceandbendingmoment_2.sizePolicy().hasHeightForWidth())
        self.Shearforceandbendingmoment_2.setSizePolicy(sizePolicy3)
        self.Shearforceandbendingmoment_2.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.verticalLayout_3.addWidget(self.Shearforceandbendingmoment_2)

        self.solidshaftandpipe = QPushButton(self.combloading)
        self.solidshaftandpipe.setObjectName(u"solidshaftandpipe")
        sizePolicy1.setHeightForWidth(self.solidshaftandpipe.sizePolicy().hasHeightForWidth())
        self.solidshaftandpipe.setSizePolicy(sizePolicy1)
        self.solidshaftandpipe.setMinimumSize(QSize(210, 25))

        self.verticalLayout_3.addWidget(self.solidshaftandpipe)

        self.beamsandloadssub.addItem(self.combloading, u"Combined Loadings")

        self.verticalLayout_2.addWidget(self.beamsandloadssub)

        self.ModuleList.addItem(self.beamsandloads, u"Beams and Loads")
        self.BasicMechanicsAnalysis = QWidget()
        self.BasicMechanicsAnalysis.setObjectName(u"BasicMechanicsAnalysis")
        self.BasicMechanicsAnalysis.setGeometry(QRect(0, 0, 508, 485))
        self.gridLayout_6 = QGridLayout(self.BasicMechanicsAnalysis)
        self.gridLayout_6.setObjectName(u"gridLayout_6")
        self.pressure = QPushButton(self.BasicMechanicsAnalysis)
        self.pressure.setObjectName(u"pressure")
        sizePolicy1.setHeightForWidth(self.pressure.sizePolicy().hasHeightForWidth())
        self.pressure.setSizePolicy(sizePolicy1)
        self.pressure.setMinimumSize(QSize(230, 25))

        self.gridLayout_6.addWidget(self.pressure, 4, 0, 1, 1)

        self.kinematicdiagraming_4 = QPushButton(self.BasicMechanicsAnalysis)
        self.kinematicdiagraming_4.setObjectName(u"kinematicdiagraming_4")
        sizePolicy1.setHeightForWidth(self.kinematicdiagraming_4.sizePolicy().hasHeightForWidth())
        self.kinematicdiagraming_4.setSizePolicy(sizePolicy1)
        self.kinematicdiagraming_4.setMinimumSize(QSize(230, 25))

        self.gridLayout_6.addWidget(self.kinematicdiagraming_4, 11, 1, 1, 1)

        self.kinematicdiagraming_3 = QPushButton(self.BasicMechanicsAnalysis)
        self.kinematicdiagraming_3.setObjectName(u"kinematicdiagraming_3")
        sizePolicy1.setHeightForWidth(self.kinematicdiagraming_3.sizePolicy().hasHeightForWidth())
        self.kinematicdiagraming_3.setSizePolicy(sizePolicy1)
        self.kinematicdiagraming_3.setMinimumSize(QSize(230, 25))

        self.gridLayout_6.addWidget(self.kinematicdiagraming_3, 11, 0, 1, 1)

        self.torsion = QPushButton(self.BasicMechanicsAnalysis)
        self.torsion.setObjectName(u"torsion")
        sizePolicy1.setHeightForWidth(self.torsion.sizePolicy().hasHeightForWidth())
        self.torsion.setSizePolicy(sizePolicy1)
        self.torsion.setMinimumSize(QSize(230, 25))

        self.gridLayout_6.addWidget(self.torsion, 1, 1, 1, 1)

        self.shearandmoment_2 = QPushButton(self.BasicMechanicsAnalysis)
        self.shearandmoment_2.setObjectName(u"shearandmoment_2")
        sizePolicy1.setHeightForWidth(self.shearandmoment_2.sizePolicy().hasHeightForWidth())
        self.shearandmoment_2.setSizePolicy(sizePolicy1)
        self.shearandmoment_2.setMinimumSize(QSize(210, 25))

        self.gridLayout_6.addWidget(self.shearandmoment_2, 1, 0, 1, 1)

        self.mohrsadditional = QPushButton(self.BasicMechanicsAnalysis)
        self.mohrsadditional.setObjectName(u"mohrsadditional")
        sizePolicy1.setHeightForWidth(self.mohrsadditional.sizePolicy().hasHeightForWidth())
        self.mohrsadditional.setSizePolicy(sizePolicy1)

        self.gridLayout_6.addWidget(self.mohrsadditional, 2, 0, 1, 1)

        self.kinematicdiagraming = QPushButton(self.BasicMechanicsAnalysis)
        self.kinematicdiagraming.setObjectName(u"kinematicdiagraming")
        sizePolicy1.setHeightForWidth(self.kinematicdiagraming.sizePolicy().hasHeightForWidth())
        self.kinematicdiagraming.setSizePolicy(sizePolicy1)
        self.kinematicdiagraming.setMinimumSize(QSize(230, 25))

        self.gridLayout_6.addWidget(self.kinematicdiagraming, 4, 1, 1, 1)

        self.flex_2 = QPushButton(self.BasicMechanicsAnalysis)
        self.flex_2.setObjectName(u"flex_2")
        sizePolicy1.setHeightForWidth(self.flex_2.sizePolicy().hasHeightForWidth())
        self.flex_2.setSizePolicy(sizePolicy1)
        self.flex_2.setMinimumSize(QSize(210, 25))

        self.gridLayout_6.addWidget(self.flex_2, 2, 1, 1, 1)

        self.ModuleList.addItem(self.BasicMechanicsAnalysis, u"Basic Mechanics Analysis")
        self.machindesignelements = QWidget()
        self.machindesignelements.setObjectName(u"machindesignelements")
        self.machindesignelements.setGeometry(QRect(0, 0, 508, 485))
        self.gridLayout_7 = QGridLayout(self.machindesignelements)
        self.gridLayout_7.setObjectName(u"gridLayout_7")
        self.pushButton_2 = QPushButton(self.machindesignelements)
        self.pushButton_2.setObjectName(u"pushButton_2")
        sizePolicy1.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy1)

        self.gridLayout_7.addWidget(self.pushButton_2, 2, 1, 1, 1)

        self.pushButton_4 = QPushButton(self.machindesignelements)
        self.pushButton_4.setObjectName(u"pushButton_4")
        sizePolicy1.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy1)

        self.gridLayout_7.addWidget(self.pushButton_4, 0, 1, 1, 1)

        self.pushButton = QPushButton(self.machindesignelements)
        self.pushButton.setObjectName(u"pushButton")
        sizePolicy1.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy1)

        self.gridLayout_7.addWidget(self.pushButton, 0, 0, 1, 1)

        self.pushButton_3 = QPushButton(self.machindesignelements)
        self.pushButton_3.setObjectName(u"pushButton_3")
        sizePolicy1.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy1)

        self.gridLayout_7.addWidget(self.pushButton_3, 2, 0, 1, 1)

        self.kinematicdiagraming_2 = QPushButton(self.machindesignelements)
        self.kinematicdiagraming_2.setObjectName(u"kinematicdiagraming_2")
        sizePolicy1.setHeightForWidth(self.kinematicdiagraming_2.sizePolicy().hasHeightForWidth())
        self.kinematicdiagraming_2.setSizePolicy(sizePolicy1)
        self.kinematicdiagraming_2.setMinimumSize(QSize(230, 25))

        self.gridLayout_7.addWidget(self.kinematicdiagraming_2, 1, 1, 1, 1)

        self.pushButton_7 = QPushButton(self.machindesignelements)
        self.pushButton_7.setObjectName(u"pushButton_7")
        sizePolicy1.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
        self.pushButton_7.setSizePolicy(sizePolicy1)

        self.gridLayout_7.addWidget(self.pushButton_7, 1, 0, 1, 1)

        self.pushButton_6 = QPushButton(self.machindesignelements)
        self.pushButton_6.setObjectName(u"pushButton_6")
        sizePolicy1.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy1)

        self.gridLayout_7.addWidget(self.pushButton_6, 3, 1, 1, 1)

        self.pushButton_5 = QPushButton(self.machindesignelements)
        self.pushButton_5.setObjectName(u"pushButton_5")
        sizePolicy1.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy1)

        self.gridLayout_7.addWidget(self.pushButton_5, 3, 0, 1, 1)

        self.ModuleList.addItem(self.machindesignelements, u"Machine Design Elements")
        self.engineeringanddrafting = QWidget()
        self.engineeringanddrafting.setObjectName(u"engineeringanddrafting")
        self.engineeringanddrafting.setGeometry(QRect(0, 0, 508, 485))
        self.gridLayout_5 = QGridLayout(self.engineeringanddrafting)
        self.gridLayout_5.setObjectName(u"gridLayout_5")
        self.GDTchecker = QPushButton(self.engineeringanddrafting)
        self.GDTchecker.setObjectName(u"GDTchecker")
        sizePolicy1.setHeightForWidth(self.GDTchecker.sizePolicy().hasHeightForWidth())
        self.GDTchecker.setSizePolicy(sizePolicy1)
        self.GDTchecker.setMinimumSize(QSize(230, 35))

        self.gridLayout_5.addWidget(self.GDTchecker, 0, 0, 1, 1)

        self.limsandfits = QPushButton(self.engineeringanddrafting)
        self.limsandfits.setObjectName(u"limsandfits")
        sizePolicy1.setHeightForWidth(self.limsandfits.sizePolicy().hasHeightForWidth())
        self.limsandfits.setSizePolicy(sizePolicy1)
        self.limsandfits.setMinimumSize(QSize(230, 25))

        self.gridLayout_5.addWidget(self.limsandfits, 4, 0, 1, 1)

        self.diamdev = QPushButton(self.engineeringanddrafting)
        self.diamdev.setObjectName(u"diamdev")
        sizePolicy1.setHeightForWidth(self.diamdev.sizePolicy().hasHeightForWidth())
        self.diamdev.setSizePolicy(sizePolicy1)
        self.diamdev.setMinimumSize(QSize(230, 25))

        self.gridLayout_5.addWidget(self.diamdev, 8, 0, 1, 1)

        self.VCcalc = QPushButton(self.engineeringanddrafting)
        self.VCcalc.setObjectName(u"VCcalc")
        sizePolicy1.setHeightForWidth(self.VCcalc.sizePolicy().hasHeightForWidth())
        self.VCcalc.setSizePolicy(sizePolicy1)
        self.VCcalc.setMinimumSize(QSize(230, 25))

        self.gridLayout_5.addWidget(self.VCcalc, 0, 1, 1, 1)

        self.fastenersGDT = QPushButton(self.engineeringanddrafting)
        self.fastenersGDT.setObjectName(u"fastenersGDT")
        sizePolicy1.setHeightForWidth(self.fastenersGDT.sizePolicy().hasHeightForWidth())
        self.fastenersGDT.setSizePolicy(sizePolicy1)
        self.fastenersGDT.setMinimumSize(QSize(230, 25))

        self.gridLayout_5.addWidget(self.fastenersGDT, 4, 1, 1, 1)

        self.tolfinder = QPushButton(self.engineeringanddrafting)
        self.tolfinder.setObjectName(u"tolfinder")
        sizePolicy1.setHeightForWidth(self.tolfinder.sizePolicy().hasHeightForWidth())
        self.tolfinder.setSizePolicy(sizePolicy1)
        self.tolfinder.setMinimumSize(QSize(230, 25))

        self.gridLayout_5.addWidget(self.tolfinder, 5, 1, 1, 1)

        self.papergauge = QPushButton(self.engineeringanddrafting)
        self.papergauge.setObjectName(u"papergauge")
        sizePolicy1.setHeightForWidth(self.papergauge.sizePolicy().hasHeightForWidth())
        self.papergauge.setSizePolicy(sizePolicy1)
        self.papergauge.setMinimumSize(QSize(230, 25))

        self.gridLayout_5.addWidget(self.papergauge, 5, 0, 1, 1)

        self.ModuleList.addItem(self.engineeringanddrafting, u"Engineering and Drafting")
        self.additional = QWidget()
        self.additional.setObjectName(u"additional")
        self.additional.setGeometry(QRect(0, 0, 508, 485))
        self.verticalLayout_8 = QVBoxLayout(self.additional)
        self.verticalLayout_8.setObjectName(u"verticalLayout_8")
        self.ModuleList.addItem(self.additional, u"Additional Calculators")

        self.gridLayout.addWidget(self.ModuleList, 0, 0, 1, 1)

        MElist.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MElist)
        self.statusbar.setObjectName(u"statusbar")
        MElist.setStatusBar(self.statusbar)
        self.menubar = QMenuBar(MElist)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 530, 33))
        self.menu_File = QMenu(self.menubar)
        self.menu_File.setObjectName(u"menu_File")
        self.menu_Settings = QMenu(self.menu_File)
        self.menu_Settings.setObjectName(u"menu_Settings")
        self.menu_Utilites = QMenu(self.menubar)
        self.menu_Utilites.setObjectName(u"menu_Utilites")
        self.menuTables = QMenu(self.menu_Utilites)
        self.menuTables.setObjectName(u"menuTables")
        self.menu_Help = QMenu(self.menubar)
        self.menu_Help.setObjectName(u"menu_Help")
        self.menuModules_help = QMenu(self.menu_Help)
        self.menuModules_help.setObjectName(u"menuModules_help")
        self.menuGeneral_Analysis_help = QMenu(self.menuModules_help)
        self.menuGeneral_Analysis_help.setObjectName(u"menuGeneral_Analysis_help")
        self.menuBeams_and_Loads_help = QMenu(self.menuModules_help)
        self.menuBeams_and_Loads_help.setObjectName(u"menuBeams_and_Loads_help")
        self.menuGeneral_Beam_Analysis = QMenu(self.menuBeams_and_Loads_help)
        self.menuGeneral_Beam_Analysis.setObjectName(u"menuGeneral_Beam_Analysis")
        self.menuCombined_Loadings_help = QMenu(self.menuBeams_and_Loads_help)
        self.menuCombined_Loadings_help.setObjectName(u"menuCombined_Loadings_help")
        self.menuEccentric_Loadings_help = QMenu(self.menuCombined_Loadings_help)
        self.menuEccentric_Loadings_help.setObjectName(u"menuEccentric_Loadings_help")
        self.menuShear_Force_and_Bending_Moment_help = QMenu(self.menuCombined_Loadings_help)
        self.menuShear_Force_and_Bending_Moment_help.setObjectName(u"menuShear_Force_and_Bending_Moment_help")
        self.menuAxial_Torsional_and_Bending_Stresses_help = QMenu(self.menuCombined_Loadings_help)
        self.menuAxial_Torsional_and_Bending_Stresses_help.setObjectName(u"menuAxial_Torsional_and_Bending_Stresses_help")
        self.menuKinematics_help = QMenu(self.menuModules_help)
        self.menuKinematics_help.setObjectName(u"menuKinematics_help")
        self.menuEngineering_and_Drafting_help = QMenu(self.menuModules_help)
        self.menuEngineering_and_Drafting_help.setObjectName(u"menuEngineering_and_Drafting_help")
        self.menuAdditional_Calculators_help = QMenu(self.menuModules_help)
        self.menuAdditional_Calculators_help.setObjectName(u"menuAdditional_Calculators_help")
        self.menu_Modules = QMenu(self.menubar)
        self.menu_Modules.setObjectName(u"menu_Modules")
        self.menu_General_Analysis = QMenu(self.menu_Modules)
        self.menu_General_Analysis.setObjectName(u"menu_General_Analysis")
        font3 = QFont()
        font3.setFamilies([u"Consolas"])
        font3.setPointSize(9)
        self.menu_General_Analysis.setFont(font3)
        self.menu_Beams_and_Loads = QMenu(self.menu_Modules)
        self.menu_Beams_and_Loads.setObjectName(u"menu_Beams_and_Loads")
        self.menu_Generic_Beam_Analysis = QMenu(self.menu_Beams_and_Loads)
        self.menu_Generic_Beam_Analysis.setObjectName(u"menu_Generic_Beam_Analysis")
        self.menuCombined_Loadings = QMenu(self.menu_Beams_and_Loads)
        self.menuCombined_Loadings.setObjectName(u"menuCombined_Loadings")
        self.menuEccentric_Loadings = QMenu(self.menuCombined_Loadings)
        self.menuEccentric_Loadings.setObjectName(u"menuEccentric_Loadings")
        self.menuShear_Force_and_Bending_Moment = QMenu(self.menuCombined_Loadings)
        self.menuShear_Force_and_Bending_Moment.setObjectName(u"menuShear_Force_and_Bending_Moment")
        self.menuAxial_Torsional_and_Bending_Stresses = QMenu(self.menuCombined_Loadings)
        self.menuAxial_Torsional_and_Bending_Stresses.setObjectName(u"menuAxial_Torsional_and_Bending_Stresses")
        self.menu_Kinematics = QMenu(self.menu_Modules)
        self.menu_Kinematics.setObjectName(u"menu_Kinematics")
        self.menu_Egineering_and_Drafting = QMenu(self.menu_Modules)
        self.menu_Egineering_and_Drafting.setObjectName(u"menu_Egineering_and_Drafting")
        self.menu_Additional_Calculators = QMenu(self.menu_Modules)
        self.menu_Additional_Calculators.setObjectName(u"menu_Additional_Calculators")
        MElist.setMenuBar(self.menubar)

        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Modules.menuAction())
        self.menubar.addAction(self.menu_Utilites.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())
        self.menu_File.addAction(self.menu_Settings.menuAction())
        self.menu_File.addAction(self.actionQuit)
        self.menu_Settings.addAction(self.actionUnit_Settings)
        self.menu_Settings.addSeparator()
        self.menu_Settings.addAction(self.actionTheme)
        self.menu_Utilites.addAction(self.actionNotepad)
        self.menu_Utilites.addAction(self.actionCalculator)
        self.menu_Utilites.addAction(self.actionUnit_Converter_2)
        self.menu_Utilites.addAction(self.actionScreenshot)
        self.menu_Utilites.addAction(self.menuTables.menuAction())
        self.menuTables.addAction(self.actionMaterials_list)
        self.menuTables.addAction(self.actionCross_Sectional_Beams_and_Shapes_Lists)
        self.menuTables.addAction(self.actionSaftey_Factors)
        self.menuTables.addAction(self.actionFit_Classes)
        self.menu_Help.addAction(self.menuModules_help.menuAction())
        self.menu_Help.addAction(self.actionAbout)
        self.menuModules_help.addAction(self.menuGeneral_Analysis_help.menuAction())
        self.menuModules_help.addAction(self.menuBeams_and_Loads_help.menuAction())
        self.menuModules_help.addAction(self.menuKinematics_help.menuAction())
        self.menuModules_help.addAction(self.menuEngineering_and_Drafting_help.menuAction())
        self.menuModules_help.addAction(self.menuAdditional_Calculators_help.menuAction())
        self.menuGeneral_Analysis_help.addAction(self.actionUnit_Converter_help)
        self.menuGeneral_Analysis_help.addAction(self.actionMoments_of_Inertia_help)
        self.menuGeneral_Analysis_help.addAction(self.actionVectors_help)
        self.menuGeneral_Analysis_help.addAction(self.actionFriction_and_Force_help)
        self.menuGeneral_Analysis_help.addAction(self.actionFasteners_help)
        self.menuGeneral_Analysis_help.addAction(self.actionMaterial_Properties_help)
        self.menuGeneral_Analysis_help.addAction(self.actionCM_and_CG_help)
        self.menuBeams_and_Loads_help.addAction(self.menuGeneral_Beam_Analysis.menuAction())
        self.menuBeams_and_Loads_help.addAction(self.menuCombined_Loadings_help.menuAction())
        self.menuGeneral_Beam_Analysis.addAction(self.actionTrusses_help)
        self.menuGeneral_Beam_Analysis.addAction(self.actionBeamsMoments_of_Inertia_help)
        self.menuGeneral_Beam_Analysis.addAction(self.actionShear_and_Moment_help)
        self.menuGeneral_Beam_Analysis.addAction(self.actionIndeterminate_Axial_Structures_help)
        self.menuGeneral_Beam_Analysis.addAction(self.actionFlexure_help)
        self.menuGeneral_Beam_Analysis.addAction(self.actionBeam_Deformation_help)
        self.menuGeneral_Beam_Analysis.addAction(self.actionAxial_Beam_Deformation_help)
        self.menuGeneral_Beam_Analysis.addAction(self.actionTorsional_Beam_Deformation_help)
        self.menuGeneral_Beam_Analysis.addAction(self.actionSupported_Beams_help)
        self.menuGeneral_Beam_Analysis.addAction(self.actionMohr_s_Circle_help)
        self.menuCombined_Loadings_help.addAction(self.menuEccentric_Loadings_help.menuAction())
        self.menuCombined_Loadings_help.addAction(self.menuShear_Force_and_Bending_Moment_help.menuAction())
        self.menuCombined_Loadings_help.addAction(self.menuAxial_Torsional_and_Bending_Stresses_help.menuAction())
        self.menuEccentric_Loadings_help.addAction(self.actionC_Clamp_help)
        self.menuEccentric_Loadings_help.addAction(self.actionCompression_Link_help)
        self.menuEccentric_Loadings_help.addAction(self.actionTension_Link_help)
        self.menuEccentric_Loadings_help.addAction(self.actionPost_help)
        self.menuShear_Force_and_Bending_Moment_help.addAction(self.actionPost_and_Beam_help)
        self.menuAxial_Torsional_and_Bending_Stresses_help.addAction(self.actionSolid_shaft_and_Pipe_help)
        self.menuKinematics_help.addAction(self.actionKinematic_Diagraming_help)
        self.menuKinematics_help.addAction(self.actionVector_and_Motion_Analysis_help)
        self.menuEngineering_and_Drafting_help.addAction(self.actionGDT_Checker_help)
        self.menuEngineering_and_Drafting_help.addAction(self.actionVirtual_Condition_Calculator_help)
        self.menuEngineering_and_Drafting_help.addAction(self.actionLimits_and_Fits_help)
        self.menuEngineering_and_Drafting_help.addAction(self.actionGDTFasteners_help)
        self.menuEngineering_and_Drafting_help.addAction(self.actionPaper_Gauging_help)
        self.menuEngineering_and_Drafting_help.addAction(self.actionTolerance_Finder_help)
        self.menuEngineering_and_Drafting_help.addAction(self.actionDiameter_Deviation_help)
        self.menuAdditional_Calculators_help.addAction(self.actionTorsion_help)
        self.menuAdditional_Calculators_help.addAction(self.actionPressure_help)
        self.menuAdditional_Calculators_help.addAction(self.actionMohr_s_Circle_2)
        self.menu_Modules.addAction(self.menu_General_Analysis.menuAction())
        self.menu_Modules.addAction(self.menu_Beams_and_Loads.menuAction())
        self.menu_Modules.addAction(self.menu_Kinematics.menuAction())
        self.menu_Modules.addAction(self.menu_Egineering_and_Drafting.menuAction())
        self.menu_Modules.addAction(self.menu_Additional_Calculators.menuAction())
        self.menu_General_Analysis.addAction(self.actionUnit_Converter)
        self.menu_General_Analysis.addAction(self.actionMoments_of_Inertia)
        self.menu_General_Analysis.addAction(self.actionVectors)
        self.menu_General_Analysis.addAction(self.actionFriction_and_Force)
        self.menu_General_Analysis.addAction(self.actionFasteners)
        self.menu_General_Analysis.addAction(self.actionMaterial_Properties)
        self.menu_General_Analysis.addAction(self.actionCM_and_CG)
        self.menu_Beams_and_Loads.addAction(self.menu_Generic_Beam_Analysis.menuAction())
        self.menu_Beams_and_Loads.addAction(self.menuCombined_Loadings.menuAction())
        self.menu_Generic_Beam_Analysis.addAction(self.actionTrusses)
        self.menu_Generic_Beam_Analysis.addAction(self.actionBeamsMoments_of_Inertia)
        self.menu_Generic_Beam_Analysis.addAction(self.actionShear_and_Moment)
        self.menu_Generic_Beam_Analysis.addAction(self.actionIndeterminate_Axial_Structures)
        self.menu_Generic_Beam_Analysis.addAction(self.actionFlexure)
        self.menu_Generic_Beam_Analysis.addAction(self.actionBeam_Deformation)
        self.menu_Generic_Beam_Analysis.addAction(self.actionAxial_Beam_Deformation)
        self.menu_Generic_Beam_Analysis.addAction(self.actionTorsional_Beam_Deformation)
        self.menu_Generic_Beam_Analysis.addAction(self.actionSupported_Beams)
        self.menu_Generic_Beam_Analysis.addAction(self.actionMohr_s_Circle)
        self.menuCombined_Loadings.addAction(self.menuEccentric_Loadings.menuAction())
        self.menuCombined_Loadings.addAction(self.menuShear_Force_and_Bending_Moment.menuAction())
        self.menuCombined_Loadings.addAction(self.menuAxial_Torsional_and_Bending_Stresses.menuAction())
        self.menuEccentric_Loadings.addAction(self.actionC_Clamp)
        self.menuEccentric_Loadings.addAction(self.actionCompression_Link)
        self.menuEccentric_Loadings.addAction(self.actionTension_Link)
        self.menuEccentric_Loadings.addAction(self.actionPost)
        self.menuShear_Force_and_Bending_Moment.addAction(self.actionPost_and_Beam)
        self.menuAxial_Torsional_and_Bending_Stresses.addAction(self.actionSolid_Shaft_and_Pipe)
        self.menu_Kinematics.addAction(self.actionKinematic_Diagraming)
        self.menu_Kinematics.addAction(self.actionVector_Analysis)
        self.menu_Egineering_and_Drafting.addAction(self.actionGDT_Checker)
        self.menu_Egineering_and_Drafting.addAction(self.actionVirtual_Condition_Calculator)
        self.menu_Egineering_and_Drafting.addAction(self.actionLimits_and_Fits)
        self.menu_Egineering_and_Drafting.addAction(self.actionGDTFasteners)
        self.menu_Egineering_and_Drafting.addAction(self.actionPaper_Gauging)
        self.menu_Egineering_and_Drafting.addAction(self.actionTolerance_Finder)
        self.menu_Egineering_and_Drafting.addAction(self.actionDiameter_Deviation)
        self.menu_Additional_Calculators.addAction(self.actionTorsion)
        self.menu_Additional_Calculators.addAction(self.actionPressure)
        self.menu_Additional_Calculators.addAction(self.actionAddMohr_s_Circle)

        self.retranslateUi(MElist)

        self.ModuleList.setCurrentIndex(0)
        self.beamsandloadssub.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(MElist)
    # setupUi

    def retranslateUi(self, MElist):
        MElist.setWindowTitle(QCoreApplication.translate("MElist", u"MainWindow", None))
        self.actionUnit_Converter.setText(QCoreApplication.translate("MElist", u"Unit Converter", None))
        self.actionMoments_of_Inertia.setText(QCoreApplication.translate("MElist", u"Moments of Inertia", None))
        self.actionVectors.setText(QCoreApplication.translate("MElist", u"Vectors", None))
        self.actionFriction_and_Force.setText(QCoreApplication.translate("MElist", u"Friction and Force", None))
        self.actionFasteners.setText(QCoreApplication.translate("MElist", u"Fasteners", None))
        self.actionMaterial_Properties.setText(QCoreApplication.translate("MElist", u"Material Properties", None))
        self.actionCM_and_CG.setText(QCoreApplication.translate("MElist", u"CM and CG", None))
        self.actionTrusses.setText(QCoreApplication.translate("MElist", u"Trusses", None))
        self.actionBeamsMoments_of_Inertia.setText(QCoreApplication.translate("MElist", u"Moments of Inertia", None))
        self.actionShear_and_Moment.setText(QCoreApplication.translate("MElist", u"Shear and Moment", None))
        self.actionIndeterminate_Axial_Structures.setText(QCoreApplication.translate("MElist", u"Indeterminate Axial Structures", None))
        self.actionFlexure.setText(QCoreApplication.translate("MElist", u"Flexure", None))
        self.actionBeam_Deformation.setText(QCoreApplication.translate("MElist", u"Beam Deformation", None))
        self.actionAxial_Beam_Deformation.setText(QCoreApplication.translate("MElist", u"Axial Beam Deformation", None))
        self.actionTorsional_Beam_Deformation.setText(QCoreApplication.translate("MElist", u"Torsional Beam Deformation", None))
        self.actionSupported_Beams.setText(QCoreApplication.translate("MElist", u"Supported Beams", None))
        self.actionMohr_s_Circle.setText(QCoreApplication.translate("MElist", u"Mohr's Circle", None))
        self.actionC_Clamp.setText(QCoreApplication.translate("MElist", u"C-Clamp", None))
        self.actionCompression_Link.setText(QCoreApplication.translate("MElist", u"Compression Link", None))
        self.actionTension_Link.setText(QCoreApplication.translate("MElist", u"Tension Link", None))
        self.actionPost.setText(QCoreApplication.translate("MElist", u"Post", None))
        self.actionPost_and_Beam.setText(QCoreApplication.translate("MElist", u"Post and Beam", None))
        self.actionKinematic_Diagraming.setText(QCoreApplication.translate("MElist", u"Kinematic Diagraming", None))
        self.actionVector_Analysis.setText(QCoreApplication.translate("MElist", u"Vector Analysis", None))
        self.actionGDT_Checker.setText(QCoreApplication.translate("MElist", u"GDT Checker", None))
        self.actionVirtual_Condition_Calculator.setText(QCoreApplication.translate("MElist", u"Virtual Condition Calculator", None))
        self.actionLimits_and_Fits.setText(QCoreApplication.translate("MElist", u"Limits and Fits", None))
        self.actionGDTFasteners.setText(QCoreApplication.translate("MElist", u"Fasteners", None))
        self.actionPaper_Gauging.setText(QCoreApplication.translate("MElist", u"Paper Gauging", None))
        self.actionTolerance_Finder.setText(QCoreApplication.translate("MElist", u"Tolerance Finder", None))
        self.actionDiameter_Deviation.setText(QCoreApplication.translate("MElist", u"Diameter Deviation", None))
        self.actionTorsion.setText(QCoreApplication.translate("MElist", u"Torsion", None))
        self.actionPressure.setText(QCoreApplication.translate("MElist", u"Pressure", None))
        self.actionAddMohr_s_Circle.setText(QCoreApplication.translate("MElist", u"Mohr's Circle", None))
        self.actionModule_List.setText(QCoreApplication.translate("MElist", u"Module List", None))
        self.actionQuit.setText(QCoreApplication.translate("MElist", u"Quit", None))
        self.actionNotepad.setText(QCoreApplication.translate("MElist", u"Notepad", None))
        self.actionCalculator.setText(QCoreApplication.translate("MElist", u"Calculator", None))
        self.actionScreenshot.setText(QCoreApplication.translate("MElist", u"Screenshot", None))
        self.actionPerfer_SI_units.setText(QCoreApplication.translate("MElist", u"Edit Saftey Factor", None))
        self.actionPerfer_Metric_Units.setText(QCoreApplication.translate("MElist", u"Theme", None))
        self.actionMaterials_list.setText(QCoreApplication.translate("MElist", u"Materials List", None))
        self.actionCross_Sectional_Beams_and_Shapes_Lists.setText(QCoreApplication.translate("MElist", u"Beams and Shapes Lists", None))
        self.actionAbout.setText(QCoreApplication.translate("MElist", u"About", None))
        self.actionUnit_Converter_help.setText(QCoreApplication.translate("MElist", u"Unit Converter", None))
        self.actionMoments_of_Inertia_help.setText(QCoreApplication.translate("MElist", u"Moments of Inertia", None))
        self.actionVectors_help.setText(QCoreApplication.translate("MElist", u"Vectors", None))
        self.actionFriction_and_Force_help.setText(QCoreApplication.translate("MElist", u"Friction and Force", None))
        self.actionFasteners_help.setText(QCoreApplication.translate("MElist", u"Fasteners", None))
        self.actionMaterial_Properties_help.setText(QCoreApplication.translate("MElist", u"Material Properties", None))
        self.actionCM_and_CG_help.setText(QCoreApplication.translate("MElist", u"CM and CG", None))
        self.actionTrusses_help.setText(QCoreApplication.translate("MElist", u"Trusses", None))
        self.actionBeamsMoments_of_Inertia_help.setText(QCoreApplication.translate("MElist", u"Moments of Inertia", None))
        self.actionShear_and_Moment_help.setText(QCoreApplication.translate("MElist", u"Shear and Moment", None))
        self.actionIndeterminate_Axial_Structures_help.setText(QCoreApplication.translate("MElist", u"Indeterminate Axial Structures", None))
        self.actionFlexure_help.setText(QCoreApplication.translate("MElist", u"Flexure", None))
        self.actionBeam_Deformation_help.setText(QCoreApplication.translate("MElist", u"Beam Deformation", None))
        self.actionAxial_Beam_Deformation_help.setText(QCoreApplication.translate("MElist", u"Axial Beam Deformation", None))
        self.actionTorsional_Beam_Deformation_help.setText(QCoreApplication.translate("MElist", u"Torsional Beam Deformation", None))
        self.actionSupported_Beams_help.setText(QCoreApplication.translate("MElist", u"Supported Beams", None))
        self.actionMohr_s_Circle_help.setText(QCoreApplication.translate("MElist", u"Mohr's Circle", None))
        self.actionC_Clamp_help.setText(QCoreApplication.translate("MElist", u"C-Clamp", None))
        self.actionCompression_Link_help.setText(QCoreApplication.translate("MElist", u"Compression Link", None))
        self.actionTension_Link_help.setText(QCoreApplication.translate("MElist", u"Tension Link", None))
        self.actionPost_help.setText(QCoreApplication.translate("MElist", u"Post", None))
        self.actionPost_and_Beam_help.setText(QCoreApplication.translate("MElist", u"Post and Beam", None))
        self.actionSolid_shaft_and_Pipe_help.setText(QCoreApplication.translate("MElist", u"Solid Shaft and Pipe", None))
        self.actionKinematic_Diagraming_help.setText(QCoreApplication.translate("MElist", u"Kinematic Diagraming", None))
        self.actionVector_and_Motion_Analysis_help.setText(QCoreApplication.translate("MElist", u"Vector and Motion Analysis", None))
        self.actionGDT_Checker_help.setText(QCoreApplication.translate("MElist", u"GDT Checker", None))
        self.actionVirtual_Condition_Calculator_help.setText(QCoreApplication.translate("MElist", u"Virtual Condition Calculator", None))
        self.actionLimits_and_Fits_help.setText(QCoreApplication.translate("MElist", u"Limits and Fits", None))
        self.actionGDTFasteners_help.setText(QCoreApplication.translate("MElist", u"Fasteners", None))
        self.actionPaper_Gauging_help.setText(QCoreApplication.translate("MElist", u"Paper Gauging", None))
        self.actionTolerance_Finder_help.setText(QCoreApplication.translate("MElist", u"Tolerance Finder", None))
        self.actionDiameter_Deviation_help.setText(QCoreApplication.translate("MElist", u"Diameter Deviation", None))
        self.actionTorsion_help.setText(QCoreApplication.translate("MElist", u"Torsion", None))
        self.actionPressure_help.setText(QCoreApplication.translate("MElist", u"Pressure", None))
        self.actionTheme.setText(QCoreApplication.translate("MElist", u"Theme", None))
        self.actionSaftey_Factors.setText(QCoreApplication.translate("MElist", u"Saftey Factors", None))
        self.actionSolid_Shaft_and_Pipe.setText(QCoreApplication.translate("MElist", u"Solid Shaft and Pipe", None))
        self.actionMohr_s_Circle_2.setText(QCoreApplication.translate("MElist", u"Mohr's Circle", None))
        self.actionFit_Classes.setText(QCoreApplication.translate("MElist", u"Fit Classes", None))
        self.actionUnit_Settings.setText(QCoreApplication.translate("MElist", u"Unit Settings", None))
        self.actionUnit_Converter_2.setText(QCoreApplication.translate("MElist", u"Unit Converter", None))
        self.vectors.setText(QCoreApplication.translate("MElist", u"Vectors", None))
        self.cmandcg.setText(QCoreApplication.translate("MElist", u"Center of Mass and\n"
"Center of Gravity", None))
        self.moi.setText(QCoreApplication.translate("MElist", u"Moments of Inertia", None))
        self.fasteners.setText(QCoreApplication.translate("MElist", u"Fasteners", None))
        self.unitconvert.setText(QCoreApplication.translate("MElist", u"Unit Converter", None))
        self.matlprop.setText(QCoreApplication.translate("MElist", u"Material Properties", None))
        self.ModuleList.setItemText(self.ModuleList.indexOf(self.generalanalysis), QCoreApplication.translate("MElist", u"General Analysis", None))
        self.indtrmaxialstructs.setText(QCoreApplication.translate("MElist", u"Indeterminate Axial\n"
"Structures", None))
        self.axialbeam.setText(QCoreApplication.translate("MElist", u"Axial Beam\n"
"Deformation", None))
        self.mohrs.setText(QCoreApplication.translate("MElist", u"Mohr's Circle", None))
        self.flex.setText(QCoreApplication.translate("MElist", u"Flexure", None))
        self.beamdeform.setText(QCoreApplication.translate("MElist", u"Beam Deformation\n"
"Analysis", None))
        self.moi_beamssub.setText(QCoreApplication.translate("MElist", u"Moments of Inertia", None))
        self.trusses.setText(QCoreApplication.translate("MElist", u"Trusses", None))
        self.shearandmoment.setText(QCoreApplication.translate("MElist", u"Determinate Beams", None))
        self.supportedbeams.setText(QCoreApplication.translate("MElist", u"Column Buckling", None))
        self.torsionbeam.setText(QCoreApplication.translate("MElist", u"Torsional Beam\n"
"Deformation", None))
        self.beamsandloadssub.setItemText(self.beamsandloadssub.indexOf(self.stdbeams), QCoreApplication.translate("MElist", u"General Beam Analysis", None))
        self.Shearforceandbendingmoment_3.setText(QCoreApplication.translate("MElist", u"Eccentric Loadings", None))
        self.complink.setText(QCoreApplication.translate("MElist", u"Compression Link", None))
        self.tensionlink.setText(QCoreApplication.translate("MElist", u"Tension Link", None))
        self.cclamp.setText(QCoreApplication.translate("MElist", u"C-Clamp", None))
        self.post.setText(QCoreApplication.translate("MElist", u"Post", None))
        self.Shearforceandbendingmoment.setText(QCoreApplication.translate("MElist", u"Shear Force and Bending Moment", None))
        self.postandbeam.setText(QCoreApplication.translate("MElist", u"Post and Beam", None))
        self.Shearforceandbendingmoment_2.setText(QCoreApplication.translate("MElist", u"Axial, Torsional, and Bending Stresses", None))
        self.solidshaftandpipe.setText(QCoreApplication.translate("MElist", u"Solid Shaft and Pipe", None))
        self.beamsandloadssub.setItemText(self.beamsandloadssub.indexOf(self.combloading), QCoreApplication.translate("MElist", u"Combined Loadings", None))
        self.ModuleList.setItemText(self.ModuleList.indexOf(self.beamsandloads), QCoreApplication.translate("MElist", u"Beams and Loads", None))
        self.pressure.setText(QCoreApplication.translate("MElist", u"Pressure", None))
        self.kinematicdiagraming_4.setText(QCoreApplication.translate("MElist", u"Indeterminate\n"
"End-to-End\n"
"Shafts", None))
        self.kinematicdiagraming_3.setText(QCoreApplication.translate("MElist", u"Indeterminate Coaxial\n"
"Shafts", None))
        self.torsion.setText(QCoreApplication.translate("MElist", u"Simple Torsion", None))
        self.shearandmoment_2.setText(QCoreApplication.translate("MElist", u"Determinate Beams", None))
        self.mohrsadditional.setText(QCoreApplication.translate("MElist", u"Mohr's Circle", None))
        self.kinematicdiagraming.setText(QCoreApplication.translate("MElist", u"Kinematic\n"
"Diagramming", None))
        self.flex_2.setText(QCoreApplication.translate("MElist", u"Flexure", None))
        self.ModuleList.setItemText(self.ModuleList.indexOf(self.BasicMechanicsAnalysis), QCoreApplication.translate("MElist", u"Basic Mechanics Analysis", None))
        self.pushButton_2.setText(QCoreApplication.translate("MElist", u"Belt Drives", None))
        self.pushButton_4.setText(QCoreApplication.translate("MElist", u"Advanced Gear\n"
"Calculator", None))
        self.pushButton.setText(QCoreApplication.translate("MElist", u"Gear Trains", None))
        self.pushButton_3.setText(QCoreApplication.translate("MElist", u"Chain Drives", None))
        self.kinematicdiagraming_2.setText(QCoreApplication.translate("MElist", u"Gear Driven Shafts", None))
        self.pushButton_7.setText(QCoreApplication.translate("MElist", u"Shaft Design", None))
        self.pushButton_6.setText(QCoreApplication.translate("MElist", u"Keyway Calculator", None))
        self.pushButton_5.setText(QCoreApplication.translate("MElist", u"Bearing Caclulator", None))
        self.ModuleList.setItemText(self.ModuleList.indexOf(self.machindesignelements), QCoreApplication.translate("MElist", u"Machine Design Elements", None))
        self.GDTchecker.setText(QCoreApplication.translate("MElist", u"Geometric\n"
"Dimensioning \n"
" and Tolerancing\n"
"Checker", None))
        self.limsandfits.setText(QCoreApplication.translate("MElist", u"Limits and Fits", None))
        self.diamdev.setText(QCoreApplication.translate("MElist", u"Diameter Deviation", None))
        self.VCcalc.setText(QCoreApplication.translate("MElist", u"Virtual Condition \n"
"Calculator", None))
        self.fastenersGDT.setText(QCoreApplication.translate("MElist", u"Fixed and Floating\n"
"Fastener Calculator", None))
        self.tolfinder.setText(QCoreApplication.translate("MElist", u"Tolerance Finder", None))
        self.papergauge.setText(QCoreApplication.translate("MElist", u"Paper Gauging", None))
        self.ModuleList.setItemText(self.ModuleList.indexOf(self.engineeringanddrafting), QCoreApplication.translate("MElist", u"Engineering and Drafting", None))
        self.ModuleList.setItemText(self.ModuleList.indexOf(self.additional), QCoreApplication.translate("MElist", u"Additional Calculators", None))
        self.menu_File.setTitle(QCoreApplication.translate("MElist", u"&File", None))
        self.menu_Settings.setTitle(QCoreApplication.translate("MElist", u"Settings", None))
        self.menu_Utilites.setTitle(QCoreApplication.translate("MElist", u"&Utilites", None))
        self.menuTables.setTitle(QCoreApplication.translate("MElist", u"Tables", None))
        self.menu_Help.setTitle(QCoreApplication.translate("MElist", u"&Help", None))
        self.menuModules_help.setTitle(QCoreApplication.translate("MElist", u"Modules", None))
        self.menuGeneral_Analysis_help.setTitle(QCoreApplication.translate("MElist", u"General Analysis", None))
        self.menuBeams_and_Loads_help.setTitle(QCoreApplication.translate("MElist", u"Beams and Loads", None))
        self.menuGeneral_Beam_Analysis.setTitle(QCoreApplication.translate("MElist", u"General Beam Analysis", None))
        self.menuCombined_Loadings_help.setTitle(QCoreApplication.translate("MElist", u"Combined Loadings", None))
        self.menuEccentric_Loadings_help.setTitle(QCoreApplication.translate("MElist", u"Eccentric Loadings", None))
        self.menuShear_Force_and_Bending_Moment_help.setTitle(QCoreApplication.translate("MElist", u"Shear Force and Bending Moment", None))
        self.menuAxial_Torsional_and_Bending_Stresses_help.setTitle(QCoreApplication.translate("MElist", u"Axial, Torsional, and Bending Stresses", None))
        self.menuKinematics_help.setTitle(QCoreApplication.translate("MElist", u"Kinematics", None))
        self.menuEngineering_and_Drafting_help.setTitle(QCoreApplication.translate("MElist", u"Engineering and Drafting", None))
        self.menuAdditional_Calculators_help.setTitle(QCoreApplication.translate("MElist", u"Additional Calculators", None))
        self.menu_Modules.setTitle(QCoreApplication.translate("MElist", u"&Modules", None))
        self.menu_General_Analysis.setTitle(QCoreApplication.translate("MElist", u"General Analysis", None))
        self.menu_Beams_and_Loads.setTitle(QCoreApplication.translate("MElist", u"Beams and Loads", None))
        self.menu_Generic_Beam_Analysis.setTitle(QCoreApplication.translate("MElist", u"Generic Beam Analysis", None))
        self.menuCombined_Loadings.setTitle(QCoreApplication.translate("MElist", u"Combined Loadings", None))
        self.menuEccentric_Loadings.setTitle(QCoreApplication.translate("MElist", u"Eccentric Loadings", None))
        self.menuShear_Force_and_Bending_Moment.setTitle(QCoreApplication.translate("MElist", u"Shear Force and Bending Moment", None))
        self.menuAxial_Torsional_and_Bending_Stresses.setTitle(QCoreApplication.translate("MElist", u"Axial, Torsional, and Bending Stresses", None))
        self.menu_Kinematics.setTitle(QCoreApplication.translate("MElist", u"Kinematics", None))
        self.menu_Egineering_and_Drafting.setTitle(QCoreApplication.translate("MElist", u"Egineering and Drafting", None))
        self.menu_Additional_Calculators.setTitle(QCoreApplication.translate("MElist", u"Additional Calculators", None))
    # retranslateUi

