# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\James Karczewski\Downloads\stuff+apps\VScode\Mechanics Engine\UnitSettings.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UnitSettings(object):
    def setupUi(self, UnitSettings):
        UnitSettings.setObjectName("UnitSettings")
        UnitSettings.resize(174, 86)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(UnitSettings.sizePolicy().hasHeightForWidth())
        UnitSettings.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(UnitSettings)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(UnitSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.comboBox = QtWidgets.QComboBox(UnitSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout.addWidget(self.comboBox)
        self.buttonBox = QtWidgets.QDialogButtonBox(UnitSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(UnitSettings)
        self.buttonBox.accepted.connect(UnitSettings.accept) # type: ignore
        self.buttonBox.rejected.connect(UnitSettings.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(UnitSettings)

    def retranslateUi(self, UnitSettings):
        _translate = QtCore.QCoreApplication.translate
        UnitSettings.setWindowTitle(_translate("UnitSettings", "Dialog"))
        self.label.setText(_translate("UnitSettings", "Set Decimal Precision"))
        self.comboBox.setItemText(0, _translate("UnitSettings", "0 (0 Place)"))
        self.comboBox.setItemText(1, _translate("UnitSettings", "0.0 (1 Place)"))
        self.comboBox.setItemText(2, _translate("UnitSettings", "0.00 (2 Place)"))
        self.comboBox.setItemText(3, _translate("UnitSettings", "0.000 (3 Place)"))
        self.comboBox.setItemText(4, _translate("UnitSettings", "0.0000 (4 Place)"))
        self.comboBox.setItemText(5, _translate("UnitSettings", "0.00000 (5 Place)"))
        self.comboBox.setItemText(6, _translate("UnitSettings", "0.000000 (6 Place)"))
