# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'gdtcheck.ui'
##
## Created by: Qt User Interface Compiler version 6.8.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QAbstractSpinBox, QApplication, QCheckBox, QComboBox,
    QDoubleSpinBox, QFrame, QGroupBox, QHBoxLayout,
    QLabel, QLineEdit, QMainWindow, QMenu,
    QMenuBar, QRadioButton, QSizePolicy, QStatusBar,
    QTabWidget, QVBoxLayout, QWidget)

class Ui_MElist(object):
    def setupUi(self, MElist):
        if not MElist.objectName():
            MElist.setObjectName(u"MElist")
        MElist.resize(873, 820)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MElist.sizePolicy().hasHeightForWidth())
        MElist.setSizePolicy(sizePolicy)
        MElist.setMinimumSize(QSize(270, 610))
        MElist.setMaximumSize(QSize(16777215, 16777215))
        MElist.setIconSize(QSize(16, 24))
        MElist.setToolButtonStyle(Qt.ToolButtonIconOnly)
        MElist.setTabShape(QTabWidget.Rounded)
        MElist.setDockNestingEnabled(False)
        MElist.setUnifiedTitleAndToolBarOnMac(False)
        self.actionUnit_Converter = QAction(MElist)
        self.actionUnit_Converter.setObjectName(u"actionUnit_Converter")
        self.actionMoments_of_Inertia = QAction(MElist)
        self.actionMoments_of_Inertia.setObjectName(u"actionMoments_of_Inertia")
        self.actionVectors = QAction(MElist)
        self.actionVectors.setObjectName(u"actionVectors")
        self.actionFriction_and_Force = QAction(MElist)
        self.actionFriction_and_Force.setObjectName(u"actionFriction_and_Force")
        self.actionFasteners = QAction(MElist)
        self.actionFasteners.setObjectName(u"actionFasteners")
        self.actionMaterial_Properties = QAction(MElist)
        self.actionMaterial_Properties.setObjectName(u"actionMaterial_Properties")
        self.actionCM_and_CG = QAction(MElist)
        self.actionCM_and_CG.setObjectName(u"actionCM_and_CG")
        self.actionTrusses = QAction(MElist)
        self.actionTrusses.setObjectName(u"actionTrusses")
        self.actionBeamsMoments_of_Inertia = QAction(MElist)
        self.actionBeamsMoments_of_Inertia.setObjectName(u"actionBeamsMoments_of_Inertia")
        self.actionShear_and_Moment = QAction(MElist)
        self.actionShear_and_Moment.setObjectName(u"actionShear_and_Moment")
        self.actionIndeterminate_Axial_Structures = QAction(MElist)
        self.actionIndeterminate_Axial_Structures.setObjectName(u"actionIndeterminate_Axial_Structures")
        self.actionFlexure = QAction(MElist)
        self.actionFlexure.setObjectName(u"actionFlexure")
        self.actionBeam_Deformation = QAction(MElist)
        self.actionBeam_Deformation.setObjectName(u"actionBeam_Deformation")
        self.actionAxial_Beam_Deformation = QAction(MElist)
        self.actionAxial_Beam_Deformation.setObjectName(u"actionAxial_Beam_Deformation")
        self.actionTorsional_Beam_Deformation = QAction(MElist)
        self.actionTorsional_Beam_Deformation.setObjectName(u"actionTorsional_Beam_Deformation")
        self.actionSupported_Beams = QAction(MElist)
        self.actionSupported_Beams.setObjectName(u"actionSupported_Beams")
        self.actionMohr_s_Circle = QAction(MElist)
        self.actionMohr_s_Circle.setObjectName(u"actionMohr_s_Circle")
        self.actionC_Clamp = QAction(MElist)
        self.actionC_Clamp.setObjectName(u"actionC_Clamp")
        self.actionCompression_Link = QAction(MElist)
        self.actionCompression_Link.setObjectName(u"actionCompression_Link")
        self.actionTension_Link = QAction(MElist)
        self.actionTension_Link.setObjectName(u"actionTension_Link")
        self.actionPost = QAction(MElist)
        self.actionPost.setObjectName(u"actionPost")
        self.actionPost_and_Beam = QAction(MElist)
        self.actionPost_and_Beam.setObjectName(u"actionPost_and_Beam")
        self.actionKinematic_Diagraming = QAction(MElist)
        self.actionKinematic_Diagraming.setObjectName(u"actionKinematic_Diagraming")
        self.actionVector_Analysis = QAction(MElist)
        self.actionVector_Analysis.setObjectName(u"actionVector_Analysis")
        self.actionGDT_Checker = QAction(MElist)
        self.actionGDT_Checker.setObjectName(u"actionGDT_Checker")
        self.actionVirtual_Condition_Calculator = QAction(MElist)
        self.actionVirtual_Condition_Calculator.setObjectName(u"actionVirtual_Condition_Calculator")
        self.actionLimits_and_Fits = QAction(MElist)
        self.actionLimits_and_Fits.setObjectName(u"actionLimits_and_Fits")
        self.actionGDTFasteners = QAction(MElist)
        self.actionGDTFasteners.setObjectName(u"actionGDTFasteners")
        self.actionPaper_Gauging = QAction(MElist)
        self.actionPaper_Gauging.setObjectName(u"actionPaper_Gauging")
        self.actionTolerance_Finder = QAction(MElist)
        self.actionTolerance_Finder.setObjectName(u"actionTolerance_Finder")
        self.actionDiameter_Deviation = QAction(MElist)
        self.actionDiameter_Deviation.setObjectName(u"actionDiameter_Deviation")
        self.actionTorsion = QAction(MElist)
        self.actionTorsion.setObjectName(u"actionTorsion")
        self.actionPressure = QAction(MElist)
        self.actionPressure.setObjectName(u"actionPressure")
        self.actionAddMohr_s_Circle = QAction(MElist)
        self.actionAddMohr_s_Circle.setObjectName(u"actionAddMohr_s_Circle")
        self.actionModule_List = QAction(MElist)
        self.actionModule_List.setObjectName(u"actionModule_List")
        self.actionQuit = QAction(MElist)
        self.actionQuit.setObjectName(u"actionQuit")
        self.actionNotepad = QAction(MElist)
        self.actionNotepad.setObjectName(u"actionNotepad")
        self.actionCalculator = QAction(MElist)
        self.actionCalculator.setObjectName(u"actionCalculator")
        self.actionScreenshot = QAction(MElist)
        self.actionScreenshot.setObjectName(u"actionScreenshot")
        self.actionPerfer_SI_units = QAction(MElist)
        self.actionPerfer_SI_units.setObjectName(u"actionPerfer_SI_units")
        self.actionPerfer_Metric_Units = QAction(MElist)
        self.actionPerfer_Metric_Units.setObjectName(u"actionPerfer_Metric_Units")
        self.actionMaterials_list = QAction(MElist)
        self.actionMaterials_list.setObjectName(u"actionMaterials_list")
        self.actionCross_Sectional_Beams_and_Shapes_Lists = QAction(MElist)
        self.actionCross_Sectional_Beams_and_Shapes_Lists.setObjectName(u"actionCross_Sectional_Beams_and_Shapes_Lists")
        self.actionAbout = QAction(MElist)
        self.actionAbout.setObjectName(u"actionAbout")
        self.actionUnit_Converter_help = QAction(MElist)
        self.actionUnit_Converter_help.setObjectName(u"actionUnit_Converter_help")
        self.actionMoments_of_Inertia_help = QAction(MElist)
        self.actionMoments_of_Inertia_help.setObjectName(u"actionMoments_of_Inertia_help")
        self.actionVectors_help = QAction(MElist)
        self.actionVectors_help.setObjectName(u"actionVectors_help")
        self.actionFriction_and_Force_help = QAction(MElist)
        self.actionFriction_and_Force_help.setObjectName(u"actionFriction_and_Force_help")
        self.actionFasteners_help = QAction(MElist)
        self.actionFasteners_help.setObjectName(u"actionFasteners_help")
        self.actionMaterial_Properties_help = QAction(MElist)
        self.actionMaterial_Properties_help.setObjectName(u"actionMaterial_Properties_help")
        self.actionCM_and_CG_help = QAction(MElist)
        self.actionCM_and_CG_help.setObjectName(u"actionCM_and_CG_help")
        self.actionTrusses_help = QAction(MElist)
        self.actionTrusses_help.setObjectName(u"actionTrusses_help")
        self.actionBeamsMoments_of_Inertia_help = QAction(MElist)
        self.actionBeamsMoments_of_Inertia_help.setObjectName(u"actionBeamsMoments_of_Inertia_help")
        self.actionShear_and_Moment_help = QAction(MElist)
        self.actionShear_and_Moment_help.setObjectName(u"actionShear_and_Moment_help")
        self.actionIndeterminate_Axial_Structures_help = QAction(MElist)
        self.actionIndeterminate_Axial_Structures_help.setObjectName(u"actionIndeterminate_Axial_Structures_help")
        self.actionFlexure_help = QAction(MElist)
        self.actionFlexure_help.setObjectName(u"actionFlexure_help")
        self.actionBeam_Deformation_help = QAction(MElist)
        self.actionBeam_Deformation_help.setObjectName(u"actionBeam_Deformation_help")
        self.actionAxial_Beam_Deformation_help = QAction(MElist)
        self.actionAxial_Beam_Deformation_help.setObjectName(u"actionAxial_Beam_Deformation_help")
        self.actionTorsional_Beam_Deformation_help = QAction(MElist)
        self.actionTorsional_Beam_Deformation_help.setObjectName(u"actionTorsional_Beam_Deformation_help")
        self.actionSupported_Beams_help = QAction(MElist)
        self.actionSupported_Beams_help.setObjectName(u"actionSupported_Beams_help")
        self.actionMohr_s_Circle_help = QAction(MElist)
        self.actionMohr_s_Circle_help.setObjectName(u"actionMohr_s_Circle_help")
        self.actionC_Clamp_help = QAction(MElist)
        self.actionC_Clamp_help.setObjectName(u"actionC_Clamp_help")
        self.actionCompression_Link_help = QAction(MElist)
        self.actionCompression_Link_help.setObjectName(u"actionCompression_Link_help")
        self.actionTension_Link_help = QAction(MElist)
        self.actionTension_Link_help.setObjectName(u"actionTension_Link_help")
        self.actionPost_help = QAction(MElist)
        self.actionPost_help.setObjectName(u"actionPost_help")
        self.actionPost_and_Beam_help = QAction(MElist)
        self.actionPost_and_Beam_help.setObjectName(u"actionPost_and_Beam_help")
        self.actionSolid_shaft_and_Pipe_help = QAction(MElist)
        self.actionSolid_shaft_and_Pipe_help.setObjectName(u"actionSolid_shaft_and_Pipe_help")
        self.actionKinematic_Diagraming_help = QAction(MElist)
        self.actionKinematic_Diagraming_help.setObjectName(u"actionKinematic_Diagraming_help")
        self.actionVector_and_Motion_Analysis_help = QAction(MElist)
        self.actionVector_and_Motion_Analysis_help.setObjectName(u"actionVector_and_Motion_Analysis_help")
        self.actionGDT_Checker_help = QAction(MElist)
        self.actionGDT_Checker_help.setObjectName(u"actionGDT_Checker_help")
        self.actionVirtual_Condition_Calculator_help = QAction(MElist)
        self.actionVirtual_Condition_Calculator_help.setObjectName(u"actionVirtual_Condition_Calculator_help")
        self.actionLimits_and_Fits_help = QAction(MElist)
        self.actionLimits_and_Fits_help.setObjectName(u"actionLimits_and_Fits_help")
        self.actionGDTFasteners_help = QAction(MElist)
        self.actionGDTFasteners_help.setObjectName(u"actionGDTFasteners_help")
        self.actionPaper_Gauging_help = QAction(MElist)
        self.actionPaper_Gauging_help.setObjectName(u"actionPaper_Gauging_help")
        self.actionTolerance_Finder_help = QAction(MElist)
        self.actionTolerance_Finder_help.setObjectName(u"actionTolerance_Finder_help")
        self.actionDiameter_Deviation_help = QAction(MElist)
        self.actionDiameter_Deviation_help.setObjectName(u"actionDiameter_Deviation_help")
        self.actionTorsion_help = QAction(MElist)
        self.actionTorsion_help.setObjectName(u"actionTorsion_help")
        self.actionPressure_help = QAction(MElist)
        self.actionPressure_help.setObjectName(u"actionPressure_help")
        self.actionTheme = QAction(MElist)
        self.actionTheme.setObjectName(u"actionTheme")
        self.actionSaftey_Factors = QAction(MElist)
        self.actionSaftey_Factors.setObjectName(u"actionSaftey_Factors")
        self.actionSolid_Shaft_and_Pipe = QAction(MElist)
        self.actionSolid_Shaft_and_Pipe.setObjectName(u"actionSolid_Shaft_and_Pipe")
        self.actionMohr_s_Circle_2 = QAction(MElist)
        self.actionMohr_s_Circle_2.setObjectName(u"actionMohr_s_Circle_2")
        self.actionFit_Classes = QAction(MElist)
        self.actionFit_Classes.setObjectName(u"actionFit_Classes")
        self.centralwidget = QWidget(MElist)
        self.centralwidget.setObjectName(u"centralwidget")
        self.line = QFrame(self.centralwidget)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(0, 340, 751, 16))
        self.line.setFrameShadow(QFrame.Plain)
        self.line.setLineWidth(2)
        self.line.setFrameShape(QFrame.Shape.HLine)
        self.FCFsymbol = QLineEdit(self.centralwidget)
        self.FCFsymbol.setObjectName(u"FCFsymbol")
        self.FCFsymbol.setGeometry(QRect(45, 705, 61, 51))
        self.FCFtolvalue = QLineEdit(self.centralwidget)
        self.FCFtolvalue.setObjectName(u"FCFtolvalue")
        self.FCFtolvalue.setGeometry(QRect(115, 705, 231, 51))
        self.FCFprimedatum = QLineEdit(self.centralwidget)
        self.FCFprimedatum.setObjectName(u"FCFprimedatum")
        self.FCFprimedatum.setGeometry(QRect(355, 705, 61, 51))
        self.FCFseconddatum = QLineEdit(self.centralwidget)
        self.FCFseconddatum.setObjectName(u"FCFseconddatum")
        self.FCFseconddatum.setGeometry(QRect(425, 705, 61, 51))
        self.FCFtertiarydatum = QLineEdit(self.centralwidget)
        self.FCFtertiarydatum.setObjectName(u"FCFtertiarydatum")
        self.FCFtertiarydatum.setGeometry(QRect(495, 705, 61, 51))
        self.line_3 = QFrame(self.centralwidget)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(40, 752, 521, 16))
        font = QFont()
        font.setFamilies([u"MS Shell Dlg 2"])
        font.setPointSize(12)
        font.setBold(False)
        self.line_3.setFont(font)
        self.line_3.setFrameShadow(QFrame.Plain)
        self.line_3.setLineWidth(3)
        self.line_3.setFrameShape(QFrame.Shape.HLine)
        self.line_4 = QFrame(self.centralwidget)
        self.line_4.setObjectName(u"line_4")
        self.line_4.setGeometry(QRect(40, 692, 521, 16))
        self.line_4.setFont(font)
        self.line_4.setFrameShadow(QFrame.Plain)
        self.line_4.setLineWidth(3)
        self.line_4.setFrameShape(QFrame.Shape.HLine)
        self.line_5 = QFrame(self.centralwidget)
        self.line_5.setObjectName(u"line_5")
        self.line_5.setGeometry(QRect(30, 700, 20, 61))
        self.line_5.setFrameShadow(QFrame.Plain)
        self.line_5.setLineWidth(3)
        self.line_5.setFrameShape(QFrame.Shape.VLine)
        self.line_6 = QFrame(self.centralwidget)
        self.line_6.setObjectName(u"line_6")
        self.line_6.setGeometry(QRect(550, 700, 20, 61))
        self.line_6.setFrameShadow(QFrame.Plain)
        self.line_6.setLineWidth(3)
        self.line_6.setFrameShape(QFrame.Shape.VLine)
        self.line_7 = QFrame(self.centralwidget)
        self.line_7.setObjectName(u"line_7")
        self.line_7.setGeometry(QRect(480, 700, 20, 61))
        self.line_7.setFrameShadow(QFrame.Plain)
        self.line_7.setLineWidth(3)
        self.line_7.setFrameShape(QFrame.Shape.VLine)
        self.line_8 = QFrame(self.centralwidget)
        self.line_8.setObjectName(u"line_8")
        self.line_8.setGeometry(QRect(410, 700, 20, 61))
        self.line_8.setFrameShadow(QFrame.Plain)
        self.line_8.setLineWidth(3)
        self.line_8.setFrameShape(QFrame.Shape.VLine)
        self.line_9 = QFrame(self.centralwidget)
        self.line_9.setObjectName(u"line_9")
        self.line_9.setGeometry(QRect(340, 700, 20, 61))
        self.line_9.setFrameShadow(QFrame.Plain)
        self.line_9.setLineWidth(3)
        self.line_9.setFrameShape(QFrame.Shape.VLine)
        self.line_10 = QFrame(self.centralwidget)
        self.line_10.setObjectName(u"line_10")
        self.line_10.setGeometry(QRect(100, 700, 20, 61))
        self.line_10.setFrameShadow(QFrame.Plain)
        self.line_10.setLineWidth(3)
        self.line_10.setFrameShape(QFrame.Shape.VLine)
        self.line_2 = QFrame(self.centralwidget)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(0, 440, 681, 16))
        self.line_2.setFrameShadow(QFrame.Plain)
        self.line_2.setLineWidth(2)
        self.line_2.setFrameShape(QFrame.Shape.HLine)
        self.groupBox_2 = QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(10, 450, 561, 221))
        font1 = QFont()
        font1.setPointSize(12)
        self.groupBox_2.setFont(font1)
        self.layoutWidget = QWidget(self.groupBox_2)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(10, 20, 221, 151))
        self.verticalLayout_4 = QVBoxLayout(self.layoutWidget)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4 = QHBoxLayout()
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.label_13 = QLabel(self.layoutWidget)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setFont(font1)

        self.horizontalLayout_4.addWidget(self.label_13)

        self.PrimaryDatum = QLineEdit(self.layoutWidget)
        self.PrimaryDatum.setObjectName(u"PrimaryDatum")
        sizePolicy.setHeightForWidth(self.PrimaryDatum.sizePolicy().hasHeightForWidth())
        self.PrimaryDatum.setSizePolicy(sizePolicy)
        self.PrimaryDatum.setMinimumSize(QSize(40, 28))
        self.PrimaryDatum.setMaximumSize(QSize(40, 28))
        self.PrimaryDatum.setFont(font1)

        self.horizontalLayout_4.addWidget(self.PrimaryDatum)

        self.PrimaryDatumSharedAxis = QLineEdit(self.layoutWidget)
        self.PrimaryDatumSharedAxis.setObjectName(u"PrimaryDatumSharedAxis")
        self.PrimaryDatumSharedAxis.setMinimumSize(QSize(40, 28))
        self.PrimaryDatumSharedAxis.setMaximumSize(QSize(40, 28))
        self.PrimaryDatumSharedAxis.setFont(font1)

        self.horizontalLayout_4.addWidget(self.PrimaryDatumSharedAxis)


        self.verticalLayout_4.addLayout(self.horizontalLayout_4)

        self.horizontalLayout_5 = QHBoxLayout()
        self.horizontalLayout_5.setObjectName(u"horizontalLayout_5")
        self.label_14 = QLabel(self.layoutWidget)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setFont(font1)

        self.horizontalLayout_5.addWidget(self.label_14)

        self.SecondayDatum = QLineEdit(self.layoutWidget)
        self.SecondayDatum.setObjectName(u"SecondayDatum")
        self.SecondayDatum.setMaximumSize(QSize(40, 28))
        self.SecondayDatum.setFont(font1)

        self.horizontalLayout_5.addWidget(self.SecondayDatum)

        self.TertiaryDatum_3 = QLineEdit(self.layoutWidget)
        self.TertiaryDatum_3.setObjectName(u"TertiaryDatum_3")
        self.TertiaryDatum_3.setMinimumSize(QSize(40, 28))
        self.TertiaryDatum_3.setMaximumSize(QSize(40, 28))
        self.TertiaryDatum_3.setFont(font1)

        self.horizontalLayout_5.addWidget(self.TertiaryDatum_3)


        self.verticalLayout_4.addLayout(self.horizontalLayout_5)

        self.horizontalLayout_6 = QHBoxLayout()
        self.horizontalLayout_6.setObjectName(u"horizontalLayout_6")
        self.label_15 = QLabel(self.layoutWidget)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setFont(font1)

        self.horizontalLayout_6.addWidget(self.label_15)

        self.TertiaryDatum = QLineEdit(self.layoutWidget)
        self.TertiaryDatum.setObjectName(u"TertiaryDatum")
        self.TertiaryDatum.setMinimumSize(QSize(40, 28))
        self.TertiaryDatum.setMaximumSize(QSize(40, 28))
        self.TertiaryDatum.setFont(font1)

        self.horizontalLayout_6.addWidget(self.TertiaryDatum)

        self.TertiaryDatum_2 = QLineEdit(self.layoutWidget)
        self.TertiaryDatum_2.setObjectName(u"TertiaryDatum_2")
        self.TertiaryDatum_2.setMinimumSize(QSize(40, 28))
        self.TertiaryDatum_2.setMaximumSize(QSize(40, 28))
        self.TertiaryDatum_2.setFont(font1)

        self.horizontalLayout_6.addWidget(self.TertiaryDatum_2)


        self.verticalLayout_4.addLayout(self.horizontalLayout_6)

        self.layoutWidget1 = QWidget(self.groupBox_2)
        self.layoutWidget1.setObjectName(u"layoutWidget1")
        self.layoutWidget1.setGeometry(QRect(370, 20, 181, 151))
        self.verticalLayout_5 = QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_5.setObjectName(u"verticalLayout_5")
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.label_10 = QLabel(self.layoutWidget1)
        self.label_10.setObjectName(u"label_10")
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMinimumSize(QSize(0, 28))
        self.label_10.setMaximumSize(QSize(16777215, 28))
        self.label_10.setFont(font1)

        self.horizontalLayout.addWidget(self.label_10)

        self.PrimaryDatumModifier = QComboBox(self.layoutWidget1)
        self.PrimaryDatumModifier.setObjectName(u"PrimaryDatumModifier")
        sizePolicy.setHeightForWidth(self.PrimaryDatumModifier.sizePolicy().hasHeightForWidth())
        self.PrimaryDatumModifier.setSizePolicy(sizePolicy)
        self.PrimaryDatumModifier.setMinimumSize(QSize(0, 28))
        self.PrimaryDatumModifier.setMaximumSize(QSize(55, 28))
        font2 = QFont()
        font2.setFamilies([u"AIGDT"])
        font2.setPointSize(12)
        self.PrimaryDatumModifier.setFont(font2)

        self.horizontalLayout.addWidget(self.PrimaryDatumModifier)


        self.verticalLayout_5.addLayout(self.horizontalLayout)

        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.label_11 = QLabel(self.layoutWidget1)
        self.label_11.setObjectName(u"label_11")
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setFont(font1)

        self.horizontalLayout_2.addWidget(self.label_11)

        self.SecondaryDatumModifier = QComboBox(self.layoutWidget1)
        self.SecondaryDatumModifier.setObjectName(u"SecondaryDatumModifier")
        self.SecondaryDatumModifier.setMinimumSize(QSize(0, 28))
        self.SecondaryDatumModifier.setMaximumSize(QSize(55, 28))
        self.SecondaryDatumModifier.setFont(font2)

        self.horizontalLayout_2.addWidget(self.SecondaryDatumModifier)


        self.verticalLayout_5.addLayout(self.horizontalLayout_2)

        self.horizontalLayout_3 = QHBoxLayout()
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.label_12 = QLabel(self.layoutWidget1)
        self.label_12.setObjectName(u"label_12")
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setFont(font1)

        self.horizontalLayout_3.addWidget(self.label_12)

        self.TertiaryDatumModifier = QComboBox(self.layoutWidget1)
        self.TertiaryDatumModifier.setObjectName(u"TertiaryDatumModifier")
        self.TertiaryDatumModifier.setMaximumSize(QSize(55, 28))
        self.TertiaryDatumModifier.setFont(font2)

        self.horizontalLayout_3.addWidget(self.TertiaryDatumModifier)


        self.verticalLayout_5.addLayout(self.horizontalLayout_3)

        self.groupBox_5 = QGroupBox(self.centralwidget)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setGeometry(QRect(580, 470, 251, 61))
        self.groupBox_5.setFont(font1)
        self.horizontalLayout_7 = QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_7.setObjectName(u"horizontalLayout_7")
        self.checkBox = QCheckBox(self.groupBox_5)
        self.checkBox.setObjectName(u"checkBox")
        self.checkBox.setFont(font1)

        self.horizontalLayout_7.addWidget(self.checkBox)

        self.checkBox_3 = QCheckBox(self.groupBox_5)
        self.checkBox_3.setObjectName(u"checkBox_3")
        self.checkBox_3.setFont(font1)

        self.horizontalLayout_7.addWidget(self.checkBox_3)

        self.checkBox_2 = QCheckBox(self.groupBox_5)
        self.checkBox_2.setObjectName(u"checkBox_2")
        self.checkBox_2.setFont(font1)

        self.horizontalLayout_7.addWidget(self.checkBox_2)

        self.checkBox_4 = QCheckBox(self.groupBox_5)
        self.checkBox_4.setObjectName(u"checkBox_4")
        self.checkBox_4.setFont(font1)

        self.horizontalLayout_7.addWidget(self.checkBox_4)

        self.checkBox_6 = QCheckBox(self.groupBox_5)
        self.checkBox_6.setObjectName(u"checkBox_6")
        self.checkBox_6.setFont(font1)

        self.horizontalLayout_7.addWidget(self.checkBox_6)

        self.checkBox_5 = QCheckBox(self.groupBox_5)
        self.checkBox_5.setObjectName(u"checkBox_5")
        self.checkBox_5.setFont(font1)

        self.horizontalLayout_7.addWidget(self.checkBox_5)

        self.groupBox_6 = QGroupBox(self.centralwidget)
        self.groupBox_6.setObjectName(u"groupBox_6")
        self.groupBox_6.setGeometry(QRect(580, 520, 251, 61))
        self.groupBox_6.setFont(font1)
        self.horizontalLayout_8 = QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_8.setObjectName(u"horizontalLayout_8")
        self.checkBox_7 = QCheckBox(self.groupBox_6)
        self.checkBox_7.setObjectName(u"checkBox_7")
        self.checkBox_7.setFont(font1)

        self.horizontalLayout_8.addWidget(self.checkBox_7)

        self.checkBox_8 = QCheckBox(self.groupBox_6)
        self.checkBox_8.setObjectName(u"checkBox_8")
        self.checkBox_8.setFont(font1)

        self.horizontalLayout_8.addWidget(self.checkBox_8)

        self.checkBox_9 = QCheckBox(self.groupBox_6)
        self.checkBox_9.setObjectName(u"checkBox_9")
        self.checkBox_9.setFont(font1)

        self.horizontalLayout_8.addWidget(self.checkBox_9)

        self.checkBox_10 = QCheckBox(self.groupBox_6)
        self.checkBox_10.setObjectName(u"checkBox_10")
        self.checkBox_10.setFont(font1)

        self.horizontalLayout_8.addWidget(self.checkBox_10)

        self.checkBox_11 = QCheckBox(self.groupBox_6)
        self.checkBox_11.setObjectName(u"checkBox_11")
        self.checkBox_11.setFont(font1)

        self.horizontalLayout_8.addWidget(self.checkBox_11)

        self.checkBox_12 = QCheckBox(self.groupBox_6)
        self.checkBox_12.setObjectName(u"checkBox_12")
        self.checkBox_12.setFont(font1)

        self.horizontalLayout_8.addWidget(self.checkBox_12)

        self.groupBox_7 = QGroupBox(self.centralwidget)
        self.groupBox_7.setObjectName(u"groupBox_7")
        self.groupBox_7.setGeometry(QRect(580, 570, 251, 61))
        self.groupBox_7.setFont(font1)
        self.horizontalLayout_9 = QHBoxLayout(self.groupBox_7)
        self.horizontalLayout_9.setObjectName(u"horizontalLayout_9")
        self.checkBox_13 = QCheckBox(self.groupBox_7)
        self.checkBox_13.setObjectName(u"checkBox_13")
        self.checkBox_13.setFont(font1)

        self.horizontalLayout_9.addWidget(self.checkBox_13)

        self.checkBox_14 = QCheckBox(self.groupBox_7)
        self.checkBox_14.setObjectName(u"checkBox_14")
        self.checkBox_14.setFont(font1)

        self.horizontalLayout_9.addWidget(self.checkBox_14)

        self.checkBox_15 = QCheckBox(self.groupBox_7)
        self.checkBox_15.setObjectName(u"checkBox_15")
        self.checkBox_15.setFont(font1)

        self.horizontalLayout_9.addWidget(self.checkBox_15)

        self.checkBox_16 = QCheckBox(self.groupBox_7)
        self.checkBox_16.setObjectName(u"checkBox_16")
        self.checkBox_16.setFont(font1)

        self.horizontalLayout_9.addWidget(self.checkBox_16)

        self.checkBox_17 = QCheckBox(self.groupBox_7)
        self.checkBox_17.setObjectName(u"checkBox_17")
        self.checkBox_17.setFont(font1)

        self.horizontalLayout_9.addWidget(self.checkBox_17)

        self.checkBox_18 = QCheckBox(self.groupBox_7)
        self.checkBox_18.setObjectName(u"checkBox_18")
        self.checkBox_18.setFont(font1)

        self.horizontalLayout_9.addWidget(self.checkBox_18)

        self.groupBox_8 = QGroupBox(self.centralwidget)
        self.groupBox_8.setObjectName(u"groupBox_8")
        self.groupBox_8.setGeometry(QRect(10, 10, 311, 331))
        self.groupBox_8.setFont(font1)
        self.groupBox_8.setFlat(False)
        self.groupBox_8.setCheckable(False)
        self.label_6 = QLabel(self.groupBox_8)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(11, 171, 123, 35))
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QSize(0, 35))
        self.label_6.setMaximumSize(QSize(16777215, 35))
        self.label_6.setFont(font1)
        self.LowerDim = QDoubleSpinBox(self.groupBox_8)
        self.LowerDim.setObjectName(u"LowerDim")
        self.LowerDim.setGeometry(QRect(160, 210, 129, 28))
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Fixed)
        sizePolicy1.setHorizontalStretch(250)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.LowerDim.sizePolicy().hasHeightForWidth())
        self.LowerDim.setSizePolicy(sizePolicy1)
        self.LowerDim.setMinimumSize(QSize(0, 28))
        self.LowerDim.setMaximumSize(QSize(16777215, 28))
        self.LowerDim.setFont(font1)
        self.LowerDim.setReadOnly(True)
        self.LowerDim.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.LowerDim.setDecimals(5)
        self.LowerDim.setMaximum(1000000000000.000000000000000)
        self.label_7 = QLabel(self.groupBox_8)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(160, 180, 123, 31))
        self.label_7.setMaximumSize(QSize(16777215, 35))
        self.label_7.setFont(font1)
        self.UpperDim = QDoubleSpinBox(self.groupBox_8)
        self.UpperDim.setObjectName(u"UpperDim")
        self.UpperDim.setGeometry(QRect(160, 130, 129, 28))
        sizePolicy1.setHeightForWidth(self.UpperDim.sizePolicy().hasHeightForWidth())
        self.UpperDim.setSizePolicy(sizePolicy1)
        self.UpperDim.setMinimumSize(QSize(0, 28))
        self.UpperDim.setMaximumSize(QSize(16777215, 28))
        self.UpperDim.setFont(font1)
        self.UpperDim.setReadOnly(True)
        self.UpperDim.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.UpperDim.setDecimals(5)
        self.UpperDim.setMaximum(1000000000000.000000000000000)
        self.UpperTol = QDoubleSpinBox(self.groupBox_8)
        self.UpperTol.setObjectName(u"UpperTol")
        self.UpperTol.setGeometry(QRect(11, 132, 129, 28))
        sizePolicy1.setHeightForWidth(self.UpperTol.sizePolicy().hasHeightForWidth())
        self.UpperTol.setSizePolicy(sizePolicy1)
        self.UpperTol.setMinimumSize(QSize(0, 28))
        self.UpperTol.setMaximumSize(QSize(16777215, 28))
        self.UpperTol.setFont(font1)
        self.UpperTol.setButtonSymbols(QAbstractSpinBox.UpDownArrows)
        self.UpperTol.setDecimals(5)
        self.UpperTol.setMaximum(1000000000000.000000000000000)
        self.ToleranceVal = QDoubleSpinBox(self.groupBox_8)
        self.ToleranceVal.setObjectName(u"ToleranceVal")
        self.ToleranceVal.setGeometry(QRect(10, 290, 129, 28))
        sizePolicy1.setHeightForWidth(self.ToleranceVal.sizePolicy().hasHeightForWidth())
        self.ToleranceVal.setSizePolicy(sizePolicy1)
        self.ToleranceVal.setMinimumSize(QSize(0, 28))
        self.ToleranceVal.setMaximumSize(QSize(16777215, 28))
        self.ToleranceVal.setFont(font1)
        self.ToleranceVal.setButtonSymbols(QAbstractSpinBox.UpDownArrows)
        self.ToleranceVal.setDecimals(5)
        self.ToleranceVal.setMaximum(1000000000000.000000000000000)
        self.label_2 = QLabel(self.groupBox_8)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 260, 113, 31))
        self.label_2.setFont(font1)
        self.label_5 = QLabel(self.groupBox_8)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(11, 91, 123, 35))
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMaximumSize(QSize(16777215, 35))
        self.label_5.setFont(font1)
        self.LowTol = QDoubleSpinBox(self.groupBox_8)
        self.LowTol.setObjectName(u"LowTol")
        self.LowTol.setGeometry(QRect(11, 212, 129, 28))
        sizePolicy1.setHeightForWidth(self.LowTol.sizePolicy().hasHeightForWidth())
        self.LowTol.setSizePolicy(sizePolicy1)
        self.LowTol.setMinimumSize(QSize(0, 28))
        self.LowTol.setMaximumSize(QSize(16777215, 28))
        self.LowTol.setFont(font1)
        self.LowTol.setButtonSymbols(QAbstractSpinBox.UpDownArrows)
        self.LowTol.setDecimals(5)
        self.LowTol.setMaximum(1000000000000.000000000000000)
        self.label_8 = QLabel(self.groupBox_8)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(160, 98, 121, 31))
        self.label_8.setMaximumSize(QSize(16777215, 35))
        self.label_8.setFont(font1)
        self.widget = QWidget(self.groupBox_8)
        self.widget.setObjectName(u"widget")
        self.widget.setGeometry(QRect(10, 30, 131, 55))
        self.verticalLayout_6 = QVBoxLayout(self.widget)
        self.verticalLayout_6.setObjectName(u"verticalLayout_6")
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.label_4 = QLabel(self.widget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setFont(font1)

        self.verticalLayout_6.addWidget(self.label_4)

        self.MainDim = QDoubleSpinBox(self.widget)
        self.MainDim.setObjectName(u"MainDim")
        sizePolicy1.setHeightForWidth(self.MainDim.sizePolicy().hasHeightForWidth())
        self.MainDim.setSizePolicy(sizePolicy1)
        self.MainDim.setMinimumSize(QSize(0, 28))
        self.MainDim.setMaximumSize(QSize(16777215, 28))
        self.MainDim.setFont(font1)
        self.MainDim.setButtonSymbols(QAbstractSpinBox.UpDownArrows)
        self.MainDim.setDecimals(5)
        self.MainDim.setMaximum(1000000000000.000000000000000)

        self.verticalLayout_6.addWidget(self.MainDim)

        self.widget1 = QWidget(self.groupBox_8)
        self.widget1.setObjectName(u"widget1")
        self.widget1.setGeometry(QRect(160, 30, 131, 55))
        self.verticalLayout_10 = QVBoxLayout(self.widget1)
        self.verticalLayout_10.setObjectName(u"verticalLayout_10")
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.label_9 = QLabel(self.widget1)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setFont(font1)

        self.verticalLayout_10.addWidget(self.label_9)

        self.TolStep = QDoubleSpinBox(self.widget1)
        self.TolStep.setObjectName(u"TolStep")
        sizePolicy1.setHeightForWidth(self.TolStep.sizePolicy().hasHeightForWidth())
        self.TolStep.setSizePolicy(sizePolicy1)
        self.TolStep.setMinimumSize(QSize(0, 28))
        self.TolStep.setMaximumSize(QSize(16777215, 28))
        self.TolStep.setFont(font1)
        self.TolStep.setButtonSymbols(QAbstractSpinBox.UpDownArrows)
        self.TolStep.setDecimals(5)
        self.TolStep.setMaximum(1000000000000.000000000000000)

        self.verticalLayout_10.addWidget(self.TolStep)

        self.label_3 = QLabel(self.groupBox_8)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(161, 251, 149, 35))
        self.label_3.setFont(font1)
        self.PTolVal = QDoubleSpinBox(self.groupBox_8)
        self.PTolVal.setObjectName(u"PTolVal")
        self.PTolVal.setGeometry(QRect(160, 290, 129, 28))
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy2.setHorizontalStretch(250)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.PTolVal.sizePolicy().hasHeightForWidth())
        self.PTolVal.setSizePolicy(sizePolicy2)
        self.PTolVal.setMinimumSize(QSize(0, 28))
        self.PTolVal.setMaximumSize(QSize(129, 28))
        self.PTolVal.setFont(font1)
        self.PTolVal.setButtonSymbols(QAbstractSpinBox.UpDownArrows)
        self.PTolVal.setDecimals(5)
        self.PTolVal.setMaximum(1000000000000.000000000000000)
        self.groupBox_9 = QGroupBox(self.centralwidget)
        self.groupBox_9.setObjectName(u"groupBox_9")
        self.groupBox_9.setGeometry(QRect(330, 10, 191, 331))
        self.groupBox_9.setFont(font1)
        self.verticalLayout_7 = QVBoxLayout(self.groupBox_9)
        self.verticalLayout_7.setObjectName(u"verticalLayout_7")
        self.diaModifier = QCheckBox(self.groupBox_9)
        self.diaModifier.setObjectName(u"diaModifier")
        self.diaModifier.setFont(font1)
        self.diaModifier.setIconSize(QSize(32, 32))

        self.verticalLayout_7.addWidget(self.diaModifier)

        self.label = QLabel(self.groupBox_9)
        self.label.setObjectName(u"label")
        self.label.setFont(font1)

        self.verticalLayout_7.addWidget(self.label)

        self.TolSymbol = QComboBox(self.groupBox_9)
        self.TolSymbol.setObjectName(u"TolSymbol")
        self.TolSymbol.setFont(font2)

        self.verticalLayout_7.addWidget(self.TolSymbol)

        self.groupBox = QGroupBox(self.groupBox_9)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setFont(font1)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.verticalLayout_3 = QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.MMCmod = QRadioButton(self.groupBox)
        self.MMCmod.setObjectName(u"MMCmod")
        font3 = QFont()
        font3.setFamilies([u"AIGDT"])
        self.MMCmod.setFont(font3)

        self.verticalLayout_3.addWidget(self.MMCmod)

        self.LMCmod = QRadioButton(self.groupBox)
        self.LMCmod.setObjectName(u"LMCmod")
        self.LMCmod.setFont(font3)

        self.verticalLayout_3.addWidget(self.LMCmod)

        self.RFSmod = QRadioButton(self.groupBox)
        self.RFSmod.setObjectName(u"RFSmod")
        self.RFSmod.setFont(font3)

        self.verticalLayout_3.addWidget(self.RFSmod)

        self.Nomod = QRadioButton(self.groupBox)
        self.Nomod.setObjectName(u"Nomod")
        font4 = QFont()
        font4.setFamilies([u"MS Shell Dlg 2"])
        self.Nomod.setFont(font4)

        self.verticalLayout_3.addWidget(self.Nomod)


        self.verticalLayout_7.addWidget(self.groupBox)

        self.groupBox_10 = QGroupBox(self.centralwidget)
        self.groupBox_10.setObjectName(u"groupBox_10")
        self.groupBox_10.setGeometry(QRect(530, 10, 221, 331))
        self.groupBox_10.setFont(font1)
        self.verticalLayout_8 = QVBoxLayout(self.groupBox_10)
        self.verticalLayout_8.setObjectName(u"verticalLayout_8")
        self.groupBox_4 = QGroupBox(self.groupBox_10)
        self.groupBox_4.setObjectName(u"groupBox_4")
        sizePolicy3 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Fixed)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy3)
        self.groupBox_4.setMinimumSize(QSize(0, 90))
        self.groupBox_4.setMaximumSize(QSize(16777215, 90))
        self.groupBox_4.setFont(font1)
        self.verticalLayout_2 = QVBoxLayout(self.groupBox_4)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.extnlineperpdatumaxisyes_2 = QRadioButton(self.groupBox_4)
        self.extnlineperpdatumaxisyes_2.setObjectName(u"extnlineperpdatumaxisyes_2")

        self.verticalLayout_2.addWidget(self.extnlineperpdatumaxisyes_2)

        self.InternalFOS = QRadioButton(self.groupBox_4)
        self.InternalFOS.setObjectName(u"InternalFOS")

        self.verticalLayout_2.addWidget(self.InternalFOS)


        self.verticalLayout_8.addWidget(self.groupBox_4)

        self.groupBox_3 = QGroupBox(self.groupBox_10)
        self.groupBox_3.setObjectName(u"groupBox_3")
        sizePolicy3.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy3)
        self.groupBox_3.setMinimumSize(QSize(0, 90))
        self.groupBox_3.setMaximumSize(QSize(16777215, 90))
        self.groupBox_3.setFont(font1)
        self.verticalLayout = QVBoxLayout(self.groupBox_3)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.FCFnexttoDim = QRadioButton(self.groupBox_3)
        self.FCFnexttoDim.setObjectName(u"FCFnexttoDim")

        self.verticalLayout.addWidget(self.FCFnexttoDim)

        self.FCFwextenline = QRadioButton(self.groupBox_3)
        self.FCFwextenline.setObjectName(u"FCFwextenline")

        self.verticalLayout.addWidget(self.FCFwextenline)


        self.verticalLayout_8.addWidget(self.groupBox_3)

        self.extnlineperpdatumaxis = QCheckBox(self.groupBox_10)
        self.extnlineperpdatumaxis.setObjectName(u"extnlineperpdatumaxis")
        self.extnlineperpdatumaxis.setFont(font1)

        self.verticalLayout_8.addWidget(self.extnlineperpdatumaxis)

        MElist.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MElist)
        self.statusbar.setObjectName(u"statusbar")
        MElist.setStatusBar(self.statusbar)
        self.menubar = QMenuBar(MElist)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 873, 21))
        self.menu_File = QMenu(self.menubar)
        self.menu_File.setObjectName(u"menu_File")
        self.menu_Settings = QMenu(self.menu_File)
        self.menu_Settings.setObjectName(u"menu_Settings")
        self.menu_Utilites = QMenu(self.menubar)
        self.menu_Utilites.setObjectName(u"menu_Utilites")
        self.menuTables = QMenu(self.menu_Utilites)
        self.menuTables.setObjectName(u"menuTables")
        self.menu_Help = QMenu(self.menubar)
        self.menu_Help.setObjectName(u"menu_Help")
        self.menuModules_help = QMenu(self.menu_Help)
        self.menuModules_help.setObjectName(u"menuModules_help")
        self.menuGeneral_Analysis_help = QMenu(self.menuModules_help)
        self.menuGeneral_Analysis_help.setObjectName(u"menuGeneral_Analysis_help")
        self.menuBeams_and_Loads_help = QMenu(self.menuModules_help)
        self.menuBeams_and_Loads_help.setObjectName(u"menuBeams_and_Loads_help")
        self.menuGeneral_Beam_Analysis = QMenu(self.menuBeams_and_Loads_help)
        self.menuGeneral_Beam_Analysis.setObjectName(u"menuGeneral_Beam_Analysis")
        self.menuCombined_Loadings_help = QMenu(self.menuBeams_and_Loads_help)
        self.menuCombined_Loadings_help.setObjectName(u"menuCombined_Loadings_help")
        self.menuEccentric_Loadings_help = QMenu(self.menuCombined_Loadings_help)
        self.menuEccentric_Loadings_help.setObjectName(u"menuEccentric_Loadings_help")
        self.menuShear_Force_and_Bending_Moment_help = QMenu(self.menuCombined_Loadings_help)
        self.menuShear_Force_and_Bending_Moment_help.setObjectName(u"menuShear_Force_and_Bending_Moment_help")
        self.menuAxial_Torsional_and_Bending_Stresses_help = QMenu(self.menuCombined_Loadings_help)
        self.menuAxial_Torsional_and_Bending_Stresses_help.setObjectName(u"menuAxial_Torsional_and_Bending_Stresses_help")
        self.menuKinematics_help = QMenu(self.menuModules_help)
        self.menuKinematics_help.setObjectName(u"menuKinematics_help")
        self.menuEngineering_and_Drafting_help = QMenu(self.menuModules_help)
        self.menuEngineering_and_Drafting_help.setObjectName(u"menuEngineering_and_Drafting_help")
        self.menuAdditional_Calculators_help = QMenu(self.menuModules_help)
        self.menuAdditional_Calculators_help.setObjectName(u"menuAdditional_Calculators_help")
        self.menu_Modules = QMenu(self.menubar)
        self.menu_Modules.setObjectName(u"menu_Modules")
        self.menu_General_Analysis = QMenu(self.menu_Modules)
        self.menu_General_Analysis.setObjectName(u"menu_General_Analysis")
        self.menu_Beams_and_Loads = QMenu(self.menu_Modules)
        self.menu_Beams_and_Loads.setObjectName(u"menu_Beams_and_Loads")
        self.menu_Generic_Beam_Analysis = QMenu(self.menu_Beams_and_Loads)
        self.menu_Generic_Beam_Analysis.setObjectName(u"menu_Generic_Beam_Analysis")
        self.menuCombined_Loadings = QMenu(self.menu_Beams_and_Loads)
        self.menuCombined_Loadings.setObjectName(u"menuCombined_Loadings")
        self.menuEccentric_Loadings = QMenu(self.menuCombined_Loadings)
        self.menuEccentric_Loadings.setObjectName(u"menuEccentric_Loadings")
        self.menuShear_Force_and_Bending_Moment = QMenu(self.menuCombined_Loadings)
        self.menuShear_Force_and_Bending_Moment.setObjectName(u"menuShear_Force_and_Bending_Moment")
        self.menuAxial_Torsional_and_Bending_Stresses = QMenu(self.menuCombined_Loadings)
        self.menuAxial_Torsional_and_Bending_Stresses.setObjectName(u"menuAxial_Torsional_and_Bending_Stresses")
        self.menu_Kinematics = QMenu(self.menu_Modules)
        self.menu_Kinematics.setObjectName(u"menu_Kinematics")
        self.menu_Egineering_and_Drafting = QMenu(self.menu_Modules)
        self.menu_Egineering_and_Drafting.setObjectName(u"menu_Egineering_and_Drafting")
        self.menu_Additional_Calculators = QMenu(self.menu_Modules)
        self.menu_Additional_Calculators.setObjectName(u"menu_Additional_Calculators")
        MElist.setMenuBar(self.menubar)

        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Modules.menuAction())
        self.menubar.addAction(self.menu_Utilites.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())
        self.menu_File.addAction(self.menu_Settings.menuAction())
        self.menu_File.addAction(self.actionQuit)
        self.menu_Settings.addAction(self.actionTheme)
        self.menu_Utilites.addAction(self.actionNotepad)
        self.menu_Utilites.addAction(self.actionCalculator)
        self.menu_Utilites.addAction(self.actionScreenshot)
        self.menu_Utilites.addAction(self.menuTables.menuAction())
        self.menuTables.addAction(self.actionMaterials_list)
        self.menuTables.addAction(self.actionCross_Sectional_Beams_and_Shapes_Lists)
        self.menuTables.addAction(self.actionSaftey_Factors)
        self.menuTables.addAction(self.actionFit_Classes)
        self.menu_Help.addAction(self.menuModules_help.menuAction())
        self.menu_Help.addAction(self.actionAbout)
        self.menuModules_help.addAction(self.menuGeneral_Analysis_help.menuAction())
        self.menuModules_help.addAction(self.menuBeams_and_Loads_help.menuAction())
        self.menuModules_help.addAction(self.menuKinematics_help.menuAction())
        self.menuModules_help.addAction(self.menuEngineering_and_Drafting_help.menuAction())
        self.menuModules_help.addAction(self.menuAdditional_Calculators_help.menuAction())
        self.menuGeneral_Analysis_help.addAction(self.actionUnit_Converter_help)
        self.menuGeneral_Analysis_help.addAction(self.actionMoments_of_Inertia_help)
        self.menuGeneral_Analysis_help.addAction(self.actionVectors_help)
        self.menuGeneral_Analysis_help.addAction(self.actionFriction_and_Force_help)
        self.menuGeneral_Analysis_help.addAction(self.actionFasteners_help)
        self.menuGeneral_Analysis_help.addAction(self.actionMaterial_Properties_help)
        self.menuGeneral_Analysis_help.addAction(self.actionCM_and_CG_help)
        self.menuBeams_and_Loads_help.addAction(self.menuGeneral_Beam_Analysis.menuAction())
        self.menuBeams_and_Loads_help.addAction(self.menuCombined_Loadings_help.menuAction())
        self.menuGeneral_Beam_Analysis.addAction(self.actionTrusses_help)
        self.menuGeneral_Beam_Analysis.addAction(self.actionBeamsMoments_of_Inertia_help)
        self.menuGeneral_Beam_Analysis.addAction(self.actionShear_and_Moment_help)
        self.menuGeneral_Beam_Analysis.addAction(self.actionIndeterminate_Axial_Structures_help)
        self.menuGeneral_Beam_Analysis.addAction(self.actionFlexure_help)
        self.menuGeneral_Beam_Analysis.addAction(self.actionBeam_Deformation_help)
        self.menuGeneral_Beam_Analysis.addAction(self.actionAxial_Beam_Deformation_help)
        self.menuGeneral_Beam_Analysis.addAction(self.actionTorsional_Beam_Deformation_help)
        self.menuGeneral_Beam_Analysis.addAction(self.actionSupported_Beams_help)
        self.menuGeneral_Beam_Analysis.addAction(self.actionMohr_s_Circle_help)
        self.menuCombined_Loadings_help.addAction(self.menuEccentric_Loadings_help.menuAction())
        self.menuCombined_Loadings_help.addAction(self.menuShear_Force_and_Bending_Moment_help.menuAction())
        self.menuCombined_Loadings_help.addAction(self.menuAxial_Torsional_and_Bending_Stresses_help.menuAction())
        self.menuEccentric_Loadings_help.addAction(self.actionC_Clamp_help)
        self.menuEccentric_Loadings_help.addAction(self.actionCompression_Link_help)
        self.menuEccentric_Loadings_help.addAction(self.actionTension_Link_help)
        self.menuEccentric_Loadings_help.addAction(self.actionPost_help)
        self.menuShear_Force_and_Bending_Moment_help.addAction(self.actionPost_and_Beam_help)
        self.menuAxial_Torsional_and_Bending_Stresses_help.addAction(self.actionSolid_shaft_and_Pipe_help)
        self.menuKinematics_help.addAction(self.actionKinematic_Diagraming_help)
        self.menuKinematics_help.addAction(self.actionVector_and_Motion_Analysis_help)
        self.menuEngineering_and_Drafting_help.addAction(self.actionGDT_Checker_help)
        self.menuEngineering_and_Drafting_help.addAction(self.actionVirtual_Condition_Calculator_help)
        self.menuEngineering_and_Drafting_help.addAction(self.actionLimits_and_Fits_help)
        self.menuEngineering_and_Drafting_help.addAction(self.actionGDTFasteners_help)
        self.menuEngineering_and_Drafting_help.addAction(self.actionPaper_Gauging_help)
        self.menuEngineering_and_Drafting_help.addAction(self.actionTolerance_Finder_help)
        self.menuEngineering_and_Drafting_help.addAction(self.actionDiameter_Deviation_help)
        self.menuAdditional_Calculators_help.addAction(self.actionTorsion_help)
        self.menuAdditional_Calculators_help.addAction(self.actionPressure_help)
        self.menuAdditional_Calculators_help.addAction(self.actionMohr_s_Circle_2)
        self.menu_Modules.addAction(self.menu_General_Analysis.menuAction())
        self.menu_Modules.addAction(self.menu_Beams_and_Loads.menuAction())
        self.menu_Modules.addAction(self.menu_Kinematics.menuAction())
        self.menu_Modules.addAction(self.menu_Egineering_and_Drafting.menuAction())
        self.menu_Modules.addAction(self.menu_Additional_Calculators.menuAction())
        self.menu_General_Analysis.addAction(self.actionUnit_Converter)
        self.menu_General_Analysis.addAction(self.actionMoments_of_Inertia)
        self.menu_General_Analysis.addAction(self.actionVectors)
        self.menu_General_Analysis.addAction(self.actionFriction_and_Force)
        self.menu_General_Analysis.addAction(self.actionFasteners)
        self.menu_General_Analysis.addAction(self.actionMaterial_Properties)
        self.menu_General_Analysis.addAction(self.actionCM_and_CG)
        self.menu_Beams_and_Loads.addAction(self.menu_Generic_Beam_Analysis.menuAction())
        self.menu_Beams_and_Loads.addAction(self.menuCombined_Loadings.menuAction())
        self.menu_Generic_Beam_Analysis.addAction(self.actionTrusses)
        self.menu_Generic_Beam_Analysis.addAction(self.actionBeamsMoments_of_Inertia)
        self.menu_Generic_Beam_Analysis.addAction(self.actionShear_and_Moment)
        self.menu_Generic_Beam_Analysis.addAction(self.actionIndeterminate_Axial_Structures)
        self.menu_Generic_Beam_Analysis.addAction(self.actionFlexure)
        self.menu_Generic_Beam_Analysis.addAction(self.actionBeam_Deformation)
        self.menu_Generic_Beam_Analysis.addAction(self.actionAxial_Beam_Deformation)
        self.menu_Generic_Beam_Analysis.addAction(self.actionTorsional_Beam_Deformation)
        self.menu_Generic_Beam_Analysis.addAction(self.actionSupported_Beams)
        self.menu_Generic_Beam_Analysis.addAction(self.actionMohr_s_Circle)
        self.menuCombined_Loadings.addAction(self.menuEccentric_Loadings.menuAction())
        self.menuCombined_Loadings.addAction(self.menuShear_Force_and_Bending_Moment.menuAction())
        self.menuCombined_Loadings.addAction(self.menuAxial_Torsional_and_Bending_Stresses.menuAction())
        self.menuEccentric_Loadings.addAction(self.actionC_Clamp)
        self.menuEccentric_Loadings.addAction(self.actionCompression_Link)
        self.menuEccentric_Loadings.addAction(self.actionTension_Link)
        self.menuEccentric_Loadings.addAction(self.actionPost)
        self.menuShear_Force_and_Bending_Moment.addAction(self.actionPost_and_Beam)
        self.menuAxial_Torsional_and_Bending_Stresses.addAction(self.actionSolid_Shaft_and_Pipe)
        self.menu_Kinematics.addAction(self.actionKinematic_Diagraming)
        self.menu_Kinematics.addAction(self.actionVector_Analysis)
        self.menu_Egineering_and_Drafting.addAction(self.actionGDT_Checker)
        self.menu_Egineering_and_Drafting.addAction(self.actionVirtual_Condition_Calculator)
        self.menu_Egineering_and_Drafting.addAction(self.actionLimits_and_Fits)
        self.menu_Egineering_and_Drafting.addAction(self.actionGDTFasteners)
        self.menu_Egineering_and_Drafting.addAction(self.actionPaper_Gauging)
        self.menu_Egineering_and_Drafting.addAction(self.actionTolerance_Finder)
        self.menu_Egineering_and_Drafting.addAction(self.actionDiameter_Deviation)
        self.menu_Additional_Calculators.addAction(self.actionTorsion)
        self.menu_Additional_Calculators.addAction(self.actionPressure)
        self.menu_Additional_Calculators.addAction(self.actionAddMohr_s_Circle)

        self.retranslateUi(MElist)

        QMetaObject.connectSlotsByName(MElist)
    # setupUi

    def retranslateUi(self, MElist):
        MElist.setWindowTitle(QCoreApplication.translate("MElist", u"MainWindow", None))
        self.actionUnit_Converter.setText(QCoreApplication.translate("MElist", u"Unit Converter", None))
        self.actionMoments_of_Inertia.setText(QCoreApplication.translate("MElist", u"Moments of Inertia", None))
        self.actionVectors.setText(QCoreApplication.translate("MElist", u"Vectors", None))
        self.actionFriction_and_Force.setText(QCoreApplication.translate("MElist", u"Friction and Force", None))
        self.actionFasteners.setText(QCoreApplication.translate("MElist", u"Fasteners", None))
        self.actionMaterial_Properties.setText(QCoreApplication.translate("MElist", u"Material Properties", None))
        self.actionCM_and_CG.setText(QCoreApplication.translate("MElist", u"CM and CG", None))
        self.actionTrusses.setText(QCoreApplication.translate("MElist", u"Trusses", None))
        self.actionBeamsMoments_of_Inertia.setText(QCoreApplication.translate("MElist", u"Moments of Inertia", None))
        self.actionShear_and_Moment.setText(QCoreApplication.translate("MElist", u"Shear and Moment", None))
        self.actionIndeterminate_Axial_Structures.setText(QCoreApplication.translate("MElist", u"Indeterminate Axial Structures", None))
        self.actionFlexure.setText(QCoreApplication.translate("MElist", u"Flexure", None))
        self.actionBeam_Deformation.setText(QCoreApplication.translate("MElist", u"Beam Deformation", None))
        self.actionAxial_Beam_Deformation.setText(QCoreApplication.translate("MElist", u"Axial Beam Deformation", None))
        self.actionTorsional_Beam_Deformation.setText(QCoreApplication.translate("MElist", u"Torsional Beam Deformation", None))
        self.actionSupported_Beams.setText(QCoreApplication.translate("MElist", u"Supported Beams", None))
        self.actionMohr_s_Circle.setText(QCoreApplication.translate("MElist", u"Mohr's Circle", None))
        self.actionC_Clamp.setText(QCoreApplication.translate("MElist", u"C-Clamp", None))
        self.actionCompression_Link.setText(QCoreApplication.translate("MElist", u"Compression Link", None))
        self.actionTension_Link.setText(QCoreApplication.translate("MElist", u"Tension Link", None))
        self.actionPost.setText(QCoreApplication.translate("MElist", u"Post", None))
        self.actionPost_and_Beam.setText(QCoreApplication.translate("MElist", u"Post and Beam", None))
        self.actionKinematic_Diagraming.setText(QCoreApplication.translate("MElist", u"Kinematic Diagraming", None))
        self.actionVector_Analysis.setText(QCoreApplication.translate("MElist", u"Vector Analysis", None))
        self.actionGDT_Checker.setText(QCoreApplication.translate("MElist", u"GDT Checker", None))
        self.actionVirtual_Condition_Calculator.setText(QCoreApplication.translate("MElist", u"Virtual Condition Calculator", None))
        self.actionLimits_and_Fits.setText(QCoreApplication.translate("MElist", u"Limits and Fits", None))
        self.actionGDTFasteners.setText(QCoreApplication.translate("MElist", u"Fasteners", None))
        self.actionPaper_Gauging.setText(QCoreApplication.translate("MElist", u"Paper Gauging", None))
        self.actionTolerance_Finder.setText(QCoreApplication.translate("MElist", u"Tolerance Finder", None))
        self.actionDiameter_Deviation.setText(QCoreApplication.translate("MElist", u"Diameter Deviation", None))
        self.actionTorsion.setText(QCoreApplication.translate("MElist", u"Torsion", None))
        self.actionPressure.setText(QCoreApplication.translate("MElist", u"Pressure", None))
        self.actionAddMohr_s_Circle.setText(QCoreApplication.translate("MElist", u"Mohr's Circle", None))
        self.actionModule_List.setText(QCoreApplication.translate("MElist", u"Module List", None))
        self.actionQuit.setText(QCoreApplication.translate("MElist", u"Quit", None))
        self.actionNotepad.setText(QCoreApplication.translate("MElist", u"Notepad", None))
        self.actionCalculator.setText(QCoreApplication.translate("MElist", u"Calculator", None))
        self.actionScreenshot.setText(QCoreApplication.translate("MElist", u"Screenshot", None))
        self.actionPerfer_SI_units.setText(QCoreApplication.translate("MElist", u"Edit Saftey Factor", None))
        self.actionPerfer_Metric_Units.setText(QCoreApplication.translate("MElist", u"Theme", None))
        self.actionMaterials_list.setText(QCoreApplication.translate("MElist", u"Materials List", None))
        self.actionCross_Sectional_Beams_and_Shapes_Lists.setText(QCoreApplication.translate("MElist", u"Beams and Shapes Lists", None))
        self.actionAbout.setText(QCoreApplication.translate("MElist", u"About", None))
        self.actionUnit_Converter_help.setText(QCoreApplication.translate("MElist", u"Unit Converter", None))
        self.actionMoments_of_Inertia_help.setText(QCoreApplication.translate("MElist", u"Moments of Inertia", None))
        self.actionVectors_help.setText(QCoreApplication.translate("MElist", u"Vectors", None))
        self.actionFriction_and_Force_help.setText(QCoreApplication.translate("MElist", u"Friction and Force", None))
        self.actionFasteners_help.setText(QCoreApplication.translate("MElist", u"Fasteners", None))
        self.actionMaterial_Properties_help.setText(QCoreApplication.translate("MElist", u"Material Properties", None))
        self.actionCM_and_CG_help.setText(QCoreApplication.translate("MElist", u"CM and CG", None))
        self.actionTrusses_help.setText(QCoreApplication.translate("MElist", u"Trusses", None))
        self.actionBeamsMoments_of_Inertia_help.setText(QCoreApplication.translate("MElist", u"Moments of Inertia", None))
        self.actionShear_and_Moment_help.setText(QCoreApplication.translate("MElist", u"Shear and Moment", None))
        self.actionIndeterminate_Axial_Structures_help.setText(QCoreApplication.translate("MElist", u"Indeterminate Axial Structures", None))
        self.actionFlexure_help.setText(QCoreApplication.translate("MElist", u"Flexure", None))
        self.actionBeam_Deformation_help.setText(QCoreApplication.translate("MElist", u"Beam Deformation", None))
        self.actionAxial_Beam_Deformation_help.setText(QCoreApplication.translate("MElist", u"Axial Beam Deformation", None))
        self.actionTorsional_Beam_Deformation_help.setText(QCoreApplication.translate("MElist", u"Torsional Beam Deformation", None))
        self.actionSupported_Beams_help.setText(QCoreApplication.translate("MElist", u"Supported Beams", None))
        self.actionMohr_s_Circle_help.setText(QCoreApplication.translate("MElist", u"Mohr's Circle", None))
        self.actionC_Clamp_help.setText(QCoreApplication.translate("MElist", u"C-Clamp", None))
        self.actionCompression_Link_help.setText(QCoreApplication.translate("MElist", u"Compression Link", None))
        self.actionTension_Link_help.setText(QCoreApplication.translate("MElist", u"Tension Link", None))
        self.actionPost_help.setText(QCoreApplication.translate("MElist", u"Post", None))
        self.actionPost_and_Beam_help.setText(QCoreApplication.translate("MElist", u"Post and Beam", None))
        self.actionSolid_shaft_and_Pipe_help.setText(QCoreApplication.translate("MElist", u"Solid Shaft and Pipe", None))
        self.actionKinematic_Diagraming_help.setText(QCoreApplication.translate("MElist", u"Kinematic Diagraming", None))
        self.actionVector_and_Motion_Analysis_help.setText(QCoreApplication.translate("MElist", u"Vector and Motion Analysis", None))
        self.actionGDT_Checker_help.setText(QCoreApplication.translate("MElist", u"GDT Checker", None))
        self.actionVirtual_Condition_Calculator_help.setText(QCoreApplication.translate("MElist", u"Virtual Condition Calculator", None))
        self.actionLimits_and_Fits_help.setText(QCoreApplication.translate("MElist", u"Limits and Fits", None))
        self.actionGDTFasteners_help.setText(QCoreApplication.translate("MElist", u"Fasteners", None))
        self.actionPaper_Gauging_help.setText(QCoreApplication.translate("MElist", u"Paper Gauging", None))
        self.actionTolerance_Finder_help.setText(QCoreApplication.translate("MElist", u"Tolerance Finder", None))
        self.actionDiameter_Deviation_help.setText(QCoreApplication.translate("MElist", u"Diameter Deviation", None))
        self.actionTorsion_help.setText(QCoreApplication.translate("MElist", u"Torsion", None))
        self.actionPressure_help.setText(QCoreApplication.translate("MElist", u"Pressure", None))
        self.actionTheme.setText(QCoreApplication.translate("MElist", u"Theme", None))
        self.actionSaftey_Factors.setText(QCoreApplication.translate("MElist", u"Saftey Factors", None))
        self.actionSolid_Shaft_and_Pipe.setText(QCoreApplication.translate("MElist", u"Solid Shaft and Pipe", None))
        self.actionMohr_s_Circle_2.setText(QCoreApplication.translate("MElist", u"Mohr's Circle", None))
        self.actionFit_Classes.setText(QCoreApplication.translate("MElist", u"Fit Classes", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MElist", u"Datum Specification", None))
        self.label_13.setText(QCoreApplication.translate("MElist", u"Primary Datum", None))
        self.label_14.setText(QCoreApplication.translate("MElist", u"Secondary Datum", None))
        self.label_15.setText(QCoreApplication.translate("MElist", u"Tertiary Datum", None))
        self.label_10.setText(QCoreApplication.translate("MElist", u"Datum Modifier", None))
        self.label_11.setText(QCoreApplication.translate("MElist", u"Datum Modifier", None))
        self.label_12.setText(QCoreApplication.translate("MElist", u"Datum Modifier", None))
        self.groupBox_5.setTitle(QCoreApplication.translate("MElist", u"Primary Degrees of Freedom", None))
        self.checkBox.setText(QCoreApplication.translate("MElist", u"X", None))
        self.checkBox_3.setText(QCoreApplication.translate("MElist", u"Y", None))
        self.checkBox_2.setText(QCoreApplication.translate("MElist", u"Z", None))
        self.checkBox_4.setText(QCoreApplication.translate("MElist", u"U", None))
        self.checkBox_6.setText(QCoreApplication.translate("MElist", u"V", None))
        self.checkBox_5.setText(QCoreApplication.translate("MElist", u"W", None))
        self.groupBox_6.setTitle(QCoreApplication.translate("MElist", u"Secondary Degrees of Freedom", None))
        self.checkBox_7.setText(QCoreApplication.translate("MElist", u"X", None))
        self.checkBox_8.setText(QCoreApplication.translate("MElist", u"Y", None))
        self.checkBox_9.setText(QCoreApplication.translate("MElist", u"Z", None))
        self.checkBox_10.setText(QCoreApplication.translate("MElist", u"U", None))
        self.checkBox_11.setText(QCoreApplication.translate("MElist", u"V", None))
        self.checkBox_12.setText(QCoreApplication.translate("MElist", u"W", None))
        self.groupBox_7.setTitle(QCoreApplication.translate("MElist", u"Tertiary Degrees of Freedom", None))
        self.checkBox_13.setText(QCoreApplication.translate("MElist", u"X", None))
        self.checkBox_14.setText(QCoreApplication.translate("MElist", u"Y", None))
        self.checkBox_15.setText(QCoreApplication.translate("MElist", u"Z", None))
        self.checkBox_16.setText(QCoreApplication.translate("MElist", u"U", None))
        self.checkBox_17.setText(QCoreApplication.translate("MElist", u"V", None))
        self.checkBox_18.setText(QCoreApplication.translate("MElist", u"W", None))
        self.groupBox_8.setTitle(QCoreApplication.translate("MElist", u"GDT Dimension and Tolerance Setup", None))
        self.label_6.setText(QCoreApplication.translate("MElist", u"Lower Dimension\n"
"Tolerance", None))
        self.label_7.setText(QCoreApplication.translate("MElist", u"Lower Dimension", None))
        self.label_2.setText(QCoreApplication.translate("MElist", u"Tolerance Value", None))
        self.label_5.setText(QCoreApplication.translate("MElist", u"Upper Dimension\n"
"Tolerance", None))
        self.label_8.setText(QCoreApplication.translate("MElist", u"Upper Dimension", None))
        self.label_4.setText(QCoreApplication.translate("MElist", u"Main Dimension", None))
        self.label_9.setText(QCoreApplication.translate("MElist", u"Tolerance Step", None))
        self.label_3.setText(QCoreApplication.translate("MElist", u"Projected Tolerance\n"
"Value", None))
        self.groupBox_9.setTitle(QCoreApplication.translate("MElist", u"GD&T Modifier Setup", None))
        self.diaModifier.setText(QCoreApplication.translate("MElist", u"Diameter Modifier\n"
"Used", None))
        self.label.setText(QCoreApplication.translate("MElist", u"Tolerance Symbol", None))
        self.groupBox.setTitle(QCoreApplication.translate("MElist", u"Tolerance Modifier", None))
        self.MMCmod.setText(QCoreApplication.translate("MElist", u"MMC m", None))
        self.LMCmod.setText(QCoreApplication.translate("MElist", u"LMC l", None))
        self.RFSmod.setText(QCoreApplication.translate("MElist", u"RFS", None))
        self.Nomod.setText(QCoreApplication.translate("MElist", u"None", None))
        self.groupBox_10.setTitle(QCoreApplication.translate("MElist", u"Feature Control Frame Setup", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("MElist", u"Feature Type", None))
        self.extnlineperpdatumaxisyes_2.setText(QCoreApplication.translate("MElist", u"External", None))
        self.InternalFOS.setText(QCoreApplication.translate("MElist", u"Internal", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("MElist", u"FCF Location", None))
        self.FCFnexttoDim.setText(QCoreApplication.translate("MElist", u"Next to Dimension", None))
        self.FCFwextenline.setText(QCoreApplication.translate("MElist", u"With Extension Line", None))
        self.extnlineperpdatumaxis.setText(QCoreApplication.translate("MElist", u"Extension Line\n"
"Perpendicular\n"
"to Datum Axis", None))
        self.menu_File.setTitle(QCoreApplication.translate("MElist", u"&File", None))
        self.menu_Settings.setTitle(QCoreApplication.translate("MElist", u"Settings", None))
        self.menu_Utilites.setTitle(QCoreApplication.translate("MElist", u"&Utilites", None))
        self.menuTables.setTitle(QCoreApplication.translate("MElist", u"Tables", None))
        self.menu_Help.setTitle(QCoreApplication.translate("MElist", u"&Help", None))
        self.menuModules_help.setTitle(QCoreApplication.translate("MElist", u"Modules", None))
        self.menuGeneral_Analysis_help.setTitle(QCoreApplication.translate("MElist", u"General Analysis", None))
        self.menuBeams_and_Loads_help.setTitle(QCoreApplication.translate("MElist", u"Beams and Loads", None))
        self.menuGeneral_Beam_Analysis.setTitle(QCoreApplication.translate("MElist", u"General Beam Analysis", None))
        self.menuCombined_Loadings_help.setTitle(QCoreApplication.translate("MElist", u"Combined Loadings", None))
        self.menuEccentric_Loadings_help.setTitle(QCoreApplication.translate("MElist", u"Eccentric Loadings", None))
        self.menuShear_Force_and_Bending_Moment_help.setTitle(QCoreApplication.translate("MElist", u"Shear Force and Bending Moment", None))
        self.menuAxial_Torsional_and_Bending_Stresses_help.setTitle(QCoreApplication.translate("MElist", u"Axial, Torsional, and Bending Stresses", None))
        self.menuKinematics_help.setTitle(QCoreApplication.translate("MElist", u"Kinematics", None))
        self.menuEngineering_and_Drafting_help.setTitle(QCoreApplication.translate("MElist", u"Engineering and Drafting", None))
        self.menuAdditional_Calculators_help.setTitle(QCoreApplication.translate("MElist", u"Additional Calculators", None))
        self.menu_Modules.setTitle(QCoreApplication.translate("MElist", u"&Modules", None))
        self.menu_General_Analysis.setTitle(QCoreApplication.translate("MElist", u"General Analysis", None))
        self.menu_Beams_and_Loads.setTitle(QCoreApplication.translate("MElist", u"Beams and Loads", None))
        self.menu_Generic_Beam_Analysis.setTitle(QCoreApplication.translate("MElist", u"Generic Beam Analysis", None))
        self.menuCombined_Loadings.setTitle(QCoreApplication.translate("MElist", u"Combined Loadings", None))
        self.menuEccentric_Loadings.setTitle(QCoreApplication.translate("MElist", u"Eccentric Loadings", None))
        self.menuShear_Force_and_Bending_Moment.setTitle(QCoreApplication.translate("MElist", u"Shear Force and Bending Moment", None))
        self.menuAxial_Torsional_and_Bending_Stresses.setTitle(QCoreApplication.translate("MElist", u"Axial, Torsional, and Bending Stresses", None))
        self.menu_Kinematics.setTitle(QCoreApplication.translate("MElist", u"Kinematics", None))
        self.menu_Egineering_and_Drafting.setTitle(QCoreApplication.translate("MElist", u"Egineering and Drafting", None))
        self.menu_Additional_Calculators.setTitle(QCoreApplication.translate("MElist", u"Additional Calculators", None))
    # retranslateUi

