# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'concenmoments.ui'
##
## Created by: Qt User Interface Compiler version 6.8.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QAbstractSpinBox, QApplication, QComboBox, QDoubleSpinBox,
    QGroupBox, QHBoxLayout, QLabel, QMainWindow,
    QMenu, QMenuBar, QSizePolicy, QStatusBar,
    QTabWidget, QVBoxLayout, QWidget)

class Ui_MElist(object):
    def setupUi(self, MElist):
        if not MElist.objectName():
            MElist.setObjectName(u"MElist")
        MElist.resize(963, 915)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MElist.sizePolicy().hasHeightForWidth())
        MElist.setSizePolicy(sizePolicy)
        MElist.setMinimumSize(QSize(270, 610))
        MElist.setMaximumSize(QSize(16777215, 16777215))
        MElist.setFocusPolicy(Qt.FocusPolicy.WheelFocus)
        MElist.setTabShape(QTabWidget.TabShape.Rounded)
        MElist.setDockNestingEnabled(False)
        MElist.setUnifiedTitleAndToolBarOnMac(False)
        self.actionUnit_Converter = QAction(MElist)
        self.actionUnit_Converter.setObjectName(u"actionUnit_Converter")
        self.actionMoments_of_Inertia = QAction(MElist)
        self.actionMoments_of_Inertia.setObjectName(u"actionMoments_of_Inertia")
        self.actionVectors = QAction(MElist)
        self.actionVectors.setObjectName(u"actionVectors")
        self.actionFriction_and_Force = QAction(MElist)
        self.actionFriction_and_Force.setObjectName(u"actionFriction_and_Force")
        self.actionFasteners = QAction(MElist)
        self.actionFasteners.setObjectName(u"actionFasteners")
        self.actionMaterial_Properties = QAction(MElist)
        self.actionMaterial_Properties.setObjectName(u"actionMaterial_Properties")
        self.actionCM_and_CG = QAction(MElist)
        self.actionCM_and_CG.setObjectName(u"actionCM_and_CG")
        self.actionTrusses = QAction(MElist)
        self.actionTrusses.setObjectName(u"actionTrusses")
        self.actionBeamsMoments_of_Inertia = QAction(MElist)
        self.actionBeamsMoments_of_Inertia.setObjectName(u"actionBeamsMoments_of_Inertia")
        self.actionShear_and_Moment = QAction(MElist)
        self.actionShear_and_Moment.setObjectName(u"actionShear_and_Moment")
        self.actionIndeterminate_Axial_Structures = QAction(MElist)
        self.actionIndeterminate_Axial_Structures.setObjectName(u"actionIndeterminate_Axial_Structures")
        self.actionFlexure = QAction(MElist)
        self.actionFlexure.setObjectName(u"actionFlexure")
        self.actionBeam_Deformation = QAction(MElist)
        self.actionBeam_Deformation.setObjectName(u"actionBeam_Deformation")
        self.actionAxial_Beam_Deformation = QAction(MElist)
        self.actionAxial_Beam_Deformation.setObjectName(u"actionAxial_Beam_Deformation")
        self.actionTorsional_Beam_Deformation = QAction(MElist)
        self.actionTorsional_Beam_Deformation.setObjectName(u"actionTorsional_Beam_Deformation")
        self.actionSupported_Beams = QAction(MElist)
        self.actionSupported_Beams.setObjectName(u"actionSupported_Beams")
        self.actionMohr_s_Circle = QAction(MElist)
        self.actionMohr_s_Circle.setObjectName(u"actionMohr_s_Circle")
        self.actionC_Clamp = QAction(MElist)
        self.actionC_Clamp.setObjectName(u"actionC_Clamp")
        self.actionCompression_Link = QAction(MElist)
        self.actionCompression_Link.setObjectName(u"actionCompression_Link")
        self.actionTension_Link = QAction(MElist)
        self.actionTension_Link.setObjectName(u"actionTension_Link")
        self.actionPost = QAction(MElist)
        self.actionPost.setObjectName(u"actionPost")
        self.actionPost_and_Beam = QAction(MElist)
        self.actionPost_and_Beam.setObjectName(u"actionPost_and_Beam")
        self.actionKinematic_Diagraming = QAction(MElist)
        self.actionKinematic_Diagraming.setObjectName(u"actionKinematic_Diagraming")
        self.actionVector_Analysis = QAction(MElist)
        self.actionVector_Analysis.setObjectName(u"actionVector_Analysis")
        self.actionGDT_Checker = QAction(MElist)
        self.actionGDT_Checker.setObjectName(u"actionGDT_Checker")
        self.actionVirtual_Condition_Calculator = QAction(MElist)
        self.actionVirtual_Condition_Calculator.setObjectName(u"actionVirtual_Condition_Calculator")
        self.actionLimits_and_Fits = QAction(MElist)
        self.actionLimits_and_Fits.setObjectName(u"actionLimits_and_Fits")
        self.actionGDTFasteners = QAction(MElist)
        self.actionGDTFasteners.setObjectName(u"actionGDTFasteners")
        self.actionPaper_Gauging = QAction(MElist)
        self.actionPaper_Gauging.setObjectName(u"actionPaper_Gauging")
        self.actionTolerance_Finder = QAction(MElist)
        self.actionTolerance_Finder.setObjectName(u"actionTolerance_Finder")
        self.actionDiameter_Deviation = QAction(MElist)
        self.actionDiameter_Deviation.setObjectName(u"actionDiameter_Deviation")
        self.actionTorsion = QAction(MElist)
        self.actionTorsion.setObjectName(u"actionTorsion")
        self.actionPressure = QAction(MElist)
        self.actionPressure.setObjectName(u"actionPressure")
        self.actionAddMohr_s_Circle = QAction(MElist)
        self.actionAddMohr_s_Circle.setObjectName(u"actionAddMohr_s_Circle")
        self.actionModule_List = QAction(MElist)
        self.actionModule_List.setObjectName(u"actionModule_List")
        self.actionQuit = QAction(MElist)
        self.actionQuit.setObjectName(u"actionQuit")
        self.actionNotepad = QAction(MElist)
        self.actionNotepad.setObjectName(u"actionNotepad")
        self.actionCalculator = QAction(MElist)
        self.actionCalculator.setObjectName(u"actionCalculator")
        self.actionScreenshot = QAction(MElist)
        self.actionScreenshot.setObjectName(u"actionScreenshot")
        self.actionPerfer_SI_units = QAction(MElist)
        self.actionPerfer_SI_units.setObjectName(u"actionPerfer_SI_units")
        self.actionPerfer_Metric_Units = QAction(MElist)
        self.actionPerfer_Metric_Units.setObjectName(u"actionPerfer_Metric_Units")
        self.actionMaterials_list = QAction(MElist)
        self.actionMaterials_list.setObjectName(u"actionMaterials_list")
        self.actionCross_Sectional_Beams_and_Shapes_Lists = QAction(MElist)
        self.actionCross_Sectional_Beams_and_Shapes_Lists.setObjectName(u"actionCross_Sectional_Beams_and_Shapes_Lists")
        self.actionAbout = QAction(MElist)
        self.actionAbout.setObjectName(u"actionAbout")
        self.actionUnit_Converter_help = QAction(MElist)
        self.actionUnit_Converter_help.setObjectName(u"actionUnit_Converter_help")
        self.actionMoments_of_Inertia_help = QAction(MElist)
        self.actionMoments_of_Inertia_help.setObjectName(u"actionMoments_of_Inertia_help")
        self.actionVectors_help = QAction(MElist)
        self.actionVectors_help.setObjectName(u"actionVectors_help")
        self.actionFriction_and_Force_help = QAction(MElist)
        self.actionFriction_and_Force_help.setObjectName(u"actionFriction_and_Force_help")
        self.actionFasteners_help = QAction(MElist)
        self.actionFasteners_help.setObjectName(u"actionFasteners_help")
        self.actionMaterial_Properties_help = QAction(MElist)
        self.actionMaterial_Properties_help.setObjectName(u"actionMaterial_Properties_help")
        self.actionCM_and_CG_help = QAction(MElist)
        self.actionCM_and_CG_help.setObjectName(u"actionCM_and_CG_help")
        self.actionTrusses_help = QAction(MElist)
        self.actionTrusses_help.setObjectName(u"actionTrusses_help")
        self.actionBeamsMoments_of_Inertia_help = QAction(MElist)
        self.actionBeamsMoments_of_Inertia_help.setObjectName(u"actionBeamsMoments_of_Inertia_help")
        self.actionShear_and_Moment_help = QAction(MElist)
        self.actionShear_and_Moment_help.setObjectName(u"actionShear_and_Moment_help")
        self.actionIndeterminate_Axial_Structures_help = QAction(MElist)
        self.actionIndeterminate_Axial_Structures_help.setObjectName(u"actionIndeterminate_Axial_Structures_help")
        self.actionFlexure_help = QAction(MElist)
        self.actionFlexure_help.setObjectName(u"actionFlexure_help")
        self.actionBeam_Deformation_help = QAction(MElist)
        self.actionBeam_Deformation_help.setObjectName(u"actionBeam_Deformation_help")
        self.actionAxial_Beam_Deformation_help = QAction(MElist)
        self.actionAxial_Beam_Deformation_help.setObjectName(u"actionAxial_Beam_Deformation_help")
        self.actionTorsional_Beam_Deformation_help = QAction(MElist)
        self.actionTorsional_Beam_Deformation_help.setObjectName(u"actionTorsional_Beam_Deformation_help")
        self.actionSupported_Beams_help = QAction(MElist)
        self.actionSupported_Beams_help.setObjectName(u"actionSupported_Beams_help")
        self.actionMohr_s_Circle_help = QAction(MElist)
        self.actionMohr_s_Circle_help.setObjectName(u"actionMohr_s_Circle_help")
        self.actionC_Clamp_help = QAction(MElist)
        self.actionC_Clamp_help.setObjectName(u"actionC_Clamp_help")
        self.actionCompression_Link_help = QAction(MElist)
        self.actionCompression_Link_help.setObjectName(u"actionCompression_Link_help")
        self.actionTension_Link_help = QAction(MElist)
        self.actionTension_Link_help.setObjectName(u"actionTension_Link_help")
        self.actionPost_help = QAction(MElist)
        self.actionPost_help.setObjectName(u"actionPost_help")
        self.actionPost_and_Beam_help = QAction(MElist)
        self.actionPost_and_Beam_help.setObjectName(u"actionPost_and_Beam_help")
        self.actionSolid_shaft_and_Pipe_help = QAction(MElist)
        self.actionSolid_shaft_and_Pipe_help.setObjectName(u"actionSolid_shaft_and_Pipe_help")
        self.actionKinematic_Diagraming_help = QAction(MElist)
        self.actionKinematic_Diagraming_help.setObjectName(u"actionKinematic_Diagraming_help")
        self.actionVector_and_Motion_Analysis_help = QAction(MElist)
        self.actionVector_and_Motion_Analysis_help.setObjectName(u"actionVector_and_Motion_Analysis_help")
        self.actionGDT_Checker_help = QAction(MElist)
        self.actionGDT_Checker_help.setObjectName(u"actionGDT_Checker_help")
        self.actionVirtual_Condition_Calculator_help = QAction(MElist)
        self.actionVirtual_Condition_Calculator_help.setObjectName(u"actionVirtual_Condition_Calculator_help")
        self.actionLimits_and_Fits_help = QAction(MElist)
        self.actionLimits_and_Fits_help.setObjectName(u"actionLimits_and_Fits_help")
        self.actionGDTFasteners_help = QAction(MElist)
        self.actionGDTFasteners_help.setObjectName(u"actionGDTFasteners_help")
        self.actionPaper_Gauging_help = QAction(MElist)
        self.actionPaper_Gauging_help.setObjectName(u"actionPaper_Gauging_help")
        self.actionTolerance_Finder_help = QAction(MElist)
        self.actionTolerance_Finder_help.setObjectName(u"actionTolerance_Finder_help")
        self.actionDiameter_Deviation_help = QAction(MElist)
        self.actionDiameter_Deviation_help.setObjectName(u"actionDiameter_Deviation_help")
        self.actionTorsion_help = QAction(MElist)
        self.actionTorsion_help.setObjectName(u"actionTorsion_help")
        self.actionPressure_help = QAction(MElist)
        self.actionPressure_help.setObjectName(u"actionPressure_help")
        self.actionTheme = QAction(MElist)
        self.actionTheme.setObjectName(u"actionTheme")
        self.actionSaftey_Factors = QAction(MElist)
        self.actionSaftey_Factors.setObjectName(u"actionSaftey_Factors")
        self.actionSolid_Shaft_and_Pipe = QAction(MElist)
        self.actionSolid_Shaft_and_Pipe.setObjectName(u"actionSolid_Shaft_and_Pipe")
        self.actionMohr_s_Circle_2 = QAction(MElist)
        self.actionMohr_s_Circle_2.setObjectName(u"actionMohr_s_Circle_2")
        self.actionFit_Classes = QAction(MElist)
        self.actionFit_Classes.setObjectName(u"actionFit_Classes")
        self.centralwidget = QWidget(MElist)
        self.centralwidget.setObjectName(u"centralwidget")
        self.supportlocation = QGroupBox(self.centralwidget)
        self.supportlocation.setObjectName(u"supportlocation")
        self.supportlocation.setGeometry(QRect(30, 130, 281, 111))
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.supportlocation.sizePolicy().hasHeightForWidth())
        self.supportlocation.setSizePolicy(sizePolicy1)
        font = QFont()
        font.setFamilies([u"Arial"])
        font.setPointSize(11)
        self.supportlocation.setFont(font)
        self.layoutWidget = QWidget(self.supportlocation)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(10, 20, 262, 84))
        self.horizontalLayout_4 = QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5 = QVBoxLayout()
        self.verticalLayout_5.setObjectName(u"verticalLayout_5")
        self.label_4 = QLabel(self.layoutWidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.verticalLayout_5.addWidget(self.label_4)

        self.doubleSpinBox = QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBox.setObjectName(u"doubleSpinBox")
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Fixed)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.doubleSpinBox.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox.setSizePolicy(sizePolicy2)
        self.doubleSpinBox.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.doubleSpinBox.setMaximum(100000000.000000000000000)

        self.verticalLayout_5.addWidget(self.doubleSpinBox)


        self.horizontalLayout_4.addLayout(self.verticalLayout_5)

        self.verticalLayout_4 = QVBoxLayout()
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.label_5 = QLabel(self.layoutWidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.verticalLayout_4.addWidget(self.label_5)

        self.doubleSpinBox_2 = QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBox_2.setObjectName(u"doubleSpinBox_2")
        sizePolicy2.setHeightForWidth(self.doubleSpinBox_2.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_2.setSizePolicy(sizePolicy2)
        self.doubleSpinBox_2.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.doubleSpinBox_2.setMaximum(100000000.000000000000000)

        self.verticalLayout_4.addWidget(self.doubleSpinBox_2)


        self.horizontalLayout_4.addLayout(self.verticalLayout_4)

        self.Beamsetuplength = QGroupBox(self.centralwidget)
        self.Beamsetuplength.setObjectName(u"Beamsetuplength")
        self.Beamsetuplength.setGeometry(QRect(30, 20, 281, 91))
        sizePolicy1.setHeightForWidth(self.Beamsetuplength.sizePolicy().hasHeightForWidth())
        self.Beamsetuplength.setSizePolicy(sizePolicy1)
        self.Beamsetuplength.setFont(font)
        self.layoutWidget_2 = QWidget(self.Beamsetuplength)
        self.layoutWidget_2.setObjectName(u"layoutWidget_2")
        self.layoutWidget_2.setGeometry(QRect(10, 20, 261, 68))
        self.horizontalLayout = QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.label_2 = QLabel(self.layoutWidget_2)
        self.label_2.setObjectName(u"label_2")
        sizePolicy3 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy3)
        self.label_2.setMinimumSize(QSize(120, 0))
        self.label_2.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.horizontalLayout.addWidget(self.label_2)

        self.verticalLayout = QVBoxLayout()
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.Beamlength = QDoubleSpinBox(self.layoutWidget_2)
        self.Beamlength.setObjectName(u"Beamlength")
        sizePolicy2.setHeightForWidth(self.Beamlength.sizePolicy().hasHeightForWidth())
        self.Beamlength.setSizePolicy(sizePolicy2)
        self.Beamlength.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.Beamlength.setMaximum(100000000.000000000000000)

        self.verticalLayout.addWidget(self.Beamlength)

        self.beamlengthunits = QComboBox(self.layoutWidget_2)
        self.beamlengthunits.setObjectName(u"beamlengthunits")

        self.verticalLayout.addWidget(self.beamlengthunits)


        self.horizontalLayout.addLayout(self.verticalLayout)

        MElist.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MElist)
        self.statusbar.setObjectName(u"statusbar")
        MElist.setStatusBar(self.statusbar)
        self.menubar = QMenuBar(MElist)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 963, 33))
        self.menu_File = QMenu(self.menubar)
        self.menu_File.setObjectName(u"menu_File")
        self.menu_Settings = QMenu(self.menu_File)
        self.menu_Settings.setObjectName(u"menu_Settings")
        self.menu_Utilites = QMenu(self.menubar)
        self.menu_Utilites.setObjectName(u"menu_Utilites")
        self.menuTables = QMenu(self.menu_Utilites)
        self.menuTables.setObjectName(u"menuTables")
        self.menu_Help = QMenu(self.menubar)
        self.menu_Help.setObjectName(u"menu_Help")
        self.menuModules_help = QMenu(self.menu_Help)
        self.menuModules_help.setObjectName(u"menuModules_help")
        self.menuGeneral_Analysis_help = QMenu(self.menuModules_help)
        self.menuGeneral_Analysis_help.setObjectName(u"menuGeneral_Analysis_help")
        self.menuBeams_and_Loads_help = QMenu(self.menuModules_help)
        self.menuBeams_and_Loads_help.setObjectName(u"menuBeams_and_Loads_help")
        self.menuGeneral_Beam_Analysis = QMenu(self.menuBeams_and_Loads_help)
        self.menuGeneral_Beam_Analysis.setObjectName(u"menuGeneral_Beam_Analysis")
        self.menuCombined_Loadings_help = QMenu(self.menuBeams_and_Loads_help)
        self.menuCombined_Loadings_help.setObjectName(u"menuCombined_Loadings_help")
        self.menuEccentric_Loadings_help = QMenu(self.menuCombined_Loadings_help)
        self.menuEccentric_Loadings_help.setObjectName(u"menuEccentric_Loadings_help")
        self.menuShear_Force_and_Bending_Moment_help = QMenu(self.menuCombined_Loadings_help)
        self.menuShear_Force_and_Bending_Moment_help.setObjectName(u"menuShear_Force_and_Bending_Moment_help")
        self.menuAxial_Torsional_and_Bending_Stresses_help = QMenu(self.menuCombined_Loadings_help)
        self.menuAxial_Torsional_and_Bending_Stresses_help.setObjectName(u"menuAxial_Torsional_and_Bending_Stresses_help")
        self.menuKinematics_help = QMenu(self.menuModules_help)
        self.menuKinematics_help.setObjectName(u"menuKinematics_help")
        self.menuEngineering_and_Drafting_help = QMenu(self.menuModules_help)
        self.menuEngineering_and_Drafting_help.setObjectName(u"menuEngineering_and_Drafting_help")
        self.menuAdditional_Calculators_help = QMenu(self.menuModules_help)
        self.menuAdditional_Calculators_help.setObjectName(u"menuAdditional_Calculators_help")
        self.menu_Modules = QMenu(self.menubar)
        self.menu_Modules.setObjectName(u"menu_Modules")
        self.menu_General_Analysis = QMenu(self.menu_Modules)
        self.menu_General_Analysis.setObjectName(u"menu_General_Analysis")
        self.menu_Beams_and_Loads = QMenu(self.menu_Modules)
        self.menu_Beams_and_Loads.setObjectName(u"menu_Beams_and_Loads")
        self.menu_Generic_Beam_Analysis = QMenu(self.menu_Beams_and_Loads)
        self.menu_Generic_Beam_Analysis.setObjectName(u"menu_Generic_Beam_Analysis")
        self.menuCombined_Loadings = QMenu(self.menu_Beams_and_Loads)
        self.menuCombined_Loadings.setObjectName(u"menuCombined_Loadings")
        self.menuEccentric_Loadings = QMenu(self.menuCombined_Loadings)
        self.menuEccentric_Loadings.setObjectName(u"menuEccentric_Loadings")
        self.menuShear_Force_and_Bending_Moment = QMenu(self.menuCombined_Loadings)
        self.menuShear_Force_and_Bending_Moment.setObjectName(u"menuShear_Force_and_Bending_Moment")
        self.menuAxial_Torsional_and_Bending_Stresses = QMenu(self.menuCombined_Loadings)
        self.menuAxial_Torsional_and_Bending_Stresses.setObjectName(u"menuAxial_Torsional_and_Bending_Stresses")
        self.menu_Kinematics = QMenu(self.menu_Modules)
        self.menu_Kinematics.setObjectName(u"menu_Kinematics")
        self.menu_Egineering_and_Drafting = QMenu(self.menu_Modules)
        self.menu_Egineering_and_Drafting.setObjectName(u"menu_Egineering_and_Drafting")
        self.menu_Additional_Calculators = QMenu(self.menu_Modules)
        self.menu_Additional_Calculators.setObjectName(u"menu_Additional_Calculators")
        MElist.setMenuBar(self.menubar)

        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Modules.menuAction())
        self.menubar.addAction(self.menu_Utilites.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())
        self.menu_File.addAction(self.menu_Settings.menuAction())
        self.menu_File.addAction(self.actionQuit)
        self.menu_Settings.addAction(self.actionTheme)
        self.menu_Utilites.addAction(self.actionNotepad)
        self.menu_Utilites.addAction(self.actionCalculator)
        self.menu_Utilites.addAction(self.actionScreenshot)
        self.menu_Utilites.addAction(self.menuTables.menuAction())
        self.menuTables.addAction(self.actionMaterials_list)
        self.menuTables.addAction(self.actionCross_Sectional_Beams_and_Shapes_Lists)
        self.menuTables.addAction(self.actionSaftey_Factors)
        self.menuTables.addAction(self.actionFit_Classes)
        self.menu_Help.addAction(self.menuModules_help.menuAction())
        self.menu_Help.addAction(self.actionAbout)
        self.menuModules_help.addAction(self.menuGeneral_Analysis_help.menuAction())
        self.menuModules_help.addAction(self.menuBeams_and_Loads_help.menuAction())
        self.menuModules_help.addAction(self.menuKinematics_help.menuAction())
        self.menuModules_help.addAction(self.menuEngineering_and_Drafting_help.menuAction())
        self.menuModules_help.addAction(self.menuAdditional_Calculators_help.menuAction())
        self.menuGeneral_Analysis_help.addAction(self.actionUnit_Converter_help)
        self.menuGeneral_Analysis_help.addAction(self.actionMoments_of_Inertia_help)
        self.menuGeneral_Analysis_help.addAction(self.actionVectors_help)
        self.menuGeneral_Analysis_help.addAction(self.actionFriction_and_Force_help)
        self.menuGeneral_Analysis_help.addAction(self.actionFasteners_help)
        self.menuGeneral_Analysis_help.addAction(self.actionMaterial_Properties_help)
        self.menuGeneral_Analysis_help.addAction(self.actionCM_and_CG_help)
        self.menuBeams_and_Loads_help.addAction(self.menuGeneral_Beam_Analysis.menuAction())
        self.menuBeams_and_Loads_help.addAction(self.menuCombined_Loadings_help.menuAction())
        self.menuGeneral_Beam_Analysis.addAction(self.actionTrusses_help)
        self.menuGeneral_Beam_Analysis.addAction(self.actionBeamsMoments_of_Inertia_help)
        self.menuGeneral_Beam_Analysis.addAction(self.actionShear_and_Moment_help)
        self.menuGeneral_Beam_Analysis.addAction(self.actionIndeterminate_Axial_Structures_help)
        self.menuGeneral_Beam_Analysis.addAction(self.actionFlexure_help)
        self.menuGeneral_Beam_Analysis.addAction(self.actionBeam_Deformation_help)
        self.menuGeneral_Beam_Analysis.addAction(self.actionAxial_Beam_Deformation_help)
        self.menuGeneral_Beam_Analysis.addAction(self.actionTorsional_Beam_Deformation_help)
        self.menuGeneral_Beam_Analysis.addAction(self.actionSupported_Beams_help)
        self.menuGeneral_Beam_Analysis.addAction(self.actionMohr_s_Circle_help)
        self.menuCombined_Loadings_help.addAction(self.menuEccentric_Loadings_help.menuAction())
        self.menuCombined_Loadings_help.addAction(self.menuShear_Force_and_Bending_Moment_help.menuAction())
        self.menuCombined_Loadings_help.addAction(self.menuAxial_Torsional_and_Bending_Stresses_help.menuAction())
        self.menuEccentric_Loadings_help.addAction(self.actionC_Clamp_help)
        self.menuEccentric_Loadings_help.addAction(self.actionCompression_Link_help)
        self.menuEccentric_Loadings_help.addAction(self.actionTension_Link_help)
        self.menuEccentric_Loadings_help.addAction(self.actionPost_help)
        self.menuShear_Force_and_Bending_Moment_help.addAction(self.actionPost_and_Beam_help)
        self.menuAxial_Torsional_and_Bending_Stresses_help.addAction(self.actionSolid_shaft_and_Pipe_help)
        self.menuKinematics_help.addAction(self.actionKinematic_Diagraming_help)
        self.menuKinematics_help.addAction(self.actionVector_and_Motion_Analysis_help)
        self.menuEngineering_and_Drafting_help.addAction(self.actionGDT_Checker_help)
        self.menuEngineering_and_Drafting_help.addAction(self.actionVirtual_Condition_Calculator_help)
        self.menuEngineering_and_Drafting_help.addAction(self.actionLimits_and_Fits_help)
        self.menuEngineering_and_Drafting_help.addAction(self.actionGDTFasteners_help)
        self.menuEngineering_and_Drafting_help.addAction(self.actionPaper_Gauging_help)
        self.menuEngineering_and_Drafting_help.addAction(self.actionTolerance_Finder_help)
        self.menuEngineering_and_Drafting_help.addAction(self.actionDiameter_Deviation_help)
        self.menuAdditional_Calculators_help.addAction(self.actionTorsion_help)
        self.menuAdditional_Calculators_help.addAction(self.actionPressure_help)
        self.menuAdditional_Calculators_help.addAction(self.actionMohr_s_Circle_2)
        self.menu_Modules.addAction(self.menu_General_Analysis.menuAction())
        self.menu_Modules.addAction(self.menu_Beams_and_Loads.menuAction())
        self.menu_Modules.addAction(self.menu_Kinematics.menuAction())
        self.menu_Modules.addAction(self.menu_Egineering_and_Drafting.menuAction())
        self.menu_Modules.addAction(self.menu_Additional_Calculators.menuAction())
        self.menu_General_Analysis.addAction(self.actionUnit_Converter)
        self.menu_General_Analysis.addAction(self.actionMoments_of_Inertia)
        self.menu_General_Analysis.addAction(self.actionVectors)
        self.menu_General_Analysis.addAction(self.actionFriction_and_Force)
        self.menu_General_Analysis.addAction(self.actionFasteners)
        self.menu_General_Analysis.addAction(self.actionMaterial_Properties)
        self.menu_General_Analysis.addAction(self.actionCM_and_CG)
        self.menu_Beams_and_Loads.addAction(self.menu_Generic_Beam_Analysis.menuAction())
        self.menu_Beams_and_Loads.addAction(self.menuCombined_Loadings.menuAction())
        self.menu_Generic_Beam_Analysis.addAction(self.actionTrusses)
        self.menu_Generic_Beam_Analysis.addAction(self.actionBeamsMoments_of_Inertia)
        self.menu_Generic_Beam_Analysis.addAction(self.actionShear_and_Moment)
        self.menu_Generic_Beam_Analysis.addAction(self.actionIndeterminate_Axial_Structures)
        self.menu_Generic_Beam_Analysis.addAction(self.actionFlexure)
        self.menu_Generic_Beam_Analysis.addAction(self.actionBeam_Deformation)
        self.menu_Generic_Beam_Analysis.addAction(self.actionAxial_Beam_Deformation)
        self.menu_Generic_Beam_Analysis.addAction(self.actionTorsional_Beam_Deformation)
        self.menu_Generic_Beam_Analysis.addAction(self.actionSupported_Beams)
        self.menu_Generic_Beam_Analysis.addAction(self.actionMohr_s_Circle)
        self.menuCombined_Loadings.addAction(self.menuEccentric_Loadings.menuAction())
        self.menuCombined_Loadings.addAction(self.menuShear_Force_and_Bending_Moment.menuAction())
        self.menuCombined_Loadings.addAction(self.menuAxial_Torsional_and_Bending_Stresses.menuAction())
        self.menuEccentric_Loadings.addAction(self.actionC_Clamp)
        self.menuEccentric_Loadings.addAction(self.actionCompression_Link)
        self.menuEccentric_Loadings.addAction(self.actionTension_Link)
        self.menuEccentric_Loadings.addAction(self.actionPost)
        self.menuShear_Force_and_Bending_Moment.addAction(self.actionPost_and_Beam)
        self.menuAxial_Torsional_and_Bending_Stresses.addAction(self.actionSolid_Shaft_and_Pipe)
        self.menu_Kinematics.addAction(self.actionKinematic_Diagraming)
        self.menu_Kinematics.addAction(self.actionVector_Analysis)
        self.menu_Egineering_and_Drafting.addAction(self.actionGDT_Checker)
        self.menu_Egineering_and_Drafting.addAction(self.actionVirtual_Condition_Calculator)
        self.menu_Egineering_and_Drafting.addAction(self.actionLimits_and_Fits)
        self.menu_Egineering_and_Drafting.addAction(self.actionGDTFasteners)
        self.menu_Egineering_and_Drafting.addAction(self.actionPaper_Gauging)
        self.menu_Egineering_and_Drafting.addAction(self.actionTolerance_Finder)
        self.menu_Egineering_and_Drafting.addAction(self.actionDiameter_Deviation)
        self.menu_Additional_Calculators.addAction(self.actionTorsion)
        self.menu_Additional_Calculators.addAction(self.actionPressure)
        self.menu_Additional_Calculators.addAction(self.actionAddMohr_s_Circle)

        self.retranslateUi(MElist)

        QMetaObject.connectSlotsByName(MElist)
    # setupUi

    def retranslateUi(self, MElist):
        MElist.setWindowTitle(QCoreApplication.translate("MElist", u"MainWindow", None))
        self.actionUnit_Converter.setText(QCoreApplication.translate("MElist", u"Unit Converter", None))
        self.actionMoments_of_Inertia.setText(QCoreApplication.translate("MElist", u"Moments of Inertia", None))
        self.actionVectors.setText(QCoreApplication.translate("MElist", u"Vectors", None))
        self.actionFriction_and_Force.setText(QCoreApplication.translate("MElist", u"Friction and Force", None))
        self.actionFasteners.setText(QCoreApplication.translate("MElist", u"Fasteners", None))
        self.actionMaterial_Properties.setText(QCoreApplication.translate("MElist", u"Material Properties", None))
        self.actionCM_and_CG.setText(QCoreApplication.translate("MElist", u"CM and CG", None))
        self.actionTrusses.setText(QCoreApplication.translate("MElist", u"Trusses", None))
        self.actionBeamsMoments_of_Inertia.setText(QCoreApplication.translate("MElist", u"Moments of Inertia", None))
        self.actionShear_and_Moment.setText(QCoreApplication.translate("MElist", u"Shear and Moment", None))
        self.actionIndeterminate_Axial_Structures.setText(QCoreApplication.translate("MElist", u"Indeterminate Axial Structures", None))
        self.actionFlexure.setText(QCoreApplication.translate("MElist", u"Flexure", None))
        self.actionBeam_Deformation.setText(QCoreApplication.translate("MElist", u"Beam Deformation", None))
        self.actionAxial_Beam_Deformation.setText(QCoreApplication.translate("MElist", u"Axial Beam Deformation", None))
        self.actionTorsional_Beam_Deformation.setText(QCoreApplication.translate("MElist", u"Torsional Beam Deformation", None))
        self.actionSupported_Beams.setText(QCoreApplication.translate("MElist", u"Supported Beams", None))
        self.actionMohr_s_Circle.setText(QCoreApplication.translate("MElist", u"Mohr's Circle", None))
        self.actionC_Clamp.setText(QCoreApplication.translate("MElist", u"C-Clamp", None))
        self.actionCompression_Link.setText(QCoreApplication.translate("MElist", u"Compression Link", None))
        self.actionTension_Link.setText(QCoreApplication.translate("MElist", u"Tension Link", None))
        self.actionPost.setText(QCoreApplication.translate("MElist", u"Post", None))
        self.actionPost_and_Beam.setText(QCoreApplication.translate("MElist", u"Post and Beam", None))
        self.actionKinematic_Diagraming.setText(QCoreApplication.translate("MElist", u"Kinematic Diagraming", None))
        self.actionVector_Analysis.setText(QCoreApplication.translate("MElist", u"Vector Analysis", None))
        self.actionGDT_Checker.setText(QCoreApplication.translate("MElist", u"GDT Checker", None))
        self.actionVirtual_Condition_Calculator.setText(QCoreApplication.translate("MElist", u"Virtual Condition Calculator", None))
        self.actionLimits_and_Fits.setText(QCoreApplication.translate("MElist", u"Limits and Fits", None))
        self.actionGDTFasteners.setText(QCoreApplication.translate("MElist", u"Fasteners", None))
        self.actionPaper_Gauging.setText(QCoreApplication.translate("MElist", u"Paper Gauging", None))
        self.actionTolerance_Finder.setText(QCoreApplication.translate("MElist", u"Tolerance Finder", None))
        self.actionDiameter_Deviation.setText(QCoreApplication.translate("MElist", u"Diameter Deviation", None))
        self.actionTorsion.setText(QCoreApplication.translate("MElist", u"Torsion", None))
        self.actionPressure.setText(QCoreApplication.translate("MElist", u"Pressure", None))
        self.actionAddMohr_s_Circle.setText(QCoreApplication.translate("MElist", u"Mohr's Circle", None))
        self.actionModule_List.setText(QCoreApplication.translate("MElist", u"Module List", None))
        self.actionQuit.setText(QCoreApplication.translate("MElist", u"Quit", None))
        self.actionNotepad.setText(QCoreApplication.translate("MElist", u"Notepad", None))
        self.actionCalculator.setText(QCoreApplication.translate("MElist", u"Calculator", None))
        self.actionScreenshot.setText(QCoreApplication.translate("MElist", u"Screenshot", None))
        self.actionPerfer_SI_units.setText(QCoreApplication.translate("MElist", u"Edit Saftey Factor", None))
        self.actionPerfer_Metric_Units.setText(QCoreApplication.translate("MElist", u"Theme", None))
        self.actionMaterials_list.setText(QCoreApplication.translate("MElist", u"Materials List", None))
        self.actionCross_Sectional_Beams_and_Shapes_Lists.setText(QCoreApplication.translate("MElist", u"Beams and Shapes Lists", None))
        self.actionAbout.setText(QCoreApplication.translate("MElist", u"About", None))
        self.actionUnit_Converter_help.setText(QCoreApplication.translate("MElist", u"Unit Converter", None))
        self.actionMoments_of_Inertia_help.setText(QCoreApplication.translate("MElist", u"Moments of Inertia", None))
        self.actionVectors_help.setText(QCoreApplication.translate("MElist", u"Vectors", None))
        self.actionFriction_and_Force_help.setText(QCoreApplication.translate("MElist", u"Friction and Force", None))
        self.actionFasteners_help.setText(QCoreApplication.translate("MElist", u"Fasteners", None))
        self.actionMaterial_Properties_help.setText(QCoreApplication.translate("MElist", u"Material Properties", None))
        self.actionCM_and_CG_help.setText(QCoreApplication.translate("MElist", u"CM and CG", None))
        self.actionTrusses_help.setText(QCoreApplication.translate("MElist", u"Trusses", None))
        self.actionBeamsMoments_of_Inertia_help.setText(QCoreApplication.translate("MElist", u"Moments of Inertia", None))
        self.actionShear_and_Moment_help.setText(QCoreApplication.translate("MElist", u"Shear and Moment", None))
        self.actionIndeterminate_Axial_Structures_help.setText(QCoreApplication.translate("MElist", u"Indeterminate Axial Structures", None))
        self.actionFlexure_help.setText(QCoreApplication.translate("MElist", u"Flexure", None))
        self.actionBeam_Deformation_help.setText(QCoreApplication.translate("MElist", u"Beam Deformation", None))
        self.actionAxial_Beam_Deformation_help.setText(QCoreApplication.translate("MElist", u"Axial Beam Deformation", None))
        self.actionTorsional_Beam_Deformation_help.setText(QCoreApplication.translate("MElist", u"Torsional Beam Deformation", None))
        self.actionSupported_Beams_help.setText(QCoreApplication.translate("MElist", u"Supported Beams", None))
        self.actionMohr_s_Circle_help.setText(QCoreApplication.translate("MElist", u"Mohr's Circle", None))
        self.actionC_Clamp_help.setText(QCoreApplication.translate("MElist", u"C-Clamp", None))
        self.actionCompression_Link_help.setText(QCoreApplication.translate("MElist", u"Compression Link", None))
        self.actionTension_Link_help.setText(QCoreApplication.translate("MElist", u"Tension Link", None))
        self.actionPost_help.setText(QCoreApplication.translate("MElist", u"Post", None))
        self.actionPost_and_Beam_help.setText(QCoreApplication.translate("MElist", u"Post and Beam", None))
        self.actionSolid_shaft_and_Pipe_help.setText(QCoreApplication.translate("MElist", u"Solid Shaft and Pipe", None))
        self.actionKinematic_Diagraming_help.setText(QCoreApplication.translate("MElist", u"Kinematic Diagraming", None))
        self.actionVector_and_Motion_Analysis_help.setText(QCoreApplication.translate("MElist", u"Vector and Motion Analysis", None))
        self.actionGDT_Checker_help.setText(QCoreApplication.translate("MElist", u"GDT Checker", None))
        self.actionVirtual_Condition_Calculator_help.setText(QCoreApplication.translate("MElist", u"Virtual Condition Calculator", None))
        self.actionLimits_and_Fits_help.setText(QCoreApplication.translate("MElist", u"Limits and Fits", None))
        self.actionGDTFasteners_help.setText(QCoreApplication.translate("MElist", u"Fasteners", None))
        self.actionPaper_Gauging_help.setText(QCoreApplication.translate("MElist", u"Paper Gauging", None))
        self.actionTolerance_Finder_help.setText(QCoreApplication.translate("MElist", u"Tolerance Finder", None))
        self.actionDiameter_Deviation_help.setText(QCoreApplication.translate("MElist", u"Diameter Deviation", None))
        self.actionTorsion_help.setText(QCoreApplication.translate("MElist", u"Torsion", None))
        self.actionPressure_help.setText(QCoreApplication.translate("MElist", u"Pressure", None))
        self.actionTheme.setText(QCoreApplication.translate("MElist", u"Theme", None))
        self.actionSaftey_Factors.setText(QCoreApplication.translate("MElist", u"Saftey Factors", None))
        self.actionSolid_Shaft_and_Pipe.setText(QCoreApplication.translate("MElist", u"Solid Shaft and Pipe", None))
        self.actionMohr_s_Circle_2.setText(QCoreApplication.translate("MElist", u"Mohr's Circle", None))
        self.actionFit_Classes.setText(QCoreApplication.translate("MElist", u"Fit Classes", None))
        self.supportlocation.setTitle(QCoreApplication.translate("MElist", u"Support Locations", None))
        self.label_4.setText(QCoreApplication.translate("MElist", u"Location of\n"
"Left Support", None))
        self.label_5.setText(QCoreApplication.translate("MElist", u"Location of\n"
"Right Support", None))
        self.Beamsetuplength.setTitle(QCoreApplication.translate("MElist", u"Beam Setup", None))
        self.label_2.setText(QCoreApplication.translate("MElist", u"Total Beam\n"
"Length", None))
        self.menu_File.setTitle(QCoreApplication.translate("MElist", u"&File", None))
        self.menu_Settings.setTitle(QCoreApplication.translate("MElist", u"Settings", None))
        self.menu_Utilites.setTitle(QCoreApplication.translate("MElist", u"&Utilites", None))
        self.menuTables.setTitle(QCoreApplication.translate("MElist", u"Tables", None))
        self.menu_Help.setTitle(QCoreApplication.translate("MElist", u"&Help", None))
        self.menuModules_help.setTitle(QCoreApplication.translate("MElist", u"Modules", None))
        self.menuGeneral_Analysis_help.setTitle(QCoreApplication.translate("MElist", u"General Analysis", None))
        self.menuBeams_and_Loads_help.setTitle(QCoreApplication.translate("MElist", u"Beams and Loads", None))
        self.menuGeneral_Beam_Analysis.setTitle(QCoreApplication.translate("MElist", u"General Beam Analysis", None))
        self.menuCombined_Loadings_help.setTitle(QCoreApplication.translate("MElist", u"Combined Loadings", None))
        self.menuEccentric_Loadings_help.setTitle(QCoreApplication.translate("MElist", u"Eccentric Loadings", None))
        self.menuShear_Force_and_Bending_Moment_help.setTitle(QCoreApplication.translate("MElist", u"Shear Force and Bending Moment", None))
        self.menuAxial_Torsional_and_Bending_Stresses_help.setTitle(QCoreApplication.translate("MElist", u"Axial, Torsional, and Bending Stresses", None))
        self.menuKinematics_help.setTitle(QCoreApplication.translate("MElist", u"Kinematics", None))
        self.menuEngineering_and_Drafting_help.setTitle(QCoreApplication.translate("MElist", u"Engineering and Drafting", None))
        self.menuAdditional_Calculators_help.setTitle(QCoreApplication.translate("MElist", u"Additional Calculators", None))
        self.menu_Modules.setTitle(QCoreApplication.translate("MElist", u"&Modules", None))
        self.menu_General_Analysis.setTitle(QCoreApplication.translate("MElist", u"General Analysis", None))
        self.menu_Beams_and_Loads.setTitle(QCoreApplication.translate("MElist", u"Beams and Loads", None))
        self.menu_Generic_Beam_Analysis.setTitle(QCoreApplication.translate("MElist", u"Generic Beam Analysis", None))
        self.menuCombined_Loadings.setTitle(QCoreApplication.translate("MElist", u"Combined Loadings", None))
        self.menuEccentric_Loadings.setTitle(QCoreApplication.translate("MElist", u"Eccentric Loadings", None))
        self.menuShear_Force_and_Bending_Moment.setTitle(QCoreApplication.translate("MElist", u"Shear Force and Bending Moment", None))
        self.menuAxial_Torsional_and_Bending_Stresses.setTitle(QCoreApplication.translate("MElist", u"Axial, Torsional, and Bending Stresses", None))
        self.menu_Kinematics.setTitle(QCoreApplication.translate("MElist", u"Kinematics", None))
        self.menu_Egineering_and_Drafting.setTitle(QCoreApplication.translate("MElist", u"Egineering and Drafting", None))
        self.menu_Additional_Calculators.setTitle(QCoreApplication.translate("MElist", u"Additional Calculators", None))
    # retranslateUi

