# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'Shearandmomentdiagramming.ui'
##
## Created by: Qt User Interface Compiler version 6.11.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QAbstractScrollArea, QAbstractSpinBox, QApplication, QComboBox,
    QDoubleSpinBox, QFrame, QGraphicsView, QGroupBox,
    QHBoxLayout, QLabel, QMainWindow, QMenu,
    QMenuBar, QPushButton, QScrollArea, QSizePolicy,
    QStatusBar, QTabWidget, QVBoxLayout, QWidget)
from . import resources_rc

class Ui_shearandmomentscalculator(object):
    def setupUi(self, shearandmomentscalculator):
        if not shearandmomentscalculator.objectName():
            shearandmomentscalculator.setObjectName(u"shearandmomentscalculator")
        shearandmomentscalculator.resize(1200, 840)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(shearandmomentscalculator.sizePolicy().hasHeightForWidth())
        shearandmomentscalculator.setSizePolicy(sizePolicy)
        shearandmomentscalculator.setMinimumSize(QSize(1200, 840))
        shearandmomentscalculator.setMaximumSize(QSize(1200, 840))
        font = QFont()
        font.setFamilies([u"Arial"])
        font.setPointSize(14)
        shearandmomentscalculator.setFont(font)
        icon = QIcon()
        icon.addFile(u":/icons/modicon.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        shearandmomentscalculator.setWindowIcon(icon)
        shearandmomentscalculator.setTabShape(QTabWidget.Rounded)
        shearandmomentscalculator.setDockNestingEnabled(False)
        shearandmomentscalculator.setUnifiedTitleAndToolBarOnMac(False)
        self.actionUnit_Converter = QAction(shearandmomentscalculator)
        self.actionUnit_Converter.setObjectName(u"actionUnit_Converter")
        self.actionMoments_of_Inertia = QAction(shearandmomentscalculator)
        self.actionMoments_of_Inertia.setObjectName(u"actionMoments_of_Inertia")
        self.actionVectors = QAction(shearandmomentscalculator)
        self.actionVectors.setObjectName(u"actionVectors")
        self.actionFriction_and_Force = QAction(shearandmomentscalculator)
        self.actionFriction_and_Force.setObjectName(u"actionFriction_and_Force")
        self.actionFasteners = QAction(shearandmomentscalculator)
        self.actionFasteners.setObjectName(u"actionFasteners")
        self.actionMaterial_Properties = QAction(shearandmomentscalculator)
        self.actionMaterial_Properties.setObjectName(u"actionMaterial_Properties")
        self.actionCM_and_CG = QAction(shearandmomentscalculator)
        self.actionCM_and_CG.setObjectName(u"actionCM_and_CG")
        self.actionTrusses = QAction(shearandmomentscalculator)
        self.actionTrusses.setObjectName(u"actionTrusses")
        self.actionBeamsMoments_of_Inertia = QAction(shearandmomentscalculator)
        self.actionBeamsMoments_of_Inertia.setObjectName(u"actionBeamsMoments_of_Inertia")
        self.actionShear_and_Moment = QAction(shearandmomentscalculator)
        self.actionShear_and_Moment.setObjectName(u"actionShear_and_Moment")
        self.actionIndeterminate_Axial_Structures = QAction(shearandmomentscalculator)
        self.actionIndeterminate_Axial_Structures.setObjectName(u"actionIndeterminate_Axial_Structures")
        self.actionFlexure = QAction(shearandmomentscalculator)
        self.actionFlexure.setObjectName(u"actionFlexure")
        self.actionBeam_Deformation = QAction(shearandmomentscalculator)
        self.actionBeam_Deformation.setObjectName(u"actionBeam_Deformation")
        self.actionAxial_Beam_Deformation = QAction(shearandmomentscalculator)
        self.actionAxial_Beam_Deformation.setObjectName(u"actionAxial_Beam_Deformation")
        self.actionTorsional_Beam_Deformation = QAction(shearandmomentscalculator)
        self.actionTorsional_Beam_Deformation.setObjectName(u"actionTorsional_Beam_Deformation")
        self.actionSupported_Beams = QAction(shearandmomentscalculator)
        self.actionSupported_Beams.setObjectName(u"actionSupported_Beams")
        self.actionMohr_s_Circle = QAction(shearandmomentscalculator)
        self.actionMohr_s_Circle.setObjectName(u"actionMohr_s_Circle")
        self.actionC_Clamp = QAction(shearandmomentscalculator)
        self.actionC_Clamp.setObjectName(u"actionC_Clamp")
        self.actionCompression_Link = QAction(shearandmomentscalculator)
        self.actionCompression_Link.setObjectName(u"actionCompression_Link")
        self.actionTension_Link = QAction(shearandmomentscalculator)
        self.actionTension_Link.setObjectName(u"actionTension_Link")
        self.actionPost = QAction(shearandmomentscalculator)
        self.actionPost.setObjectName(u"actionPost")
        self.actionPost_and_Beam = QAction(shearandmomentscalculator)
        self.actionPost_and_Beam.setObjectName(u"actionPost_and_Beam")
        self.actionKinematic_Diagraming = QAction(shearandmomentscalculator)
        self.actionKinematic_Diagraming.setObjectName(u"actionKinematic_Diagraming")
        self.actionVector_Analysis = QAction(shearandmomentscalculator)
        self.actionVector_Analysis.setObjectName(u"actionVector_Analysis")
        self.actionGDT_Checker = QAction(shearandmomentscalculator)
        self.actionGDT_Checker.setObjectName(u"actionGDT_Checker")
        self.actionVirtual_Condition_Calculator = QAction(shearandmomentscalculator)
        self.actionVirtual_Condition_Calculator.setObjectName(u"actionVirtual_Condition_Calculator")
        self.actionLimits_and_Fits = QAction(shearandmomentscalculator)
        self.actionLimits_and_Fits.setObjectName(u"actionLimits_and_Fits")
        self.actionGDTFasteners = QAction(shearandmomentscalculator)
        self.actionGDTFasteners.setObjectName(u"actionGDTFasteners")
        self.actionPaper_Gauging = QAction(shearandmomentscalculator)
        self.actionPaper_Gauging.setObjectName(u"actionPaper_Gauging")
        self.actionTolerance_Finder = QAction(shearandmomentscalculator)
        self.actionTolerance_Finder.setObjectName(u"actionTolerance_Finder")
        self.actionDiameter_Deviation = QAction(shearandmomentscalculator)
        self.actionDiameter_Deviation.setObjectName(u"actionDiameter_Deviation")
        self.actionTorsion = QAction(shearandmomentscalculator)
        self.actionTorsion.setObjectName(u"actionTorsion")
        self.actionPressure = QAction(shearandmomentscalculator)
        self.actionPressure.setObjectName(u"actionPressure")
        self.actionAddMohr_s_Circle = QAction(shearandmomentscalculator)
        self.actionAddMohr_s_Circle.setObjectName(u"actionAddMohr_s_Circle")
        self.actionModule_List = QAction(shearandmomentscalculator)
        self.actionModule_List.setObjectName(u"actionModule_List")
        self.actionQuit = QAction(shearandmomentscalculator)
        self.actionQuit.setObjectName(u"actionQuit")
        self.actionNotepad = QAction(shearandmomentscalculator)
        self.actionNotepad.setObjectName(u"actionNotepad")
        self.actionCalculator = QAction(shearandmomentscalculator)
        self.actionCalculator.setObjectName(u"actionCalculator")
        self.actionScreenshot = QAction(shearandmomentscalculator)
        self.actionScreenshot.setObjectName(u"actionScreenshot")
        self.actionPerfer_SI_units = QAction(shearandmomentscalculator)
        self.actionPerfer_SI_units.setObjectName(u"actionPerfer_SI_units")
        self.actionPerfer_Metric_Units = QAction(shearandmomentscalculator)
        self.actionPerfer_Metric_Units.setObjectName(u"actionPerfer_Metric_Units")
        self.actionMaterials_list = QAction(shearandmomentscalculator)
        self.actionMaterials_list.setObjectName(u"actionMaterials_list")
        self.actionCross_Sectional_Beams_and_Shapes_Lists = QAction(shearandmomentscalculator)
        self.actionCross_Sectional_Beams_and_Shapes_Lists.setObjectName(u"actionCross_Sectional_Beams_and_Shapes_Lists")
        self.actionAbout = QAction(shearandmomentscalculator)
        self.actionAbout.setObjectName(u"actionAbout")
        self.actionUnit_Converter_help = QAction(shearandmomentscalculator)
        self.actionUnit_Converter_help.setObjectName(u"actionUnit_Converter_help")
        self.actionMoments_of_Inertia_help = QAction(shearandmomentscalculator)
        self.actionMoments_of_Inertia_help.setObjectName(u"actionMoments_of_Inertia_help")
        self.actionVectors_help = QAction(shearandmomentscalculator)
        self.actionVectors_help.setObjectName(u"actionVectors_help")
        self.actionFriction_and_Force_help = QAction(shearandmomentscalculator)
        self.actionFriction_and_Force_help.setObjectName(u"actionFriction_and_Force_help")
        self.actionFasteners_help = QAction(shearandmomentscalculator)
        self.actionFasteners_help.setObjectName(u"actionFasteners_help")
        self.actionMaterial_Properties_help = QAction(shearandmomentscalculator)
        self.actionMaterial_Properties_help.setObjectName(u"actionMaterial_Properties_help")
        self.actionCM_and_CG_help = QAction(shearandmomentscalculator)
        self.actionCM_and_CG_help.setObjectName(u"actionCM_and_CG_help")
        self.actionTrusses_help = QAction(shearandmomentscalculator)
        self.actionTrusses_help.setObjectName(u"actionTrusses_help")
        self.actionBeamsMoments_of_Inertia_help = QAction(shearandmomentscalculator)
        self.actionBeamsMoments_of_Inertia_help.setObjectName(u"actionBeamsMoments_of_Inertia_help")
        self.actionShear_and_Moment_help = QAction(shearandmomentscalculator)
        self.actionShear_and_Moment_help.setObjectName(u"actionShear_and_Moment_help")
        self.actionIndeterminate_Axial_Structures_help = QAction(shearandmomentscalculator)
        self.actionIndeterminate_Axial_Structures_help.setObjectName(u"actionIndeterminate_Axial_Structures_help")
        self.actionFlexure_help = QAction(shearandmomentscalculator)
        self.actionFlexure_help.setObjectName(u"actionFlexure_help")
        self.actionBeam_Deformation_help = QAction(shearandmomentscalculator)
        self.actionBeam_Deformation_help.setObjectName(u"actionBeam_Deformation_help")
        self.actionAxial_Beam_Deformation_help = QAction(shearandmomentscalculator)
        self.actionAxial_Beam_Deformation_help.setObjectName(u"actionAxial_Beam_Deformation_help")
        self.actionTorsional_Beam_Deformation_help = QAction(shearandmomentscalculator)
        self.actionTorsional_Beam_Deformation_help.setObjectName(u"actionTorsional_Beam_Deformation_help")
        self.actionSupported_Beams_help = QAction(shearandmomentscalculator)
        self.actionSupported_Beams_help.setObjectName(u"actionSupported_Beams_help")
        self.actionMohr_s_Circle_help = QAction(shearandmomentscalculator)
        self.actionMohr_s_Circle_help.setObjectName(u"actionMohr_s_Circle_help")
        self.actionC_Clamp_help = QAction(shearandmomentscalculator)
        self.actionC_Clamp_help.setObjectName(u"actionC_Clamp_help")
        self.actionCompression_Link_help = QAction(shearandmomentscalculator)
        self.actionCompression_Link_help.setObjectName(u"actionCompression_Link_help")
        self.actionTension_Link_help = QAction(shearandmomentscalculator)
        self.actionTension_Link_help.setObjectName(u"actionTension_Link_help")
        self.actionPost_help = QAction(shearandmomentscalculator)
        self.actionPost_help.setObjectName(u"actionPost_help")
        self.actionPost_and_Beam_help = QAction(shearandmomentscalculator)
        self.actionPost_and_Beam_help.setObjectName(u"actionPost_and_Beam_help")
        self.actionSolid_shaft_and_Pipe_help = QAction(shearandmomentscalculator)
        self.actionSolid_shaft_and_Pipe_help.setObjectName(u"actionSolid_shaft_and_Pipe_help")
        self.actionKinematic_Diagraming_help = QAction(shearandmomentscalculator)
        self.actionKinematic_Diagraming_help.setObjectName(u"actionKinematic_Diagraming_help")
        self.actionVector_and_Motion_Analysis_help = QAction(shearandmomentscalculator)
        self.actionVector_and_Motion_Analysis_help.setObjectName(u"actionVector_and_Motion_Analysis_help")
        self.actionGDT_Checker_help = QAction(shearandmomentscalculator)
        self.actionGDT_Checker_help.setObjectName(u"actionGDT_Checker_help")
        self.actionVirtual_Condition_Calculator_help = QAction(shearandmomentscalculator)
        self.actionVirtual_Condition_Calculator_help.setObjectName(u"actionVirtual_Condition_Calculator_help")
        self.actionLimits_and_Fits_help = QAction(shearandmomentscalculator)
        self.actionLimits_and_Fits_help.setObjectName(u"actionLimits_and_Fits_help")
        self.actionGDTFasteners_help = QAction(shearandmomentscalculator)
        self.actionGDTFasteners_help.setObjectName(u"actionGDTFasteners_help")
        self.actionPaper_Gauging_help = QAction(shearandmomentscalculator)
        self.actionPaper_Gauging_help.setObjectName(u"actionPaper_Gauging_help")
        self.actionTolerance_Finder_help = QAction(shearandmomentscalculator)
        self.actionTolerance_Finder_help.setObjectName(u"actionTolerance_Finder_help")
        self.actionDiameter_Deviation_help = QAction(shearandmomentscalculator)
        self.actionDiameter_Deviation_help.setObjectName(u"actionDiameter_Deviation_help")
        self.actionTorsion_help = QAction(shearandmomentscalculator)
        self.actionTorsion_help.setObjectName(u"actionTorsion_help")
        self.actionPressure_help = QAction(shearandmomentscalculator)
        self.actionPressure_help.setObjectName(u"actionPressure_help")
        self.actionTheme = QAction(shearandmomentscalculator)
        self.actionTheme.setObjectName(u"actionTheme")
        self.actionSaftey_Factors = QAction(shearandmomentscalculator)
        self.actionSaftey_Factors.setObjectName(u"actionSaftey_Factors")
        self.actionSolid_Shaft_and_Pipe = QAction(shearandmomentscalculator)
        self.actionSolid_Shaft_and_Pipe.setObjectName(u"actionSolid_Shaft_and_Pipe")
        self.actionMohr_s_Circle_2 = QAction(shearandmomentscalculator)
        self.actionMohr_s_Circle_2.setObjectName(u"actionMohr_s_Circle_2")
        self.actionFit_Classes = QAction(shearandmomentscalculator)
        self.actionFit_Classes.setObjectName(u"actionFit_Classes")
        self.actionShear_and_Moment_Diagrams = QAction(shearandmomentscalculator)
        self.actionShear_and_Moment_Diagrams.setObjectName(u"actionShear_and_Moment_Diagrams")
        self.actionSlope_and_Deflection_Diagrams = QAction(shearandmomentscalculator)
        self.actionSlope_and_Deflection_Diagrams.setObjectName(u"actionSlope_and_Deflection_Diagrams")
        self.actionGraph_Details = QAction(shearandmomentscalculator)
        self.actionGraph_Details.setObjectName(u"actionGraph_Details")
        self.actionDesign = QAction(shearandmomentscalculator)
        self.actionDesign.setObjectName(u"actionDesign")
        self.actionFlexural_Stiffness_EI = QAction(shearandmomentscalculator)
        self.actionFlexural_Stiffness_EI.setObjectName(u"actionFlexural_Stiffness_EI")
        self.actionQuit_All = QAction(shearandmomentscalculator)
        self.actionQuit_All.setObjectName(u"actionQuit_All")
        self.actionOutput_Loads_and_Reactions = QAction(shearandmomentscalculator)
        self.actionOutput_Loads_and_Reactions.setObjectName(u"actionOutput_Loads_and_Reactions")
        self.centralwidget = QWidget(shearandmomentscalculator)
        self.centralwidget.setObjectName(u"centralwidget")
        self.variablesupports = QPushButton(self.centralwidget)
        self.variablesupports.setObjectName(u"variablesupports")
        self.variablesupports.setGeometry(QRect(10, 10, 90, 60))
        self.variablesupports.setAutoFillBackground(False)
        icon1 = QIcon()
        icon1.addFile(u":/icons/varsup.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.variablesupports.setIcon(icon1)
        self.variablesupports.setIconSize(QSize(64, 64))
        self.variablesupports.setCheckable(False)
        self.variablesupports.setAutoExclusive(False)
        self.variablesupports.setAutoDefault(False)
        self.variablesupports.setFlat(False)
        self.lftsidesupport = QPushButton(self.centralwidget)
        self.lftsidesupport.setObjectName(u"lftsidesupport")
        self.lftsidesupport.setGeometry(QRect(110, 10, 90, 60))
        icon2 = QIcon()
        icon2.addFile(u":/icons/lcantsup.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.lftsidesupport.setIcon(icon2)
        self.lftsidesupport.setIconSize(QSize(64, 64))
        self.rtsidesupport = QPushButton(self.centralwidget)
        self.rtsidesupport.setObjectName(u"rtsidesupport")
        self.rtsidesupport.setGeometry(QRect(210, 10, 90, 60))
        icon3 = QIcon()
        icon3.addFile(u":/icons/rcantsup.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.rtsidesupport.setIcon(icon3)
        self.rtsidesupport.setIconSize(QSize(64, 64))
        self.Uppntload = QPushButton(self.centralwidget)
        self.Uppntload.setObjectName(u"Uppntload")
        self.Uppntload.setGeometry(QRect(10, 80, 50, 50))
        icon4 = QIcon()
        icon4.addFile(u":/icons/cpl_up.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.Uppntload.setIcon(icon4)
        self.Uppntload.setIconSize(QSize(30, 30))
        self.Downpntload = QPushButton(self.centralwidget)
        self.Downpntload.setObjectName(u"Downpntload")
        self.Downpntload.setGeometry(QRect(10, 140, 50, 50))
        icon5 = QIcon()
        icon5.addFile(u":/icons/cpl_dwn.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.Downpntload.setIcon(icon5)
        self.Downpntload.setIconSize(QSize(30, 30))
        self.lineardistribloadup = QPushButton(self.centralwidget)
        self.lineardistribloadup.setObjectName(u"lineardistribloadup")
        self.lineardistribloadup.setGeometry(QRect(10, 200, 50, 50))
        icon6 = QIcon()
        icon6.addFile(u":/icons/udl_up.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.lineardistribloadup.setIcon(icon6)
        self.lineardistribloadup.setIconSize(QSize(37, 37))
        self.lineardistribloaddown = QPushButton(self.centralwidget)
        self.lineardistribloaddown.setObjectName(u"lineardistribloaddown")
        self.lineardistribloaddown.setGeometry(QRect(10, 260, 50, 50))
        icon7 = QIcon()
        icon7.addFile(u":/icons/udl_dwn.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.lineardistribloaddown.setIcon(icon7)
        self.lineardistribloaddown.setIconSize(QSize(37, 37))
        self.varibledistribloadup = QPushButton(self.centralwidget)
        self.varibledistribloadup.setObjectName(u"varibledistribloadup")
        self.varibledistribloadup.setGeometry(QRect(10, 320, 50, 50))
        icon8 = QIcon()
        icon8.addFile(u":/icons/ldl_up.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.varibledistribloadup.setIcon(icon8)
        self.varibledistribloadup.setIconSize(QSize(37, 37))
        self.varibdistribloaddown = QPushButton(self.centralwidget)
        self.varibdistribloaddown.setObjectName(u"varibdistribloaddown")
        self.varibdistribloaddown.setGeometry(QRect(10, 380, 50, 50))
        icon9 = QIcon()
        icon9.addFile(u":/icons/ldl_dwn.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.varibdistribloaddown.setIcon(icon9)
        self.varibdistribloaddown.setIconSize(QSize(37, 37))
        self.momentccw = QPushButton(self.centralwidget)
        self.momentccw.setObjectName(u"momentccw")
        self.momentccw.setGeometry(QRect(10, 440, 50, 50))
        icon10 = QIcon()
        icon10.addFile(u":/icons/m_ccw.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.momentccw.setIcon(icon10)
        self.momentccw.setIconSize(QSize(35, 35))
        self.momentcw = QPushButton(self.centralwidget)
        self.momentcw.setObjectName(u"momentcw")
        self.momentcw.setGeometry(QRect(10, 500, 50, 50))
        icon11 = QIcon()
        icon11.addFile(u":/icons/m_cw.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.momentcw.setIcon(icon11)
        self.momentcw.setIconSize(QSize(35, 35))
        self.elemetsscrollarea = QScrollArea(self.centralwidget)
        self.elemetsscrollarea.setObjectName(u"elemetsscrollarea")
        self.elemetsscrollarea.setGeometry(QRect(70, 320, 311, 461))
        self.elemetsscrollarea.setFrameShape(QFrame.Panel)
        self.elemetsscrollarea.setFrameShadow(QFrame.Plain)
        self.elemetsscrollarea.setLineWidth(2)
        self.elemetsscrollarea.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setObjectName(u"scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setGeometry(QRect(0, 0, 307, 457))
        self.elemetsscrollarea.setWidget(self.scrollAreaWidgetContents)
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(70, 300, 311, 16))
        font1 = QFont()
        font1.setFamilies([u"Consolas"])
        font1.setPointSize(14)
        self.label_7.setFont(font1)
        self.label_7.setAlignment(Qt.AlignCenter)
        self.Beamsetuplength = QGroupBox(self.centralwidget)
        self.Beamsetuplength.setObjectName(u"Beamsetuplength")
        self.Beamsetuplength.setGeometry(QRect(70, 80, 281, 94))
        font2 = QFont()
        font2.setFamilies([u"Arial"])
        font2.setPointSize(12)
        self.Beamsetuplength.setFont(font2)
        self.horizontalLayout = QHBoxLayout(self.Beamsetuplength)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.label_2 = QLabel(self.Beamsetuplength)
        self.label_2.setObjectName(u"label_2")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy1)
        self.label_2.setMinimumSize(QSize(126, 0))
        self.label_2.setFont(font2)
        self.label_2.setAlignment(Qt.AlignCenter)

        self.horizontalLayout.addWidget(self.label_2)

        self.verticalLayout = QVBoxLayout()
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.Beamlength = QDoubleSpinBox(self.Beamsetuplength)
        self.Beamlength.setObjectName(u"Beamlength")
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Fixed)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.Beamlength.sizePolicy().hasHeightForWidth())
        self.Beamlength.setSizePolicy(sizePolicy2)
        self.Beamlength.setMinimumSize(QSize(0, 0))
        self.Beamlength.setFont(font2)
        self.Beamlength.setButtonSymbols(QAbstractSpinBox.UpDownArrows)
        self.Beamlength.setMaximum(100000000.000000000000000)

        self.verticalLayout.addWidget(self.Beamlength)

        self.beamlengthunits = QComboBox(self.Beamsetuplength)
        self.beamlengthunits.addItem("")
        self.beamlengthunits.addItem("")
        self.beamlengthunits.addItem("")
        self.beamlengthunits.addItem("")
        self.beamlengthunits.addItem("")
        self.beamlengthunits.setObjectName(u"beamlengthunits")
        sizePolicy2.setHeightForWidth(self.beamlengthunits.sizePolicy().hasHeightForWidth())
        self.beamlengthunits.setSizePolicy(sizePolicy2)
        self.beamlengthunits.setMinimumSize(QSize(0, 0))
        self.beamlengthunits.setFont(font2)

        self.verticalLayout.addWidget(self.beamlengthunits)


        self.horizontalLayout.addLayout(self.verticalLayout)

        self.supportlocation = QGroupBox(self.centralwidget)
        self.supportlocation.setObjectName(u"supportlocation")
        self.supportlocation.setGeometry(QRect(70, 180, 281, 107))
        self.supportlocation.setFont(font2)
        self.horizontalLayout_2 = QHBoxLayout(self.supportlocation)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.verticalLayout_2 = QVBoxLayout()
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.label_4 = QLabel(self.supportlocation)
        self.label_4.setObjectName(u"label_4")
        sizePolicy3 = QSizePolicy(QSizePolicy.Policy.MinimumExpanding, QSizePolicy.Policy.Preferred)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy3)
        self.label_4.setFont(font2)
        self.label_4.setAlignment(Qt.AlignCenter)

        self.verticalLayout_2.addWidget(self.label_4)

        self.leftsupportlocation = QDoubleSpinBox(self.supportlocation)
        self.leftsupportlocation.setObjectName(u"leftsupportlocation")
        self.leftsupportlocation.setEnabled(True)
        sizePolicy4 = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Fixed)
        sizePolicy4.setHorizontalStretch(0)
        sizePolicy4.setVerticalStretch(0)
        sizePolicy4.setHeightForWidth(self.leftsupportlocation.sizePolicy().hasHeightForWidth())
        self.leftsupportlocation.setSizePolicy(sizePolicy4)
        self.leftsupportlocation.setFont(font2)
        self.leftsupportlocation.setFrame(True)
        self.leftsupportlocation.setButtonSymbols(QAbstractSpinBox.UpDownArrows)
        self.leftsupportlocation.setMaximum(100000000.000000000000000)

        self.verticalLayout_2.addWidget(self.leftsupportlocation)


        self.horizontalLayout_2.addLayout(self.verticalLayout_2)

        self.verticalLayout_3 = QVBoxLayout()
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.label_5 = QLabel(self.supportlocation)
        self.label_5.setObjectName(u"label_5")
        sizePolicy3.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy3)
        self.label_5.setFont(font2)
        self.label_5.setAlignment(Qt.AlignCenter)

        self.verticalLayout_3.addWidget(self.label_5)

        self.rightsupportlocation = QDoubleSpinBox(self.supportlocation)
        self.rightsupportlocation.setObjectName(u"rightsupportlocation")
        sizePolicy4.setHeightForWidth(self.rightsupportlocation.sizePolicy().hasHeightForWidth())
        self.rightsupportlocation.setSizePolicy(sizePolicy4)
        self.rightsupportlocation.setFont(font2)
        self.rightsupportlocation.setFrame(True)
        self.rightsupportlocation.setButtonSymbols(QAbstractSpinBox.UpDownArrows)
        self.rightsupportlocation.setMaximum(100000000.000000000000000)

        self.verticalLayout_3.addWidget(self.rightsupportlocation)


        self.horizontalLayout_2.addLayout(self.verticalLayout_3)

        self.loadsscroll = QScrollArea(self.centralwidget)
        self.loadsscroll.setObjectName(u"loadsscroll")
        self.loadsscroll.setGeometry(QRect(360, 100, 141, 71))
        font3 = QFont()
        font3.setPointSize(11)
        self.loadsscroll.setFont(font3)
        self.loadsscroll.setWidgetResizable(True)
        self.scrollAreaWidgetContents_2 = QWidget()
        self.scrollAreaWidgetContents_2.setObjectName(u"scrollAreaWidgetContents_2")
        self.scrollAreaWidgetContents_2.setGeometry(QRect(0, 0, 139, 69))
        self.loadsscroll.setWidget(self.scrollAreaWidgetContents_2)
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(360, 80, 141, 21))
        self.label_6.setFont(font1)
        self.reactionsscroll = QScrollArea(self.centralwidget)
        self.reactionsscroll.setObjectName(u"reactionsscroll")
        self.reactionsscroll.setGeometry(QRect(360, 190, 141, 71))
        self.reactionsscroll.setFont(font3)
        self.reactionsscroll.setWidgetResizable(True)
        self.scrollAreaWidgetContents_3 = QWidget()
        self.scrollAreaWidgetContents_3.setObjectName(u"scrollAreaWidgetContents_3")
        self.scrollAreaWidgetContents_3.setGeometry(QRect(0, 0, 139, 69))
        self.reactionsscroll.setWidget(self.scrollAreaWidgetContents_3)
        self.label_8 = QLabel(self.centralwidget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(360, 170, 141, 21))
        self.label_8.setFont(font1)
        self.entersetup = QPushButton(self.centralwidget)
        self.entersetup.setObjectName(u"entersetup")
        self.entersetup.setGeometry(QRect(310, 10, 81, 59))
        sizePolicy5 = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Preferred)
        sizePolicy5.setHorizontalStretch(0)
        sizePolicy5.setVerticalStretch(0)
        sizePolicy5.setHeightForWidth(self.entersetup.sizePolicy().hasHeightForWidth())
        self.entersetup.setSizePolicy(sizePolicy5)
        font4 = QFont()
        font4.setPointSize(13)
        self.entersetup.setFont(font4)
        self.widget = QWidget(self.centralwidget)
        self.widget.setObjectName(u"widget")
        self.widget.setGeometry(QRect(510, 10, 681, 781))
        self.verticalLayout_5 = QVBoxLayout(self.widget)
        self.verticalLayout_5.setObjectName(u"verticalLayout_5")
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.label_9 = QLabel(self.widget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setAlignment(Qt.AlignCenter)

        self.verticalLayout_5.addWidget(self.label_9)

        self.Loadsdiagram = QGraphicsView(self.widget)
        self.Loadsdiagram.setObjectName(u"Loadsdiagram")
        self.Loadsdiagram.setFrameShape(QFrame.Panel)
        self.Loadsdiagram.setVerticalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        self.Loadsdiagram.setHorizontalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        self.Loadsdiagram.setSizeAdjustPolicy(QAbstractScrollArea.AdjustIgnored)

        self.verticalLayout_5.addWidget(self.Loadsdiagram)

        self.label_10 = QLabel(self.widget)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setAlignment(Qt.AlignCenter)

        self.verticalLayout_5.addWidget(self.label_10)

        self.Sheargraph = QGraphicsView(self.widget)
        self.Sheargraph.setObjectName(u"Sheargraph")
        self.Sheargraph.setFrameShape(QFrame.Panel)

        self.verticalLayout_5.addWidget(self.Sheargraph)

        self.label_11 = QLabel(self.widget)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setAlignment(Qt.AlignCenter)

        self.verticalLayout_5.addWidget(self.label_11)

        self.Momentgraph = QGraphicsView(self.widget)
        self.Momentgraph.setObjectName(u"Momentgraph")
        self.Momentgraph.setFrameShape(QFrame.Panel)

        self.verticalLayout_5.addWidget(self.Momentgraph)

        shearandmomentscalculator.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(shearandmomentscalculator)
        self.statusbar.setObjectName(u"statusbar")
        shearandmomentscalculator.setStatusBar(self.statusbar)
        self.menubar = QMenuBar(shearandmomentscalculator)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1200, 21))
        self.menu_Utilites = QMenu(self.menubar)
        self.menu_Utilites.setObjectName(u"menu_Utilites")
        self.menu_Help = QMenu(self.menubar)
        self.menu_Help.setObjectName(u"menu_Help")
        self.menuOptions = QMenu(self.menubar)
        self.menuOptions.setObjectName(u"menuOptions")
        shearandmomentscalculator.setMenuBar(self.menubar)

        self.menubar.addAction(self.menu_Utilites.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())
        self.menubar.addAction(self.menuOptions.menuAction())
        self.menu_Utilites.addAction(self.actionScreenshot)
        self.menu_Help.addAction(self.actionAbout)
        self.menuOptions.addAction(self.actionShear_and_Moment_Diagrams)
        self.menuOptions.addAction(self.actionSlope_and_Deflection_Diagrams)
        self.menuOptions.addSeparator()
        self.menuOptions.addAction(self.actionGraph_Details)
        self.menuOptions.addAction(self.actionDesign)
        self.menuOptions.addSeparator()
        self.menuOptions.addAction(self.actionFlexural_Stiffness_EI)

        self.retranslateUi(shearandmomentscalculator)

        self.variablesupports.setDefault(False)


        QMetaObject.connectSlotsByName(shearandmomentscalculator)
    # setupUi

    def retranslateUi(self, shearandmomentscalculator):
        shearandmomentscalculator.setWindowTitle(QCoreApplication.translate("shearandmomentscalculator", u"MainWindow", None))
        self.actionUnit_Converter.setText(QCoreApplication.translate("shearandmomentscalculator", u"Unit Converter", None))
        self.actionMoments_of_Inertia.setText(QCoreApplication.translate("shearandmomentscalculator", u"Moments of Inertia", None))
        self.actionVectors.setText(QCoreApplication.translate("shearandmomentscalculator", u"Vectors", None))
        self.actionFriction_and_Force.setText(QCoreApplication.translate("shearandmomentscalculator", u"Friction and Force", None))
        self.actionFasteners.setText(QCoreApplication.translate("shearandmomentscalculator", u"Fasteners", None))
        self.actionMaterial_Properties.setText(QCoreApplication.translate("shearandmomentscalculator", u"Material Properties", None))
        self.actionCM_and_CG.setText(QCoreApplication.translate("shearandmomentscalculator", u"CM and CG", None))
        self.actionTrusses.setText(QCoreApplication.translate("shearandmomentscalculator", u"Trusses", None))
        self.actionBeamsMoments_of_Inertia.setText(QCoreApplication.translate("shearandmomentscalculator", u"Moments of Inertia", None))
        self.actionShear_and_Moment.setText(QCoreApplication.translate("shearandmomentscalculator", u"Shear and Moment", None))
        self.actionIndeterminate_Axial_Structures.setText(QCoreApplication.translate("shearandmomentscalculator", u"Indeterminate Axial Structures", None))
        self.actionFlexure.setText(QCoreApplication.translate("shearandmomentscalculator", u"Flexure", None))
        self.actionBeam_Deformation.setText(QCoreApplication.translate("shearandmomentscalculator", u"Beam Deformation", None))
        self.actionAxial_Beam_Deformation.setText(QCoreApplication.translate("shearandmomentscalculator", u"Axial Beam Deformation", None))
        self.actionTorsional_Beam_Deformation.setText(QCoreApplication.translate("shearandmomentscalculator", u"Torsional Beam Deformation", None))
        self.actionSupported_Beams.setText(QCoreApplication.translate("shearandmomentscalculator", u"Supported Beams", None))
        self.actionMohr_s_Circle.setText(QCoreApplication.translate("shearandmomentscalculator", u"Mohr's Circle", None))
        self.actionC_Clamp.setText(QCoreApplication.translate("shearandmomentscalculator", u"C-Clamp", None))
        self.actionCompression_Link.setText(QCoreApplication.translate("shearandmomentscalculator", u"Compression Link", None))
        self.actionTension_Link.setText(QCoreApplication.translate("shearandmomentscalculator", u"Tension Link", None))
        self.actionPost.setText(QCoreApplication.translate("shearandmomentscalculator", u"Post", None))
        self.actionPost_and_Beam.setText(QCoreApplication.translate("shearandmomentscalculator", u"Post and Beam", None))
        self.actionKinematic_Diagraming.setText(QCoreApplication.translate("shearandmomentscalculator", u"Kinematic Diagraming", None))
        self.actionVector_Analysis.setText(QCoreApplication.translate("shearandmomentscalculator", u"Vector Analysis", None))
        self.actionGDT_Checker.setText(QCoreApplication.translate("shearandmomentscalculator", u"GDT Checker", None))
        self.actionVirtual_Condition_Calculator.setText(QCoreApplication.translate("shearandmomentscalculator", u"Virtual Condition Calculator", None))
        self.actionLimits_and_Fits.setText(QCoreApplication.translate("shearandmomentscalculator", u"Limits and Fits", None))
        self.actionGDTFasteners.setText(QCoreApplication.translate("shearandmomentscalculator", u"Fasteners", None))
        self.actionPaper_Gauging.setText(QCoreApplication.translate("shearandmomentscalculator", u"Paper Gauging", None))
        self.actionTolerance_Finder.setText(QCoreApplication.translate("shearandmomentscalculator", u"Tolerance Finder", None))
        self.actionDiameter_Deviation.setText(QCoreApplication.translate("shearandmomentscalculator", u"Diameter Deviation", None))
        self.actionTorsion.setText(QCoreApplication.translate("shearandmomentscalculator", u"Torsion", None))
        self.actionPressure.setText(QCoreApplication.translate("shearandmomentscalculator", u"Pressure", None))
        self.actionAddMohr_s_Circle.setText(QCoreApplication.translate("shearandmomentscalculator", u"Mohr's Circle", None))
        self.actionModule_List.setText(QCoreApplication.translate("shearandmomentscalculator", u"Module List", None))
        self.actionQuit.setText(QCoreApplication.translate("shearandmomentscalculator", u"Quit", None))
        self.actionNotepad.setText(QCoreApplication.translate("shearandmomentscalculator", u"Notepad", None))
        self.actionCalculator.setText(QCoreApplication.translate("shearandmomentscalculator", u"Calculator", None))
        self.actionScreenshot.setText(QCoreApplication.translate("shearandmomentscalculator", u"Screenshot", None))
        self.actionPerfer_SI_units.setText(QCoreApplication.translate("shearandmomentscalculator", u"Edit Saftey Factor", None))
        self.actionPerfer_Metric_Units.setText(QCoreApplication.translate("shearandmomentscalculator", u"Theme", None))
        self.actionMaterials_list.setText(QCoreApplication.translate("shearandmomentscalculator", u"Materials List", None))
        self.actionCross_Sectional_Beams_and_Shapes_Lists.setText(QCoreApplication.translate("shearandmomentscalculator", u"Beams and Shapes Lists", None))
        self.actionAbout.setText(QCoreApplication.translate("shearandmomentscalculator", u"About", None))
        self.actionUnit_Converter_help.setText(QCoreApplication.translate("shearandmomentscalculator", u"Unit Converter", None))
        self.actionMoments_of_Inertia_help.setText(QCoreApplication.translate("shearandmomentscalculator", u"Moments of Inertia", None))
        self.actionVectors_help.setText(QCoreApplication.translate("shearandmomentscalculator", u"Vectors", None))
        self.actionFriction_and_Force_help.setText(QCoreApplication.translate("shearandmomentscalculator", u"Friction and Force", None))
        self.actionFasteners_help.setText(QCoreApplication.translate("shearandmomentscalculator", u"Fasteners", None))
        self.actionMaterial_Properties_help.setText(QCoreApplication.translate("shearandmomentscalculator", u"Material Properties", None))
        self.actionCM_and_CG_help.setText(QCoreApplication.translate("shearandmomentscalculator", u"CM and CG", None))
        self.actionTrusses_help.setText(QCoreApplication.translate("shearandmomentscalculator", u"Trusses", None))
        self.actionBeamsMoments_of_Inertia_help.setText(QCoreApplication.translate("shearandmomentscalculator", u"Moments of Inertia", None))
        self.actionShear_and_Moment_help.setText(QCoreApplication.translate("shearandmomentscalculator", u"Shear and Moment", None))
        self.actionIndeterminate_Axial_Structures_help.setText(QCoreApplication.translate("shearandmomentscalculator", u"Indeterminate Axial Structures", None))
        self.actionFlexure_help.setText(QCoreApplication.translate("shearandmomentscalculator", u"Flexure", None))
        self.actionBeam_Deformation_help.setText(QCoreApplication.translate("shearandmomentscalculator", u"Beam Deformation", None))
        self.actionAxial_Beam_Deformation_help.setText(QCoreApplication.translate("shearandmomentscalculator", u"Axial Beam Deformation", None))
        self.actionTorsional_Beam_Deformation_help.setText(QCoreApplication.translate("shearandmomentscalculator", u"Torsional Beam Deformation", None))
        self.actionSupported_Beams_help.setText(QCoreApplication.translate("shearandmomentscalculator", u"Supported Beams", None))
        self.actionMohr_s_Circle_help.setText(QCoreApplication.translate("shearandmomentscalculator", u"Mohr's Circle", None))
        self.actionC_Clamp_help.setText(QCoreApplication.translate("shearandmomentscalculator", u"C-Clamp", None))
        self.actionCompression_Link_help.setText(QCoreApplication.translate("shearandmomentscalculator", u"Compression Link", None))
        self.actionTension_Link_help.setText(QCoreApplication.translate("shearandmomentscalculator", u"Tension Link", None))
        self.actionPost_help.setText(QCoreApplication.translate("shearandmomentscalculator", u"Post", None))
        self.actionPost_and_Beam_help.setText(QCoreApplication.translate("shearandmomentscalculator", u"Post and Beam", None))
        self.actionSolid_shaft_and_Pipe_help.setText(QCoreApplication.translate("shearandmomentscalculator", u"Solid Shaft and Pipe", None))
        self.actionKinematic_Diagraming_help.setText(QCoreApplication.translate("shearandmomentscalculator", u"Kinematic Diagraming", None))
        self.actionVector_and_Motion_Analysis_help.setText(QCoreApplication.translate("shearandmomentscalculator", u"Vector and Motion Analysis", None))
        self.actionGDT_Checker_help.setText(QCoreApplication.translate("shearandmomentscalculator", u"GDT Checker", None))
        self.actionVirtual_Condition_Calculator_help.setText(QCoreApplication.translate("shearandmomentscalculator", u"Virtual Condition Calculator", None))
        self.actionLimits_and_Fits_help.setText(QCoreApplication.translate("shearandmomentscalculator", u"Limits and Fits", None))
        self.actionGDTFasteners_help.setText(QCoreApplication.translate("shearandmomentscalculator", u"Fasteners", None))
        self.actionPaper_Gauging_help.setText(QCoreApplication.translate("shearandmomentscalculator", u"Paper Gauging", None))
        self.actionTolerance_Finder_help.setText(QCoreApplication.translate("shearandmomentscalculator", u"Tolerance Finder", None))
        self.actionDiameter_Deviation_help.setText(QCoreApplication.translate("shearandmomentscalculator", u"Diameter Deviation", None))
        self.actionTorsion_help.setText(QCoreApplication.translate("shearandmomentscalculator", u"Torsion", None))
        self.actionPressure_help.setText(QCoreApplication.translate("shearandmomentscalculator", u"Pressure", None))
        self.actionTheme.setText(QCoreApplication.translate("shearandmomentscalculator", u"Theme", None))
        self.actionSaftey_Factors.setText(QCoreApplication.translate("shearandmomentscalculator", u"Saftey Factors", None))
        self.actionSolid_Shaft_and_Pipe.setText(QCoreApplication.translate("shearandmomentscalculator", u"Solid Shaft and Pipe", None))
        self.actionMohr_s_Circle_2.setText(QCoreApplication.translate("shearandmomentscalculator", u"Mohr's Circle", None))
        self.actionFit_Classes.setText(QCoreApplication.translate("shearandmomentscalculator", u"Fit Classes", None))
        self.actionShear_and_Moment_Diagrams.setText(QCoreApplication.translate("shearandmomentscalculator", u"Shear and Moment Diagrams", None))
        self.actionSlope_and_Deflection_Diagrams.setText(QCoreApplication.translate("shearandmomentscalculator", u"Slope and Deflection Diagrams", None))
        self.actionGraph_Details.setText(QCoreApplication.translate("shearandmomentscalculator", u"Graph Details", None))
        self.actionDesign.setText(QCoreApplication.translate("shearandmomentscalculator", u"Design", None))
        self.actionFlexural_Stiffness_EI.setText(QCoreApplication.translate("shearandmomentscalculator", u"Flexural Stiffness EI", None))
        self.actionQuit_All.setText(QCoreApplication.translate("shearandmomentscalculator", u"Quit All", None))
        self.actionOutput_Loads_and_Reactions.setText(QCoreApplication.translate("shearandmomentscalculator", u"Output Loads and Reactions", None))
        self.variablesupports.setText("")
        self.lftsidesupport.setText("")
        self.rtsidesupport.setText("")
        self.Uppntload.setText("")
        self.Downpntload.setText("")
        self.lineardistribloadup.setText("")
        self.lineardistribloaddown.setText("")
        self.varibledistribloadup.setText("")
        self.varibdistribloaddown.setText("")
        self.momentccw.setText("")
        self.momentcw.setText("")
        self.label_7.setText(QCoreApplication.translate("shearandmomentscalculator", u"Elements", None))
        self.Beamsetuplength.setTitle(QCoreApplication.translate("shearandmomentscalculator", u"Beam Setup", None))
        self.label_2.setText(QCoreApplication.translate("shearandmomentscalculator", u"Total Beam\n"
"Length", None))
        self.beamlengthunits.setItemText(0, "")
        self.beamlengthunits.setItemText(1, QCoreApplication.translate("shearandmomentscalculator", u"mm", None))
        self.beamlengthunits.setItemText(2, QCoreApplication.translate("shearandmomentscalculator", u"m", None))
        self.beamlengthunits.setItemText(3, QCoreApplication.translate("shearandmomentscalculator", u"in.", None))
        self.beamlengthunits.setItemText(4, QCoreApplication.translate("shearandmomentscalculator", u"ft", None))

        self.supportlocation.setTitle(QCoreApplication.translate("shearandmomentscalculator", u"Support Locations", None))
        self.label_4.setText(QCoreApplication.translate("shearandmomentscalculator", u"Location of\n"
"Left Support", None))
        self.label_5.setText(QCoreApplication.translate("shearandmomentscalculator", u"Location of\n"
"Right Support", None))
        self.label_6.setText(QCoreApplication.translate("shearandmomentscalculator", u"Loads", None))
        self.label_8.setText(QCoreApplication.translate("shearandmomentscalculator", u"Reactions", None))
        self.entersetup.setText(QCoreApplication.translate("shearandmomentscalculator", u"Calculate", None))
        self.label_9.setText(QCoreApplication.translate("shearandmomentscalculator", u"Load Diagram", None))
        self.label_10.setText(QCoreApplication.translate("shearandmomentscalculator", u"Shear Force Diagram", None))
        self.label_11.setText(QCoreApplication.translate("shearandmomentscalculator", u"Moment Diagram", None))
        self.menu_Utilites.setTitle(QCoreApplication.translate("shearandmomentscalculator", u"&Utilites", None))
        self.menu_Help.setTitle(QCoreApplication.translate("shearandmomentscalculator", u"&Help", None))
        self.menuOptions.setTitle(QCoreApplication.translate("shearandmomentscalculator", u"Options", None))
    # retranslateUi

