# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'UnitConverter.ui'
##
## Created by: Qt User Interface Compiler version 6.8.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QAbstractSpinBox, QApplication, QComboBox, QDoubleSpinBox,
    QFrame, QGroupBox, QHBoxLayout, QMainWindow,
    QMenuBar, QSizePolicy, QStatusBar, QTabWidget,
    QVBoxLayout, QWidget)

class Ui_UnitConverter(object):
    def setupUi(self, UnitConverter):
        if not UnitConverter.objectName():
            UnitConverter.setObjectName(u"UnitConverter")
        UnitConverter.setWindowModality(Qt.WindowModality.NonModal)
        UnitConverter.resize(566, 260)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(UnitConverter.sizePolicy().hasHeightForWidth())
        UnitConverter.setSizePolicy(sizePolicy)
        UnitConverter.setMinimumSize(QSize(566, 260))
        UnitConverter.setMaximumSize(QSize(566, 260))
        font = QFont()
        font.setFamilies([u"Arial"])
        font.setPointSize(10)
        UnitConverter.setFont(font)
        UnitConverter.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonFollowStyle)
        UnitConverter.setTabShape(QTabWidget.TabShape.Rounded)
        UnitConverter.setDockNestingEnabled(False)
        UnitConverter.setUnifiedTitleAndToolBarOnMac(False)
        self.actionUnit_Converter = QAction(UnitConverter)
        self.actionUnit_Converter.setObjectName(u"actionUnit_Converter")
        self.actionMoments_of_Inertia = QAction(UnitConverter)
        self.actionMoments_of_Inertia.setObjectName(u"actionMoments_of_Inertia")
        self.actionVectors = QAction(UnitConverter)
        self.actionVectors.setObjectName(u"actionVectors")
        self.actionFriction_and_Force = QAction(UnitConverter)
        self.actionFriction_and_Force.setObjectName(u"actionFriction_and_Force")
        self.actionFasteners = QAction(UnitConverter)
        self.actionFasteners.setObjectName(u"actionFasteners")
        self.actionMaterial_Properties = QAction(UnitConverter)
        self.actionMaterial_Properties.setObjectName(u"actionMaterial_Properties")
        self.actionCM_and_CG = QAction(UnitConverter)
        self.actionCM_and_CG.setObjectName(u"actionCM_and_CG")
        self.actionTrusses = QAction(UnitConverter)
        self.actionTrusses.setObjectName(u"actionTrusses")
        self.actionBeamsMoments_of_Inertia = QAction(UnitConverter)
        self.actionBeamsMoments_of_Inertia.setObjectName(u"actionBeamsMoments_of_Inertia")
        self.actionShear_and_Moment = QAction(UnitConverter)
        self.actionShear_and_Moment.setObjectName(u"actionShear_and_Moment")
        self.actionIndeterminate_Axial_Structures = QAction(UnitConverter)
        self.actionIndeterminate_Axial_Structures.setObjectName(u"actionIndeterminate_Axial_Structures")
        self.actionFlexure = QAction(UnitConverter)
        self.actionFlexure.setObjectName(u"actionFlexure")
        self.actionBeam_Deformation = QAction(UnitConverter)
        self.actionBeam_Deformation.setObjectName(u"actionBeam_Deformation")
        self.actionAxial_Beam_Deformation = QAction(UnitConverter)
        self.actionAxial_Beam_Deformation.setObjectName(u"actionAxial_Beam_Deformation")
        self.actionTorsional_Beam_Deformation = QAction(UnitConverter)
        self.actionTorsional_Beam_Deformation.setObjectName(u"actionTorsional_Beam_Deformation")
        self.actionSupported_Beams = QAction(UnitConverter)
        self.actionSupported_Beams.setObjectName(u"actionSupported_Beams")
        self.actionMohr_s_Circle = QAction(UnitConverter)
        self.actionMohr_s_Circle.setObjectName(u"actionMohr_s_Circle")
        self.actionC_Clamp = QAction(UnitConverter)
        self.actionC_Clamp.setObjectName(u"actionC_Clamp")
        self.actionCompression_Link = QAction(UnitConverter)
        self.actionCompression_Link.setObjectName(u"actionCompression_Link")
        self.actionTension_Link = QAction(UnitConverter)
        self.actionTension_Link.setObjectName(u"actionTension_Link")
        self.actionPost = QAction(UnitConverter)
        self.actionPost.setObjectName(u"actionPost")
        self.actionPost_and_Beam = QAction(UnitConverter)
        self.actionPost_and_Beam.setObjectName(u"actionPost_and_Beam")
        self.actionKinematic_Diagraming = QAction(UnitConverter)
        self.actionKinematic_Diagraming.setObjectName(u"actionKinematic_Diagraming")
        self.actionVector_Analysis = QAction(UnitConverter)
        self.actionVector_Analysis.setObjectName(u"actionVector_Analysis")
        self.actionGDT_Checker = QAction(UnitConverter)
        self.actionGDT_Checker.setObjectName(u"actionGDT_Checker")
        self.actionVirtual_Condition_Calculator = QAction(UnitConverter)
        self.actionVirtual_Condition_Calculator.setObjectName(u"actionVirtual_Condition_Calculator")
        self.actionLimits_and_Fits = QAction(UnitConverter)
        self.actionLimits_and_Fits.setObjectName(u"actionLimits_and_Fits")
        self.actionGDTFasteners = QAction(UnitConverter)
        self.actionGDTFasteners.setObjectName(u"actionGDTFasteners")
        self.actionPaper_Gauging = QAction(UnitConverter)
        self.actionPaper_Gauging.setObjectName(u"actionPaper_Gauging")
        self.actionTolerance_Finder = QAction(UnitConverter)
        self.actionTolerance_Finder.setObjectName(u"actionTolerance_Finder")
        self.actionDiameter_Deviation = QAction(UnitConverter)
        self.actionDiameter_Deviation.setObjectName(u"actionDiameter_Deviation")
        self.actionTorsion = QAction(UnitConverter)
        self.actionTorsion.setObjectName(u"actionTorsion")
        self.actionPressure = QAction(UnitConverter)
        self.actionPressure.setObjectName(u"actionPressure")
        self.actionAddMohr_s_Circle = QAction(UnitConverter)
        self.actionAddMohr_s_Circle.setObjectName(u"actionAddMohr_s_Circle")
        self.actionModule_List = QAction(UnitConverter)
        self.actionModule_List.setObjectName(u"actionModule_List")
        self.actionQuit = QAction(UnitConverter)
        self.actionQuit.setObjectName(u"actionQuit")
        self.actionNotepad = QAction(UnitConverter)
        self.actionNotepad.setObjectName(u"actionNotepad")
        self.actionCalculator = QAction(UnitConverter)
        self.actionCalculator.setObjectName(u"actionCalculator")
        self.actionScreenshot = QAction(UnitConverter)
        self.actionScreenshot.setObjectName(u"actionScreenshot")
        self.actionPerfer_SI_units = QAction(UnitConverter)
        self.actionPerfer_SI_units.setObjectName(u"actionPerfer_SI_units")
        self.actionPerfer_Metric_Units = QAction(UnitConverter)
        self.actionPerfer_Metric_Units.setObjectName(u"actionPerfer_Metric_Units")
        self.actionMaterials_list = QAction(UnitConverter)
        self.actionMaterials_list.setObjectName(u"actionMaterials_list")
        self.actionCross_Sectional_Beams_and_Shapes_Lists = QAction(UnitConverter)
        self.actionCross_Sectional_Beams_and_Shapes_Lists.setObjectName(u"actionCross_Sectional_Beams_and_Shapes_Lists")
        self.actionAbout = QAction(UnitConverter)
        self.actionAbout.setObjectName(u"actionAbout")
        self.actionUnit_Converter_help = QAction(UnitConverter)
        self.actionUnit_Converter_help.setObjectName(u"actionUnit_Converter_help")
        self.actionMoments_of_Inertia_help = QAction(UnitConverter)
        self.actionMoments_of_Inertia_help.setObjectName(u"actionMoments_of_Inertia_help")
        self.actionVectors_help = QAction(UnitConverter)
        self.actionVectors_help.setObjectName(u"actionVectors_help")
        self.actionFriction_and_Force_help = QAction(UnitConverter)
        self.actionFriction_and_Force_help.setObjectName(u"actionFriction_and_Force_help")
        self.actionFasteners_help = QAction(UnitConverter)
        self.actionFasteners_help.setObjectName(u"actionFasteners_help")
        self.actionMaterial_Properties_help = QAction(UnitConverter)
        self.actionMaterial_Properties_help.setObjectName(u"actionMaterial_Properties_help")
        self.actionCM_and_CG_help = QAction(UnitConverter)
        self.actionCM_and_CG_help.setObjectName(u"actionCM_and_CG_help")
        self.actionTrusses_help = QAction(UnitConverter)
        self.actionTrusses_help.setObjectName(u"actionTrusses_help")
        self.actionBeamsMoments_of_Inertia_help = QAction(UnitConverter)
        self.actionBeamsMoments_of_Inertia_help.setObjectName(u"actionBeamsMoments_of_Inertia_help")
        self.actionShear_and_Moment_help = QAction(UnitConverter)
        self.actionShear_and_Moment_help.setObjectName(u"actionShear_and_Moment_help")
        self.actionIndeterminate_Axial_Structures_help = QAction(UnitConverter)
        self.actionIndeterminate_Axial_Structures_help.setObjectName(u"actionIndeterminate_Axial_Structures_help")
        self.actionFlexure_help = QAction(UnitConverter)
        self.actionFlexure_help.setObjectName(u"actionFlexure_help")
        self.actionBeam_Deformation_help = QAction(UnitConverter)
        self.actionBeam_Deformation_help.setObjectName(u"actionBeam_Deformation_help")
        self.actionAxial_Beam_Deformation_help = QAction(UnitConverter)
        self.actionAxial_Beam_Deformation_help.setObjectName(u"actionAxial_Beam_Deformation_help")
        self.actionTorsional_Beam_Deformation_help = QAction(UnitConverter)
        self.actionTorsional_Beam_Deformation_help.setObjectName(u"actionTorsional_Beam_Deformation_help")
        self.actionSupported_Beams_help = QAction(UnitConverter)
        self.actionSupported_Beams_help.setObjectName(u"actionSupported_Beams_help")
        self.actionMohr_s_Circle_help = QAction(UnitConverter)
        self.actionMohr_s_Circle_help.setObjectName(u"actionMohr_s_Circle_help")
        self.actionC_Clamp_help = QAction(UnitConverter)
        self.actionC_Clamp_help.setObjectName(u"actionC_Clamp_help")
        self.actionCompression_Link_help = QAction(UnitConverter)
        self.actionCompression_Link_help.setObjectName(u"actionCompression_Link_help")
        self.actionTension_Link_help = QAction(UnitConverter)
        self.actionTension_Link_help.setObjectName(u"actionTension_Link_help")
        self.actionPost_help = QAction(UnitConverter)
        self.actionPost_help.setObjectName(u"actionPost_help")
        self.actionPost_and_Beam_help = QAction(UnitConverter)
        self.actionPost_and_Beam_help.setObjectName(u"actionPost_and_Beam_help")
        self.actionSolid_shaft_and_Pipe_help = QAction(UnitConverter)
        self.actionSolid_shaft_and_Pipe_help.setObjectName(u"actionSolid_shaft_and_Pipe_help")
        self.actionKinematic_Diagraming_help = QAction(UnitConverter)
        self.actionKinematic_Diagraming_help.setObjectName(u"actionKinematic_Diagraming_help")
        self.actionVector_and_Motion_Analysis_help = QAction(UnitConverter)
        self.actionVector_and_Motion_Analysis_help.setObjectName(u"actionVector_and_Motion_Analysis_help")
        self.actionGDT_Checker_help = QAction(UnitConverter)
        self.actionGDT_Checker_help.setObjectName(u"actionGDT_Checker_help")
        self.actionVirtual_Condition_Calculator_help = QAction(UnitConverter)
        self.actionVirtual_Condition_Calculator_help.setObjectName(u"actionVirtual_Condition_Calculator_help")
        self.actionLimits_and_Fits_help = QAction(UnitConverter)
        self.actionLimits_and_Fits_help.setObjectName(u"actionLimits_and_Fits_help")
        self.actionGDTFasteners_help = QAction(UnitConverter)
        self.actionGDTFasteners_help.setObjectName(u"actionGDTFasteners_help")
        self.actionPaper_Gauging_help = QAction(UnitConverter)
        self.actionPaper_Gauging_help.setObjectName(u"actionPaper_Gauging_help")
        self.actionTolerance_Finder_help = QAction(UnitConverter)
        self.actionTolerance_Finder_help.setObjectName(u"actionTolerance_Finder_help")
        self.actionDiameter_Deviation_help = QAction(UnitConverter)
        self.actionDiameter_Deviation_help.setObjectName(u"actionDiameter_Deviation_help")
        self.actionTorsion_help = QAction(UnitConverter)
        self.actionTorsion_help.setObjectName(u"actionTorsion_help")
        self.actionPressure_help = QAction(UnitConverter)
        self.actionPressure_help.setObjectName(u"actionPressure_help")
        self.actionTheme = QAction(UnitConverter)
        self.actionTheme.setObjectName(u"actionTheme")
        self.actionSaftey_Factors = QAction(UnitConverter)
        self.actionSaftey_Factors.setObjectName(u"actionSaftey_Factors")
        self.actionSolid_Shaft_and_Pipe = QAction(UnitConverter)
        self.actionSolid_Shaft_and_Pipe.setObjectName(u"actionSolid_Shaft_and_Pipe")
        self.actionMohr_s_Circle_2 = QAction(UnitConverter)
        self.actionMohr_s_Circle_2.setObjectName(u"actionMohr_s_Circle_2")
        self.actionFit_Classes = QAction(UnitConverter)
        self.actionFit_Classes.setObjectName(u"actionFit_Classes")
        self.actionUnit_Settings = QAction(UnitConverter)
        self.actionUnit_Settings.setObjectName(u"actionUnit_Settings")
        self.actionQuit_All = QAction(UnitConverter)
        self.actionQuit_All.setObjectName(u"actionQuit_All")
        self.centralwidget = QWidget(UnitConverter)
        self.centralwidget.setObjectName(u"centralwidget")
        self.groupBox_2 = QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(10, 170, 548, 67))
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy1)
        self.groupBox_2.setFont(font)
        self.verticalLayout_4 = QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.horizontalLayout_5 = QHBoxLayout()
        self.horizontalLayout_5.setObjectName(u"horizontalLayout_5")
        self.NUMunit_output = QDoubleSpinBox(self.groupBox_2)
        self.NUMunit_output.setObjectName(u"NUMunit_output")
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.NUMunit_output.sizePolicy().hasHeightForWidth())
        self.NUMunit_output.setSizePolicy(sizePolicy2)
        self.NUMunit_output.setMinimumSize(QSize(140, 30))
        self.NUMunit_output.setMaximumSize(QSize(140, 30))
        self.NUMunit_output.setFont(font)
        self.NUMunit_output.setWrapping(True)
        self.NUMunit_output.setReadOnly(True)
        self.NUMunit_output.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.NUMunit_output.setDecimals(10)
        self.NUMunit_output.setMinimum(-99999999999999995164818811802792197885196090803013355167206819763650035712.000000000000000)
        self.NUMunit_output.setMaximum(99999999999999995164818811802792197885196090803013355167206819763650035712.000000000000000)

        self.horizontalLayout_5.addWidget(self.NUMunit_output)

        self.units_to = QComboBox(self.groupBox_2)
        self.units_to.setObjectName(u"units_to")
        sizePolicy2.setHeightForWidth(self.units_to.sizePolicy().hasHeightForWidth())
        self.units_to.setSizePolicy(sizePolicy2)
        self.units_to.setMinimumSize(QSize(380, 30))
        self.units_to.setMaximumSize(QSize(380, 30))
        self.units_to.setFont(font)
        self.units_to.setMaxVisibleItems(20)

        self.horizontalLayout_5.addWidget(self.units_to)


        self.verticalLayout_4.addLayout(self.horizontalLayout_5)

        self.frame = QFrame(self.centralwidget)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(9, 9, 548, 85))
        sizePolicy1.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy1)
        self.frame.setMaximumSize(QSize(16777215, 85))
        self.frame.setFont(font)
        self.frame.setFrameShape(QFrame.Shape.WinPanel)
        self.frame.setFrameShadow(QFrame.Shadow.Raised)
        self.frame.setLineWidth(2)
        self.frame.setMidLineWidth(2)
        self.horizontalLayout_4 = QHBoxLayout(self.frame)
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.groupBox_3 = QGroupBox(self.frame)
        self.groupBox_3.setObjectName(u"groupBox_3")
        sizePolicy2.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy2)
        self.groupBox_3.setMinimumSize(QSize(180, 0))
        self.groupBox_3.setMaximumSize(QSize(16777215, 16777215))
        self.groupBox_3.setFont(font)
        self.groupBox_3.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.horizontalLayout_6 = QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_6.setObjectName(u"horizontalLayout_6")
        self.unitstyle = QComboBox(self.groupBox_3)
        self.unitstyle.setObjectName(u"unitstyle")
        sizePolicy2.setHeightForWidth(self.unitstyle.sizePolicy().hasHeightForWidth())
        self.unitstyle.setSizePolicy(sizePolicy2)
        self.unitstyle.setMinimumSize(QSize(0, 30))
        self.unitstyle.setMaximumSize(QSize(16777215, 30))
        self.unitstyle.setFont(font)

        self.horizontalLayout_6.addWidget(self.unitstyle)


        self.horizontalLayout_4.addWidget(self.groupBox_3)

        self.groupBox_4 = QGroupBox(self.frame)
        self.groupBox_4.setObjectName(u"groupBox_4")
        sizePolicy2.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy2)
        self.groupBox_4.setMinimumSize(QSize(0, 0))
        self.groupBox_4.setMaximumSize(QSize(16777215, 16777215))
        self.groupBox_4.setFont(font)
        self.groupBox_4.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.horizontalLayout_2 = QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.unitplane = QComboBox(self.groupBox_4)
        self.unitplane.setObjectName(u"unitplane")
        sizePolicy2.setHeightForWidth(self.unitplane.sizePolicy().hasHeightForWidth())
        self.unitplane.setSizePolicy(sizePolicy2)
        self.unitplane.setMinimumSize(QSize(0, 30))
        self.unitplane.setMaximumSize(QSize(16777215, 30))
        self.unitplane.setFont(font)

        self.horizontalLayout_2.addWidget(self.unitplane)


        self.horizontalLayout_4.addWidget(self.groupBox_4)

        self.groupBox_5 = QGroupBox(self.frame)
        self.groupBox_5.setObjectName(u"groupBox_5")
        sizePolicy2.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy2)
        self.groupBox_5.setMinimumSize(QSize(185, 0))
        self.groupBox_5.setMaximumSize(QSize(16777215, 16777215))
        self.groupBox_5.setFont(font)
        self.groupBox_5.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.groupBox_5.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.verticalLayout_2 = QVBoxLayout(self.groupBox_5)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.unitsubcat = QComboBox(self.groupBox_5)
        self.unitsubcat.setObjectName(u"unitsubcat")
        sizePolicy2.setHeightForWidth(self.unitsubcat.sizePolicy().hasHeightForWidth())
        self.unitsubcat.setSizePolicy(sizePolicy2)
        self.unitsubcat.setMinimumSize(QSize(0, 30))
        self.unitsubcat.setMaximumSize(QSize(16777215, 30))
        self.unitsubcat.setFont(font)
        self.unitsubcat.setMaxVisibleItems(15)

        self.verticalLayout_2.addWidget(self.unitsubcat)


        self.horizontalLayout_4.addWidget(self.groupBox_5)

        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, 100, 548, 67))
        sizePolicy3 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy3)
        self.groupBox.setFont(font)
        self.verticalLayout = QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.NUMunit_input = QDoubleSpinBox(self.groupBox)
        self.NUMunit_input.setObjectName(u"NUMunit_input")
        sizePolicy2.setHeightForWidth(self.NUMunit_input.sizePolicy().hasHeightForWidth())
        self.NUMunit_input.setSizePolicy(sizePolicy2)
        self.NUMunit_input.setMinimumSize(QSize(140, 30))
        self.NUMunit_input.setMaximumSize(QSize(140, 30))
        self.NUMunit_input.setFont(font)
        self.NUMunit_input.setWrapping(True)
        self.NUMunit_input.setDecimals(10)
        self.NUMunit_input.setMinimum(-99999999999999995164818811802792197885196090803013355167206819763650035712.000000000000000)
        self.NUMunit_input.setMaximum(99999999999999995164818811802792197885196090803013355167206819763650035712.000000000000000)
        self.NUMunit_input.setStepType(QAbstractSpinBox.StepType.DefaultStepType)

        self.horizontalLayout.addWidget(self.NUMunit_input)

        self.units_from = QComboBox(self.groupBox)
        self.units_from.setObjectName(u"units_from")
        sizePolicy2.setHeightForWidth(self.units_from.sizePolicy().hasHeightForWidth())
        self.units_from.setSizePolicy(sizePolicy2)
        self.units_from.setMinimumSize(QSize(380, 30))
        self.units_from.setMaximumSize(QSize(380, 30))
        self.units_from.setFont(font)
        self.units_from.setMaxVisibleItems(20)

        self.horizontalLayout.addWidget(self.units_from)


        self.verticalLayout.addLayout(self.horizontalLayout)

        UnitConverter.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(UnitConverter)
        self.statusbar.setObjectName(u"statusbar")
        UnitConverter.setStatusBar(self.statusbar)
        self.menubar = QMenuBar(UnitConverter)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 566, 33))
        UnitConverter.setMenuBar(self.menubar)

        self.retranslateUi(UnitConverter)
        self.unitplane.currentTextChanged.connect(self.unitsubcat.setCurrentText)
        self.unitstyle.currentTextChanged.connect(self.unitsubcat.setCurrentText)

        QMetaObject.connectSlotsByName(UnitConverter)
    # setupUi

    def retranslateUi(self, UnitConverter):
        UnitConverter.setWindowTitle("")
        self.actionUnit_Converter.setText(QCoreApplication.translate("UnitConverter", u"Unit Converter", None))
        self.actionMoments_of_Inertia.setText(QCoreApplication.translate("UnitConverter", u"Moments of Inertia", None))
        self.actionVectors.setText(QCoreApplication.translate("UnitConverter", u"Vectors", None))
        self.actionFriction_and_Force.setText(QCoreApplication.translate("UnitConverter", u"Friction and Force", None))
        self.actionFasteners.setText(QCoreApplication.translate("UnitConverter", u"Fasteners", None))
        self.actionMaterial_Properties.setText(QCoreApplication.translate("UnitConverter", u"Material Properties", None))
        self.actionCM_and_CG.setText(QCoreApplication.translate("UnitConverter", u"CM and CG", None))
        self.actionTrusses.setText(QCoreApplication.translate("UnitConverter", u"Trusses", None))
        self.actionBeamsMoments_of_Inertia.setText(QCoreApplication.translate("UnitConverter", u"Moments of Inertia", None))
        self.actionShear_and_Moment.setText(QCoreApplication.translate("UnitConverter", u"Shear and Moment", None))
        self.actionIndeterminate_Axial_Structures.setText(QCoreApplication.translate("UnitConverter", u"Indeterminate Axial Structures", None))
        self.actionFlexure.setText(QCoreApplication.translate("UnitConverter", u"Flexure", None))
        self.actionBeam_Deformation.setText(QCoreApplication.translate("UnitConverter", u"Beam Deformation", None))
        self.actionAxial_Beam_Deformation.setText(QCoreApplication.translate("UnitConverter", u"Axial Beam Deformation", None))
        self.actionTorsional_Beam_Deformation.setText(QCoreApplication.translate("UnitConverter", u"Torsional Beam Deformation", None))
        self.actionSupported_Beams.setText(QCoreApplication.translate("UnitConverter", u"Supported Beams", None))
        self.actionMohr_s_Circle.setText(QCoreApplication.translate("UnitConverter", u"Mohr's Circle", None))
        self.actionC_Clamp.setText(QCoreApplication.translate("UnitConverter", u"C-Clamp", None))
        self.actionCompression_Link.setText(QCoreApplication.translate("UnitConverter", u"Compression Link", None))
        self.actionTension_Link.setText(QCoreApplication.translate("UnitConverter", u"Tension Link", None))
        self.actionPost.setText(QCoreApplication.translate("UnitConverter", u"Post", None))
        self.actionPost_and_Beam.setText(QCoreApplication.translate("UnitConverter", u"Post and Beam", None))
        self.actionKinematic_Diagraming.setText(QCoreApplication.translate("UnitConverter", u"Kinematic Diagraming", None))
        self.actionVector_Analysis.setText(QCoreApplication.translate("UnitConverter", u"Vector Analysis", None))
        self.actionGDT_Checker.setText(QCoreApplication.translate("UnitConverter", u"GDT Checker", None))
        self.actionVirtual_Condition_Calculator.setText(QCoreApplication.translate("UnitConverter", u"Virtual Condition Calculator", None))
        self.actionLimits_and_Fits.setText(QCoreApplication.translate("UnitConverter", u"Limits and Fits", None))
        self.actionGDTFasteners.setText(QCoreApplication.translate("UnitConverter", u"Fasteners", None))
        self.actionPaper_Gauging.setText(QCoreApplication.translate("UnitConverter", u"Paper Gauging", None))
        self.actionTolerance_Finder.setText(QCoreApplication.translate("UnitConverter", u"Tolerance Finder", None))
        self.actionDiameter_Deviation.setText(QCoreApplication.translate("UnitConverter", u"Diameter Deviation", None))
        self.actionTorsion.setText(QCoreApplication.translate("UnitConverter", u"Torsion", None))
        self.actionPressure.setText(QCoreApplication.translate("UnitConverter", u"Pressure", None))
        self.actionAddMohr_s_Circle.setText(QCoreApplication.translate("UnitConverter", u"Mohr's Circle", None))
        self.actionModule_List.setText(QCoreApplication.translate("UnitConverter", u"Module List", None))
        self.actionQuit.setText(QCoreApplication.translate("UnitConverter", u"Quit", None))
        self.actionNotepad.setText(QCoreApplication.translate("UnitConverter", u"Notepad", None))
        self.actionCalculator.setText(QCoreApplication.translate("UnitConverter", u"Calculator", None))
        self.actionScreenshot.setText(QCoreApplication.translate("UnitConverter", u"Screenshot", None))
        self.actionPerfer_SI_units.setText(QCoreApplication.translate("UnitConverter", u"Edit Saftey Factor", None))
        self.actionPerfer_Metric_Units.setText(QCoreApplication.translate("UnitConverter", u"Theme", None))
        self.actionMaterials_list.setText(QCoreApplication.translate("UnitConverter", u"Materials List", None))
        self.actionCross_Sectional_Beams_and_Shapes_Lists.setText(QCoreApplication.translate("UnitConverter", u"Beams and Shapes Lists", None))
        self.actionAbout.setText(QCoreApplication.translate("UnitConverter", u"About", None))
        self.actionUnit_Converter_help.setText(QCoreApplication.translate("UnitConverter", u"Unit Converter", None))
        self.actionMoments_of_Inertia_help.setText(QCoreApplication.translate("UnitConverter", u"Moments of Inertia", None))
        self.actionVectors_help.setText(QCoreApplication.translate("UnitConverter", u"Vectors", None))
        self.actionFriction_and_Force_help.setText(QCoreApplication.translate("UnitConverter", u"Friction and Force", None))
        self.actionFasteners_help.setText(QCoreApplication.translate("UnitConverter", u"Fasteners", None))
        self.actionMaterial_Properties_help.setText(QCoreApplication.translate("UnitConverter", u"Material Properties", None))
        self.actionCM_and_CG_help.setText(QCoreApplication.translate("UnitConverter", u"CM and CG", None))
        self.actionTrusses_help.setText(QCoreApplication.translate("UnitConverter", u"Trusses", None))
        self.actionBeamsMoments_of_Inertia_help.setText(QCoreApplication.translate("UnitConverter", u"Moments of Inertia", None))
        self.actionShear_and_Moment_help.setText(QCoreApplication.translate("UnitConverter", u"Shear and Moment", None))
        self.actionIndeterminate_Axial_Structures_help.setText(QCoreApplication.translate("UnitConverter", u"Indeterminate Axial Structures", None))
        self.actionFlexure_help.setText(QCoreApplication.translate("UnitConverter", u"Flexure", None))
        self.actionBeam_Deformation_help.setText(QCoreApplication.translate("UnitConverter", u"Beam Deformation", None))
        self.actionAxial_Beam_Deformation_help.setText(QCoreApplication.translate("UnitConverter", u"Axial Beam Deformation", None))
        self.actionTorsional_Beam_Deformation_help.setText(QCoreApplication.translate("UnitConverter", u"Torsional Beam Deformation", None))
        self.actionSupported_Beams_help.setText(QCoreApplication.translate("UnitConverter", u"Supported Beams", None))
        self.actionMohr_s_Circle_help.setText(QCoreApplication.translate("UnitConverter", u"Mohr's Circle", None))
        self.actionC_Clamp_help.setText(QCoreApplication.translate("UnitConverter", u"C-Clamp", None))
        self.actionCompression_Link_help.setText(QCoreApplication.translate("UnitConverter", u"Compression Link", None))
        self.actionTension_Link_help.setText(QCoreApplication.translate("UnitConverter", u"Tension Link", None))
        self.actionPost_help.setText(QCoreApplication.translate("UnitConverter", u"Post", None))
        self.actionPost_and_Beam_help.setText(QCoreApplication.translate("UnitConverter", u"Post and Beam", None))
        self.actionSolid_shaft_and_Pipe_help.setText(QCoreApplication.translate("UnitConverter", u"Solid Shaft and Pipe", None))
        self.actionKinematic_Diagraming_help.setText(QCoreApplication.translate("UnitConverter", u"Kinematic Diagraming", None))
        self.actionVector_and_Motion_Analysis_help.setText(QCoreApplication.translate("UnitConverter", u"Vector and Motion Analysis", None))
        self.actionGDT_Checker_help.setText(QCoreApplication.translate("UnitConverter", u"GDT Checker", None))
        self.actionVirtual_Condition_Calculator_help.setText(QCoreApplication.translate("UnitConverter", u"Virtual Condition Calculator", None))
        self.actionLimits_and_Fits_help.setText(QCoreApplication.translate("UnitConverter", u"Limits and Fits", None))
        self.actionGDTFasteners_help.setText(QCoreApplication.translate("UnitConverter", u"Fasteners", None))
        self.actionPaper_Gauging_help.setText(QCoreApplication.translate("UnitConverter", u"Paper Gauging", None))
        self.actionTolerance_Finder_help.setText(QCoreApplication.translate("UnitConverter", u"Tolerance Finder", None))
        self.actionDiameter_Deviation_help.setText(QCoreApplication.translate("UnitConverter", u"Diameter Deviation", None))
        self.actionTorsion_help.setText(QCoreApplication.translate("UnitConverter", u"Torsion", None))
        self.actionPressure_help.setText(QCoreApplication.translate("UnitConverter", u"Pressure", None))
        self.actionTheme.setText(QCoreApplication.translate("UnitConverter", u"Theme", None))
        self.actionSaftey_Factors.setText(QCoreApplication.translate("UnitConverter", u"Saftey Factors", None))
        self.actionSolid_Shaft_and_Pipe.setText(QCoreApplication.translate("UnitConverter", u"Solid Shaft and Pipe", None))
        self.actionMohr_s_Circle_2.setText(QCoreApplication.translate("UnitConverter", u"Mohr's Circle", None))
        self.actionFit_Classes.setText(QCoreApplication.translate("UnitConverter", u"Fit Classes", None))
        self.actionUnit_Settings.setText(QCoreApplication.translate("UnitConverter", u"Unit Settings", None))
        self.actionQuit_All.setText(QCoreApplication.translate("UnitConverter", u"Quit All", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("UnitConverter", u"To", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("UnitConverter", u"Converter Type", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("UnitConverter", u"Unit Plane", None))
        self.groupBox_5.setTitle(QCoreApplication.translate("UnitConverter", u"Unit Category", None))
        self.unitsubcat.setCurrentText("")
        self.groupBox.setTitle(QCoreApplication.translate("UnitConverter", u"From", None))
    # retranslateUi

