# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'MOIshapeselector.ui'
##
## Created by: Qt User Interface Compiler version 6.8.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QLayout, QMainWindow,
    QMenu, QMenuBar, QPushButton, QSizePolicy,
    QStatusBar, QTabWidget, QToolBox, QWidget)

class Ui_MOIshapeselect(object):
    def setupUi(self, MOIshapeselect):
        if not MOIshapeselect.objectName():
            MOIshapeselect.setObjectName(u"MOIshapeselect")
        MOIshapeselect.resize(400, 770)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MOIshapeselect.sizePolicy().hasHeightForWidth())
        MOIshapeselect.setSizePolicy(sizePolicy)
        MOIshapeselect.setMinimumSize(QSize(400, 770))
        MOIshapeselect.setMaximumSize(QSize(400, 770))
        MOIshapeselect.setTabShape(QTabWidget.Rounded)
        MOIshapeselect.setDockNestingEnabled(False)
        MOIshapeselect.setUnifiedTitleAndToolBarOnMac(False)
        self.actionUnit_Converter = QAction(MOIshapeselect)
        self.actionUnit_Converter.setObjectName(u"actionUnit_Converter")
        self.actionMoments_of_Inertia = QAction(MOIshapeselect)
        self.actionMoments_of_Inertia.setObjectName(u"actionMoments_of_Inertia")
        self.actionVectors = QAction(MOIshapeselect)
        self.actionVectors.setObjectName(u"actionVectors")
        self.actionFriction_and_Force = QAction(MOIshapeselect)
        self.actionFriction_and_Force.setObjectName(u"actionFriction_and_Force")
        self.actionFasteners = QAction(MOIshapeselect)
        self.actionFasteners.setObjectName(u"actionFasteners")
        self.actionMaterial_Properties = QAction(MOIshapeselect)
        self.actionMaterial_Properties.setObjectName(u"actionMaterial_Properties")
        self.actionCM_and_CG = QAction(MOIshapeselect)
        self.actionCM_and_CG.setObjectName(u"actionCM_and_CG")
        self.actionTrusses = QAction(MOIshapeselect)
        self.actionTrusses.setObjectName(u"actionTrusses")
        self.actionBeamsMoments_of_Inertia = QAction(MOIshapeselect)
        self.actionBeamsMoments_of_Inertia.setObjectName(u"actionBeamsMoments_of_Inertia")
        self.actionShear_and_Moment = QAction(MOIshapeselect)
        self.actionShear_and_Moment.setObjectName(u"actionShear_and_Moment")
        self.actionIndeterminate_Axial_Structures = QAction(MOIshapeselect)
        self.actionIndeterminate_Axial_Structures.setObjectName(u"actionIndeterminate_Axial_Structures")
        self.actionFlexure = QAction(MOIshapeselect)
        self.actionFlexure.setObjectName(u"actionFlexure")
        self.actionBeam_Deformation = QAction(MOIshapeselect)
        self.actionBeam_Deformation.setObjectName(u"actionBeam_Deformation")
        self.actionAxial_Beam_Deformation = QAction(MOIshapeselect)
        self.actionAxial_Beam_Deformation.setObjectName(u"actionAxial_Beam_Deformation")
        self.actionTorsional_Beam_Deformation = QAction(MOIshapeselect)
        self.actionTorsional_Beam_Deformation.setObjectName(u"actionTorsional_Beam_Deformation")
        self.actionSupported_Beams = QAction(MOIshapeselect)
        self.actionSupported_Beams.setObjectName(u"actionSupported_Beams")
        self.actionMohr_s_Circle = QAction(MOIshapeselect)
        self.actionMohr_s_Circle.setObjectName(u"actionMohr_s_Circle")
        self.actionC_Clamp = QAction(MOIshapeselect)
        self.actionC_Clamp.setObjectName(u"actionC_Clamp")
        self.actionCompression_Link = QAction(MOIshapeselect)
        self.actionCompression_Link.setObjectName(u"actionCompression_Link")
        self.actionTension_Link = QAction(MOIshapeselect)
        self.actionTension_Link.setObjectName(u"actionTension_Link")
        self.actionPost = QAction(MOIshapeselect)
        self.actionPost.setObjectName(u"actionPost")
        self.actionPost_and_Beam = QAction(MOIshapeselect)
        self.actionPost_and_Beam.setObjectName(u"actionPost_and_Beam")
        self.actionKinematic_Diagraming = QAction(MOIshapeselect)
        self.actionKinematic_Diagraming.setObjectName(u"actionKinematic_Diagraming")
        self.actionVector_Analysis = QAction(MOIshapeselect)
        self.actionVector_Analysis.setObjectName(u"actionVector_Analysis")
        self.actionGDT_Checker = QAction(MOIshapeselect)
        self.actionGDT_Checker.setObjectName(u"actionGDT_Checker")
        self.actionVirtual_Condition_Calculator = QAction(MOIshapeselect)
        self.actionVirtual_Condition_Calculator.setObjectName(u"actionVirtual_Condition_Calculator")
        self.actionLimits_and_Fits = QAction(MOIshapeselect)
        self.actionLimits_and_Fits.setObjectName(u"actionLimits_and_Fits")
        self.actionGDTFasteners = QAction(MOIshapeselect)
        self.actionGDTFasteners.setObjectName(u"actionGDTFasteners")
        self.actionPaper_Gauging = QAction(MOIshapeselect)
        self.actionPaper_Gauging.setObjectName(u"actionPaper_Gauging")
        self.actionTolerance_Finder = QAction(MOIshapeselect)
        self.actionTolerance_Finder.setObjectName(u"actionTolerance_Finder")
        self.actionDiameter_Deviation = QAction(MOIshapeselect)
        self.actionDiameter_Deviation.setObjectName(u"actionDiameter_Deviation")
        self.actionTorsion = QAction(MOIshapeselect)
        self.actionTorsion.setObjectName(u"actionTorsion")
        self.actionPressure = QAction(MOIshapeselect)
        self.actionPressure.setObjectName(u"actionPressure")
        self.actionAddMohr_s_Circle = QAction(MOIshapeselect)
        self.actionAddMohr_s_Circle.setObjectName(u"actionAddMohr_s_Circle")
        self.actionModule_List = QAction(MOIshapeselect)
        self.actionModule_List.setObjectName(u"actionModule_List")
        self.actionQuit = QAction(MOIshapeselect)
        self.actionQuit.setObjectName(u"actionQuit")
        self.actionNotepad = QAction(MOIshapeselect)
        self.actionNotepad.setObjectName(u"actionNotepad")
        self.actionCalculator = QAction(MOIshapeselect)
        self.actionCalculator.setObjectName(u"actionCalculator")
        self.actionScreenshot = QAction(MOIshapeselect)
        self.actionScreenshot.setObjectName(u"actionScreenshot")
        self.actionPerfer_SI_units = QAction(MOIshapeselect)
        self.actionPerfer_SI_units.setObjectName(u"actionPerfer_SI_units")
        self.actionPerfer_Metric_Units = QAction(MOIshapeselect)
        self.actionPerfer_Metric_Units.setObjectName(u"actionPerfer_Metric_Units")
        self.actionMaterials_list = QAction(MOIshapeselect)
        self.actionMaterials_list.setObjectName(u"actionMaterials_list")
        self.actionCross_Sectional_Beams_and_Shapes_Lists = QAction(MOIshapeselect)
        self.actionCross_Sectional_Beams_and_Shapes_Lists.setObjectName(u"actionCross_Sectional_Beams_and_Shapes_Lists")
        self.actionAbout = QAction(MOIshapeselect)
        self.actionAbout.setObjectName(u"actionAbout")
        self.actionUnit_Converter_help = QAction(MOIshapeselect)
        self.actionUnit_Converter_help.setObjectName(u"actionUnit_Converter_help")
        self.actionMoments_of_Inertia_help = QAction(MOIshapeselect)
        self.actionMoments_of_Inertia_help.setObjectName(u"actionMoments_of_Inertia_help")
        self.actionVectors_help = QAction(MOIshapeselect)
        self.actionVectors_help.setObjectName(u"actionVectors_help")
        self.actionFriction_and_Force_help = QAction(MOIshapeselect)
        self.actionFriction_and_Force_help.setObjectName(u"actionFriction_and_Force_help")
        self.actionFasteners_help = QAction(MOIshapeselect)
        self.actionFasteners_help.setObjectName(u"actionFasteners_help")
        self.actionMaterial_Properties_help = QAction(MOIshapeselect)
        self.actionMaterial_Properties_help.setObjectName(u"actionMaterial_Properties_help")
        self.actionCM_and_CG_help = QAction(MOIshapeselect)
        self.actionCM_and_CG_help.setObjectName(u"actionCM_and_CG_help")
        self.actionTrusses_help = QAction(MOIshapeselect)
        self.actionTrusses_help.setObjectName(u"actionTrusses_help")
        self.actionBeamsMoments_of_Inertia_help = QAction(MOIshapeselect)
        self.actionBeamsMoments_of_Inertia_help.setObjectName(u"actionBeamsMoments_of_Inertia_help")
        self.actionShear_and_Moment_help = QAction(MOIshapeselect)
        self.actionShear_and_Moment_help.setObjectName(u"actionShear_and_Moment_help")
        self.actionIndeterminate_Axial_Structures_help = QAction(MOIshapeselect)
        self.actionIndeterminate_Axial_Structures_help.setObjectName(u"actionIndeterminate_Axial_Structures_help")
        self.actionFlexure_help = QAction(MOIshapeselect)
        self.actionFlexure_help.setObjectName(u"actionFlexure_help")
        self.actionBeam_Deformation_help = QAction(MOIshapeselect)
        self.actionBeam_Deformation_help.setObjectName(u"actionBeam_Deformation_help")
        self.actionAxial_Beam_Deformation_help = QAction(MOIshapeselect)
        self.actionAxial_Beam_Deformation_help.setObjectName(u"actionAxial_Beam_Deformation_help")
        self.actionTorsional_Beam_Deformation_help = QAction(MOIshapeselect)
        self.actionTorsional_Beam_Deformation_help.setObjectName(u"actionTorsional_Beam_Deformation_help")
        self.actionSupported_Beams_help = QAction(MOIshapeselect)
        self.actionSupported_Beams_help.setObjectName(u"actionSupported_Beams_help")
        self.actionMohr_s_Circle_help = QAction(MOIshapeselect)
        self.actionMohr_s_Circle_help.setObjectName(u"actionMohr_s_Circle_help")
        self.actionC_Clamp_help = QAction(MOIshapeselect)
        self.actionC_Clamp_help.setObjectName(u"actionC_Clamp_help")
        self.actionCompression_Link_help = QAction(MOIshapeselect)
        self.actionCompression_Link_help.setObjectName(u"actionCompression_Link_help")
        self.actionTension_Link_help = QAction(MOIshapeselect)
        self.actionTension_Link_help.setObjectName(u"actionTension_Link_help")
        self.actionPost_help = QAction(MOIshapeselect)
        self.actionPost_help.setObjectName(u"actionPost_help")
        self.actionPost_and_Beam_help = QAction(MOIshapeselect)
        self.actionPost_and_Beam_help.setObjectName(u"actionPost_and_Beam_help")
        self.actionSolid_shaft_and_Pipe_help = QAction(MOIshapeselect)
        self.actionSolid_shaft_and_Pipe_help.setObjectName(u"actionSolid_shaft_and_Pipe_help")
        self.actionKinematic_Diagraming_help = QAction(MOIshapeselect)
        self.actionKinematic_Diagraming_help.setObjectName(u"actionKinematic_Diagraming_help")
        self.actionVector_and_Motion_Analysis_help = QAction(MOIshapeselect)
        self.actionVector_and_Motion_Analysis_help.setObjectName(u"actionVector_and_Motion_Analysis_help")
        self.actionGDT_Checker_help = QAction(MOIshapeselect)
        self.actionGDT_Checker_help.setObjectName(u"actionGDT_Checker_help")
        self.actionVirtual_Condition_Calculator_help = QAction(MOIshapeselect)
        self.actionVirtual_Condition_Calculator_help.setObjectName(u"actionVirtual_Condition_Calculator_help")
        self.actionLimits_and_Fits_help = QAction(MOIshapeselect)
        self.actionLimits_and_Fits_help.setObjectName(u"actionLimits_and_Fits_help")
        self.actionGDTFasteners_help = QAction(MOIshapeselect)
        self.actionGDTFasteners_help.setObjectName(u"actionGDTFasteners_help")
        self.actionPaper_Gauging_help = QAction(MOIshapeselect)
        self.actionPaper_Gauging_help.setObjectName(u"actionPaper_Gauging_help")
        self.actionTolerance_Finder_help = QAction(MOIshapeselect)
        self.actionTolerance_Finder_help.setObjectName(u"actionTolerance_Finder_help")
        self.actionDiameter_Deviation_help = QAction(MOIshapeselect)
        self.actionDiameter_Deviation_help.setObjectName(u"actionDiameter_Deviation_help")
        self.actionTorsion_help = QAction(MOIshapeselect)
        self.actionTorsion_help.setObjectName(u"actionTorsion_help")
        self.actionPressure_help = QAction(MOIshapeselect)
        self.actionPressure_help.setObjectName(u"actionPressure_help")
        self.actionTheme = QAction(MOIshapeselect)
        self.actionTheme.setObjectName(u"actionTheme")
        self.actionSaftey_Factors = QAction(MOIshapeselect)
        self.actionSaftey_Factors.setObjectName(u"actionSaftey_Factors")
        self.actionSolid_Shaft_and_Pipe = QAction(MOIshapeselect)
        self.actionSolid_Shaft_and_Pipe.setObjectName(u"actionSolid_Shaft_and_Pipe")
        self.actionMohr_s_Circle_2 = QAction(MOIshapeselect)
        self.actionMohr_s_Circle_2.setObjectName(u"actionMohr_s_Circle_2")
        self.actionFit_Classes = QAction(MOIshapeselect)
        self.actionFit_Classes.setObjectName(u"actionFit_Classes")
        self.actionQuit_All = QAction(MOIshapeselect)
        self.actionQuit_All.setObjectName(u"actionQuit_All")
        self.centralwidget = QWidget(MOIshapeselect)
        self.centralwidget.setObjectName(u"centralwidget")
        self.toolBox_2 = QToolBox(self.centralwidget)
        self.toolBox_2.setObjectName(u"toolBox_2")
        self.toolBox_2.setGeometry(QRect(10, 10, 380, 701))
        self.page_5 = QWidget()
        self.page_5.setObjectName(u"page_5")
        self.page_5.setGeometry(QRect(0, 0, 380, 593))
        self.squarerectangle = QPushButton(self.page_5)
        self.squarerectangle.setObjectName(u"squarerectangle")
        self.squarerectangle.setGeometry(QRect(0, 0, 120, 120))
        self.Circle = QPushButton(self.page_5)
        self.Circle.setObjectName(u"Circle")
        self.Circle.setGeometry(QRect(0, 130, 120, 120))
        self.box = QPushButton(self.page_5)
        self.box.setObjectName(u"box")
        self.box.setGeometry(QRect(130, 0, 120, 120))
        self.Tubepipe = QPushButton(self.page_5)
        self.Tubepipe.setObjectName(u"Tubepipe")
        self.Tubepipe.setGeometry(QRect(130, 130, 120, 120))
        self.toolBox_2.addItem(self.page_5, u"Simple Shapes")
        self.page_6 = QWidget()
        self.page_6.setObjectName(u"page_6")
        self.page_6.setGeometry(QRect(0, 0, 380, 583))
        self.Customflanged = QPushButton(self.page_6)
        self.Customflanged.setObjectName(u"Customflanged")
        self.Customflanged.setGeometry(QRect(0, 0, 120, 120))
        self.Customchannel = QPushButton(self.page_6)
        self.Customchannel.setObjectName(u"Customchannel")
        self.Customchannel.setGeometry(QRect(130, 0, 120, 120))
        self.Ishape = QPushButton(self.page_6)
        self.Ishape.setObjectName(u"Ishape")
        self.Ishape.setGeometry(QRect(0, 130, 120, 120))
        self.Lshape = QPushButton(self.page_6)
        self.Lshape.setObjectName(u"Lshape")
        self.Lshape.setGeometry(QRect(130, 130, 120, 120))
        self.Cshape = QPushButton(self.page_6)
        self.Cshape.setObjectName(u"Cshape")
        self.Cshape.setGeometry(QRect(260, 130, 120, 120))
        self.Tshape = QPushButton(self.page_6)
        self.Tshape.setObjectName(u"Tshape")
        self.Tshape.setGeometry(QRect(0, 260, 120, 120))
        self.stiffTshape = QPushButton(self.page_6)
        self.stiffTshape.setObjectName(u"stiffTshape")
        self.stiffTshape.setGeometry(QRect(130, 260, 120, 120))
        self.StiffTshapeup = QPushButton(self.page_6)
        self.StiffTshapeup.setObjectName(u"StiffTshapeup")
        self.StiffTshapeup.setGeometry(QRect(260, 260, 120, 120))
        self.Zshape = QPushButton(self.page_6)
        self.Zshape.setObjectName(u"Zshape")
        self.Zshape.setGeometry(QRect(0, 390, 120, 120))
        self.reversedZ = QPushButton(self.page_6)
        self.reversedZ.setObjectName(u"reversedZ")
        self.reversedZ.setGeometry(QRect(130, 390, 120, 120))
        self.Flaredchannel = QPushButton(self.page_6)
        self.Flaredchannel.setObjectName(u"Flaredchannel")
        self.Flaredchannel.setGeometry(QRect(260, 390, 120, 120))
        self.line_4 = QFrame(self.page_6)
        self.line_4.setObjectName(u"line_4")
        self.line_4.setGeometry(QRect(0, 120, 391, 16))
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.line_4.sizePolicy().hasHeightForWidth())
        self.line_4.setSizePolicy(sizePolicy1)
        font = QFont()
        font.setBold(False)
        self.line_4.setFont(font)
        self.line_4.setLineWidth(3)
        self.line_4.setFrameShape(QFrame.Shape.HLine)
        self.line_4.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_5 = QFrame(self.page_6)
        self.line_5.setObjectName(u"line_5")
        self.line_5.setGeometry(QRect(0, 250, 391, 16))
        sizePolicy1.setHeightForWidth(self.line_5.sizePolicy().hasHeightForWidth())
        self.line_5.setSizePolicy(sizePolicy1)
        self.line_5.setFont(font)
        self.line_5.setLineWidth(3)
        self.line_5.setFrameShape(QFrame.Shape.HLine)
        self.line_5.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_6 = QFrame(self.page_6)
        self.line_6.setObjectName(u"line_6")
        self.line_6.setGeometry(QRect(-10, 380, 391, 16))
        sizePolicy1.setHeightForWidth(self.line_6.sizePolicy().hasHeightForWidth())
        self.line_6.setSizePolicy(sizePolicy1)
        self.line_6.setFont(font)
        self.line_6.setLineWidth(3)
        self.line_6.setFrameShape(QFrame.Shape.HLine)
        self.line_6.setFrameShadow(QFrame.Shadow.Sunken)
        self.toolBox_2.addItem(self.page_6, u"Engineering and Structural Shapes")
        self.page_7 = QWidget()
        self.page_7.setObjectName(u"page_7")
        self.page_7.setGeometry(QRect(0, 0, 380, 583))
        self.DoubleI = QPushButton(self.page_7)
        self.DoubleI.setObjectName(u"DoubleI")
        self.DoubleI.setGeometry(QRect(0, 0, 120, 120))
        self.DoubleC = QPushButton(self.page_7)
        self.DoubleC.setObjectName(u"DoubleC")
        self.DoubleC.setGeometry(QRect(130, 0, 120, 120))
        self.DoubleCtoetoe = QPushButton(self.page_7)
        self.DoubleCtoetoe.setObjectName(u"DoubleCtoetoe")
        self.DoubleCtoetoe.setGeometry(QRect(260, 0, 120, 120))
        self.DoubleT = QPushButton(self.page_7)
        self.DoubleT.setObjectName(u"DoubleT")
        self.DoubleT.setGeometry(QRect(0, 130, 120, 120))
        self.DoubleL = QPushButton(self.page_7)
        self.DoubleL.setObjectName(u"DoubleL")
        self.DoubleL.setGeometry(QRect(130, 130, 120, 120))
        self.toolBox_2.addItem(self.page_7, u"Double Shapes")
        self.page_8 = QWidget()
        self.page_8.setObjectName(u"page_8")
        self.page_8.setGeometry(QRect(0, 0, 380, 593))
        self.toolBox_3 = QToolBox(self.page_8)
        self.toolBox_3.setObjectName(u"toolBox_3")
        self.toolBox_3.setGeometry(QRect(10, 0, 361, 581))
        self.page_9 = QWidget()
        self.page_9.setObjectName(u"page_9")
        self.page_9.setGeometry(QRect(0, 0, 361, 419))
        self.usPipe = QPushButton(self.page_9)
        self.usPipe.setObjectName(u"usPipe")
        self.usPipe.setGeometry(QRect(0, 260, 111, 120))
        self.usAngle = QPushButton(self.page_9)
        self.usAngle.setObjectName(u"usAngle")
        self.usAngle.setGeometry(QRect(0, 130, 111, 121))
        self.usRecthollowsection = QPushButton(self.page_9)
        self.usRecthollowsection.setObjectName(u"usRecthollowsection")
        self.usRecthollowsection.setGeometry(QRect(240, 130, 111, 120))
        self.usChannel = QPushButton(self.page_9)
        self.usChannel.setObjectName(u"usChannel")
        self.usChannel.setGeometry(QRect(120, 0, 111, 121))
        self.usFlanged = QPushButton(self.page_9)
        self.usFlanged.setObjectName(u"usFlanged")
        self.usFlanged.setGeometry(QRect(0, 0, 111, 121))
        self.usDoubleangle = QPushButton(self.page_9)
        self.usDoubleangle.setObjectName(u"usDoubleangle")
        self.usDoubleangle.setGeometry(QRect(120, 130, 111, 120))
        self.usT = QPushButton(self.page_9)
        self.usT.setObjectName(u"usT")
        self.usT.setGeometry(QRect(240, 0, 111, 121))
        self.toolBox_3.addItem(self.page_9, u"Steel - ASIC US Customary Designations")
        self.page_10 = QWidget()
        self.page_10.setObjectName(u"page_10")
        self.page_10.setGeometry(QRect(0, 0, 361, 419))
        self.metricFlanged = QPushButton(self.page_10)
        self.metricFlanged.setObjectName(u"metricFlanged")
        self.metricFlanged.setGeometry(QRect(0, 10, 111, 120))
        self.metricPipe = QPushButton(self.page_10)
        self.metricPipe.setObjectName(u"metricPipe")
        self.metricPipe.setGeometry(QRect(0, 270, 111, 120))
        self.metricChannel = QPushButton(self.page_10)
        self.metricChannel.setObjectName(u"metricChannel")
        self.metricChannel.setGeometry(QRect(120, 10, 111, 120))
        self.metricDoubleAngle = QPushButton(self.page_10)
        self.metricDoubleAngle.setObjectName(u"metricDoubleAngle")
        self.metricDoubleAngle.setGeometry(QRect(120, 140, 111, 120))
        self.metricT = QPushButton(self.page_10)
        self.metricT.setObjectName(u"metricT")
        self.metricT.setGeometry(QRect(240, 10, 111, 120))
        self.metricAngle = QPushButton(self.page_10)
        self.metricAngle.setObjectName(u"metricAngle")
        self.metricAngle.setGeometry(QRect(0, 140, 111, 120))
        self.metricRectholloesection = QPushButton(self.page_10)
        self.metricRectholloesection.setObjectName(u"metricRectholloesection")
        self.metricRectholloesection.setGeometry(QRect(240, 140, 111, 120))
        self.toolBox_3.addItem(self.page_10, u"Steel - ASIC Metric Designations")
        self.page_11 = QWidget()
        self.page_11.setObjectName(u"page_11")
        self.page_11.setGeometry(QRect(0, 0, 361, 419))
        self.euroFlanged = QPushButton(self.page_11)
        self.euroFlanged.setObjectName(u"euroFlanged")
        self.euroFlanged.setGeometry(QRect(0, 10, 111, 120))
        self.euroRecthollowsection = QPushButton(self.page_11)
        self.euroRecthollowsection.setObjectName(u"euroRecthollowsection")
        self.euroRecthollowsection.setGeometry(QRect(240, 10, 111, 120))
        self.euroChannel = QPushButton(self.page_11)
        self.euroChannel.setObjectName(u"euroChannel")
        self.euroChannel.setGeometry(QRect(120, 10, 111, 120))
        self.toolBox_3.addItem(self.page_11, u"Steel - European Designations")
        self.page_12 = QWidget()
        self.page_12.setObjectName(u"page_12")
        self.page_12.setGeometry(QRect(0, 0, 361, 419))
        self.britFlanged = QPushButton(self.page_12)
        self.britFlanged.setObjectName(u"britFlanged")
        self.britFlanged.setGeometry(QRect(0, 10, 111, 120))
        self.britRecthollowsection = QPushButton(self.page_12)
        self.britRecthollowsection.setObjectName(u"britRecthollowsection")
        self.britRecthollowsection.setGeometry(QRect(240, 10, 111, 120))
        self.britChannel = QPushButton(self.page_12)
        self.britChannel.setObjectName(u"britChannel")
        self.britChannel.setGeometry(QRect(120, 10, 111, 120))
        self.toolBox_3.addItem(self.page_12, u"Steel - British Designations")
        self.page = QWidget()
        self.page.setObjectName(u"page")
        self.page.setGeometry(QRect(0, 0, 361, 419))
        self.aluFlanged = QPushButton(self.page)
        self.aluFlanged.setObjectName(u"aluFlanged")
        self.aluFlanged.setGeometry(QRect(0, 10, 111, 120))
        self.aluChannel = QPushButton(self.page)
        self.aluChannel.setObjectName(u"aluChannel")
        self.aluChannel.setGeometry(QRect(120, 10, 111, 120))
        self.aluPipe = QPushButton(self.page)
        self.aluPipe.setObjectName(u"aluPipe")
        self.aluPipe.setGeometry(QRect(240, 10, 111, 120))
        self.toolBox_3.addItem(self.page, u"Aluminum - US Customary Designations")
        self.page_2 = QWidget()
        self.page_2.setObjectName(u"page_2")
        self.page_2.setGeometry(QRect(0, 0, 361, 419))
        self.wood_2 = QPushButton(self.page_2)
        self.wood_2.setObjectName(u"wood_2")
        self.wood_2.setGeometry(QRect(10, 10, 111, 120))
        self.toolBox_3.addItem(self.page_2, u"Wood")
        self.toolBox_2.addItem(self.page_8, u"Standard Shapes")
        MOIshapeselect.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MOIshapeselect)
        self.statusbar.setObjectName(u"statusbar")
        MOIshapeselect.setStatusBar(self.statusbar)
        self.menubar = QMenuBar(MOIshapeselect)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 400, 21))
        self.menu_File = QMenu(self.menubar)
        self.menu_File.setObjectName(u"menu_File")
        self.menu_Settings = QMenu(self.menu_File)
        self.menu_Settings.setObjectName(u"menu_Settings")
        self.menu_Utilites = QMenu(self.menubar)
        self.menu_Utilites.setObjectName(u"menu_Utilites")
        self.menuTables = QMenu(self.menu_Utilites)
        self.menuTables.setObjectName(u"menuTables")
        self.menu_Help = QMenu(self.menubar)
        self.menu_Help.setObjectName(u"menu_Help")
        self.menuModules_help = QMenu(self.menu_Help)
        self.menuModules_help.setObjectName(u"menuModules_help")
        self.menuGeneral_Analysis_help = QMenu(self.menuModules_help)
        self.menuGeneral_Analysis_help.setObjectName(u"menuGeneral_Analysis_help")
        self.menuBeams_and_Loads_help = QMenu(self.menuModules_help)
        self.menuBeams_and_Loads_help.setObjectName(u"menuBeams_and_Loads_help")
        self.menuGeneral_Beam_Analysis = QMenu(self.menuBeams_and_Loads_help)
        self.menuGeneral_Beam_Analysis.setObjectName(u"menuGeneral_Beam_Analysis")
        self.menuCombined_Loadings_help = QMenu(self.menuBeams_and_Loads_help)
        self.menuCombined_Loadings_help.setObjectName(u"menuCombined_Loadings_help")
        self.menuEccentric_Loadings_help = QMenu(self.menuCombined_Loadings_help)
        self.menuEccentric_Loadings_help.setObjectName(u"menuEccentric_Loadings_help")
        self.menuShear_Force_and_Bending_Moment_help = QMenu(self.menuCombined_Loadings_help)
        self.menuShear_Force_and_Bending_Moment_help.setObjectName(u"menuShear_Force_and_Bending_Moment_help")
        self.menuAxial_Torsional_and_Bending_Stresses_help = QMenu(self.menuCombined_Loadings_help)
        self.menuAxial_Torsional_and_Bending_Stresses_help.setObjectName(u"menuAxial_Torsional_and_Bending_Stresses_help")
        self.menuKinematics_help = QMenu(self.menuModules_help)
        self.menuKinematics_help.setObjectName(u"menuKinematics_help")
        self.menuEngineering_and_Drafting_help = QMenu(self.menuModules_help)
        self.menuEngineering_and_Drafting_help.setObjectName(u"menuEngineering_and_Drafting_help")
        self.menuAdditional_Calculators_help = QMenu(self.menuModules_help)
        self.menuAdditional_Calculators_help.setObjectName(u"menuAdditional_Calculators_help")
        self.menu_Modules = QMenu(self.menubar)
        self.menu_Modules.setObjectName(u"menu_Modules")
        self.menu_General_Analysis = QMenu(self.menu_Modules)
        self.menu_General_Analysis.setObjectName(u"menu_General_Analysis")
        self.menu_Beams_and_Loads = QMenu(self.menu_Modules)
        self.menu_Beams_and_Loads.setObjectName(u"menu_Beams_and_Loads")
        self.menu_Generic_Beam_Analysis = QMenu(self.menu_Beams_and_Loads)
        self.menu_Generic_Beam_Analysis.setObjectName(u"menu_Generic_Beam_Analysis")
        self.menuCombined_Loadings = QMenu(self.menu_Beams_and_Loads)
        self.menuCombined_Loadings.setObjectName(u"menuCombined_Loadings")
        self.menuEccentric_Loadings = QMenu(self.menuCombined_Loadings)
        self.menuEccentric_Loadings.setObjectName(u"menuEccentric_Loadings")
        self.menuShear_Force_and_Bending_Moment = QMenu(self.menuCombined_Loadings)
        self.menuShear_Force_and_Bending_Moment.setObjectName(u"menuShear_Force_and_Bending_Moment")
        self.menuAxial_Torsional_and_Bending_Stresses = QMenu(self.menuCombined_Loadings)
        self.menuAxial_Torsional_and_Bending_Stresses.setObjectName(u"menuAxial_Torsional_and_Bending_Stresses")
        self.menu_Kinematics = QMenu(self.menu_Modules)
        self.menu_Kinematics.setObjectName(u"menu_Kinematics")
        self.menu_Egineering_and_Drafting = QMenu(self.menu_Modules)
        self.menu_Egineering_and_Drafting.setObjectName(u"menu_Egineering_and_Drafting")
        self.menu_Additional_Calculators = QMenu(self.menu_Modules)
        self.menu_Additional_Calculators.setObjectName(u"menu_Additional_Calculators")
        MOIshapeselect.setMenuBar(self.menubar)

        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Modules.menuAction())
        self.menubar.addAction(self.menu_Utilites.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())
        self.menu_File.addAction(self.menu_Settings.menuAction())
        self.menu_File.addAction(self.actionQuit)
        self.menu_File.addAction(self.actionQuit_All)
        self.menu_Settings.addAction(self.actionTheme)
        self.menu_Utilites.addAction(self.actionNotepad)
        self.menu_Utilites.addAction(self.actionCalculator)
        self.menu_Utilites.addAction(self.actionScreenshot)
        self.menu_Utilites.addAction(self.menuTables.menuAction())
        self.menuTables.addAction(self.actionMaterials_list)
        self.menuTables.addAction(self.actionCross_Sectional_Beams_and_Shapes_Lists)
        self.menuTables.addAction(self.actionSaftey_Factors)
        self.menuTables.addAction(self.actionFit_Classes)
        self.menu_Help.addAction(self.menuModules_help.menuAction())
        self.menu_Help.addAction(self.actionAbout)
        self.menuModules_help.addAction(self.menuGeneral_Analysis_help.menuAction())
        self.menuModules_help.addAction(self.menuBeams_and_Loads_help.menuAction())
        self.menuModules_help.addAction(self.menuKinematics_help.menuAction())
        self.menuModules_help.addAction(self.menuEngineering_and_Drafting_help.menuAction())
        self.menuModules_help.addAction(self.menuAdditional_Calculators_help.menuAction())
        self.menuGeneral_Analysis_help.addAction(self.actionUnit_Converter_help)
        self.menuGeneral_Analysis_help.addAction(self.actionMoments_of_Inertia_help)
        self.menuGeneral_Analysis_help.addAction(self.actionVectors_help)
        self.menuGeneral_Analysis_help.addAction(self.actionFriction_and_Force_help)
        self.menuGeneral_Analysis_help.addAction(self.actionFasteners_help)
        self.menuGeneral_Analysis_help.addAction(self.actionMaterial_Properties_help)
        self.menuGeneral_Analysis_help.addAction(self.actionCM_and_CG_help)
        self.menuBeams_and_Loads_help.addAction(self.menuGeneral_Beam_Analysis.menuAction())
        self.menuBeams_and_Loads_help.addAction(self.menuCombined_Loadings_help.menuAction())
        self.menuGeneral_Beam_Analysis.addAction(self.actionTrusses_help)
        self.menuGeneral_Beam_Analysis.addAction(self.actionBeamsMoments_of_Inertia_help)
        self.menuGeneral_Beam_Analysis.addAction(self.actionShear_and_Moment_help)
        self.menuGeneral_Beam_Analysis.addAction(self.actionIndeterminate_Axial_Structures_help)
        self.menuGeneral_Beam_Analysis.addAction(self.actionFlexure_help)
        self.menuGeneral_Beam_Analysis.addAction(self.actionBeam_Deformation_help)
        self.menuGeneral_Beam_Analysis.addAction(self.actionAxial_Beam_Deformation_help)
        self.menuGeneral_Beam_Analysis.addAction(self.actionTorsional_Beam_Deformation_help)
        self.menuGeneral_Beam_Analysis.addAction(self.actionSupported_Beams_help)
        self.menuGeneral_Beam_Analysis.addAction(self.actionMohr_s_Circle_help)
        self.menuCombined_Loadings_help.addAction(self.menuEccentric_Loadings_help.menuAction())
        self.menuCombined_Loadings_help.addAction(self.menuShear_Force_and_Bending_Moment_help.menuAction())
        self.menuCombined_Loadings_help.addAction(self.menuAxial_Torsional_and_Bending_Stresses_help.menuAction())
        self.menuEccentric_Loadings_help.addAction(self.actionC_Clamp_help)
        self.menuEccentric_Loadings_help.addAction(self.actionCompression_Link_help)
        self.menuEccentric_Loadings_help.addAction(self.actionTension_Link_help)
        self.menuEccentric_Loadings_help.addAction(self.actionPost_help)
        self.menuShear_Force_and_Bending_Moment_help.addAction(self.actionPost_and_Beam_help)
        self.menuAxial_Torsional_and_Bending_Stresses_help.addAction(self.actionSolid_shaft_and_Pipe_help)
        self.menuKinematics_help.addAction(self.actionKinematic_Diagraming_help)
        self.menuKinematics_help.addAction(self.actionVector_and_Motion_Analysis_help)
        self.menuEngineering_and_Drafting_help.addAction(self.actionGDT_Checker_help)
        self.menuEngineering_and_Drafting_help.addAction(self.actionVirtual_Condition_Calculator_help)
        self.menuEngineering_and_Drafting_help.addAction(self.actionLimits_and_Fits_help)
        self.menuEngineering_and_Drafting_help.addAction(self.actionGDTFasteners_help)
        self.menuEngineering_and_Drafting_help.addAction(self.actionPaper_Gauging_help)
        self.menuEngineering_and_Drafting_help.addAction(self.actionTolerance_Finder_help)
        self.menuEngineering_and_Drafting_help.addAction(self.actionDiameter_Deviation_help)
        self.menuAdditional_Calculators_help.addAction(self.actionTorsion_help)
        self.menuAdditional_Calculators_help.addAction(self.actionPressure_help)
        self.menuAdditional_Calculators_help.addAction(self.actionMohr_s_Circle_2)
        self.menu_Modules.addAction(self.menu_General_Analysis.menuAction())
        self.menu_Modules.addAction(self.menu_Beams_and_Loads.menuAction())
        self.menu_Modules.addAction(self.menu_Kinematics.menuAction())
        self.menu_Modules.addAction(self.menu_Egineering_and_Drafting.menuAction())
        self.menu_Modules.addAction(self.menu_Additional_Calculators.menuAction())
        self.menu_General_Analysis.addAction(self.actionUnit_Converter)
        self.menu_General_Analysis.addAction(self.actionMoments_of_Inertia)
        self.menu_General_Analysis.addAction(self.actionVectors)
        self.menu_General_Analysis.addAction(self.actionFriction_and_Force)
        self.menu_General_Analysis.addAction(self.actionFasteners)
        self.menu_General_Analysis.addAction(self.actionMaterial_Properties)
        self.menu_General_Analysis.addAction(self.actionCM_and_CG)
        self.menu_Beams_and_Loads.addAction(self.menu_Generic_Beam_Analysis.menuAction())
        self.menu_Beams_and_Loads.addAction(self.menuCombined_Loadings.menuAction())
        self.menu_Generic_Beam_Analysis.addAction(self.actionTrusses)
        self.menu_Generic_Beam_Analysis.addAction(self.actionBeamsMoments_of_Inertia)
        self.menu_Generic_Beam_Analysis.addAction(self.actionShear_and_Moment)
        self.menu_Generic_Beam_Analysis.addAction(self.actionIndeterminate_Axial_Structures)
        self.menu_Generic_Beam_Analysis.addAction(self.actionFlexure)
        self.menu_Generic_Beam_Analysis.addAction(self.actionBeam_Deformation)
        self.menu_Generic_Beam_Analysis.addAction(self.actionAxial_Beam_Deformation)
        self.menu_Generic_Beam_Analysis.addAction(self.actionTorsional_Beam_Deformation)
        self.menu_Generic_Beam_Analysis.addAction(self.actionSupported_Beams)
        self.menu_Generic_Beam_Analysis.addAction(self.actionMohr_s_Circle)
        self.menuCombined_Loadings.addAction(self.menuEccentric_Loadings.menuAction())
        self.menuCombined_Loadings.addAction(self.menuShear_Force_and_Bending_Moment.menuAction())
        self.menuCombined_Loadings.addAction(self.menuAxial_Torsional_and_Bending_Stresses.menuAction())
        self.menuEccentric_Loadings.addAction(self.actionC_Clamp)
        self.menuEccentric_Loadings.addAction(self.actionCompression_Link)
        self.menuEccentric_Loadings.addAction(self.actionTension_Link)
        self.menuEccentric_Loadings.addAction(self.actionPost)
        self.menuShear_Force_and_Bending_Moment.addAction(self.actionPost_and_Beam)
        self.menuAxial_Torsional_and_Bending_Stresses.addAction(self.actionSolid_Shaft_and_Pipe)
        self.menu_Kinematics.addAction(self.actionKinematic_Diagraming)
        self.menu_Kinematics.addAction(self.actionVector_Analysis)
        self.menu_Egineering_and_Drafting.addAction(self.actionGDT_Checker)
        self.menu_Egineering_and_Drafting.addAction(self.actionVirtual_Condition_Calculator)
        self.menu_Egineering_and_Drafting.addAction(self.actionLimits_and_Fits)
        self.menu_Egineering_and_Drafting.addAction(self.actionGDTFasteners)
        self.menu_Egineering_and_Drafting.addAction(self.actionPaper_Gauging)
        self.menu_Egineering_and_Drafting.addAction(self.actionTolerance_Finder)
        self.menu_Egineering_and_Drafting.addAction(self.actionDiameter_Deviation)
        self.menu_Additional_Calculators.addAction(self.actionTorsion)
        self.menu_Additional_Calculators.addAction(self.actionPressure)
        self.menu_Additional_Calculators.addAction(self.actionAddMohr_s_Circle)

        self.retranslateUi(MOIshapeselect)

        self.toolBox_2.setCurrentIndex(0)
        self.toolBox_3.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MOIshapeselect)
    # setupUi

    def retranslateUi(self, MOIshapeselect):
        MOIshapeselect.setWindowTitle(QCoreApplication.translate("MOIshapeselect", u"MainWindow", None))
        self.actionUnit_Converter.setText(QCoreApplication.translate("MOIshapeselect", u"Unit Converter", None))
        self.actionMoments_of_Inertia.setText(QCoreApplication.translate("MOIshapeselect", u"Moments of Inertia", None))
        self.actionVectors.setText(QCoreApplication.translate("MOIshapeselect", u"Vectors", None))
        self.actionFriction_and_Force.setText(QCoreApplication.translate("MOIshapeselect", u"Friction and Force", None))
        self.actionFasteners.setText(QCoreApplication.translate("MOIshapeselect", u"Fasteners", None))
        self.actionMaterial_Properties.setText(QCoreApplication.translate("MOIshapeselect", u"Material Properties", None))
        self.actionCM_and_CG.setText(QCoreApplication.translate("MOIshapeselect", u"CM and CG", None))
        self.actionTrusses.setText(QCoreApplication.translate("MOIshapeselect", u"Trusses", None))
        self.actionBeamsMoments_of_Inertia.setText(QCoreApplication.translate("MOIshapeselect", u"Moments of Inertia", None))
        self.actionShear_and_Moment.setText(QCoreApplication.translate("MOIshapeselect", u"Shear and Moment", None))
        self.actionIndeterminate_Axial_Structures.setText(QCoreApplication.translate("MOIshapeselect", u"Indeterminate Axial Structures", None))
        self.actionFlexure.setText(QCoreApplication.translate("MOIshapeselect", u"Flexure", None))
        self.actionBeam_Deformation.setText(QCoreApplication.translate("MOIshapeselect", u"Beam Deformation", None))
        self.actionAxial_Beam_Deformation.setText(QCoreApplication.translate("MOIshapeselect", u"Axial Beam Deformation", None))
        self.actionTorsional_Beam_Deformation.setText(QCoreApplication.translate("MOIshapeselect", u"Torsional Beam Deformation", None))
        self.actionSupported_Beams.setText(QCoreApplication.translate("MOIshapeselect", u"Supported Beams", None))
        self.actionMohr_s_Circle.setText(QCoreApplication.translate("MOIshapeselect", u"Mohr's Circle", None))
        self.actionC_Clamp.setText(QCoreApplication.translate("MOIshapeselect", u"C-Clamp", None))
        self.actionCompression_Link.setText(QCoreApplication.translate("MOIshapeselect", u"Compression Link", None))
        self.actionTension_Link.setText(QCoreApplication.translate("MOIshapeselect", u"Tension Link", None))
        self.actionPost.setText(QCoreApplication.translate("MOIshapeselect", u"Post", None))
        self.actionPost_and_Beam.setText(QCoreApplication.translate("MOIshapeselect", u"Post and Beam", None))
        self.actionKinematic_Diagraming.setText(QCoreApplication.translate("MOIshapeselect", u"Kinematic Diagraming", None))
        self.actionVector_Analysis.setText(QCoreApplication.translate("MOIshapeselect", u"Vector Analysis", None))
        self.actionGDT_Checker.setText(QCoreApplication.translate("MOIshapeselect", u"GDT Checker", None))
        self.actionVirtual_Condition_Calculator.setText(QCoreApplication.translate("MOIshapeselect", u"Virtual Condition Calculator", None))
        self.actionLimits_and_Fits.setText(QCoreApplication.translate("MOIshapeselect", u"Limits and Fits", None))
        self.actionGDTFasteners.setText(QCoreApplication.translate("MOIshapeselect", u"Fasteners", None))
        self.actionPaper_Gauging.setText(QCoreApplication.translate("MOIshapeselect", u"Paper Gauging", None))
        self.actionTolerance_Finder.setText(QCoreApplication.translate("MOIshapeselect", u"Tolerance Finder", None))
        self.actionDiameter_Deviation.setText(QCoreApplication.translate("MOIshapeselect", u"Diameter Deviation", None))
        self.actionTorsion.setText(QCoreApplication.translate("MOIshapeselect", u"Torsion", None))
        self.actionPressure.setText(QCoreApplication.translate("MOIshapeselect", u"Pressure", None))
        self.actionAddMohr_s_Circle.setText(QCoreApplication.translate("MOIshapeselect", u"Mohr's Circle", None))
        self.actionModule_List.setText(QCoreApplication.translate("MOIshapeselect", u"Module List", None))
        self.actionQuit.setText(QCoreApplication.translate("MOIshapeselect", u"Quit", None))
        self.actionNotepad.setText(QCoreApplication.translate("MOIshapeselect", u"Notepad", None))
        self.actionCalculator.setText(QCoreApplication.translate("MOIshapeselect", u"Calculator", None))
        self.actionScreenshot.setText(QCoreApplication.translate("MOIshapeselect", u"Screenshot", None))
        self.actionPerfer_SI_units.setText(QCoreApplication.translate("MOIshapeselect", u"Edit Saftey Factor", None))
        self.actionPerfer_Metric_Units.setText(QCoreApplication.translate("MOIshapeselect", u"Theme", None))
        self.actionMaterials_list.setText(QCoreApplication.translate("MOIshapeselect", u"Materials List", None))
        self.actionCross_Sectional_Beams_and_Shapes_Lists.setText(QCoreApplication.translate("MOIshapeselect", u"Beams and Shapes Lists", None))
        self.actionAbout.setText(QCoreApplication.translate("MOIshapeselect", u"About", None))
        self.actionUnit_Converter_help.setText(QCoreApplication.translate("MOIshapeselect", u"Unit Converter", None))
        self.actionMoments_of_Inertia_help.setText(QCoreApplication.translate("MOIshapeselect", u"Moments of Inertia", None))
        self.actionVectors_help.setText(QCoreApplication.translate("MOIshapeselect", u"Vectors", None))
        self.actionFriction_and_Force_help.setText(QCoreApplication.translate("MOIshapeselect", u"Friction and Force", None))
        self.actionFasteners_help.setText(QCoreApplication.translate("MOIshapeselect", u"Fasteners", None))
        self.actionMaterial_Properties_help.setText(QCoreApplication.translate("MOIshapeselect", u"Material Properties", None))
        self.actionCM_and_CG_help.setText(QCoreApplication.translate("MOIshapeselect", u"CM and CG", None))
        self.actionTrusses_help.setText(QCoreApplication.translate("MOIshapeselect", u"Trusses", None))
        self.actionBeamsMoments_of_Inertia_help.setText(QCoreApplication.translate("MOIshapeselect", u"Moments of Inertia", None))
        self.actionShear_and_Moment_help.setText(QCoreApplication.translate("MOIshapeselect", u"Shear and Moment", None))
        self.actionIndeterminate_Axial_Structures_help.setText(QCoreApplication.translate("MOIshapeselect", u"Indeterminate Axial Structures", None))
        self.actionFlexure_help.setText(QCoreApplication.translate("MOIshapeselect", u"Flexure", None))
        self.actionBeam_Deformation_help.setText(QCoreApplication.translate("MOIshapeselect", u"Beam Deformation", None))
        self.actionAxial_Beam_Deformation_help.setText(QCoreApplication.translate("MOIshapeselect", u"Axial Beam Deformation", None))
        self.actionTorsional_Beam_Deformation_help.setText(QCoreApplication.translate("MOIshapeselect", u"Torsional Beam Deformation", None))
        self.actionSupported_Beams_help.setText(QCoreApplication.translate("MOIshapeselect", u"Supported Beams", None))
        self.actionMohr_s_Circle_help.setText(QCoreApplication.translate("MOIshapeselect", u"Mohr's Circle", None))
        self.actionC_Clamp_help.setText(QCoreApplication.translate("MOIshapeselect", u"C-Clamp", None))
        self.actionCompression_Link_help.setText(QCoreApplication.translate("MOIshapeselect", u"Compression Link", None))
        self.actionTension_Link_help.setText(QCoreApplication.translate("MOIshapeselect", u"Tension Link", None))
        self.actionPost_help.setText(QCoreApplication.translate("MOIshapeselect", u"Post", None))
        self.actionPost_and_Beam_help.setText(QCoreApplication.translate("MOIshapeselect", u"Post and Beam", None))
        self.actionSolid_shaft_and_Pipe_help.setText(QCoreApplication.translate("MOIshapeselect", u"Solid Shaft and Pipe", None))
        self.actionKinematic_Diagraming_help.setText(QCoreApplication.translate("MOIshapeselect", u"Kinematic Diagraming", None))
        self.actionVector_and_Motion_Analysis_help.setText(QCoreApplication.translate("MOIshapeselect", u"Vector and Motion Analysis", None))
        self.actionGDT_Checker_help.setText(QCoreApplication.translate("MOIshapeselect", u"GDT Checker", None))
        self.actionVirtual_Condition_Calculator_help.setText(QCoreApplication.translate("MOIshapeselect", u"Virtual Condition Calculator", None))
        self.actionLimits_and_Fits_help.setText(QCoreApplication.translate("MOIshapeselect", u"Limits and Fits", None))
        self.actionGDTFasteners_help.setText(QCoreApplication.translate("MOIshapeselect", u"Fasteners", None))
        self.actionPaper_Gauging_help.setText(QCoreApplication.translate("MOIshapeselect", u"Paper Gauging", None))
        self.actionTolerance_Finder_help.setText(QCoreApplication.translate("MOIshapeselect", u"Tolerance Finder", None))
        self.actionDiameter_Deviation_help.setText(QCoreApplication.translate("MOIshapeselect", u"Diameter Deviation", None))
        self.actionTorsion_help.setText(QCoreApplication.translate("MOIshapeselect", u"Torsion", None))
        self.actionPressure_help.setText(QCoreApplication.translate("MOIshapeselect", u"Pressure", None))
        self.actionTheme.setText(QCoreApplication.translate("MOIshapeselect", u"Theme", None))
        self.actionSaftey_Factors.setText(QCoreApplication.translate("MOIshapeselect", u"Saftey Factors", None))
        self.actionSolid_Shaft_and_Pipe.setText(QCoreApplication.translate("MOIshapeselect", u"Solid Shaft and Pipe", None))
        self.actionMohr_s_Circle_2.setText(QCoreApplication.translate("MOIshapeselect", u"Mohr's Circle", None))
        self.actionFit_Classes.setText(QCoreApplication.translate("MOIshapeselect", u"Fit Classes", None))
        self.actionQuit_All.setText(QCoreApplication.translate("MOIshapeselect", u"Quit All", None))
        self.squarerectangle.setText(QCoreApplication.translate("MOIshapeselect", u"Square / Rectangle", None))
        self.Circle.setText(QCoreApplication.translate("MOIshapeselect", u"Circle", None))
        self.box.setText(QCoreApplication.translate("MOIshapeselect", u"Box", None))
        self.Tubepipe.setText(QCoreApplication.translate("MOIshapeselect", u"Tube / Pipe", None))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.page_5), QCoreApplication.translate("MOIshapeselect", u"Simple Shapes", None))
        self.Customflanged.setText(QCoreApplication.translate("MOIshapeselect", u"Custom Flanged", None))
        self.Customchannel.setText(QCoreApplication.translate("MOIshapeselect", u"Custom Channel", None))
        self.Ishape.setText(QCoreApplication.translate("MOIshapeselect", u"I - Shape", None))
        self.Lshape.setText(QCoreApplication.translate("MOIshapeselect", u"L - Shape", None))
        self.Cshape.setText(QCoreApplication.translate("MOIshapeselect", u"C - Shape", None))
        self.Tshape.setText(QCoreApplication.translate("MOIshapeselect", u"T - Shape", None))
        self.stiffTshape.setText(QCoreApplication.translate("MOIshapeselect", u"Stiffened\n"
"T - Shape\n"
"(Down)", None))
        self.StiffTshapeup.setText(QCoreApplication.translate("MOIshapeselect", u"Stiffened\n"
"T - Shape\n"
"(Up)", None))
        self.Zshape.setText(QCoreApplication.translate("MOIshapeselect", u"Z - Shape", None))
        self.reversedZ.setText(QCoreApplication.translate("MOIshapeselect", u"Z - Shape\n"
"(reversed)", None))
        self.Flaredchannel.setText(QCoreApplication.translate("MOIshapeselect", u"Flared Channel", None))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.page_6), QCoreApplication.translate("MOIshapeselect", u"Engineering and Structural Shapes", None))
        self.DoubleI.setText(QCoreApplication.translate("MOIshapeselect", u"Double I - Shape", None))
        self.DoubleC.setText(QCoreApplication.translate("MOIshapeselect", u"Double C- Shape\n"
"(Back to Back)", None))
        self.DoubleCtoetoe.setText(QCoreApplication.translate("MOIshapeselect", u"Double C- Shape\n"
"(Toe to Toe)", None))
        self.DoubleT.setText(QCoreApplication.translate("MOIshapeselect", u"Double T - Shape", None))
        self.DoubleL.setText(QCoreApplication.translate("MOIshapeselect", u"Double L - Shape", None))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.page_7), QCoreApplication.translate("MOIshapeselect", u"Double Shapes", None))
        self.usPipe.setText(QCoreApplication.translate("MOIshapeselect", u"Round HSS and Pipe", None))
        self.usAngle.setText(QCoreApplication.translate("MOIshapeselect", u"Angle Shapes\n"
"(L)", None))
        self.usRecthollowsection.setText(QCoreApplication.translate("MOIshapeselect", u"Rectangular Hollow\n"
"Structural Section\n"
"(HSS)", None))
        self.usChannel.setText(QCoreApplication.translate("MOIshapeselect", u"Channel Shapes\n"
"(C, MC)", None))
        self.usFlanged.setText(QCoreApplication.translate("MOIshapeselect", u"Flanged Shapes\n"
" (W, M, S, HP)", None))
        self.usDoubleangle.setText(QCoreApplication.translate("MOIshapeselect", u"Double Angle Shapes\n"
"(2L)", None))
        self.usT.setText(QCoreApplication.translate("MOIshapeselect", u"Tee Shapes\n"
"(WT, MT, ST)", None))
        self.toolBox_3.setItemText(self.toolBox_3.indexOf(self.page_9), QCoreApplication.translate("MOIshapeselect", u"Steel - ASIC US Customary Designations", None))
        self.metricFlanged.setText(QCoreApplication.translate("MOIshapeselect", u"Flanged Shapes\n"
" (W, M, S, HP)", None))
        self.metricPipe.setText(QCoreApplication.translate("MOIshapeselect", u"Round HSS and Pipe", None))
        self.metricChannel.setText(QCoreApplication.translate("MOIshapeselect", u"Channel Shapes\n"
"(C, MC)", None))
        self.metricDoubleAngle.setText(QCoreApplication.translate("MOIshapeselect", u"Double Angle Shapes\n"
"(2L)", None))
        self.metricT.setText(QCoreApplication.translate("MOIshapeselect", u"Tee Shapes\n"
"(WT, MT, ST)", None))
        self.metricAngle.setText(QCoreApplication.translate("MOIshapeselect", u"Angle Shapes\n"
"(L)", None))
        self.metricRectholloesection.setText(QCoreApplication.translate("MOIshapeselect", u"Rectangular Hollow\n"
"Structural Section\n"
"(HSS)", None))
        self.toolBox_3.setItemText(self.toolBox_3.indexOf(self.page_10), QCoreApplication.translate("MOIshapeselect", u"Steel - ASIC Metric Designations", None))
        self.euroFlanged.setText(QCoreApplication.translate("MOIshapeselect", u"Flanged Shapes\n"
" (HE, HL, HD,\n"
"IPE, IPN, HP)", None))
        self.euroRecthollowsection.setText(QCoreApplication.translate("MOIshapeselect", u"Rectangular Hollow\n"
"Structural Section\n"
"(SHS, RHS)", None))
        self.euroChannel.setText(QCoreApplication.translate("MOIshapeselect", u"Channel Shapes\n"
"(UPN, U, UPE)", None))
        self.toolBox_3.setItemText(self.toolBox_3.indexOf(self.page_11), QCoreApplication.translate("MOIshapeselect", u"Steel - European Designations", None))
        self.britFlanged.setText(QCoreApplication.translate("MOIshapeselect", u"Flanged Shapes\n"
" (UB, UC, J, UBP)", None))
        self.britRecthollowsection.setText(QCoreApplication.translate("MOIshapeselect", u"Rectangular Hollow\n"
"Structural Section\n"
"(SHS, RHS)", None))
        self.britChannel.setText(QCoreApplication.translate("MOIshapeselect", u"Channel Shapes\n"
"(CH, PFC)", None))
        self.toolBox_3.setItemText(self.toolBox_3.indexOf(self.page_12), QCoreApplication.translate("MOIshapeselect", u"Steel - British Designations", None))
        self.aluFlanged.setText(QCoreApplication.translate("MOIshapeselect", u"Flanged Shapes\n"
"(W, S) ", None))
        self.aluChannel.setText(QCoreApplication.translate("MOIshapeselect", u"Channel Shapes", None))
        self.aluPipe.setText(QCoreApplication.translate("MOIshapeselect", u"Pipe", None))
        self.toolBox_3.setItemText(self.toolBox_3.indexOf(self.page), QCoreApplication.translate("MOIshapeselect", u"Aluminum - US Customary Designations", None))
        self.wood_2.setText(QCoreApplication.translate("MOIshapeselect", u"Wood", None))
        self.toolBox_3.setItemText(self.toolBox_3.indexOf(self.page_2), QCoreApplication.translate("MOIshapeselect", u"Wood", None))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.page_8), QCoreApplication.translate("MOIshapeselect", u"Standard Shapes", None))
        self.menu_File.setTitle(QCoreApplication.translate("MOIshapeselect", u"&File", None))
        self.menu_Settings.setTitle(QCoreApplication.translate("MOIshapeselect", u"Settings", None))
        self.menu_Utilites.setTitle(QCoreApplication.translate("MOIshapeselect", u"&Utilites", None))
        self.menuTables.setTitle(QCoreApplication.translate("MOIshapeselect", u"Tables", None))
        self.menu_Help.setTitle(QCoreApplication.translate("MOIshapeselect", u"&Help", None))
        self.menuModules_help.setTitle(QCoreApplication.translate("MOIshapeselect", u"Modules", None))
        self.menuGeneral_Analysis_help.setTitle(QCoreApplication.translate("MOIshapeselect", u"General Analysis", None))
        self.menuBeams_and_Loads_help.setTitle(QCoreApplication.translate("MOIshapeselect", u"Beams and Loads", None))
        self.menuGeneral_Beam_Analysis.setTitle(QCoreApplication.translate("MOIshapeselect", u"General Beam Analysis", None))
        self.menuCombined_Loadings_help.setTitle(QCoreApplication.translate("MOIshapeselect", u"Combined Loadings", None))
        self.menuEccentric_Loadings_help.setTitle(QCoreApplication.translate("MOIshapeselect", u"Eccentric Loadings", None))
        self.menuShear_Force_and_Bending_Moment_help.setTitle(QCoreApplication.translate("MOIshapeselect", u"Shear Force and Bending Moment", None))
        self.menuAxial_Torsional_and_Bending_Stresses_help.setTitle(QCoreApplication.translate("MOIshapeselect", u"Axial, Torsional, and Bending Stresses", None))
        self.menuKinematics_help.setTitle(QCoreApplication.translate("MOIshapeselect", u"Kinematics", None))
        self.menuEngineering_and_Drafting_help.setTitle(QCoreApplication.translate("MOIshapeselect", u"Engineering and Drafting", None))
        self.menuAdditional_Calculators_help.setTitle(QCoreApplication.translate("MOIshapeselect", u"Additional Calculators", None))
        self.menu_Modules.setTitle(QCoreApplication.translate("MOIshapeselect", u"&Modules", None))
        self.menu_General_Analysis.setTitle(QCoreApplication.translate("MOIshapeselect", u"General Analysis", None))
        self.menu_Beams_and_Loads.setTitle(QCoreApplication.translate("MOIshapeselect", u"Beams and Loads", None))
        self.menu_Generic_Beam_Analysis.setTitle(QCoreApplication.translate("MOIshapeselect", u"Generic Beam Analysis", None))
        self.menuCombined_Loadings.setTitle(QCoreApplication.translate("MOIshapeselect", u"Combined Loadings", None))
        self.menuEccentric_Loadings.setTitle(QCoreApplication.translate("MOIshapeselect", u"Eccentric Loadings", None))
        self.menuShear_Force_and_Bending_Moment.setTitle(QCoreApplication.translate("MOIshapeselect", u"Shear Force and Bending Moment", None))
        self.menuAxial_Torsional_and_Bending_Stresses.setTitle(QCoreApplication.translate("MOIshapeselect", u"Axial, Torsional, and Bending Stresses", None))
        self.menu_Kinematics.setTitle(QCoreApplication.translate("MOIshapeselect", u"Kinematics", None))
        self.menu_Egineering_and_Drafting.setTitle(QCoreApplication.translate("MOIshapeselect", u"Egineering and Drafting", None))
        self.menu_Additional_Calculators.setTitle(QCoreApplication.translate("MOIshapeselect", u"Additional Calculators", None))
    # retranslateUi

