# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'MOIadvcompalwd.ui'
##
## Created by: Qt User Interface Compiler version 6.8.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QGraphicsView, QGroupBox,
    QLabel, QLineEdit, QMainWindow, QMenu,
    QMenuBar, QPushButton, QRadioButton, QSizePolicy,
    QStatusBar, QTabWidget, QVBoxLayout, QWidget)

class Ui_MOIadvcompalwd(object):
    def setupUi(self, MOIadvcompalwd):
        if not MOIadvcompalwd.objectName():
            MOIadvcompalwd.setObjectName(u"MOIadvcompalwd")
        MOIadvcompalwd.resize(1060, 1030)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MOIadvcompalwd.sizePolicy().hasHeightForWidth())
        MOIadvcompalwd.setSizePolicy(sizePolicy)
        MOIadvcompalwd.setMinimumSize(QSize(1060, 1030))
        MOIadvcompalwd.setMaximumSize(QSize(1060, 1030))
        MOIadvcompalwd.setTabShape(QTabWidget.Rounded)
        MOIadvcompalwd.setDockNestingEnabled(False)
        MOIadvcompalwd.setUnifiedTitleAndToolBarOnMac(False)
        self.actionUnit_Converter = QAction(MOIadvcompalwd)
        self.actionUnit_Converter.setObjectName(u"actionUnit_Converter")
        self.actionMoments_of_Inertia = QAction(MOIadvcompalwd)
        self.actionMoments_of_Inertia.setObjectName(u"actionMoments_of_Inertia")
        self.actionVectors = QAction(MOIadvcompalwd)
        self.actionVectors.setObjectName(u"actionVectors")
        self.actionFriction_and_Force = QAction(MOIadvcompalwd)
        self.actionFriction_and_Force.setObjectName(u"actionFriction_and_Force")
        self.actionFasteners = QAction(MOIadvcompalwd)
        self.actionFasteners.setObjectName(u"actionFasteners")
        self.actionMaterial_Properties = QAction(MOIadvcompalwd)
        self.actionMaterial_Properties.setObjectName(u"actionMaterial_Properties")
        self.actionCM_and_CG = QAction(MOIadvcompalwd)
        self.actionCM_and_CG.setObjectName(u"actionCM_and_CG")
        self.actionTrusses = QAction(MOIadvcompalwd)
        self.actionTrusses.setObjectName(u"actionTrusses")
        self.actionBeamsMoments_of_Inertia = QAction(MOIadvcompalwd)
        self.actionBeamsMoments_of_Inertia.setObjectName(u"actionBeamsMoments_of_Inertia")
        self.actionShear_and_Moment = QAction(MOIadvcompalwd)
        self.actionShear_and_Moment.setObjectName(u"actionShear_and_Moment")
        self.actionIndeterminate_Axial_Structures = QAction(MOIadvcompalwd)
        self.actionIndeterminate_Axial_Structures.setObjectName(u"actionIndeterminate_Axial_Structures")
        self.actionFlexure = QAction(MOIadvcompalwd)
        self.actionFlexure.setObjectName(u"actionFlexure")
        self.actionBeam_Deformation = QAction(MOIadvcompalwd)
        self.actionBeam_Deformation.setObjectName(u"actionBeam_Deformation")
        self.actionAxial_Beam_Deformation = QAction(MOIadvcompalwd)
        self.actionAxial_Beam_Deformation.setObjectName(u"actionAxial_Beam_Deformation")
        self.actionTorsional_Beam_Deformation = QAction(MOIadvcompalwd)
        self.actionTorsional_Beam_Deformation.setObjectName(u"actionTorsional_Beam_Deformation")
        self.actionSupported_Beams = QAction(MOIadvcompalwd)
        self.actionSupported_Beams.setObjectName(u"actionSupported_Beams")
        self.actionMohr_s_Circle = QAction(MOIadvcompalwd)
        self.actionMohr_s_Circle.setObjectName(u"actionMohr_s_Circle")
        self.actionC_Clamp = QAction(MOIadvcompalwd)
        self.actionC_Clamp.setObjectName(u"actionC_Clamp")
        self.actionCompression_Link = QAction(MOIadvcompalwd)
        self.actionCompression_Link.setObjectName(u"actionCompression_Link")
        self.actionTension_Link = QAction(MOIadvcompalwd)
        self.actionTension_Link.setObjectName(u"actionTension_Link")
        self.actionPost = QAction(MOIadvcompalwd)
        self.actionPost.setObjectName(u"actionPost")
        self.actionPost_and_Beam = QAction(MOIadvcompalwd)
        self.actionPost_and_Beam.setObjectName(u"actionPost_and_Beam")
        self.actionKinematic_Diagraming = QAction(MOIadvcompalwd)
        self.actionKinematic_Diagraming.setObjectName(u"actionKinematic_Diagraming")
        self.actionVector_Analysis = QAction(MOIadvcompalwd)
        self.actionVector_Analysis.setObjectName(u"actionVector_Analysis")
        self.actionGDT_Checker = QAction(MOIadvcompalwd)
        self.actionGDT_Checker.setObjectName(u"actionGDT_Checker")
        self.actionVirtual_Condition_Calculator = QAction(MOIadvcompalwd)
        self.actionVirtual_Condition_Calculator.setObjectName(u"actionVirtual_Condition_Calculator")
        self.actionLimits_and_Fits = QAction(MOIadvcompalwd)
        self.actionLimits_and_Fits.setObjectName(u"actionLimits_and_Fits")
        self.actionGDTFasteners = QAction(MOIadvcompalwd)
        self.actionGDTFasteners.setObjectName(u"actionGDTFasteners")
        self.actionPaper_Gauging = QAction(MOIadvcompalwd)
        self.actionPaper_Gauging.setObjectName(u"actionPaper_Gauging")
        self.actionTolerance_Finder = QAction(MOIadvcompalwd)
        self.actionTolerance_Finder.setObjectName(u"actionTolerance_Finder")
        self.actionDiameter_Deviation = QAction(MOIadvcompalwd)
        self.actionDiameter_Deviation.setObjectName(u"actionDiameter_Deviation")
        self.actionTorsion = QAction(MOIadvcompalwd)
        self.actionTorsion.setObjectName(u"actionTorsion")
        self.actionPressure = QAction(MOIadvcompalwd)
        self.actionPressure.setObjectName(u"actionPressure")
        self.actionAddMohr_s_Circle = QAction(MOIadvcompalwd)
        self.actionAddMohr_s_Circle.setObjectName(u"actionAddMohr_s_Circle")
        self.actionModule_List = QAction(MOIadvcompalwd)
        self.actionModule_List.setObjectName(u"actionModule_List")
        self.actionQuit = QAction(MOIadvcompalwd)
        self.actionQuit.setObjectName(u"actionQuit")
        self.actionNotepad = QAction(MOIadvcompalwd)
        self.actionNotepad.setObjectName(u"actionNotepad")
        self.actionCalculator = QAction(MOIadvcompalwd)
        self.actionCalculator.setObjectName(u"actionCalculator")
        self.actionScreenshot = QAction(MOIadvcompalwd)
        self.actionScreenshot.setObjectName(u"actionScreenshot")
        self.actionPerfer_SI_units = QAction(MOIadvcompalwd)
        self.actionPerfer_SI_units.setObjectName(u"actionPerfer_SI_units")
        self.actionPerfer_Metric_Units = QAction(MOIadvcompalwd)
        self.actionPerfer_Metric_Units.setObjectName(u"actionPerfer_Metric_Units")
        self.actionMaterials_list = QAction(MOIadvcompalwd)
        self.actionMaterials_list.setObjectName(u"actionMaterials_list")
        self.actionCross_Sectional_Beams_and_Shapes_Lists = QAction(MOIadvcompalwd)
        self.actionCross_Sectional_Beams_and_Shapes_Lists.setObjectName(u"actionCross_Sectional_Beams_and_Shapes_Lists")
        self.actionAbout = QAction(MOIadvcompalwd)
        self.actionAbout.setObjectName(u"actionAbout")
        self.actionUnit_Converter_help = QAction(MOIadvcompalwd)
        self.actionUnit_Converter_help.setObjectName(u"actionUnit_Converter_help")
        self.actionMoments_of_Inertia_help = QAction(MOIadvcompalwd)
        self.actionMoments_of_Inertia_help.setObjectName(u"actionMoments_of_Inertia_help")
        self.actionVectors_help = QAction(MOIadvcompalwd)
        self.actionVectors_help.setObjectName(u"actionVectors_help")
        self.actionFriction_and_Force_help = QAction(MOIadvcompalwd)
        self.actionFriction_and_Force_help.setObjectName(u"actionFriction_and_Force_help")
        self.actionFasteners_help = QAction(MOIadvcompalwd)
        self.actionFasteners_help.setObjectName(u"actionFasteners_help")
        self.actionMaterial_Properties_help = QAction(MOIadvcompalwd)
        self.actionMaterial_Properties_help.setObjectName(u"actionMaterial_Properties_help")
        self.actionCM_and_CG_help = QAction(MOIadvcompalwd)
        self.actionCM_and_CG_help.setObjectName(u"actionCM_and_CG_help")
        self.actionTrusses_help = QAction(MOIadvcompalwd)
        self.actionTrusses_help.setObjectName(u"actionTrusses_help")
        self.actionBeamsMoments_of_Inertia_help = QAction(MOIadvcompalwd)
        self.actionBeamsMoments_of_Inertia_help.setObjectName(u"actionBeamsMoments_of_Inertia_help")
        self.actionShear_and_Moment_help = QAction(MOIadvcompalwd)
        self.actionShear_and_Moment_help.setObjectName(u"actionShear_and_Moment_help")
        self.actionIndeterminate_Axial_Structures_help = QAction(MOIadvcompalwd)
        self.actionIndeterminate_Axial_Structures_help.setObjectName(u"actionIndeterminate_Axial_Structures_help")
        self.actionFlexure_help = QAction(MOIadvcompalwd)
        self.actionFlexure_help.setObjectName(u"actionFlexure_help")
        self.actionBeam_Deformation_help = QAction(MOIadvcompalwd)
        self.actionBeam_Deformation_help.setObjectName(u"actionBeam_Deformation_help")
        self.actionAxial_Beam_Deformation_help = QAction(MOIadvcompalwd)
        self.actionAxial_Beam_Deformation_help.setObjectName(u"actionAxial_Beam_Deformation_help")
        self.actionTorsional_Beam_Deformation_help = QAction(MOIadvcompalwd)
        self.actionTorsional_Beam_Deformation_help.setObjectName(u"actionTorsional_Beam_Deformation_help")
        self.actionSupported_Beams_help = QAction(MOIadvcompalwd)
        self.actionSupported_Beams_help.setObjectName(u"actionSupported_Beams_help")
        self.actionMohr_s_Circle_help = QAction(MOIadvcompalwd)
        self.actionMohr_s_Circle_help.setObjectName(u"actionMohr_s_Circle_help")
        self.actionC_Clamp_help = QAction(MOIadvcompalwd)
        self.actionC_Clamp_help.setObjectName(u"actionC_Clamp_help")
        self.actionCompression_Link_help = QAction(MOIadvcompalwd)
        self.actionCompression_Link_help.setObjectName(u"actionCompression_Link_help")
        self.actionTension_Link_help = QAction(MOIadvcompalwd)
        self.actionTension_Link_help.setObjectName(u"actionTension_Link_help")
        self.actionPost_help = QAction(MOIadvcompalwd)
        self.actionPost_help.setObjectName(u"actionPost_help")
        self.actionPost_and_Beam_help = QAction(MOIadvcompalwd)
        self.actionPost_and_Beam_help.setObjectName(u"actionPost_and_Beam_help")
        self.actionSolid_shaft_and_Pipe_help = QAction(MOIadvcompalwd)
        self.actionSolid_shaft_and_Pipe_help.setObjectName(u"actionSolid_shaft_and_Pipe_help")
        self.actionKinematic_Diagraming_help = QAction(MOIadvcompalwd)
        self.actionKinematic_Diagraming_help.setObjectName(u"actionKinematic_Diagraming_help")
        self.actionVector_and_Motion_Analysis_help = QAction(MOIadvcompalwd)
        self.actionVector_and_Motion_Analysis_help.setObjectName(u"actionVector_and_Motion_Analysis_help")
        self.actionGDT_Checker_help = QAction(MOIadvcompalwd)
        self.actionGDT_Checker_help.setObjectName(u"actionGDT_Checker_help")
        self.actionVirtual_Condition_Calculator_help = QAction(MOIadvcompalwd)
        self.actionVirtual_Condition_Calculator_help.setObjectName(u"actionVirtual_Condition_Calculator_help")
        self.actionLimits_and_Fits_help = QAction(MOIadvcompalwd)
        self.actionLimits_and_Fits_help.setObjectName(u"actionLimits_and_Fits_help")
        self.actionGDTFasteners_help = QAction(MOIadvcompalwd)
        self.actionGDTFasteners_help.setObjectName(u"actionGDTFasteners_help")
        self.actionPaper_Gauging_help = QAction(MOIadvcompalwd)
        self.actionPaper_Gauging_help.setObjectName(u"actionPaper_Gauging_help")
        self.actionTolerance_Finder_help = QAction(MOIadvcompalwd)
        self.actionTolerance_Finder_help.setObjectName(u"actionTolerance_Finder_help")
        self.actionDiameter_Deviation_help = QAction(MOIadvcompalwd)
        self.actionDiameter_Deviation_help.setObjectName(u"actionDiameter_Deviation_help")
        self.actionTorsion_help = QAction(MOIadvcompalwd)
        self.actionTorsion_help.setObjectName(u"actionTorsion_help")
        self.actionPressure_help = QAction(MOIadvcompalwd)
        self.actionPressure_help.setObjectName(u"actionPressure_help")
        self.actionTheme = QAction(MOIadvcompalwd)
        self.actionTheme.setObjectName(u"actionTheme")
        self.actionSaftey_Factors = QAction(MOIadvcompalwd)
        self.actionSaftey_Factors.setObjectName(u"actionSaftey_Factors")
        self.actionSolid_Shaft_and_Pipe = QAction(MOIadvcompalwd)
        self.actionSolid_Shaft_and_Pipe.setObjectName(u"actionSolid_Shaft_and_Pipe")
        self.actionMohr_s_Circle_2 = QAction(MOIadvcompalwd)
        self.actionMohr_s_Circle_2.setObjectName(u"actionMohr_s_Circle_2")
        self.actionFit_Classes = QAction(MOIadvcompalwd)
        self.actionFit_Classes.setObjectName(u"actionFit_Classes")
        self.actionQuit_All = QAction(MOIadvcompalwd)
        self.actionQuit_All.setObjectName(u"actionQuit_All")
        self.actionBack_to_Shape_Selector = QAction(MOIadvcompalwd)
        self.actionBack_to_Shape_Selector.setObjectName(u"actionBack_to_Shape_Selector")
        self.centralwidget = QWidget(MOIadvcompalwd)
        self.centralwidget.setObjectName(u"centralwidget")
        self.graphicsView = QGraphicsView(self.centralwidget)
        self.graphicsView.setObjectName(u"graphicsView")
        self.graphicsView.setGeometry(QRect(10, 10, 550, 550))
        sizePolicy.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy)
        font = QFont()
        font.setPointSize(12)
        self.graphicsView.setFont(font)
        self.Mohrs = QPushButton(self.centralwidget)
        self.Mohrs.setObjectName(u"Mohrs")
        self.Mohrs.setGeometry(QRect(570, 370, 111, 41))
        self.Mohrs.setFont(font)
        self.computeMOI = QPushButton(self.centralwidget)
        self.computeMOI.setObjectName(u"computeMOI")
        self.computeMOI.setGeometry(QRect(570, 420, 111, 41))
        self.computeMOI.setFont(font)
        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(570, 10, 111, 81))
        self.groupBox.setFont(font)
        self.verticalLayout_2 = QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.xyaxis_2 = QRadioButton(self.groupBox)
        self.xyaxis_2.setObjectName(u"xyaxis_2")
        self.xyaxis_2.setFont(font)

        self.verticalLayout_2.addWidget(self.xyaxis_2)

        self.yzaxis_2 = QRadioButton(self.groupBox)
        self.yzaxis_2.setObjectName(u"yzaxis_2")
        self.yzaxis_2.setFont(font)

        self.verticalLayout_2.addWidget(self.yzaxis_2)

        self.groupBox_2 = QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(570, 90, 111, 71))
        self.groupBox_2.setFont(font)
        self.verticalLayout = QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.Unitscombobox = QComboBox(self.groupBox_2)
        self.Unitscombobox.setObjectName(u"Unitscombobox")
        self.Unitscombobox.setFont(font)

        self.verticalLayout.addWidget(self.Unitscombobox)

        self.groupBox_3 = QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(570, 160, 111, 201))
        self.groupBox_3.setFont(font)
        self.verticalLayout_3 = QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.rotate0deg = QRadioButton(self.groupBox_3)
        self.rotate0deg.setObjectName(u"rotate0deg")
        self.rotate0deg.setFont(font)

        self.verticalLayout_3.addWidget(self.rotate0deg)

        self.rotate90deg = QRadioButton(self.groupBox_3)
        self.rotate90deg.setObjectName(u"rotate90deg")
        self.rotate90deg.setFont(font)

        self.verticalLayout_3.addWidget(self.rotate90deg)

        self.rotate180deg = QRadioButton(self.groupBox_3)
        self.rotate180deg.setObjectName(u"rotate180deg")
        self.rotate180deg.setFont(font)

        self.verticalLayout_3.addWidget(self.rotate180deg)

        self.rotate270deg = QRadioButton(self.groupBox_3)
        self.rotate270deg.setObjectName(u"rotate270deg")
        self.rotate270deg.setFont(font)

        self.verticalLayout_3.addWidget(self.rotate270deg)

        self.rotate = QPushButton(self.groupBox_3)
        self.rotate.setObjectName(u"rotate")
        self.rotate.setFont(font)

        self.verticalLayout_3.addWidget(self.rotate)

        self.groupBox_5 = QGroupBox(self.centralwidget)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setGeometry(QRect(10, 570, 551, 201))
        self.groupBox_5.setFont(font)
        self.label_7 = QLabel(self.groupBox_5)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(340, 20, 168, 19))
        self.label_7.setFont(font)
        self.Matlelasticmodulus_2 = QComboBox(self.groupBox_5)
        self.Matlelasticmodulus_2.setObjectName(u"Matlelasticmodulus_2")
        self.Matlelasticmodulus_2.setGeometry(QRect(340, 40, 191, 25))
        self.Matlelasticmodulus_2.setFont(font)
        self.shapesize = QComboBox(self.groupBox_5)
        self.shapesize.setObjectName(u"shapesize")
        self.shapesize.setGeometry(QRect(20, 40, 281, 25))
        self.label_8 = QLabel(self.groupBox_5)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(20, 20, 31, 19))
        self.label_8.setFont(font)
        self.label_9 = QLabel(self.groupBox_5)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(340, 80, 168, 41))
        self.label_9.setFont(font)
        self.Matlelasticmodulusunits = QComboBox(self.groupBox_5)
        self.Matlelasticmodulusunits.setObjectName(u"Matlelasticmodulusunits")
        self.Matlelasticmodulusunits.setGeometry(QRect(340, 120, 191, 25))
        self.Matlelasticmodulusunits.setFont(font)
        self.groupBox_4 = QGroupBox(self.centralwidget)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(700, 10, 351, 951))
        self.groupBox_4.setFont(font)
        self.AxisProperties = QLabel(self.groupBox_4)
        self.AxisProperties.setObjectName(u"AxisProperties")
        self.AxisProperties.setGeometry(QRect(10, 20, 361, 21))
        self.AxisProperties.setLayoutDirection(Qt.LeftToRight)
        self.AxisProperties.setAlignment(Qt.AlignCenter)
        self.elasticmoduluslabel = QLabel(self.groupBox_4)
        self.elasticmoduluslabel.setObjectName(u"elasticmoduluslabel")
        self.elasticmoduluslabel.setGeometry(QRect(10, 50, 111, 16))
        self.elasticmod = QLineEdit(self.groupBox_4)
        self.elasticmod.setObjectName(u"elasticmod")
        self.elasticmod.setGeometry(QRect(10, 70, 251, 25))
        self.elasticmod.setReadOnly(True)
        self.elasticmodunits = QLineEdit(self.groupBox_4)
        self.elasticmodunits.setObjectName(u"elasticmodunits")
        self.elasticmodunits.setGeometry(QRect(290, 70, 51, 25))
        self.elasticmodvar = QLabel(self.groupBox_4)
        self.elasticmodvar.setObjectName(u"elasticmodvar")
        self.elasticmodvar.setGeometry(QRect(290, 50, 51, 21))
        self.elasticmodvar.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.bottomtocentroid = QLineEdit(self.groupBox_4)
        self.bottomtocentroid.setObjectName(u"bottomtocentroid")
        self.bottomtocentroid.setGeometry(QRect(10, 130, 251, 25))
        self.bottomtocentroid.setReadOnly(True)
        self.bottomtocentroidlabel = QLabel(self.groupBox_4)
        self.bottomtocentroidlabel.setObjectName(u"bottomtocentroidlabel")
        self.bottomtocentroidlabel.setGeometry(QRect(10, 110, 261, 21))
        self.bottomtocentroidlabel.setWordWrap(False)
        self.bottomtocentroidvar = QLabel(self.groupBox_4)
        self.bottomtocentroidvar.setObjectName(u"bottomtocentroidvar")
        self.bottomtocentroidvar.setGeometry(QRect(290, 110, 51, 21))
        self.bottomtocentroidvar.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.toptocentroidunits = QLineEdit(self.groupBox_4)
        self.toptocentroidunits.setObjectName(u"toptocentroidunits")
        self.toptocentroidunits.setGeometry(QRect(290, 180, 51, 25))
        self.toptocentroid = QLineEdit(self.groupBox_4)
        self.toptocentroid.setObjectName(u"toptocentroid")
        self.toptocentroid.setGeometry(QRect(10, 180, 251, 25))
        self.toptocentroid.setReadOnly(True)
        self.toptocentroidlabel = QLabel(self.groupBox_4)
        self.toptocentroidlabel.setObjectName(u"toptocentroidlabel")
        self.toptocentroidlabel.setGeometry(QRect(10, 160, 231, 21))
        self.toptocentroidlabel.setWordWrap(False)
        self.toptocentroidvar = QLabel(self.groupBox_4)
        self.toptocentroidvar.setObjectName(u"toptocentroidvar")
        self.toptocentroidvar.setGeometry(QRect(290, 160, 51, 21))
        self.toptocentroidvar.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.MOIlabel = QLabel(self.groupBox_4)
        self.MOIlabel.setObjectName(u"MOIlabel")
        self.MOIlabel.setGeometry(QRect(290, 220, 51, 21))
        self.MOIlabel.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.MOI = QLineEdit(self.groupBox_4)
        self.MOI.setObjectName(u"MOI")
        self.MOI.setGeometry(QRect(10, 240, 251, 25))
        self.MOI.setReadOnly(True)
        self.MOIunits = QLineEdit(self.groupBox_4)
        self.MOIunits.setObjectName(u"MOIunits")
        self.MOIunits.setGeometry(QRect(290, 240, 51, 25))
        self.MOIlabel_2 = QLabel(self.groupBox_4)
        self.MOIlabel_2.setObjectName(u"MOIlabel_2")
        self.MOIlabel_2.setGeometry(QRect(10, 220, 161, 21))
        self.MOIlabel_2.setWordWrap(False)
        self.sectionmodvar = QLabel(self.groupBox_4)
        self.sectionmodvar.setObjectName(u"sectionmodvar")
        self.sectionmodvar.setGeometry(QRect(290, 270, 51, 21))
        self.sectionmodvar.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.sectionmodunits = QLineEdit(self.groupBox_4)
        self.sectionmodunits.setObjectName(u"sectionmodunits")
        self.sectionmodunits.setGeometry(QRect(290, 290, 51, 25))
        self.sectionmodlabel = QLabel(self.groupBox_4)
        self.sectionmodlabel.setObjectName(u"sectionmodlabel")
        self.sectionmodlabel.setGeometry(QRect(10, 270, 161, 21))
        self.sectionmodlabel.setWordWrap(False)
        self.sectionmod = QLineEdit(self.groupBox_4)
        self.sectionmod.setObjectName(u"sectionmod")
        self.sectionmod.setGeometry(QRect(10, 290, 251, 25))
        self.sectionmod.setReadOnly(True)
        self.sectionmodbottom = QLineEdit(self.groupBox_4)
        self.sectionmodbottom.setObjectName(u"sectionmodbottom")
        self.sectionmodbottom.setGeometry(QRect(10, 340, 251, 25))
        self.sectionmodbottom.setReadOnly(True)
        self.sectionmodbottomvar = QLabel(self.groupBox_4)
        self.sectionmodbottomvar.setObjectName(u"sectionmodbottomvar")
        self.sectionmodbottomvar.setGeometry(QRect(290, 320, 51, 21))
        self.sectionmodbottomvar.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.sectionmodbottomlabel = QLabel(self.groupBox_4)
        self.sectionmodbottomlabel.setObjectName(u"sectionmodbottomlabel")
        self.sectionmodbottomlabel.setGeometry(QRect(10, 320, 191, 21))
        self.sectionmodbottomlabel.setWordWrap(False)
        self.sectionmodbottomunits = QLineEdit(self.groupBox_4)
        self.sectionmodbottomunits.setObjectName(u"sectionmodbottomunits")
        self.sectionmodbottomunits.setGeometry(QRect(290, 340, 51, 25))
        self.sectionmodtopvar = QLabel(self.groupBox_4)
        self.sectionmodtopvar.setObjectName(u"sectionmodtopvar")
        self.sectionmodtopvar.setGeometry(QRect(290, 370, 51, 21))
        self.sectionmodtopvar.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.sectionmodtop = QLineEdit(self.groupBox_4)
        self.sectionmodtop.setObjectName(u"sectionmodtop")
        self.sectionmodtop.setGeometry(QRect(10, 390, 251, 25))
        self.sectionmodtop.setReadOnly(True)
        self.sectionmodtoplabel = QLabel(self.groupBox_4)
        self.sectionmodtoplabel.setObjectName(u"sectionmodtoplabel")
        self.sectionmodtoplabel.setGeometry(QRect(10, 370, 161, 21))
        self.sectionmodtoplabel.setWordWrap(False)
        self.sectionmodtopunits = QLineEdit(self.groupBox_4)
        self.sectionmodtopunits.setObjectName(u"sectionmodtopunits")
        self.sectionmodtopunits.setGeometry(QRect(290, 390, 51, 25))
        self.radofgyration = QLineEdit(self.groupBox_4)
        self.radofgyration.setObjectName(u"radofgyration")
        self.radofgyration.setGeometry(QRect(10, 440, 251, 25))
        self.radofgyration.setReadOnly(True)
        self.radofgyrationlabel = QLabel(self.groupBox_4)
        self.radofgyrationlabel.setObjectName(u"radofgyrationlabel")
        self.radofgyrationlabel.setGeometry(QRect(10, 420, 161, 21))
        self.radofgyrationlabel.setWordWrap(False)
        self.radofgyrationvar = QLabel(self.groupBox_4)
        self.radofgyrationvar.setObjectName(u"radofgyrationvar")
        self.radofgyrationvar.setGeometry(QRect(290, 420, 51, 21))
        self.radofgyrationvar.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.radofgyrationunits = QLineEdit(self.groupBox_4)
        self.radofgyrationunits.setObjectName(u"radofgyrationunits")
        self.radofgyrationunits.setGeometry(QRect(290, 440, 51, 25))
        self.plasticmod = QLineEdit(self.groupBox_4)
        self.plasticmod.setObjectName(u"plasticmod")
        self.plasticmod.setGeometry(QRect(10, 500, 251, 25))
        self.plasticmod.setReadOnly(True)
        self.plasticmodvar = QLabel(self.groupBox_4)
        self.plasticmodvar.setObjectName(u"plasticmodvar")
        self.plasticmodvar.setGeometry(QRect(290, 480, 51, 21))
        self.plasticmodvar.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.plasticmodlabel = QLabel(self.groupBox_4)
        self.plasticmodlabel.setObjectName(u"plasticmodlabel")
        self.plasticmodlabel.setGeometry(QRect(10, 480, 161, 21))
        self.plasticmodlabel.setWordWrap(False)
        self.plasticmodunits = QLineEdit(self.groupBox_4)
        self.plasticmodunits.setObjectName(u"plasticmodunits")
        self.plasticmodunits.setGeometry(QRect(290, 500, 51, 25))
        self.bottomtoplastic = QLineEdit(self.groupBox_4)
        self.bottomtoplastic.setObjectName(u"bottomtoplastic")
        self.bottomtoplastic.setGeometry(QRect(10, 600, 251, 25))
        self.bottomtoplastic.setReadOnly(True)
        self.plasticlabel = QLabel(self.groupBox_4)
        self.plasticlabel.setObjectName(u"plasticlabel")
        self.plasticlabel.setGeometry(QRect(10, 580, 201, 21))
        self.plasticlabel.setWordWrap(False)
        self.plastictotoplabel = QLabel(self.groupBox_4)
        self.plastictotoplabel.setObjectName(u"plastictotoplabel")
        self.plastictotoplabel.setGeometry(QRect(10, 630, 171, 21))
        self.plastictotoplabel.setWordWrap(False)
        self.plastictotopunits = QLineEdit(self.groupBox_4)
        self.plastictotopunits.setObjectName(u"plastictotopunits")
        self.plastictotopunits.setGeometry(QRect(290, 650, 51, 25))
        self.plastictotop = QLineEdit(self.groupBox_4)
        self.plastictotop.setObjectName(u"plastictotop")
        self.plastictotop.setGeometry(QRect(10, 650, 251, 25))
        self.plastictotop.setReadOnly(True)
        self.plastictotopvar = QLabel(self.groupBox_4)
        self.plastictotopvar.setObjectName(u"plastictotopvar")
        self.plastictotopvar.setGeometry(QRect(280, 630, 61, 21))
        self.plastictotopvar.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.bottomtocentroidunits = QLineEdit(self.groupBox_4)
        self.bottomtocentroidunits.setObjectName(u"bottomtocentroidunits")
        self.bottomtocentroidunits.setGeometry(QRect(290, 130, 51, 25))
        self.shapefactor = QLineEdit(self.groupBox_4)
        self.shapefactor.setObjectName(u"shapefactor")
        self.shapefactor.setGeometry(QRect(10, 550, 251, 25))
        self.shapefactor.setReadOnly(True)
        self.shapefactorlabel = QLabel(self.groupBox_4)
        self.shapefactorlabel.setObjectName(u"shapefactorlabel")
        self.shapefactorlabel.setGeometry(QRect(10, 530, 161, 21))
        self.shapefactorlabel.setWordWrap(False)
        self.plastictobottomunits = QLineEdit(self.groupBox_4)
        self.plastictobottomunits.setObjectName(u"plastictobottomunits")
        self.plastictobottomunits.setGeometry(QRect(290, 600, 51, 25))
        self.plasticbottomvariable = QLabel(self.groupBox_4)
        self.plasticbottomvariable.setObjectName(u"plasticbottomvariable")
        self.plasticbottomvariable.setGeometry(QRect(280, 580, 61, 21))
        self.plasticbottomvariable.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.polarMOIlabel = QLabel(self.groupBox_4)
        self.polarMOIlabel.setObjectName(u"polarMOIlabel")
        self.polarMOIlabel.setGeometry(QRect(10, 690, 171, 21))
        self.polarMOIlabel.setWordWrap(False)
        self.polarMOIvar = QLabel(self.groupBox_4)
        self.polarMOIvar.setObjectName(u"polarMOIvar")
        self.polarMOIvar.setGeometry(QRect(280, 690, 61, 21))
        self.polarMOIvar.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.polarMOIunits = QLineEdit(self.groupBox_4)
        self.polarMOIunits.setObjectName(u"polarMOIunits")
        self.polarMOIunits.setGeometry(QRect(290, 710, 51, 25))
        self.polarMOI = QLineEdit(self.groupBox_4)
        self.polarMOI.setObjectName(u"polarMOI")
        self.polarMOI.setGeometry(QRect(10, 710, 251, 25))
        self.polarMOI.setReadOnly(True)
        self.productofinertia = QLineEdit(self.groupBox_4)
        self.productofinertia.setObjectName(u"productofinertia")
        self.productofinertia.setGeometry(QRect(10, 760, 251, 25))
        self.productofinertia.setReadOnly(True)
        self.productofinertialabel = QLabel(self.groupBox_4)
        self.productofinertialabel.setObjectName(u"productofinertialabel")
        self.productofinertialabel.setGeometry(QRect(10, 740, 171, 21))
        self.productofinertialabel.setWordWrap(False)
        self.productofinertiaunits = QLineEdit(self.groupBox_4)
        self.productofinertiaunits.setObjectName(u"productofinertiaunits")
        self.productofinertiaunits.setGeometry(QRect(290, 760, 51, 25))
        self.productofinertiavar = QLabel(self.groupBox_4)
        self.productofinertiavar.setObjectName(u"productofinertiavar")
        self.productofinertiavar.setGeometry(QRect(280, 740, 61, 21))
        self.productofinertiavar.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.maxMOIlabel = QLabel(self.groupBox_4)
        self.maxMOIlabel.setObjectName(u"maxMOIlabel")
        self.maxMOIlabel.setGeometry(QRect(10, 790, 211, 21))
        self.maxMOIlabel.setWordWrap(False)
        self.maxMOIvar = QLabel(self.groupBox_4)
        self.maxMOIvar.setObjectName(u"maxMOIvar")
        self.maxMOIvar.setGeometry(QRect(280, 790, 61, 21))
        self.maxMOIvar.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.maxMOIunits = QLineEdit(self.groupBox_4)
        self.maxMOIunits.setObjectName(u"maxMOIunits")
        self.maxMOIunits.setGeometry(QRect(290, 810, 51, 25))
        self.maxMOI = QLineEdit(self.groupBox_4)
        self.maxMOI.setObjectName(u"maxMOI")
        self.maxMOI.setGeometry(QRect(10, 810, 251, 25))
        self.maxMOI.setReadOnly(True)
        self.minMOI = QLineEdit(self.groupBox_4)
        self.minMOI.setObjectName(u"minMOI")
        self.minMOI.setGeometry(QRect(10, 860, 251, 25))
        self.minMOI.setReadOnly(True)
        self.minMOIvar = QLabel(self.groupBox_4)
        self.minMOIvar.setObjectName(u"minMOIvar")
        self.minMOIvar.setGeometry(QRect(280, 840, 61, 21))
        self.minMOIvar.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.minMOIlabel = QLabel(self.groupBox_4)
        self.minMOIlabel.setObjectName(u"minMOIlabel")
        self.minMOIlabel.setGeometry(QRect(10, 840, 201, 21))
        self.minMOIlabel.setWordWrap(False)
        self.minMOIunits = QLineEdit(self.groupBox_4)
        self.minMOIunits.setObjectName(u"minMOIunits")
        self.minMOIunits.setGeometry(QRect(290, 860, 51, 25))
        self.axisangle = QLineEdit(self.groupBox_4)
        self.axisangle.setObjectName(u"axisangle")
        self.axisangle.setGeometry(QRect(10, 910, 251, 25))
        self.axisangle.setReadOnly(True)
        self.axisangleunits = QLineEdit(self.groupBox_4)
        self.axisangleunits.setObjectName(u"axisangleunits")
        self.axisangleunits.setGeometry(QRect(290, 910, 51, 25))
        self.axisanglevar = QLabel(self.groupBox_4)
        self.axisanglevar.setObjectName(u"axisanglevar")
        self.axisanglevar.setGeometry(QRect(280, 890, 61, 21))
        self.axisanglevar.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.axisanglelabel = QLabel(self.groupBox_4)
        self.axisanglelabel.setObjectName(u"axisanglelabel")
        self.axisanglelabel.setGeometry(QRect(10, 890, 241, 21))
        self.axisanglelabel.setWordWrap(False)
        MOIadvcompalwd.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MOIadvcompalwd)
        self.statusbar.setObjectName(u"statusbar")
        MOIadvcompalwd.setStatusBar(self.statusbar)
        self.menubar = QMenuBar(MOIadvcompalwd)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1060, 21))
        self.menu_File = QMenu(self.menubar)
        self.menu_File.setObjectName(u"menu_File")
        self.menu_Settings = QMenu(self.menu_File)
        self.menu_Settings.setObjectName(u"menu_Settings")
        self.menu_Utilites = QMenu(self.menubar)
        self.menu_Utilites.setObjectName(u"menu_Utilites")
        self.menuTables = QMenu(self.menu_Utilites)
        self.menuTables.setObjectName(u"menuTables")
        self.menu_Help = QMenu(self.menubar)
        self.menu_Help.setObjectName(u"menu_Help")
        self.menuModules_help = QMenu(self.menu_Help)
        self.menuModules_help.setObjectName(u"menuModules_help")
        self.menuGeneral_Analysis_help = QMenu(self.menuModules_help)
        self.menuGeneral_Analysis_help.setObjectName(u"menuGeneral_Analysis_help")
        self.menuBeams_and_Loads_help = QMenu(self.menuModules_help)
        self.menuBeams_and_Loads_help.setObjectName(u"menuBeams_and_Loads_help")
        self.menuGeneral_Beam_Analysis = QMenu(self.menuBeams_and_Loads_help)
        self.menuGeneral_Beam_Analysis.setObjectName(u"menuGeneral_Beam_Analysis")
        self.menuCombined_Loadings_help = QMenu(self.menuBeams_and_Loads_help)
        self.menuCombined_Loadings_help.setObjectName(u"menuCombined_Loadings_help")
        self.menuEccentric_Loadings_help = QMenu(self.menuCombined_Loadings_help)
        self.menuEccentric_Loadings_help.setObjectName(u"menuEccentric_Loadings_help")
        self.menuShear_Force_and_Bending_Moment_help = QMenu(self.menuCombined_Loadings_help)
        self.menuShear_Force_and_Bending_Moment_help.setObjectName(u"menuShear_Force_and_Bending_Moment_help")
        self.menuAxial_Torsional_and_Bending_Stresses_help = QMenu(self.menuCombined_Loadings_help)
        self.menuAxial_Torsional_and_Bending_Stresses_help.setObjectName(u"menuAxial_Torsional_and_Bending_Stresses_help")
        self.menuKinematics_help = QMenu(self.menuModules_help)
        self.menuKinematics_help.setObjectName(u"menuKinematics_help")
        self.menuEngineering_and_Drafting_help = QMenu(self.menuModules_help)
        self.menuEngineering_and_Drafting_help.setObjectName(u"menuEngineering_and_Drafting_help")
        self.menuAdditional_Calculators_help = QMenu(self.menuModules_help)
        self.menuAdditional_Calculators_help.setObjectName(u"menuAdditional_Calculators_help")
        self.menu_Modules = QMenu(self.menubar)
        self.menu_Modules.setObjectName(u"menu_Modules")
        self.menu_General_Analysis = QMenu(self.menu_Modules)
        self.menu_General_Analysis.setObjectName(u"menu_General_Analysis")
        self.menu_Beams_and_Loads = QMenu(self.menu_Modules)
        self.menu_Beams_and_Loads.setObjectName(u"menu_Beams_and_Loads")
        self.menu_Generic_Beam_Analysis = QMenu(self.menu_Beams_and_Loads)
        self.menu_Generic_Beam_Analysis.setObjectName(u"menu_Generic_Beam_Analysis")
        self.menuCombined_Loadings = QMenu(self.menu_Beams_and_Loads)
        self.menuCombined_Loadings.setObjectName(u"menuCombined_Loadings")
        self.menuEccentric_Loadings = QMenu(self.menuCombined_Loadings)
        self.menuEccentric_Loadings.setObjectName(u"menuEccentric_Loadings")
        self.menuShear_Force_and_Bending_Moment = QMenu(self.menuCombined_Loadings)
        self.menuShear_Force_and_Bending_Moment.setObjectName(u"menuShear_Force_and_Bending_Moment")
        self.menuAxial_Torsional_and_Bending_Stresses = QMenu(self.menuCombined_Loadings)
        self.menuAxial_Torsional_and_Bending_Stresses.setObjectName(u"menuAxial_Torsional_and_Bending_Stresses")
        self.menu_Kinematics = QMenu(self.menu_Modules)
        self.menu_Kinematics.setObjectName(u"menu_Kinematics")
        self.menu_Egineering_and_Drafting = QMenu(self.menu_Modules)
        self.menu_Egineering_and_Drafting.setObjectName(u"menu_Egineering_and_Drafting")
        self.menu_Additional_Calculators = QMenu(self.menu_Modules)
        self.menu_Additional_Calculators.setObjectName(u"menu_Additional_Calculators")
        MOIadvcompalwd.setMenuBar(self.menubar)

        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Modules.menuAction())
        self.menubar.addAction(self.menu_Utilites.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())
        self.menu_File.addAction(self.menu_Settings.menuAction())
        self.menu_File.addAction(self.actionQuit)
        self.menu_File.addAction(self.actionQuit_All)
        self.menu_File.addAction(self.actionBack_to_Shape_Selector)
        self.menu_Settings.addAction(self.actionTheme)
        self.menu_Utilites.addAction(self.actionNotepad)
        self.menu_Utilites.addAction(self.actionCalculator)
        self.menu_Utilites.addAction(self.actionScreenshot)
        self.menu_Utilites.addAction(self.menuTables.menuAction())
        self.menuTables.addAction(self.actionMaterials_list)
        self.menuTables.addAction(self.actionCross_Sectional_Beams_and_Shapes_Lists)
        self.menuTables.addAction(self.actionSaftey_Factors)
        self.menuTables.addAction(self.actionFit_Classes)
        self.menu_Help.addAction(self.menuModules_help.menuAction())
        self.menu_Help.addAction(self.actionAbout)
        self.menuModules_help.addAction(self.menuGeneral_Analysis_help.menuAction())
        self.menuModules_help.addAction(self.menuBeams_and_Loads_help.menuAction())
        self.menuModules_help.addAction(self.menuKinematics_help.menuAction())
        self.menuModules_help.addAction(self.menuEngineering_and_Drafting_help.menuAction())
        self.menuModules_help.addAction(self.menuAdditional_Calculators_help.menuAction())
        self.menuGeneral_Analysis_help.addAction(self.actionUnit_Converter_help)
        self.menuGeneral_Analysis_help.addAction(self.actionMoments_of_Inertia_help)
        self.menuGeneral_Analysis_help.addAction(self.actionVectors_help)
        self.menuGeneral_Analysis_help.addAction(self.actionFriction_and_Force_help)
        self.menuGeneral_Analysis_help.addAction(self.actionFasteners_help)
        self.menuGeneral_Analysis_help.addAction(self.actionMaterial_Properties_help)
        self.menuGeneral_Analysis_help.addAction(self.actionCM_and_CG_help)
        self.menuBeams_and_Loads_help.addAction(self.menuGeneral_Beam_Analysis.menuAction())
        self.menuBeams_and_Loads_help.addAction(self.menuCombined_Loadings_help.menuAction())
        self.menuGeneral_Beam_Analysis.addAction(self.actionTrusses_help)
        self.menuGeneral_Beam_Analysis.addAction(self.actionBeamsMoments_of_Inertia_help)
        self.menuGeneral_Beam_Analysis.addAction(self.actionShear_and_Moment_help)
        self.menuGeneral_Beam_Analysis.addAction(self.actionIndeterminate_Axial_Structures_help)
        self.menuGeneral_Beam_Analysis.addAction(self.actionFlexure_help)
        self.menuGeneral_Beam_Analysis.addAction(self.actionBeam_Deformation_help)
        self.menuGeneral_Beam_Analysis.addAction(self.actionAxial_Beam_Deformation_help)
        self.menuGeneral_Beam_Analysis.addAction(self.actionTorsional_Beam_Deformation_help)
        self.menuGeneral_Beam_Analysis.addAction(self.actionSupported_Beams_help)
        self.menuGeneral_Beam_Analysis.addAction(self.actionMohr_s_Circle_help)
        self.menuCombined_Loadings_help.addAction(self.menuEccentric_Loadings_help.menuAction())
        self.menuCombined_Loadings_help.addAction(self.menuShear_Force_and_Bending_Moment_help.menuAction())
        self.menuCombined_Loadings_help.addAction(self.menuAxial_Torsional_and_Bending_Stresses_help.menuAction())
        self.menuEccentric_Loadings_help.addAction(self.actionC_Clamp_help)
        self.menuEccentric_Loadings_help.addAction(self.actionCompression_Link_help)
        self.menuEccentric_Loadings_help.addAction(self.actionTension_Link_help)
        self.menuEccentric_Loadings_help.addAction(self.actionPost_help)
        self.menuShear_Force_and_Bending_Moment_help.addAction(self.actionPost_and_Beam_help)
        self.menuAxial_Torsional_and_Bending_Stresses_help.addAction(self.actionSolid_shaft_and_Pipe_help)
        self.menuKinematics_help.addAction(self.actionKinematic_Diagraming_help)
        self.menuKinematics_help.addAction(self.actionVector_and_Motion_Analysis_help)
        self.menuEngineering_and_Drafting_help.addAction(self.actionGDT_Checker_help)
        self.menuEngineering_and_Drafting_help.addAction(self.actionVirtual_Condition_Calculator_help)
        self.menuEngineering_and_Drafting_help.addAction(self.actionLimits_and_Fits_help)
        self.menuEngineering_and_Drafting_help.addAction(self.actionGDTFasteners_help)
        self.menuEngineering_and_Drafting_help.addAction(self.actionPaper_Gauging_help)
        self.menuEngineering_and_Drafting_help.addAction(self.actionTolerance_Finder_help)
        self.menuEngineering_and_Drafting_help.addAction(self.actionDiameter_Deviation_help)
        self.menuAdditional_Calculators_help.addAction(self.actionTorsion_help)
        self.menuAdditional_Calculators_help.addAction(self.actionPressure_help)
        self.menuAdditional_Calculators_help.addAction(self.actionMohr_s_Circle_2)
        self.menu_Modules.addAction(self.menu_General_Analysis.menuAction())
        self.menu_Modules.addAction(self.menu_Beams_and_Loads.menuAction())
        self.menu_Modules.addAction(self.menu_Kinematics.menuAction())
        self.menu_Modules.addAction(self.menu_Egineering_and_Drafting.menuAction())
        self.menu_Modules.addAction(self.menu_Additional_Calculators.menuAction())
        self.menu_General_Analysis.addAction(self.actionUnit_Converter)
        self.menu_General_Analysis.addAction(self.actionMoments_of_Inertia)
        self.menu_General_Analysis.addAction(self.actionVectors)
        self.menu_General_Analysis.addAction(self.actionFriction_and_Force)
        self.menu_General_Analysis.addAction(self.actionFasteners)
        self.menu_General_Analysis.addAction(self.actionMaterial_Properties)
        self.menu_General_Analysis.addAction(self.actionCM_and_CG)
        self.menu_Beams_and_Loads.addAction(self.menu_Generic_Beam_Analysis.menuAction())
        self.menu_Beams_and_Loads.addAction(self.menuCombined_Loadings.menuAction())
        self.menu_Generic_Beam_Analysis.addAction(self.actionTrusses)
        self.menu_Generic_Beam_Analysis.addAction(self.actionBeamsMoments_of_Inertia)
        self.menu_Generic_Beam_Analysis.addAction(self.actionShear_and_Moment)
        self.menu_Generic_Beam_Analysis.addAction(self.actionIndeterminate_Axial_Structures)
        self.menu_Generic_Beam_Analysis.addAction(self.actionFlexure)
        self.menu_Generic_Beam_Analysis.addAction(self.actionBeam_Deformation)
        self.menu_Generic_Beam_Analysis.addAction(self.actionAxial_Beam_Deformation)
        self.menu_Generic_Beam_Analysis.addAction(self.actionTorsional_Beam_Deformation)
        self.menu_Generic_Beam_Analysis.addAction(self.actionSupported_Beams)
        self.menu_Generic_Beam_Analysis.addAction(self.actionMohr_s_Circle)
        self.menuCombined_Loadings.addAction(self.menuEccentric_Loadings.menuAction())
        self.menuCombined_Loadings.addAction(self.menuShear_Force_and_Bending_Moment.menuAction())
        self.menuCombined_Loadings.addAction(self.menuAxial_Torsional_and_Bending_Stresses.menuAction())
        self.menuEccentric_Loadings.addAction(self.actionC_Clamp)
        self.menuEccentric_Loadings.addAction(self.actionCompression_Link)
        self.menuEccentric_Loadings.addAction(self.actionTension_Link)
        self.menuEccentric_Loadings.addAction(self.actionPost)
        self.menuShear_Force_and_Bending_Moment.addAction(self.actionPost_and_Beam)
        self.menuAxial_Torsional_and_Bending_Stresses.addAction(self.actionSolid_Shaft_and_Pipe)
        self.menu_Kinematics.addAction(self.actionKinematic_Diagraming)
        self.menu_Kinematics.addAction(self.actionVector_Analysis)
        self.menu_Egineering_and_Drafting.addAction(self.actionGDT_Checker)
        self.menu_Egineering_and_Drafting.addAction(self.actionVirtual_Condition_Calculator)
        self.menu_Egineering_and_Drafting.addAction(self.actionLimits_and_Fits)
        self.menu_Egineering_and_Drafting.addAction(self.actionGDTFasteners)
        self.menu_Egineering_and_Drafting.addAction(self.actionPaper_Gauging)
        self.menu_Egineering_and_Drafting.addAction(self.actionTolerance_Finder)
        self.menu_Egineering_and_Drafting.addAction(self.actionDiameter_Deviation)
        self.menu_Additional_Calculators.addAction(self.actionTorsion)
        self.menu_Additional_Calculators.addAction(self.actionPressure)
        self.menu_Additional_Calculators.addAction(self.actionAddMohr_s_Circle)

        self.retranslateUi(MOIadvcompalwd)

        QMetaObject.connectSlotsByName(MOIadvcompalwd)
    # setupUi

    def retranslateUi(self, MOIadvcompalwd):
        MOIadvcompalwd.setWindowTitle(QCoreApplication.translate("MOIadvcompalwd", u"MainWindow", None))
        self.actionUnit_Converter.setText(QCoreApplication.translate("MOIadvcompalwd", u"Unit Converter", None))
        self.actionMoments_of_Inertia.setText(QCoreApplication.translate("MOIadvcompalwd", u"Moments of Inertia", None))
        self.actionVectors.setText(QCoreApplication.translate("MOIadvcompalwd", u"Vectors", None))
        self.actionFriction_and_Force.setText(QCoreApplication.translate("MOIadvcompalwd", u"Friction and Force", None))
        self.actionFasteners.setText(QCoreApplication.translate("MOIadvcompalwd", u"Fasteners", None))
        self.actionMaterial_Properties.setText(QCoreApplication.translate("MOIadvcompalwd", u"Material Properties", None))
        self.actionCM_and_CG.setText(QCoreApplication.translate("MOIadvcompalwd", u"CM and CG", None))
        self.actionTrusses.setText(QCoreApplication.translate("MOIadvcompalwd", u"Trusses", None))
        self.actionBeamsMoments_of_Inertia.setText(QCoreApplication.translate("MOIadvcompalwd", u"Moments of Inertia", None))
        self.actionShear_and_Moment.setText(QCoreApplication.translate("MOIadvcompalwd", u"Shear and Moment", None))
        self.actionIndeterminate_Axial_Structures.setText(QCoreApplication.translate("MOIadvcompalwd", u"Indeterminate Axial Structures", None))
        self.actionFlexure.setText(QCoreApplication.translate("MOIadvcompalwd", u"Flexure", None))
        self.actionBeam_Deformation.setText(QCoreApplication.translate("MOIadvcompalwd", u"Beam Deformation", None))
        self.actionAxial_Beam_Deformation.setText(QCoreApplication.translate("MOIadvcompalwd", u"Axial Beam Deformation", None))
        self.actionTorsional_Beam_Deformation.setText(QCoreApplication.translate("MOIadvcompalwd", u"Torsional Beam Deformation", None))
        self.actionSupported_Beams.setText(QCoreApplication.translate("MOIadvcompalwd", u"Supported Beams", None))
        self.actionMohr_s_Circle.setText(QCoreApplication.translate("MOIadvcompalwd", u"Mohr's Circle", None))
        self.actionC_Clamp.setText(QCoreApplication.translate("MOIadvcompalwd", u"C-Clamp", None))
        self.actionCompression_Link.setText(QCoreApplication.translate("MOIadvcompalwd", u"Compression Link", None))
        self.actionTension_Link.setText(QCoreApplication.translate("MOIadvcompalwd", u"Tension Link", None))
        self.actionPost.setText(QCoreApplication.translate("MOIadvcompalwd", u"Post", None))
        self.actionPost_and_Beam.setText(QCoreApplication.translate("MOIadvcompalwd", u"Post and Beam", None))
        self.actionKinematic_Diagraming.setText(QCoreApplication.translate("MOIadvcompalwd", u"Kinematic Diagraming", None))
        self.actionVector_Analysis.setText(QCoreApplication.translate("MOIadvcompalwd", u"Vector Analysis", None))
        self.actionGDT_Checker.setText(QCoreApplication.translate("MOIadvcompalwd", u"GDT Checker", None))
        self.actionVirtual_Condition_Calculator.setText(QCoreApplication.translate("MOIadvcompalwd", u"Virtual Condition Calculator", None))
        self.actionLimits_and_Fits.setText(QCoreApplication.translate("MOIadvcompalwd", u"Limits and Fits", None))
        self.actionGDTFasteners.setText(QCoreApplication.translate("MOIadvcompalwd", u"Fasteners", None))
        self.actionPaper_Gauging.setText(QCoreApplication.translate("MOIadvcompalwd", u"Paper Gauging", None))
        self.actionTolerance_Finder.setText(QCoreApplication.translate("MOIadvcompalwd", u"Tolerance Finder", None))
        self.actionDiameter_Deviation.setText(QCoreApplication.translate("MOIadvcompalwd", u"Diameter Deviation", None))
        self.actionTorsion.setText(QCoreApplication.translate("MOIadvcompalwd", u"Torsion", None))
        self.actionPressure.setText(QCoreApplication.translate("MOIadvcompalwd", u"Pressure", None))
        self.actionAddMohr_s_Circle.setText(QCoreApplication.translate("MOIadvcompalwd", u"Mohr's Circle", None))
        self.actionModule_List.setText(QCoreApplication.translate("MOIadvcompalwd", u"Module List", None))
        self.actionQuit.setText(QCoreApplication.translate("MOIadvcompalwd", u"Quit", None))
        self.actionNotepad.setText(QCoreApplication.translate("MOIadvcompalwd", u"Notepad", None))
        self.actionCalculator.setText(QCoreApplication.translate("MOIadvcompalwd", u"Calculator", None))
        self.actionScreenshot.setText(QCoreApplication.translate("MOIadvcompalwd", u"Screenshot", None))
        self.actionPerfer_SI_units.setText(QCoreApplication.translate("MOIadvcompalwd", u"Edit Saftey Factor", None))
        self.actionPerfer_Metric_Units.setText(QCoreApplication.translate("MOIadvcompalwd", u"Theme", None))
        self.actionMaterials_list.setText(QCoreApplication.translate("MOIadvcompalwd", u"Materials List", None))
        self.actionCross_Sectional_Beams_and_Shapes_Lists.setText(QCoreApplication.translate("MOIadvcompalwd", u"Beams and Shapes Lists", None))
        self.actionAbout.setText(QCoreApplication.translate("MOIadvcompalwd", u"About", None))
        self.actionUnit_Converter_help.setText(QCoreApplication.translate("MOIadvcompalwd", u"Unit Converter", None))
        self.actionMoments_of_Inertia_help.setText(QCoreApplication.translate("MOIadvcompalwd", u"Moments of Inertia", None))
        self.actionVectors_help.setText(QCoreApplication.translate("MOIadvcompalwd", u"Vectors", None))
        self.actionFriction_and_Force_help.setText(QCoreApplication.translate("MOIadvcompalwd", u"Friction and Force", None))
        self.actionFasteners_help.setText(QCoreApplication.translate("MOIadvcompalwd", u"Fasteners", None))
        self.actionMaterial_Properties_help.setText(QCoreApplication.translate("MOIadvcompalwd", u"Material Properties", None))
        self.actionCM_and_CG_help.setText(QCoreApplication.translate("MOIadvcompalwd", u"CM and CG", None))
        self.actionTrusses_help.setText(QCoreApplication.translate("MOIadvcompalwd", u"Trusses", None))
        self.actionBeamsMoments_of_Inertia_help.setText(QCoreApplication.translate("MOIadvcompalwd", u"Moments of Inertia", None))
        self.actionShear_and_Moment_help.setText(QCoreApplication.translate("MOIadvcompalwd", u"Shear and Moment", None))
        self.actionIndeterminate_Axial_Structures_help.setText(QCoreApplication.translate("MOIadvcompalwd", u"Indeterminate Axial Structures", None))
        self.actionFlexure_help.setText(QCoreApplication.translate("MOIadvcompalwd", u"Flexure", None))
        self.actionBeam_Deformation_help.setText(QCoreApplication.translate("MOIadvcompalwd", u"Beam Deformation", None))
        self.actionAxial_Beam_Deformation_help.setText(QCoreApplication.translate("MOIadvcompalwd", u"Axial Beam Deformation", None))
        self.actionTorsional_Beam_Deformation_help.setText(QCoreApplication.translate("MOIadvcompalwd", u"Torsional Beam Deformation", None))
        self.actionSupported_Beams_help.setText(QCoreApplication.translate("MOIadvcompalwd", u"Supported Beams", None))
        self.actionMohr_s_Circle_help.setText(QCoreApplication.translate("MOIadvcompalwd", u"Mohr's Circle", None))
        self.actionC_Clamp_help.setText(QCoreApplication.translate("MOIadvcompalwd", u"C-Clamp", None))
        self.actionCompression_Link_help.setText(QCoreApplication.translate("MOIadvcompalwd", u"Compression Link", None))
        self.actionTension_Link_help.setText(QCoreApplication.translate("MOIadvcompalwd", u"Tension Link", None))
        self.actionPost_help.setText(QCoreApplication.translate("MOIadvcompalwd", u"Post", None))
        self.actionPost_and_Beam_help.setText(QCoreApplication.translate("MOIadvcompalwd", u"Post and Beam", None))
        self.actionSolid_shaft_and_Pipe_help.setText(QCoreApplication.translate("MOIadvcompalwd", u"Solid Shaft and Pipe", None))
        self.actionKinematic_Diagraming_help.setText(QCoreApplication.translate("MOIadvcompalwd", u"Kinematic Diagraming", None))
        self.actionVector_and_Motion_Analysis_help.setText(QCoreApplication.translate("MOIadvcompalwd", u"Vector and Motion Analysis", None))
        self.actionGDT_Checker_help.setText(QCoreApplication.translate("MOIadvcompalwd", u"GDT Checker", None))
        self.actionVirtual_Condition_Calculator_help.setText(QCoreApplication.translate("MOIadvcompalwd", u"Virtual Condition Calculator", None))
        self.actionLimits_and_Fits_help.setText(QCoreApplication.translate("MOIadvcompalwd", u"Limits and Fits", None))
        self.actionGDTFasteners_help.setText(QCoreApplication.translate("MOIadvcompalwd", u"Fasteners", None))
        self.actionPaper_Gauging_help.setText(QCoreApplication.translate("MOIadvcompalwd", u"Paper Gauging", None))
        self.actionTolerance_Finder_help.setText(QCoreApplication.translate("MOIadvcompalwd", u"Tolerance Finder", None))
        self.actionDiameter_Deviation_help.setText(QCoreApplication.translate("MOIadvcompalwd", u"Diameter Deviation", None))
        self.actionTorsion_help.setText(QCoreApplication.translate("MOIadvcompalwd", u"Torsion", None))
        self.actionPressure_help.setText(QCoreApplication.translate("MOIadvcompalwd", u"Pressure", None))
        self.actionTheme.setText(QCoreApplication.translate("MOIadvcompalwd", u"Theme", None))
        self.actionSaftey_Factors.setText(QCoreApplication.translate("MOIadvcompalwd", u"Saftey Factors", None))
        self.actionSolid_Shaft_and_Pipe.setText(QCoreApplication.translate("MOIadvcompalwd", u"Solid Shaft and Pipe", None))
        self.actionMohr_s_Circle_2.setText(QCoreApplication.translate("MOIadvcompalwd", u"Mohr's Circle", None))
        self.actionFit_Classes.setText(QCoreApplication.translate("MOIadvcompalwd", u"Fit Classes", None))
        self.actionQuit_All.setText(QCoreApplication.translate("MOIadvcompalwd", u"Quit All", None))
        self.actionBack_to_Shape_Selector.setText(QCoreApplication.translate("MOIadvcompalwd", u"Back to Shape Selector", None))
        self.Mohrs.setText(QCoreApplication.translate("MOIadvcompalwd", u"Mohr's Circle", None))
        self.computeMOI.setText(QCoreApplication.translate("MOIadvcompalwd", u"Compute", None))
        self.groupBox.setTitle(QCoreApplication.translate("MOIadvcompalwd", u"Axis", None))
        self.xyaxis_2.setText(QCoreApplication.translate("MOIadvcompalwd", u"X - Y", None))
        self.yzaxis_2.setText(QCoreApplication.translate("MOIadvcompalwd", u"Y - Z ", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MOIadvcompalwd", u"Units", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("MOIadvcompalwd", u"Rotate", None))
        self.rotate0deg.setText(QCoreApplication.translate("MOIadvcompalwd", u"0 ", None))
        self.rotate90deg.setText(QCoreApplication.translate("MOIadvcompalwd", u"90", None))
        self.rotate180deg.setText(QCoreApplication.translate("MOIadvcompalwd", u"180", None))
        self.rotate270deg.setText(QCoreApplication.translate("MOIadvcompalwd", u"270", None))
        self.rotate.setText(QCoreApplication.translate("MOIadvcompalwd", u"Rotate", None))
        self.groupBox_5.setTitle("")
        self.label_7.setText(QCoreApplication.translate("MOIadvcompalwd", u"Material Elastic Modulus", None))
        self.label_8.setText(QCoreApplication.translate("MOIadvcompalwd", u"Size ", None))
        self.label_9.setText(QCoreApplication.translate("MOIadvcompalwd", u"Material Elastic Modulus\n"
"Units", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("MOIadvcompalwd", u"Output", None))
        self.AxisProperties.setText(QCoreApplication.translate("MOIadvcompalwd", u"Z Axis Properties", None))
        self.elasticmoduluslabel.setText(QCoreApplication.translate("MOIadvcompalwd", u"Elastic Modulus", None))
        self.elasticmod.setText("")
        self.elasticmodvar.setText(QCoreApplication.translate("MOIadvcompalwd", u"E", None))
        self.bottomtocentroid.setText("")
        self.bottomtocentroidlabel.setText(QCoreApplication.translate("MOIadvcompalwd", u"Distance from Bottom into Centroid ", None))
        self.bottomtocentroidvar.setText(QCoreApplication.translate("MOIadvcompalwd", u"y (bot)", None))
        self.toptocentroid.setText("")
        self.toptocentroidlabel.setText(QCoreApplication.translate("MOIadvcompalwd", u"Distance from Top into Centroid ", None))
        self.toptocentroidvar.setText(QCoreApplication.translate("MOIadvcompalwd", u"y (top)", None))
        self.MOIlabel.setText(QCoreApplication.translate("MOIadvcompalwd", u"Iz", None))
        self.MOI.setText("")
        self.MOIlabel_2.setText(QCoreApplication.translate("MOIadvcompalwd", u"Moment of Inertia", None))
        self.sectionmodvar.setText(QCoreApplication.translate("MOIadvcompalwd", u"Sz", None))
        self.sectionmodlabel.setText(QCoreApplication.translate("MOIadvcompalwd", u"Section Modulus", None))
        self.sectionmod.setText("")
        self.sectionmodbottom.setText("")
        self.sectionmodbottomvar.setText(QCoreApplication.translate("MOIadvcompalwd", u"S (bot)", None))
        self.sectionmodbottomlabel.setText(QCoreApplication.translate("MOIadvcompalwd", u"Section Modulus (Bottom)", None))
        self.sectionmodbottomunits.setText("")
        self.sectionmodtopvar.setText(QCoreApplication.translate("MOIadvcompalwd", u"S (top)", None))
        self.sectionmodtop.setText("")
        self.sectionmodtoplabel.setText(QCoreApplication.translate("MOIadvcompalwd", u"Section Modulus (Top)", None))
        self.sectionmodtopunits.setText("")
        self.radofgyration.setText("")
        self.radofgyrationlabel.setText(QCoreApplication.translate("MOIadvcompalwd", u"Radius of Gyration", None))
        self.radofgyrationvar.setText(QCoreApplication.translate("MOIadvcompalwd", u"rz", None))
        self.radofgyrationunits.setText("")
        self.plasticmod.setText("")
        self.plasticmodvar.setText(QCoreApplication.translate("MOIadvcompalwd", u"Zz", None))
        self.plasticmodlabel.setText(QCoreApplication.translate("MOIadvcompalwd", u"Plastic Modulus", None))
        self.plasticmodunits.setText("")
        self.bottomtoplastic.setText("")
        self.plasticlabel.setText(QCoreApplication.translate("MOIadvcompalwd", u"From Bottom to Plastic n.a", None))
        self.plastictotoplabel.setText(QCoreApplication.translate("MOIadvcompalwd", u"From Plastic n.a to Top", None))
        self.plastictotopunits.setText("")
        self.plastictotop.setText("")
        self.plastictotopvar.setText(QCoreApplication.translate("MOIadvcompalwd", u"yp (top)", None))
        self.shapefactor.setText("")
        self.shapefactorlabel.setText(QCoreApplication.translate("MOIadvcompalwd", u"Shape Factor", None))
        self.plastictobottomunits.setText("")
        self.plasticbottomvariable.setText(QCoreApplication.translate("MOIadvcompalwd", u"yp (bot)", None))
        self.polarMOIlabel.setText(QCoreApplication.translate("MOIadvcompalwd", u"Polar Moment of Inertia", None))
        self.polarMOIvar.setText(QCoreApplication.translate("MOIadvcompalwd", u"J", None))
        self.polarMOIunits.setText("")
        self.polarMOI.setText("")
        self.productofinertia.setText("")
        self.productofinertialabel.setText(QCoreApplication.translate("MOIadvcompalwd", u"Product of Inertia", None))
        self.productofinertiaunits.setText("")
        self.productofinertiavar.setText(QCoreApplication.translate("MOIadvcompalwd", u"Iyz", None))
        self.maxMOIlabel.setText(QCoreApplication.translate("MOIadvcompalwd", u"Maximum Moment of Inertia", None))
        self.maxMOIvar.setText(QCoreApplication.translate("MOIadvcompalwd", u"Imax", None))
        self.maxMOIunits.setText("")
        self.maxMOI.setText("")
        self.minMOI.setText("")
        self.minMOIvar.setText(QCoreApplication.translate("MOIadvcompalwd", u"Imin", None))
        self.minMOIlabel.setText(QCoreApplication.translate("MOIadvcompalwd", u"Minimum Moment of Inertia", None))
        self.minMOIunits.setText("")
        self.axisangle.setText("")
        self.axisangleunits.setText("")
        self.axisanglevar.setText(QCoreApplication.translate("MOIadvcompalwd", u"	\u03b2", None))
        self.axisanglelabel.setText(QCoreApplication.translate("MOIadvcompalwd", u"Angle From Z Axis to Imax Axis", None))
        self.menu_File.setTitle(QCoreApplication.translate("MOIadvcompalwd", u"&File", None))
        self.menu_Settings.setTitle(QCoreApplication.translate("MOIadvcompalwd", u"Settings", None))
        self.menu_Utilites.setTitle(QCoreApplication.translate("MOIadvcompalwd", u"&Utilites", None))
        self.menuTables.setTitle(QCoreApplication.translate("MOIadvcompalwd", u"Tables", None))
        self.menu_Help.setTitle(QCoreApplication.translate("MOIadvcompalwd", u"&Help", None))
        self.menuModules_help.setTitle(QCoreApplication.translate("MOIadvcompalwd", u"Modules", None))
        self.menuGeneral_Analysis_help.setTitle(QCoreApplication.translate("MOIadvcompalwd", u"General Analysis", None))
        self.menuBeams_and_Loads_help.setTitle(QCoreApplication.translate("MOIadvcompalwd", u"Beams and Loads", None))
        self.menuGeneral_Beam_Analysis.setTitle(QCoreApplication.translate("MOIadvcompalwd", u"General Beam Analysis", None))
        self.menuCombined_Loadings_help.setTitle(QCoreApplication.translate("MOIadvcompalwd", u"Combined Loadings", None))
        self.menuEccentric_Loadings_help.setTitle(QCoreApplication.translate("MOIadvcompalwd", u"Eccentric Loadings", None))
        self.menuShear_Force_and_Bending_Moment_help.setTitle(QCoreApplication.translate("MOIadvcompalwd", u"Shear Force and Bending Moment", None))
        self.menuAxial_Torsional_and_Bending_Stresses_help.setTitle(QCoreApplication.translate("MOIadvcompalwd", u"Axial, Torsional, and Bending Stresses", None))
        self.menuKinematics_help.setTitle(QCoreApplication.translate("MOIadvcompalwd", u"Kinematics", None))
        self.menuEngineering_and_Drafting_help.setTitle(QCoreApplication.translate("MOIadvcompalwd", u"Engineering and Drafting", None))
        self.menuAdditional_Calculators_help.setTitle(QCoreApplication.translate("MOIadvcompalwd", u"Additional Calculators", None))
        self.menu_Modules.setTitle(QCoreApplication.translate("MOIadvcompalwd", u"&Modules", None))
        self.menu_General_Analysis.setTitle(QCoreApplication.translate("MOIadvcompalwd", u"General Analysis", None))
        self.menu_Beams_and_Loads.setTitle(QCoreApplication.translate("MOIadvcompalwd", u"Beams and Loads", None))
        self.menu_Generic_Beam_Analysis.setTitle(QCoreApplication.translate("MOIadvcompalwd", u"Generic Beam Analysis", None))
        self.menuCombined_Loadings.setTitle(QCoreApplication.translate("MOIadvcompalwd", u"Combined Loadings", None))
        self.menuEccentric_Loadings.setTitle(QCoreApplication.translate("MOIadvcompalwd", u"Eccentric Loadings", None))
        self.menuShear_Force_and_Bending_Moment.setTitle(QCoreApplication.translate("MOIadvcompalwd", u"Shear Force and Bending Moment", None))
        self.menuAxial_Torsional_and_Bending_Stresses.setTitle(QCoreApplication.translate("MOIadvcompalwd", u"Axial, Torsional, and Bending Stresses", None))
        self.menu_Kinematics.setTitle(QCoreApplication.translate("MOIadvcompalwd", u"Kinematics", None))
        self.menu_Egineering_and_Drafting.setTitle(QCoreApplication.translate("MOIadvcompalwd", u"Egineering and Drafting", None))
        self.menu_Additional_Calculators.setTitle(QCoreApplication.translate("MOIadvcompalwd", u"Additional Calculators", None))
    # retranslateUi

