# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'MOIBasiccomp.ui'
##
## Created by: Qt User Interface Compiler version 6.8.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QAbstractSpinBox, QApplication, QCheckBox, QComboBox,
    QDoubleSpinBox, QFrame, QGraphicsView, QGroupBox,
    QLabel, QLineEdit, QMainWindow, QMenu,
    QMenuBar, QPushButton, QRadioButton, QSizePolicy,
    QStatusBar, QTabWidget, QVBoxLayout, QWidget)

class Ui_MOIBasiccomp(object):
    def setupUi(self, MOIBasiccomp):
        if not MOIBasiccomp.objectName():
            MOIBasiccomp.setObjectName(u"MOIBasiccomp")
        MOIBasiccomp.resize(1145, 910)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MOIBasiccomp.sizePolicy().hasHeightForWidth())
        MOIBasiccomp.setSizePolicy(sizePolicy)
        MOIBasiccomp.setMinimumSize(QSize(1145, 910))
        MOIBasiccomp.setMaximumSize(QSize(1145, 910))
        MOIBasiccomp.setTabShape(QTabWidget.Rounded)
        MOIBasiccomp.setDockNestingEnabled(False)
        MOIBasiccomp.setUnifiedTitleAndToolBarOnMac(False)
        self.actionUnit_Converter = QAction(MOIBasiccomp)
        self.actionUnit_Converter.setObjectName(u"actionUnit_Converter")
        self.actionMoments_of_Inertia = QAction(MOIBasiccomp)
        self.actionMoments_of_Inertia.setObjectName(u"actionMoments_of_Inertia")
        self.actionVectors = QAction(MOIBasiccomp)
        self.actionVectors.setObjectName(u"actionVectors")
        self.actionFriction_and_Force = QAction(MOIBasiccomp)
        self.actionFriction_and_Force.setObjectName(u"actionFriction_and_Force")
        self.actionFasteners = QAction(MOIBasiccomp)
        self.actionFasteners.setObjectName(u"actionFasteners")
        self.actionMaterial_Properties = QAction(MOIBasiccomp)
        self.actionMaterial_Properties.setObjectName(u"actionMaterial_Properties")
        self.actionCM_and_CG = QAction(MOIBasiccomp)
        self.actionCM_and_CG.setObjectName(u"actionCM_and_CG")
        self.actionTrusses = QAction(MOIBasiccomp)
        self.actionTrusses.setObjectName(u"actionTrusses")
        self.actionBeamsMoments_of_Inertia = QAction(MOIBasiccomp)
        self.actionBeamsMoments_of_Inertia.setObjectName(u"actionBeamsMoments_of_Inertia")
        self.actionShear_and_Moment = QAction(MOIBasiccomp)
        self.actionShear_and_Moment.setObjectName(u"actionShear_and_Moment")
        self.actionIndeterminate_Axial_Structures = QAction(MOIBasiccomp)
        self.actionIndeterminate_Axial_Structures.setObjectName(u"actionIndeterminate_Axial_Structures")
        self.actionFlexure = QAction(MOIBasiccomp)
        self.actionFlexure.setObjectName(u"actionFlexure")
        self.actionBeam_Deformation = QAction(MOIBasiccomp)
        self.actionBeam_Deformation.setObjectName(u"actionBeam_Deformation")
        self.actionAxial_Beam_Deformation = QAction(MOIBasiccomp)
        self.actionAxial_Beam_Deformation.setObjectName(u"actionAxial_Beam_Deformation")
        self.actionTorsional_Beam_Deformation = QAction(MOIBasiccomp)
        self.actionTorsional_Beam_Deformation.setObjectName(u"actionTorsional_Beam_Deformation")
        self.actionSupported_Beams = QAction(MOIBasiccomp)
        self.actionSupported_Beams.setObjectName(u"actionSupported_Beams")
        self.actionMohr_s_Circle = QAction(MOIBasiccomp)
        self.actionMohr_s_Circle.setObjectName(u"actionMohr_s_Circle")
        self.actionC_Clamp = QAction(MOIBasiccomp)
        self.actionC_Clamp.setObjectName(u"actionC_Clamp")
        self.actionCompression_Link = QAction(MOIBasiccomp)
        self.actionCompression_Link.setObjectName(u"actionCompression_Link")
        self.actionTension_Link = QAction(MOIBasiccomp)
        self.actionTension_Link.setObjectName(u"actionTension_Link")
        self.actionPost = QAction(MOIBasiccomp)
        self.actionPost.setObjectName(u"actionPost")
        self.actionPost_and_Beam = QAction(MOIBasiccomp)
        self.actionPost_and_Beam.setObjectName(u"actionPost_and_Beam")
        self.actionKinematic_Diagraming = QAction(MOIBasiccomp)
        self.actionKinematic_Diagraming.setObjectName(u"actionKinematic_Diagraming")
        self.actionVector_Analysis = QAction(MOIBasiccomp)
        self.actionVector_Analysis.setObjectName(u"actionVector_Analysis")
        self.actionGDT_Checker = QAction(MOIBasiccomp)
        self.actionGDT_Checker.setObjectName(u"actionGDT_Checker")
        self.actionVirtual_Condition_Calculator = QAction(MOIBasiccomp)
        self.actionVirtual_Condition_Calculator.setObjectName(u"actionVirtual_Condition_Calculator")
        self.actionLimits_and_Fits = QAction(MOIBasiccomp)
        self.actionLimits_and_Fits.setObjectName(u"actionLimits_and_Fits")
        self.actionGDTFasteners = QAction(MOIBasiccomp)
        self.actionGDTFasteners.setObjectName(u"actionGDTFasteners")
        self.actionPaper_Gauging = QAction(MOIBasiccomp)
        self.actionPaper_Gauging.setObjectName(u"actionPaper_Gauging")
        self.actionTolerance_Finder = QAction(MOIBasiccomp)
        self.actionTolerance_Finder.setObjectName(u"actionTolerance_Finder")
        self.actionDiameter_Deviation = QAction(MOIBasiccomp)
        self.actionDiameter_Deviation.setObjectName(u"actionDiameter_Deviation")
        self.actionTorsion = QAction(MOIBasiccomp)
        self.actionTorsion.setObjectName(u"actionTorsion")
        self.actionPressure = QAction(MOIBasiccomp)
        self.actionPressure.setObjectName(u"actionPressure")
        self.actionAddMohr_s_Circle = QAction(MOIBasiccomp)
        self.actionAddMohr_s_Circle.setObjectName(u"actionAddMohr_s_Circle")
        self.actionModule_List = QAction(MOIBasiccomp)
        self.actionModule_List.setObjectName(u"actionModule_List")
        self.actionQuit = QAction(MOIBasiccomp)
        self.actionQuit.setObjectName(u"actionQuit")
        self.actionNotepad = QAction(MOIBasiccomp)
        self.actionNotepad.setObjectName(u"actionNotepad")
        self.actionCalculator = QAction(MOIBasiccomp)
        self.actionCalculator.setObjectName(u"actionCalculator")
        self.actionScreenshot = QAction(MOIBasiccomp)
        self.actionScreenshot.setObjectName(u"actionScreenshot")
        self.actionPerfer_SI_units = QAction(MOIBasiccomp)
        self.actionPerfer_SI_units.setObjectName(u"actionPerfer_SI_units")
        self.actionPerfer_Metric_Units = QAction(MOIBasiccomp)
        self.actionPerfer_Metric_Units.setObjectName(u"actionPerfer_Metric_Units")
        self.actionMaterials_list = QAction(MOIBasiccomp)
        self.actionMaterials_list.setObjectName(u"actionMaterials_list")
        self.actionCross_Sectional_Beams_and_Shapes_Lists = QAction(MOIBasiccomp)
        self.actionCross_Sectional_Beams_and_Shapes_Lists.setObjectName(u"actionCross_Sectional_Beams_and_Shapes_Lists")
        self.actionAbout = QAction(MOIBasiccomp)
        self.actionAbout.setObjectName(u"actionAbout")
        self.actionUnit_Converter_help = QAction(MOIBasiccomp)
        self.actionUnit_Converter_help.setObjectName(u"actionUnit_Converter_help")
        self.actionMoments_of_Inertia_help = QAction(MOIBasiccomp)
        self.actionMoments_of_Inertia_help.setObjectName(u"actionMoments_of_Inertia_help")
        self.actionVectors_help = QAction(MOIBasiccomp)
        self.actionVectors_help.setObjectName(u"actionVectors_help")
        self.actionFriction_and_Force_help = QAction(MOIBasiccomp)
        self.actionFriction_and_Force_help.setObjectName(u"actionFriction_and_Force_help")
        self.actionFasteners_help = QAction(MOIBasiccomp)
        self.actionFasteners_help.setObjectName(u"actionFasteners_help")
        self.actionMaterial_Properties_help = QAction(MOIBasiccomp)
        self.actionMaterial_Properties_help.setObjectName(u"actionMaterial_Properties_help")
        self.actionCM_and_CG_help = QAction(MOIBasiccomp)
        self.actionCM_and_CG_help.setObjectName(u"actionCM_and_CG_help")
        self.actionTrusses_help = QAction(MOIBasiccomp)
        self.actionTrusses_help.setObjectName(u"actionTrusses_help")
        self.actionBeamsMoments_of_Inertia_help = QAction(MOIBasiccomp)
        self.actionBeamsMoments_of_Inertia_help.setObjectName(u"actionBeamsMoments_of_Inertia_help")
        self.actionShear_and_Moment_help = QAction(MOIBasiccomp)
        self.actionShear_and_Moment_help.setObjectName(u"actionShear_and_Moment_help")
        self.actionIndeterminate_Axial_Structures_help = QAction(MOIBasiccomp)
        self.actionIndeterminate_Axial_Structures_help.setObjectName(u"actionIndeterminate_Axial_Structures_help")
        self.actionFlexure_help = QAction(MOIBasiccomp)
        self.actionFlexure_help.setObjectName(u"actionFlexure_help")
        self.actionBeam_Deformation_help = QAction(MOIBasiccomp)
        self.actionBeam_Deformation_help.setObjectName(u"actionBeam_Deformation_help")
        self.actionAxial_Beam_Deformation_help = QAction(MOIBasiccomp)
        self.actionAxial_Beam_Deformation_help.setObjectName(u"actionAxial_Beam_Deformation_help")
        self.actionTorsional_Beam_Deformation_help = QAction(MOIBasiccomp)
        self.actionTorsional_Beam_Deformation_help.setObjectName(u"actionTorsional_Beam_Deformation_help")
        self.actionSupported_Beams_help = QAction(MOIBasiccomp)
        self.actionSupported_Beams_help.setObjectName(u"actionSupported_Beams_help")
        self.actionMohr_s_Circle_help = QAction(MOIBasiccomp)
        self.actionMohr_s_Circle_help.setObjectName(u"actionMohr_s_Circle_help")
        self.actionC_Clamp_help = QAction(MOIBasiccomp)
        self.actionC_Clamp_help.setObjectName(u"actionC_Clamp_help")
        self.actionCompression_Link_help = QAction(MOIBasiccomp)
        self.actionCompression_Link_help.setObjectName(u"actionCompression_Link_help")
        self.actionTension_Link_help = QAction(MOIBasiccomp)
        self.actionTension_Link_help.setObjectName(u"actionTension_Link_help")
        self.actionPost_help = QAction(MOIBasiccomp)
        self.actionPost_help.setObjectName(u"actionPost_help")
        self.actionPost_and_Beam_help = QAction(MOIBasiccomp)
        self.actionPost_and_Beam_help.setObjectName(u"actionPost_and_Beam_help")
        self.actionSolid_shaft_and_Pipe_help = QAction(MOIBasiccomp)
        self.actionSolid_shaft_and_Pipe_help.setObjectName(u"actionSolid_shaft_and_Pipe_help")
        self.actionKinematic_Diagraming_help = QAction(MOIBasiccomp)
        self.actionKinematic_Diagraming_help.setObjectName(u"actionKinematic_Diagraming_help")
        self.actionVector_and_Motion_Analysis_help = QAction(MOIBasiccomp)
        self.actionVector_and_Motion_Analysis_help.setObjectName(u"actionVector_and_Motion_Analysis_help")
        self.actionGDT_Checker_help = QAction(MOIBasiccomp)
        self.actionGDT_Checker_help.setObjectName(u"actionGDT_Checker_help")
        self.actionVirtual_Condition_Calculator_help = QAction(MOIBasiccomp)
        self.actionVirtual_Condition_Calculator_help.setObjectName(u"actionVirtual_Condition_Calculator_help")
        self.actionLimits_and_Fits_help = QAction(MOIBasiccomp)
        self.actionLimits_and_Fits_help.setObjectName(u"actionLimits_and_Fits_help")
        self.actionGDTFasteners_help = QAction(MOIBasiccomp)
        self.actionGDTFasteners_help.setObjectName(u"actionGDTFasteners_help")
        self.actionPaper_Gauging_help = QAction(MOIBasiccomp)
        self.actionPaper_Gauging_help.setObjectName(u"actionPaper_Gauging_help")
        self.actionTolerance_Finder_help = QAction(MOIBasiccomp)
        self.actionTolerance_Finder_help.setObjectName(u"actionTolerance_Finder_help")
        self.actionDiameter_Deviation_help = QAction(MOIBasiccomp)
        self.actionDiameter_Deviation_help.setObjectName(u"actionDiameter_Deviation_help")
        self.actionTorsion_help = QAction(MOIBasiccomp)
        self.actionTorsion_help.setObjectName(u"actionTorsion_help")
        self.actionPressure_help = QAction(MOIBasiccomp)
        self.actionPressure_help.setObjectName(u"actionPressure_help")
        self.actionTheme = QAction(MOIBasiccomp)
        self.actionTheme.setObjectName(u"actionTheme")
        self.actionSaftey_Factors = QAction(MOIBasiccomp)
        self.actionSaftey_Factors.setObjectName(u"actionSaftey_Factors")
        self.actionSolid_Shaft_and_Pipe = QAction(MOIBasiccomp)
        self.actionSolid_Shaft_and_Pipe.setObjectName(u"actionSolid_Shaft_and_Pipe")
        self.actionMohr_s_Circle_2 = QAction(MOIBasiccomp)
        self.actionMohr_s_Circle_2.setObjectName(u"actionMohr_s_Circle_2")
        self.actionFit_Classes = QAction(MOIBasiccomp)
        self.actionFit_Classes.setObjectName(u"actionFit_Classes")
        self.actionQuit_All = QAction(MOIBasiccomp)
        self.actionQuit_All.setObjectName(u"actionQuit_All")
        self.actionBack_to_Shape_Selector = QAction(MOIBasiccomp)
        self.actionBack_to_Shape_Selector.setObjectName(u"actionBack_to_Shape_Selector")
        self.centralwidget = QWidget(MOIBasiccomp)
        self.centralwidget.setObjectName(u"centralwidget")
        self.graphicsView = QGraphicsView(self.centralwidget)
        self.graphicsView.setObjectName(u"graphicsView")
        self.graphicsView.setGeometry(QRect(130, 59, 321, 521))
        sizePolicy.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy)
        font = QFont()
        font.setPointSize(12)
        self.graphicsView.setFont(font)
        self.pushButton = QPushButton(self.centralwidget)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(510, 360, 111, 41))
        self.pushButton.setFont(font)
        self.computeMOI = QPushButton(self.centralwidget)
        self.computeMOI.setObjectName(u"computeMOI")
        self.computeMOI.setGeometry(QRect(510, 410, 111, 41))
        self.computeMOI.setFont(font)
        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(510, 0, 111, 81))
        self.groupBox.setFont(font)
        self.verticalLayout_2 = QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.xyaxis_2 = QRadioButton(self.groupBox)
        self.xyaxis_2.setObjectName(u"xyaxis_2")
        self.xyaxis_2.setFont(font)

        self.verticalLayout_2.addWidget(self.xyaxis_2)

        self.yzaxis_2 = QRadioButton(self.groupBox)
        self.yzaxis_2.setObjectName(u"yzaxis_2")
        self.yzaxis_2.setFont(font)

        self.verticalLayout_2.addWidget(self.yzaxis_2)

        self.groupBox_2 = QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(510, 80, 111, 61))
        self.groupBox_2.setFont(font)
        self.verticalLayout = QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.Unitscombobox = QComboBox(self.groupBox_2)
        self.Unitscombobox.setObjectName(u"Unitscombobox")
        self.Unitscombobox.setFont(font)

        self.verticalLayout.addWidget(self.Unitscombobox)

        self.groupBox_3 = QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(510, 150, 111, 201))
        self.groupBox_3.setFont(font)
        self.verticalLayout_3 = QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.rotate0deg = QRadioButton(self.groupBox_3)
        self.rotate0deg.setObjectName(u"rotate0deg")
        self.rotate0deg.setFont(font)

        self.verticalLayout_3.addWidget(self.rotate0deg)

        self.rotate90deg = QRadioButton(self.groupBox_3)
        self.rotate90deg.setObjectName(u"rotate90deg")
        self.rotate90deg.setFont(font)

        self.verticalLayout_3.addWidget(self.rotate90deg)

        self.rotate180deg = QRadioButton(self.groupBox_3)
        self.rotate180deg.setObjectName(u"rotate180deg")
        self.rotate180deg.setFont(font)

        self.verticalLayout_3.addWidget(self.rotate180deg)

        self.rotate270deg = QRadioButton(self.groupBox_3)
        self.rotate270deg.setObjectName(u"rotate270deg")
        self.rotate270deg.setFont(font)

        self.verticalLayout_3.addWidget(self.rotate270deg)

        self.rotate = QPushButton(self.groupBox_3)
        self.rotate.setObjectName(u"rotate")
        self.rotate.setFont(font)

        self.verticalLayout_3.addWidget(self.rotate)

        self.lineEdit = QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(100, 10, 391, 41))
        self.lineEdit.setAlignment(Qt.AlignCenter)
        self.lineEdit.setReadOnly(True)
        self.groupBox_5 = QGroupBox(self.centralwidget)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setGeometry(QRect(640, 0, 491, 751))
        self.groupBox_5.setFont(font)
        self.plasticmodvar = QLabel(self.groupBox_5)
        self.plasticmodvar.setObjectName(u"plasticmodvar")
        self.plasticmodvar.setGeometry(QRect(370, 392, 61, 28))
        self.plasticmodvar.setMinimumSize(QSize(0, 28))
        self.plasticmodvar.setMaximumSize(QSize(16777215, 28))
        font1 = QFont()
        font1.setPointSize(11)
        self.plasticmodvar.setFont(font1)
        self.plasticmodvar.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.plasticmodunits = QLineEdit(self.groupBox_5)
        self.plasticmodunits.setObjectName(u"plasticmodunits")
        self.plasticmodunits.setGeometry(QRect(441, 392, 40, 28))
        self.plasticmodunits.setMinimumSize(QSize(0, 28))
        self.plasticmodunits.setMaximumSize(QSize(16777215, 28))
        self.plasticmodunits.setReadOnly(True)
        self.plastictotopunits = QLineEdit(self.groupBox_5)
        self.plastictotopunits.setObjectName(u"plastictotopunits")
        self.plastictotopunits.setGeometry(QRect(441, 499, 39, 28))
        self.plastictotopunits.setMinimumSize(QSize(0, 28))
        self.plastictotopunits.setMaximumSize(QSize(16777215, 28))
        self.plastictotopunits.setReadOnly(True)
        self.plastictotopvar = QLabel(self.groupBox_5)
        self.plastictotopvar.setObjectName(u"plastictotopvar")
        self.plastictotopvar.setGeometry(QRect(370, 499, 61, 28))
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.plastictotopvar.sizePolicy().hasHeightForWidth())
        self.plastictotopvar.setSizePolicy(sizePolicy1)
        self.plastictotopvar.setMinimumSize(QSize(0, 28))
        self.plastictotopvar.setMaximumSize(QSize(16777215, 28))
        self.plastictotopvar.setFont(font1)
        self.plastictotopvar.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.plastictobottomunits = QLineEdit(self.groupBox_5)
        self.plastictobottomunits.setObjectName(u"plastictobottomunits")
        self.plastictobottomunits.setGeometry(QRect(441, 465, 39, 28))
        self.plastictobottomunits.setMinimumSize(QSize(0, 28))
        self.plastictobottomunits.setMaximumSize(QSize(16777215, 28))
        self.plastictobottomunits.setReadOnly(True)
        self.plasticbottomvariable = QLabel(self.groupBox_5)
        self.plasticbottomvariable.setObjectName(u"plasticbottomvariable")
        self.plasticbottomvariable.setGeometry(QRect(370, 465, 61, 28))
        self.plasticbottomvariable.setMinimumSize(QSize(0, 28))
        self.plasticbottomvariable.setMaximumSize(QSize(16777215, 28))
        self.plasticbottomvariable.setFont(font1)
        self.plasticbottomvariable.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.polarMOIunits = QLineEdit(self.groupBox_5)
        self.polarMOIunits.setObjectName(u"polarMOIunits")
        self.polarMOIunits.setGeometry(QRect(441, 551, 39, 28))
        sizePolicy.setHeightForWidth(self.polarMOIunits.sizePolicy().hasHeightForWidth())
        self.polarMOIunits.setSizePolicy(sizePolicy)
        self.polarMOIunits.setMinimumSize(QSize(0, 28))
        self.polarMOIunits.setMaximumSize(QSize(39, 28))
        self.polarMOIunits.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.polarMOIunits.setReadOnly(True)
        self.productofinertiaunits = QLineEdit(self.groupBox_5)
        self.productofinertiaunits.setObjectName(u"productofinertiaunits")
        self.productofinertiaunits.setGeometry(QRect(441, 585, 39, 28))
        sizePolicy.setHeightForWidth(self.productofinertiaunits.sizePolicy().hasHeightForWidth())
        self.productofinertiaunits.setSizePolicy(sizePolicy)
        self.productofinertiaunits.setMinimumSize(QSize(0, 28))
        self.productofinertiaunits.setMaximumSize(QSize(39, 28))
        self.productofinertiaunits.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.productofinertiaunits.setReadOnly(True)
        self.axisprops = QComboBox(self.groupBox_5)
        self.axisprops.addItem("")
        self.axisprops.addItem("")
        self.axisprops.setObjectName(u"axisprops")
        self.axisprops.setGeometry(QRect(150, 20, 191, 25))
        self.axisprops.setFont(font)
        self.minMOIunits = QLineEdit(self.groupBox_5)
        self.minMOIunits.setObjectName(u"minMOIunits")
        self.minMOIunits.setGeometry(QRect(441, 653, 39, 28))
        sizePolicy.setHeightForWidth(self.minMOIunits.sizePolicy().hasHeightForWidth())
        self.minMOIunits.setSizePolicy(sizePolicy)
        self.minMOIunits.setMinimumSize(QSize(0, 28))
        self.minMOIunits.setMaximumSize(QSize(39, 28))
        self.minMOIunits.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.minMOIunits.setReadOnly(True)
        self.axisangleunits = QLineEdit(self.groupBox_5)
        self.axisangleunits.setObjectName(u"axisangleunits")
        self.axisangleunits.setGeometry(QRect(399, 690, 81, 28))
        sizePolicy.setHeightForWidth(self.axisangleunits.sizePolicy().hasHeightForWidth())
        self.axisangleunits.setSizePolicy(sizePolicy)
        self.axisangleunits.setMinimumSize(QSize(60, 28))
        self.axisangleunits.setMaximumSize(QSize(16777215, 28))
        self.axisangleunits.setReadOnly(True)
        self.maxMOIunits = QLineEdit(self.groupBox_5)
        self.maxMOIunits.setObjectName(u"maxMOIunits")
        self.maxMOIunits.setGeometry(QRect(441, 619, 39, 28))
        sizePolicy.setHeightForWidth(self.maxMOIunits.sizePolicy().hasHeightForWidth())
        self.maxMOIunits.setSizePolicy(sizePolicy)
        self.maxMOIunits.setMinimumSize(QSize(0, 28))
        self.maxMOIunits.setMaximumSize(QSize(39, 28))
        self.maxMOIunits.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.maxMOIunits.setReadOnly(True)
        self.axisangledirec = QLabel(self.groupBox_5)
        self.axisangledirec.setObjectName(u"axisangledirec")
        self.axisangledirec.setGeometry(QRect(243, 720, 131, 21))
        sizePolicy1.setHeightForWidth(self.axisangledirec.sizePolicy().hasHeightForWidth())
        self.axisangledirec.setSizePolicy(sizePolicy1)
        self.axisangledirec.setFont(font1)
        self.axisangledirec.setWordWrap(False)
        self.layoutWidget_2 = QWidget(self.groupBox_5)
        self.layoutWidget_2.setObjectName(u"layoutWidget_2")
        self.layoutWidget_2.setGeometry(QRect(10, 550, 231, 171))
        self.verticalLayout_6 = QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_6.setObjectName(u"verticalLayout_6")
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.polarMOIlabel = QLabel(self.layoutWidget_2)
        self.polarMOIlabel.setObjectName(u"polarMOIlabel")
        self.polarMOIlabel.setMinimumSize(QSize(0, 28))
        self.polarMOIlabel.setMaximumSize(QSize(16777215, 28))
        self.polarMOIlabel.setFont(font1)
        self.polarMOIlabel.setWordWrap(False)

        self.verticalLayout_6.addWidget(self.polarMOIlabel)

        self.productofinertialabel = QLabel(self.layoutWidget_2)
        self.productofinertialabel.setObjectName(u"productofinertialabel")
        self.productofinertialabel.setMinimumSize(QSize(0, 28))
        self.productofinertialabel.setMaximumSize(QSize(16777215, 28))
        self.productofinertialabel.setFont(font1)
        self.productofinertialabel.setWordWrap(False)

        self.verticalLayout_6.addWidget(self.productofinertialabel)

        self.maxMOIlabel = QLabel(self.layoutWidget_2)
        self.maxMOIlabel.setObjectName(u"maxMOIlabel")
        self.maxMOIlabel.setMinimumSize(QSize(0, 28))
        self.maxMOIlabel.setMaximumSize(QSize(16777215, 28))
        self.maxMOIlabel.setFont(font1)
        self.maxMOIlabel.setWordWrap(False)

        self.verticalLayout_6.addWidget(self.maxMOIlabel)

        self.minMOIlabel = QLabel(self.layoutWidget_2)
        self.minMOIlabel.setObjectName(u"minMOIlabel")
        self.minMOIlabel.setMinimumSize(QSize(0, 28))
        self.minMOIlabel.setMaximumSize(QSize(16777215, 28))
        self.minMOIlabel.setFont(font1)
        self.minMOIlabel.setWordWrap(False)

        self.verticalLayout_6.addWidget(self.minMOIlabel)

        self.axisanglelabel = QLabel(self.layoutWidget_2)
        self.axisanglelabel.setObjectName(u"axisanglelabel")
        self.axisanglelabel.setMinimumSize(QSize(0, 28))
        self.axisanglelabel.setMaximumSize(QSize(16777215, 28))
        self.axisanglelabel.setFont(font1)
        self.axisanglelabel.setWordWrap(False)

        self.verticalLayout_6.addWidget(self.axisanglelabel)

        self.layoutWidget_3 = QWidget(self.groupBox_5)
        self.layoutWidget_3.setObjectName(u"layoutWidget_3")
        self.layoutWidget_3.setGeometry(QRect(10, 390, 231, 141))
        self.verticalLayout_7 = QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_7.setObjectName(u"verticalLayout_7")
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.plasticmodlabel = QLabel(self.layoutWidget_3)
        self.plasticmodlabel.setObjectName(u"plasticmodlabel")
        self.plasticmodlabel.setMinimumSize(QSize(0, 28))
        self.plasticmodlabel.setMaximumSize(QSize(16777215, 28))
        self.plasticmodlabel.setFont(font1)
        self.plasticmodlabel.setWordWrap(False)

        self.verticalLayout_7.addWidget(self.plasticmodlabel)

        self.shapefactorlabel = QLabel(self.layoutWidget_3)
        self.shapefactorlabel.setObjectName(u"shapefactorlabel")
        self.shapefactorlabel.setMinimumSize(QSize(0, 28))
        self.shapefactorlabel.setMaximumSize(QSize(16777215, 28))
        self.shapefactorlabel.setFont(font1)
        self.shapefactorlabel.setWordWrap(False)

        self.verticalLayout_7.addWidget(self.shapefactorlabel)

        self.plasticlabel = QLabel(self.layoutWidget_3)
        self.plasticlabel.setObjectName(u"plasticlabel")
        self.plasticlabel.setMinimumSize(QSize(0, 28))
        self.plasticlabel.setMaximumSize(QSize(16777215, 28))
        self.plasticlabel.setFont(font1)
        self.plasticlabel.setWordWrap(False)

        self.verticalLayout_7.addWidget(self.plasticlabel)

        self.plastictotoplabel = QLabel(self.layoutWidget_3)
        self.plastictotoplabel.setObjectName(u"plastictotoplabel")
        self.plastictotoplabel.setMinimumSize(QSize(0, 28))
        self.plastictotoplabel.setMaximumSize(QSize(16777215, 28))
        self.plastictotoplabel.setFont(font1)
        self.plastictotoplabel.setWordWrap(False)

        self.verticalLayout_7.addWidget(self.plastictotoplabel)

        self.layoutWidget_4 = QWidget(self.groupBox_5)
        self.layoutWidget_4.setObjectName(u"layoutWidget_4")
        self.layoutWidget_4.setGeometry(QRect(10, 200, 231, 171))
        self.verticalLayout_8 = QVBoxLayout(self.layoutWidget_4)
        self.verticalLayout_8.setObjectName(u"verticalLayout_8")
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.MOIlabel_2 = QLabel(self.layoutWidget_4)
        self.MOIlabel_2.setObjectName(u"MOIlabel_2")
        self.MOIlabel_2.setMinimumSize(QSize(0, 28))
        self.MOIlabel_2.setMaximumSize(QSize(16777215, 28))
        self.MOIlabel_2.setFont(font1)
        self.MOIlabel_2.setWordWrap(False)

        self.verticalLayout_8.addWidget(self.MOIlabel_2)

        self.sectionmodlabel = QLabel(self.layoutWidget_4)
        self.sectionmodlabel.setObjectName(u"sectionmodlabel")
        self.sectionmodlabel.setMinimumSize(QSize(0, 28))
        self.sectionmodlabel.setMaximumSize(QSize(16777215, 28))
        self.sectionmodlabel.setFont(font1)
        self.sectionmodlabel.setWordWrap(False)

        self.verticalLayout_8.addWidget(self.sectionmodlabel)

        self.sectionmodbottomlabel = QLabel(self.layoutWidget_4)
        self.sectionmodbottomlabel.setObjectName(u"sectionmodbottomlabel")
        self.sectionmodbottomlabel.setMinimumSize(QSize(0, 28))
        self.sectionmodbottomlabel.setMaximumSize(QSize(16777215, 28))
        self.sectionmodbottomlabel.setFont(font1)
        self.sectionmodbottomlabel.setWordWrap(False)

        self.verticalLayout_8.addWidget(self.sectionmodbottomlabel)

        self.sectionmodtoplabel = QLabel(self.layoutWidget_4)
        self.sectionmodtoplabel.setObjectName(u"sectionmodtoplabel")
        self.sectionmodtoplabel.setMinimumSize(QSize(0, 28))
        self.sectionmodtoplabel.setMaximumSize(QSize(16777215, 28))
        self.sectionmodtoplabel.setFont(font1)
        self.sectionmodtoplabel.setWordWrap(False)

        self.verticalLayout_8.addWidget(self.sectionmodtoplabel)

        self.radofgyrationlabel = QLabel(self.layoutWidget_4)
        self.radofgyrationlabel.setObjectName(u"radofgyrationlabel")
        self.radofgyrationlabel.setMinimumSize(QSize(0, 28))
        self.radofgyrationlabel.setMaximumSize(QSize(16777215, 28))
        self.radofgyrationlabel.setFont(font1)
        self.radofgyrationlabel.setWordWrap(False)

        self.verticalLayout_8.addWidget(self.radofgyrationlabel)

        self.layoutWidget_5 = QWidget(self.groupBox_5)
        self.layoutWidget_5.setObjectName(u"layoutWidget_5")
        self.layoutWidget_5.setGeometry(QRect(10, 50, 231, 131))
        self.verticalLayout_9 = QVBoxLayout(self.layoutWidget_5)
        self.verticalLayout_9.setObjectName(u"verticalLayout_9")
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.elasticmoduluslabel = QLabel(self.layoutWidget_5)
        self.elasticmoduluslabel.setObjectName(u"elasticmoduluslabel")
        self.elasticmoduluslabel.setFont(font1)

        self.verticalLayout_9.addWidget(self.elasticmoduluslabel)

        self.bottomtocentroidlabel = QLabel(self.layoutWidget_5)
        self.bottomtocentroidlabel.setObjectName(u"bottomtocentroidlabel")
        self.bottomtocentroidlabel.setFont(font1)
        self.bottomtocentroidlabel.setWordWrap(False)

        self.verticalLayout_9.addWidget(self.bottomtocentroidlabel)

        self.toptocentroidlabel = QLabel(self.layoutWidget_5)
        self.toptocentroidlabel.setObjectName(u"toptocentroidlabel")
        self.toptocentroidlabel.setFont(font1)
        self.toptocentroidlabel.setWordWrap(False)

        self.verticalLayout_9.addWidget(self.toptocentroidlabel)

        self.arealabel = QLabel(self.layoutWidget_5)
        self.arealabel.setObjectName(u"arealabel")
        self.arealabel.setFont(font1)
        self.arealabel.setWordWrap(False)

        self.verticalLayout_9.addWidget(self.arealabel)

        self.layoutWidget_6 = QWidget(self.groupBox_5)
        self.layoutWidget_6.setObjectName(u"layoutWidget_6")
        self.layoutWidget_6.setGeometry(QRect(240, 50, 121, 132))
        self.verticalLayout_10 = QVBoxLayout(self.layoutWidget_6)
        self.verticalLayout_10.setObjectName(u"verticalLayout_10")
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.elasticmod = QDoubleSpinBox(self.layoutWidget_6)
        self.elasticmod.setObjectName(u"elasticmod")
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Fixed)
        sizePolicy2.setHorizontalStretch(250)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.elasticmod.sizePolicy().hasHeightForWidth())
        self.elasticmod.setSizePolicy(sizePolicy2)
        self.elasticmod.setMinimumSize(QSize(0, 28))
        self.elasticmod.setMaximumSize(QSize(16777215, 28))
        self.elasticmod.setFont(font)
        self.elasticmod.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.elasticmod.setDecimals(10)
        self.elasticmod.setMaximum(1000000000000.000000000000000)

        self.verticalLayout_10.addWidget(self.elasticmod)

        self.bottomtocentroid = QDoubleSpinBox(self.layoutWidget_6)
        self.bottomtocentroid.setObjectName(u"bottomtocentroid")
        sizePolicy2.setHeightForWidth(self.bottomtocentroid.sizePolicy().hasHeightForWidth())
        self.bottomtocentroid.setSizePolicy(sizePolicy2)
        self.bottomtocentroid.setMinimumSize(QSize(0, 28))
        self.bottomtocentroid.setMaximumSize(QSize(16777215, 28))
        self.bottomtocentroid.setFont(font)
        self.bottomtocentroid.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.bottomtocentroid.setDecimals(10)
        self.bottomtocentroid.setMaximum(1000000000000.000000000000000)

        self.verticalLayout_10.addWidget(self.bottomtocentroid)

        self.toptocentroid = QDoubleSpinBox(self.layoutWidget_6)
        self.toptocentroid.setObjectName(u"toptocentroid")
        sizePolicy2.setHeightForWidth(self.toptocentroid.sizePolicy().hasHeightForWidth())
        self.toptocentroid.setSizePolicy(sizePolicy2)
        self.toptocentroid.setMinimumSize(QSize(0, 28))
        self.toptocentroid.setMaximumSize(QSize(16777215, 28))
        self.toptocentroid.setFont(font)
        self.toptocentroid.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.toptocentroid.setDecimals(10)
        self.toptocentroid.setMaximum(1000000000000.000000000000000)

        self.verticalLayout_10.addWidget(self.toptocentroid)

        self.area = QDoubleSpinBox(self.layoutWidget_6)
        self.area.setObjectName(u"area")
        sizePolicy2.setHeightForWidth(self.area.sizePolicy().hasHeightForWidth())
        self.area.setSizePolicy(sizePolicy2)
        self.area.setMinimumSize(QSize(0, 28))
        self.area.setMaximumSize(QSize(16777215, 28))
        self.area.setFont(font)
        self.area.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.area.setDecimals(10)
        self.area.setMaximum(1000000000000.000000000000000)

        self.verticalLayout_10.addWidget(self.area)

        self.layoutWidget_7 = QWidget(self.groupBox_5)
        self.layoutWidget_7.setObjectName(u"layoutWidget_7")
        self.layoutWidget_7.setGeometry(QRect(240, 200, 121, 171))
        self.verticalLayout_11 = QVBoxLayout(self.layoutWidget_7)
        self.verticalLayout_11.setObjectName(u"verticalLayout_11")
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.MOI = QDoubleSpinBox(self.layoutWidget_7)
        self.MOI.setObjectName(u"MOI")
        sizePolicy2.setHeightForWidth(self.MOI.sizePolicy().hasHeightForWidth())
        self.MOI.setSizePolicy(sizePolicy2)
        self.MOI.setMinimumSize(QSize(0, 28))
        self.MOI.setMaximumSize(QSize(16777215, 28))
        self.MOI.setFont(font)
        self.MOI.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.MOI.setDecimals(10)
        self.MOI.setMaximum(1000000000000.000000000000000)

        self.verticalLayout_11.addWidget(self.MOI)

        self.sectionmod = QDoubleSpinBox(self.layoutWidget_7)
        self.sectionmod.setObjectName(u"sectionmod")
        sizePolicy2.setHeightForWidth(self.sectionmod.sizePolicy().hasHeightForWidth())
        self.sectionmod.setSizePolicy(sizePolicy2)
        self.sectionmod.setMinimumSize(QSize(0, 28))
        self.sectionmod.setMaximumSize(QSize(16777215, 28))
        self.sectionmod.setFont(font)
        self.sectionmod.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.sectionmod.setDecimals(10)
        self.sectionmod.setMaximum(1000000000000.000000000000000)

        self.verticalLayout_11.addWidget(self.sectionmod)

        self.sectionmodbottom = QDoubleSpinBox(self.layoutWidget_7)
        self.sectionmodbottom.setObjectName(u"sectionmodbottom")
        sizePolicy2.setHeightForWidth(self.sectionmodbottom.sizePolicy().hasHeightForWidth())
        self.sectionmodbottom.setSizePolicy(sizePolicy2)
        self.sectionmodbottom.setMinimumSize(QSize(0, 28))
        self.sectionmodbottom.setMaximumSize(QSize(16777215, 28))
        self.sectionmodbottom.setFont(font)
        self.sectionmodbottom.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.sectionmodbottom.setDecimals(10)
        self.sectionmodbottom.setMaximum(1000000000000.000000000000000)

        self.verticalLayout_11.addWidget(self.sectionmodbottom)

        self.sectionmodtop = QDoubleSpinBox(self.layoutWidget_7)
        self.sectionmodtop.setObjectName(u"sectionmodtop")
        sizePolicy2.setHeightForWidth(self.sectionmodtop.sizePolicy().hasHeightForWidth())
        self.sectionmodtop.setSizePolicy(sizePolicy2)
        self.sectionmodtop.setMinimumSize(QSize(0, 28))
        self.sectionmodtop.setMaximumSize(QSize(16777215, 28))
        self.sectionmodtop.setFont(font)
        self.sectionmodtop.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.sectionmodtop.setDecimals(10)
        self.sectionmodtop.setMaximum(1000000000000.000000000000000)

        self.verticalLayout_11.addWidget(self.sectionmodtop)

        self.radofgyration = QDoubleSpinBox(self.layoutWidget_7)
        self.radofgyration.setObjectName(u"radofgyration")
        sizePolicy2.setHeightForWidth(self.radofgyration.sizePolicy().hasHeightForWidth())
        self.radofgyration.setSizePolicy(sizePolicy2)
        self.radofgyration.setMinimumSize(QSize(0, 28))
        self.radofgyration.setMaximumSize(QSize(16777215, 28))
        self.radofgyration.setFont(font)
        self.radofgyration.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.radofgyration.setDecimals(10)
        self.radofgyration.setMaximum(1000000000000.000000000000000)

        self.verticalLayout_11.addWidget(self.radofgyration)

        self.layoutWidget_8 = QWidget(self.groupBox_5)
        self.layoutWidget_8.setObjectName(u"layoutWidget_8")
        self.layoutWidget_8.setGeometry(QRect(240, 390, 121, 141))
        self.verticalLayout_12 = QVBoxLayout(self.layoutWidget_8)
        self.verticalLayout_12.setObjectName(u"verticalLayout_12")
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.plasticmod = QDoubleSpinBox(self.layoutWidget_8)
        self.plasticmod.setObjectName(u"plasticmod")
        sizePolicy2.setHeightForWidth(self.plasticmod.sizePolicy().hasHeightForWidth())
        self.plasticmod.setSizePolicy(sizePolicy2)
        self.plasticmod.setMinimumSize(QSize(0, 28))
        self.plasticmod.setMaximumSize(QSize(16777215, 28))
        self.plasticmod.setFont(font)
        self.plasticmod.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.plasticmod.setDecimals(10)
        self.plasticmod.setMaximum(1000000000000.000000000000000)

        self.verticalLayout_12.addWidget(self.plasticmod)

        self.shapefactor = QDoubleSpinBox(self.layoutWidget_8)
        self.shapefactor.setObjectName(u"shapefactor")
        sizePolicy2.setHeightForWidth(self.shapefactor.sizePolicy().hasHeightForWidth())
        self.shapefactor.setSizePolicy(sizePolicy2)
        self.shapefactor.setMinimumSize(QSize(0, 28))
        self.shapefactor.setMaximumSize(QSize(16777215, 28))
        self.shapefactor.setFont(font)
        self.shapefactor.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.shapefactor.setDecimals(10)
        self.shapefactor.setMaximum(1000000000000.000000000000000)

        self.verticalLayout_12.addWidget(self.shapefactor)

        self.bottomtoplastic = QDoubleSpinBox(self.layoutWidget_8)
        self.bottomtoplastic.setObjectName(u"bottomtoplastic")
        sizePolicy2.setHeightForWidth(self.bottomtoplastic.sizePolicy().hasHeightForWidth())
        self.bottomtoplastic.setSizePolicy(sizePolicy2)
        self.bottomtoplastic.setMinimumSize(QSize(0, 28))
        self.bottomtoplastic.setMaximumSize(QSize(16777215, 28))
        self.bottomtoplastic.setFont(font)
        self.bottomtoplastic.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.bottomtoplastic.setDecimals(10)
        self.bottomtoplastic.setMaximum(1000000000000.000000000000000)

        self.verticalLayout_12.addWidget(self.bottomtoplastic)

        self.plastictotop = QDoubleSpinBox(self.layoutWidget_8)
        self.plastictotop.setObjectName(u"plastictotop")
        sizePolicy2.setHeightForWidth(self.plastictotop.sizePolicy().hasHeightForWidth())
        self.plastictotop.setSizePolicy(sizePolicy2)
        self.plastictotop.setMinimumSize(QSize(0, 28))
        self.plastictotop.setMaximumSize(QSize(16777215, 28))
        self.plastictotop.setFont(font)
        self.plastictotop.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.plastictotop.setDecimals(10)
        self.plastictotop.setMaximum(1000000000000.000000000000000)

        self.verticalLayout_12.addWidget(self.plastictotop)

        self.layoutWidget_9 = QWidget(self.groupBox_5)
        self.layoutWidget_9.setObjectName(u"layoutWidget_9")
        self.layoutWidget_9.setGeometry(QRect(240, 550, 131, 171))
        self.verticalLayout_13 = QVBoxLayout(self.layoutWidget_9)
        self.verticalLayout_13.setObjectName(u"verticalLayout_13")
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.polarMOI = QDoubleSpinBox(self.layoutWidget_9)
        self.polarMOI.setObjectName(u"polarMOI")
        sizePolicy3 = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Preferred)
        sizePolicy3.setHorizontalStretch(250)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.polarMOI.sizePolicy().hasHeightForWidth())
        self.polarMOI.setSizePolicy(sizePolicy3)
        self.polarMOI.setMinimumSize(QSize(0, 28))
        self.polarMOI.setMaximumSize(QSize(16777215, 28))
        self.polarMOI.setFont(font)
        self.polarMOI.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.polarMOI.setDecimals(10)
        self.polarMOI.setMaximum(1000000000000.000000000000000)

        self.verticalLayout_13.addWidget(self.polarMOI)

        self.productofinertia = QDoubleSpinBox(self.layoutWidget_9)
        self.productofinertia.setObjectName(u"productofinertia")
        sizePolicy3.setHeightForWidth(self.productofinertia.sizePolicy().hasHeightForWidth())
        self.productofinertia.setSizePolicy(sizePolicy3)
        self.productofinertia.setMinimumSize(QSize(0, 28))
        self.productofinertia.setMaximumSize(QSize(16777215, 28))
        self.productofinertia.setFont(font)
        self.productofinertia.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.productofinertia.setDecimals(10)
        self.productofinertia.setMaximum(1000000000000.000000000000000)

        self.verticalLayout_13.addWidget(self.productofinertia)

        self.maxMOI = QDoubleSpinBox(self.layoutWidget_9)
        self.maxMOI.setObjectName(u"maxMOI")
        sizePolicy3.setHeightForWidth(self.maxMOI.sizePolicy().hasHeightForWidth())
        self.maxMOI.setSizePolicy(sizePolicy3)
        self.maxMOI.setMinimumSize(QSize(0, 28))
        self.maxMOI.setMaximumSize(QSize(16777215, 28))
        self.maxMOI.setFont(font)
        self.maxMOI.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.maxMOI.setDecimals(10)
        self.maxMOI.setMaximum(1000000000000.000000000000000)

        self.verticalLayout_13.addWidget(self.maxMOI)

        self.minMOI = QDoubleSpinBox(self.layoutWidget_9)
        self.minMOI.setObjectName(u"minMOI")
        sizePolicy3.setHeightForWidth(self.minMOI.sizePolicy().hasHeightForWidth())
        self.minMOI.setSizePolicy(sizePolicy3)
        self.minMOI.setMinimumSize(QSize(0, 28))
        self.minMOI.setMaximumSize(QSize(16777215, 28))
        self.minMOI.setFont(font)
        self.minMOI.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.minMOI.setDecimals(10)
        self.minMOI.setMaximum(1000000000000.000000000000000)

        self.verticalLayout_13.addWidget(self.minMOI)

        self.axisangle = QDoubleSpinBox(self.layoutWidget_9)
        self.axisangle.setObjectName(u"axisangle")
        sizePolicy3.setHeightForWidth(self.axisangle.sizePolicy().hasHeightForWidth())
        self.axisangle.setSizePolicy(sizePolicy3)
        self.axisangle.setMinimumSize(QSize(0, 28))
        self.axisangle.setMaximumSize(QSize(16777215, 28))
        self.axisangle.setFont(font)
        self.axisangle.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.axisangle.setDecimals(10)
        self.axisangle.setMaximum(1000000000000.000000000000000)

        self.verticalLayout_13.addWidget(self.axisangle)

        self.layoutWidget_10 = QWidget(self.groupBox_5)
        self.layoutWidget_10.setObjectName(u"layoutWidget_10")
        self.layoutWidget_10.setGeometry(QRect(360, 50, 71, 132))
        self.verticalLayout_14 = QVBoxLayout(self.layoutWidget_10)
        self.verticalLayout_14.setObjectName(u"verticalLayout_14")
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.elasticmodvar = QLabel(self.layoutWidget_10)
        self.elasticmodvar.setObjectName(u"elasticmodvar")
        self.elasticmodvar.setMinimumSize(QSize(0, 28))
        self.elasticmodvar.setMaximumSize(QSize(16777215, 28))
        self.elasticmodvar.setFont(font1)
        self.elasticmodvar.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)

        self.verticalLayout_14.addWidget(self.elasticmodvar)

        self.bottomtocentroidvar = QLabel(self.layoutWidget_10)
        self.bottomtocentroidvar.setObjectName(u"bottomtocentroidvar")
        self.bottomtocentroidvar.setMinimumSize(QSize(0, 28))
        self.bottomtocentroidvar.setMaximumSize(QSize(16777215, 28))
        self.bottomtocentroidvar.setFont(font1)
        self.bottomtocentroidvar.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)

        self.verticalLayout_14.addWidget(self.bottomtocentroidvar)

        self.toptocentroidvar = QLabel(self.layoutWidget_10)
        self.toptocentroidvar.setObjectName(u"toptocentroidvar")
        self.toptocentroidvar.setMinimumSize(QSize(0, 28))
        self.toptocentroidvar.setMaximumSize(QSize(16777215, 28))
        self.toptocentroidvar.setFont(font1)
        self.toptocentroidvar.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)

        self.verticalLayout_14.addWidget(self.toptocentroidvar)

        self.areavar = QLabel(self.layoutWidget_10)
        self.areavar.setObjectName(u"areavar")
        self.areavar.setMinimumSize(QSize(0, 28))
        self.areavar.setMaximumSize(QSize(16777215, 28))
        self.areavar.setFont(font1)
        self.areavar.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)

        self.verticalLayout_14.addWidget(self.areavar)

        self.layoutWidget_11 = QWidget(self.groupBox_5)
        self.layoutWidget_11.setObjectName(u"layoutWidget_11")
        self.layoutWidget_11.setGeometry(QRect(440, 50, 68, 132))
        self.verticalLayout_15 = QVBoxLayout(self.layoutWidget_11)
        self.verticalLayout_15.setObjectName(u"verticalLayout_15")
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.elasticmodunitsoutput = QLineEdit(self.layoutWidget_11)
        self.elasticmodunitsoutput.setObjectName(u"elasticmodunitsoutput")
        self.elasticmodunitsoutput.setMinimumSize(QSize(0, 28))
        self.elasticmodunitsoutput.setMaximumSize(QSize(16777215, 28))
        self.elasticmodunitsoutput.setReadOnly(True)

        self.verticalLayout_15.addWidget(self.elasticmodunitsoutput)

        self.bottomtocentroidunits = QLineEdit(self.layoutWidget_11)
        self.bottomtocentroidunits.setObjectName(u"bottomtocentroidunits")
        self.bottomtocentroidunits.setMinimumSize(QSize(0, 28))
        self.bottomtocentroidunits.setMaximumSize(QSize(16777215, 28))
        self.bottomtocentroidunits.setReadOnly(True)

        self.verticalLayout_15.addWidget(self.bottomtocentroidunits)

        self.toptocentroidunits = QLineEdit(self.layoutWidget_11)
        self.toptocentroidunits.setObjectName(u"toptocentroidunits")
        self.toptocentroidunits.setMinimumSize(QSize(0, 28))
        self.toptocentroidunits.setMaximumSize(QSize(16777215, 28))
        self.toptocentroidunits.setReadOnly(True)

        self.verticalLayout_15.addWidget(self.toptocentroidunits)

        self.areaunits = QLineEdit(self.layoutWidget_11)
        self.areaunits.setObjectName(u"areaunits")
        self.areaunits.setMinimumSize(QSize(0, 28))
        self.areaunits.setMaximumSize(QSize(16777215, 28))
        self.areaunits.setReadOnly(True)

        self.verticalLayout_15.addWidget(self.areaunits)

        self.layoutWidget_12 = QWidget(self.groupBox_5)
        self.layoutWidget_12.setObjectName(u"layoutWidget_12")
        self.layoutWidget_12.setGeometry(QRect(360, 200, 71, 171))
        self.verticalLayout_18 = QVBoxLayout(self.layoutWidget_12)
        self.verticalLayout_18.setObjectName(u"verticalLayout_18")
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.MOIlabel = QLabel(self.layoutWidget_12)
        self.MOIlabel.setObjectName(u"MOIlabel")
        self.MOIlabel.setMinimumSize(QSize(0, 28))
        self.MOIlabel.setMaximumSize(QSize(16777215, 28))
        self.MOIlabel.setFont(font1)
        self.MOIlabel.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)

        self.verticalLayout_18.addWidget(self.MOIlabel)

        self.sectionmodvar = QLabel(self.layoutWidget_12)
        self.sectionmodvar.setObjectName(u"sectionmodvar")
        self.sectionmodvar.setMinimumSize(QSize(0, 28))
        self.sectionmodvar.setMaximumSize(QSize(16777215, 28))
        self.sectionmodvar.setFont(font1)
        self.sectionmodvar.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)

        self.verticalLayout_18.addWidget(self.sectionmodvar)

        self.sectionmodbottomvar = QLabel(self.layoutWidget_12)
        self.sectionmodbottomvar.setObjectName(u"sectionmodbottomvar")
        self.sectionmodbottomvar.setMinimumSize(QSize(0, 28))
        self.sectionmodbottomvar.setMaximumSize(QSize(16777215, 28))
        self.sectionmodbottomvar.setFont(font1)
        self.sectionmodbottomvar.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)

        self.verticalLayout_18.addWidget(self.sectionmodbottomvar)

        self.sectionmodtopvar = QLabel(self.layoutWidget_12)
        self.sectionmodtopvar.setObjectName(u"sectionmodtopvar")
        self.sectionmodtopvar.setMinimumSize(QSize(0, 28))
        self.sectionmodtopvar.setMaximumSize(QSize(16777215, 28))
        self.sectionmodtopvar.setFont(font1)
        self.sectionmodtopvar.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)

        self.verticalLayout_18.addWidget(self.sectionmodtopvar)

        self.radofgyrationvar = QLabel(self.layoutWidget_12)
        self.radofgyrationvar.setObjectName(u"radofgyrationvar")
        self.radofgyrationvar.setMinimumSize(QSize(0, 28))
        self.radofgyrationvar.setMaximumSize(QSize(16777215, 28))
        self.radofgyrationvar.setFont(font1)
        self.radofgyrationvar.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)

        self.verticalLayout_18.addWidget(self.radofgyrationvar)

        self.layoutWidget_13 = QWidget(self.groupBox_5)
        self.layoutWidget_13.setObjectName(u"layoutWidget_13")
        self.layoutWidget_13.setGeometry(QRect(440, 200, 68, 171))
        self.verticalLayout_19 = QVBoxLayout(self.layoutWidget_13)
        self.verticalLayout_19.setObjectName(u"verticalLayout_19")
        self.verticalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.MOIunits = QLineEdit(self.layoutWidget_13)
        self.MOIunits.setObjectName(u"MOIunits")
        self.MOIunits.setMinimumSize(QSize(0, 28))
        self.MOIunits.setMaximumSize(QSize(16777215, 28))
        self.MOIunits.setReadOnly(True)

        self.verticalLayout_19.addWidget(self.MOIunits)

        self.sectionmodunits = QLineEdit(self.layoutWidget_13)
        self.sectionmodunits.setObjectName(u"sectionmodunits")
        self.sectionmodunits.setMinimumSize(QSize(0, 28))
        self.sectionmodunits.setMaximumSize(QSize(16777215, 28))
        self.sectionmodunits.setReadOnly(True)

        self.verticalLayout_19.addWidget(self.sectionmodunits)

        self.sectionmodbottomunits = QLineEdit(self.layoutWidget_13)
        self.sectionmodbottomunits.setObjectName(u"sectionmodbottomunits")
        self.sectionmodbottomunits.setMinimumSize(QSize(0, 28))
        self.sectionmodbottomunits.setMaximumSize(QSize(16777215, 28))
        self.sectionmodbottomunits.setReadOnly(True)

        self.verticalLayout_19.addWidget(self.sectionmodbottomunits)

        self.sectionmodtopunits = QLineEdit(self.layoutWidget_13)
        self.sectionmodtopunits.setObjectName(u"sectionmodtopunits")
        self.sectionmodtopunits.setMinimumSize(QSize(0, 28))
        self.sectionmodtopunits.setMaximumSize(QSize(16777215, 28))
        self.sectionmodtopunits.setReadOnly(True)

        self.verticalLayout_19.addWidget(self.sectionmodtopunits)

        self.radofgyrationunits = QLineEdit(self.layoutWidget_13)
        self.radofgyrationunits.setObjectName(u"radofgyrationunits")
        self.radofgyrationunits.setMinimumSize(QSize(0, 28))
        self.radofgyrationunits.setMaximumSize(QSize(16777215, 28))
        self.radofgyrationunits.setReadOnly(True)

        self.verticalLayout_19.addWidget(self.radofgyrationunits)

        self.layoutWidget_14 = QWidget(self.groupBox_5)
        self.layoutWidget_14.setObjectName(u"layoutWidget_14")
        self.layoutWidget_14.setGeometry(QRect(370, 550, 62, 171))
        self.verticalLayout_16 = QVBoxLayout(self.layoutWidget_14)
        self.verticalLayout_16.setObjectName(u"verticalLayout_16")
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.polarMOIvar = QLabel(self.layoutWidget_14)
        self.polarMOIvar.setObjectName(u"polarMOIvar")
        self.polarMOIvar.setMinimumSize(QSize(0, 28))
        self.polarMOIvar.setMaximumSize(QSize(16777215, 28))
        self.polarMOIvar.setFont(font1)
        self.polarMOIvar.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)

        self.verticalLayout_16.addWidget(self.polarMOIvar)

        self.productofinertiavar = QLabel(self.layoutWidget_14)
        self.productofinertiavar.setObjectName(u"productofinertiavar")
        self.productofinertiavar.setMinimumSize(QSize(0, 28))
        self.productofinertiavar.setMaximumSize(QSize(16777215, 28))
        self.productofinertiavar.setFont(font1)
        self.productofinertiavar.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)

        self.verticalLayout_16.addWidget(self.productofinertiavar)

        self.maxMOIvar = QLabel(self.layoutWidget_14)
        self.maxMOIvar.setObjectName(u"maxMOIvar")
        self.maxMOIvar.setMinimumSize(QSize(0, 28))
        self.maxMOIvar.setMaximumSize(QSize(16777215, 28))
        self.maxMOIvar.setFont(font1)
        self.maxMOIvar.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)

        self.verticalLayout_16.addWidget(self.maxMOIvar)

        self.minMOIvar = QLabel(self.layoutWidget_14)
        self.minMOIvar.setObjectName(u"minMOIvar")
        self.minMOIvar.setMinimumSize(QSize(0, 28))
        self.minMOIvar.setMaximumSize(QSize(16777215, 28))
        self.minMOIvar.setFont(font1)
        self.minMOIvar.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)

        self.verticalLayout_16.addWidget(self.minMOIvar)

        self.axisanglevar = QLabel(self.layoutWidget_14)
        self.axisanglevar.setObjectName(u"axisanglevar")
        self.axisanglevar.setMinimumSize(QSize(0, 28))
        self.axisanglevar.setMaximumSize(QSize(25, 28))
        self.axisanglevar.setFont(font1)
        self.axisanglevar.setAlignment(Qt.AlignCenter)

        self.verticalLayout_16.addWidget(self.axisanglevar)

        self.groupBox_4 = QGroupBox(self.centralwidget)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(10, 590, 581, 261))
        self.groupBox_4.setFont(font)
        self.label_5 = QLabel(self.groupBox_4)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 30, 168, 19))
        self.label_5.setFont(font)
        self.matlelasticmod = QComboBox(self.groupBox_4)
        self.matlelasticmod.setObjectName(u"matlelasticmod")
        self.matlelasticmod.setGeometry(QRect(10, 50, 191, 25))
        self.matlelasticmod.setFont(font)
        self.label_10 = QLabel(self.groupBox_4)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(210, 200, 191, 41))
        self.label_10.setFont(font)
        self.label_9 = QLabel(self.groupBox_4)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(210, 120, 211, 41))
        self.label_9.setFont(font)
        self.compositeXsec = QCheckBox(self.groupBox_4)
        self.compositeXsec.setObjectName(u"compositeXsec")
        self.compositeXsec.setEnabled(True)
        self.compositeXsec.setGeometry(QRect(10, 90, 211, 17))
        self.compositeXsec.setFont(font)
        self.elasticmodunits = QComboBox(self.groupBox_4)
        self.elasticmodunits.setObjectName(u"elasticmodunits")
        self.elasticmodunits.setGeometry(QRect(380, 50, 71, 25))
        self.elasticmodunits.setFont(font)
        self.label_11 = QLabel(self.groupBox_4)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(380, 30, 161, 16))
        self.label_11.setFont(font)
        self.line = QFrame(self.groupBox_4)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(0, 180, 591, 20))
        self.line.setLineWidth(3)
        self.line.setFrameShape(QFrame.Shape.HLine)
        self.line.setFrameShadow(QFrame.Shadow.Sunken)
        self.layoutWidget = QWidget(self.groupBox_4)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(10, 200, 191, 52))
        self.verticalLayout_4 = QVBoxLayout(self.layoutWidget)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.label_8 = QLabel(self.layoutWidget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setFont(font)

        self.verticalLayout_4.addWidget(self.label_8)

        self.matlB = QComboBox(self.layoutWidget)
        self.matlB.setObjectName(u"matlB")
        self.matlB.setFont(font)

        self.verticalLayout_4.addWidget(self.matlB)

        self.layoutWidget_15 = QWidget(self.groupBox_4)
        self.layoutWidget_15.setObjectName(u"layoutWidget_15")
        self.layoutWidget_15.setGeometry(QRect(10, 120, 191, 52))
        self.verticalLayout_5 = QVBoxLayout(self.layoutWidget_15)
        self.verticalLayout_5.setObjectName(u"verticalLayout_5")
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.label_7 = QLabel(self.layoutWidget_15)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setFont(font)

        self.verticalLayout_5.addWidget(self.label_7)

        self.matlA = QComboBox(self.layoutWidget_15)
        self.matlA.setObjectName(u"matlA")
        self.matlA.setFont(font)

        self.verticalLayout_5.addWidget(self.matlA)

        self.elasticmodnum = QDoubleSpinBox(self.groupBox_4)
        self.elasticmodnum.setObjectName(u"elasticmodnum")
        self.elasticmodnum.setGeometry(QRect(220, 50, 141, 25))
        self.elasticmodnum.setReadOnly(True)
        self.elasticmodnum.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.label_6 = QLabel(self.groupBox_4)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(220, 30, 168, 19))
        self.label_6.setFont(font)
        MOIBasiccomp.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MOIBasiccomp)
        self.statusbar.setObjectName(u"statusbar")
        MOIBasiccomp.setStatusBar(self.statusbar)
        self.menubar = QMenuBar(MOIBasiccomp)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1145, 21))
        self.menu_File = QMenu(self.menubar)
        self.menu_File.setObjectName(u"menu_File")
        self.menu_Settings = QMenu(self.menu_File)
        self.menu_Settings.setObjectName(u"menu_Settings")
        self.menu_Utilites = QMenu(self.menubar)
        self.menu_Utilites.setObjectName(u"menu_Utilites")
        self.menuTables = QMenu(self.menu_Utilites)
        self.menuTables.setObjectName(u"menuTables")
        self.menu_Help = QMenu(self.menubar)
        self.menu_Help.setObjectName(u"menu_Help")
        self.menuModules_help = QMenu(self.menu_Help)
        self.menuModules_help.setObjectName(u"menuModules_help")
        self.menuGeneral_Analysis_help = QMenu(self.menuModules_help)
        self.menuGeneral_Analysis_help.setObjectName(u"menuGeneral_Analysis_help")
        self.menuBeams_and_Loads_help = QMenu(self.menuModules_help)
        self.menuBeams_and_Loads_help.setObjectName(u"menuBeams_and_Loads_help")
        self.menuGeneral_Beam_Analysis = QMenu(self.menuBeams_and_Loads_help)
        self.menuGeneral_Beam_Analysis.setObjectName(u"menuGeneral_Beam_Analysis")
        self.menuCombined_Loadings_help = QMenu(self.menuBeams_and_Loads_help)
        self.menuCombined_Loadings_help.setObjectName(u"menuCombined_Loadings_help")
        self.menuEccentric_Loadings_help = QMenu(self.menuCombined_Loadings_help)
        self.menuEccentric_Loadings_help.setObjectName(u"menuEccentric_Loadings_help")
        self.menuShear_Force_and_Bending_Moment_help = QMenu(self.menuCombined_Loadings_help)
        self.menuShear_Force_and_Bending_Moment_help.setObjectName(u"menuShear_Force_and_Bending_Moment_help")
        self.menuAxial_Torsional_and_Bending_Stresses_help = QMenu(self.menuCombined_Loadings_help)
        self.menuAxial_Torsional_and_Bending_Stresses_help.setObjectName(u"menuAxial_Torsional_and_Bending_Stresses_help")
        self.menuKinematics_help = QMenu(self.menuModules_help)
        self.menuKinematics_help.setObjectName(u"menuKinematics_help")
        self.menuEngineering_and_Drafting_help = QMenu(self.menuModules_help)
        self.menuEngineering_and_Drafting_help.setObjectName(u"menuEngineering_and_Drafting_help")
        self.menuAdditional_Calculators_help = QMenu(self.menuModules_help)
        self.menuAdditional_Calculators_help.setObjectName(u"menuAdditional_Calculators_help")
        self.menu_Modules = QMenu(self.menubar)
        self.menu_Modules.setObjectName(u"menu_Modules")
        self.menu_General_Analysis = QMenu(self.menu_Modules)
        self.menu_General_Analysis.setObjectName(u"menu_General_Analysis")
        self.menu_Beams_and_Loads = QMenu(self.menu_Modules)
        self.menu_Beams_and_Loads.setObjectName(u"menu_Beams_and_Loads")
        self.menu_Generic_Beam_Analysis = QMenu(self.menu_Beams_and_Loads)
        self.menu_Generic_Beam_Analysis.setObjectName(u"menu_Generic_Beam_Analysis")
        self.menuCombined_Loadings = QMenu(self.menu_Beams_and_Loads)
        self.menuCombined_Loadings.setObjectName(u"menuCombined_Loadings")
        self.menuEccentric_Loadings = QMenu(self.menuCombined_Loadings)
        self.menuEccentric_Loadings.setObjectName(u"menuEccentric_Loadings")
        self.menuShear_Force_and_Bending_Moment = QMenu(self.menuCombined_Loadings)
        self.menuShear_Force_and_Bending_Moment.setObjectName(u"menuShear_Force_and_Bending_Moment")
        self.menuAxial_Torsional_and_Bending_Stresses = QMenu(self.menuCombined_Loadings)
        self.menuAxial_Torsional_and_Bending_Stresses.setObjectName(u"menuAxial_Torsional_and_Bending_Stresses")
        self.menu_Kinematics = QMenu(self.menu_Modules)
        self.menu_Kinematics.setObjectName(u"menu_Kinematics")
        self.menu_Egineering_and_Drafting = QMenu(self.menu_Modules)
        self.menu_Egineering_and_Drafting.setObjectName(u"menu_Egineering_and_Drafting")
        self.menu_Additional_Calculators = QMenu(self.menu_Modules)
        self.menu_Additional_Calculators.setObjectName(u"menu_Additional_Calculators")
        MOIBasiccomp.setMenuBar(self.menubar)

        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Modules.menuAction())
        self.menubar.addAction(self.menu_Utilites.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())
        self.menu_File.addAction(self.menu_Settings.menuAction())
        self.menu_File.addAction(self.actionQuit)
        self.menu_File.addAction(self.actionQuit_All)
        self.menu_File.addAction(self.actionBack_to_Shape_Selector)
        self.menu_Settings.addAction(self.actionTheme)
        self.menu_Utilites.addAction(self.actionNotepad)
        self.menu_Utilites.addAction(self.actionCalculator)
        self.menu_Utilites.addAction(self.actionScreenshot)
        self.menu_Utilites.addAction(self.menuTables.menuAction())
        self.menuTables.addAction(self.actionMaterials_list)
        self.menuTables.addAction(self.actionCross_Sectional_Beams_and_Shapes_Lists)
        self.menuTables.addAction(self.actionSaftey_Factors)
        self.menuTables.addAction(self.actionFit_Classes)
        self.menu_Help.addAction(self.menuModules_help.menuAction())
        self.menu_Help.addAction(self.actionAbout)
        self.menuModules_help.addAction(self.menuGeneral_Analysis_help.menuAction())
        self.menuModules_help.addAction(self.menuBeams_and_Loads_help.menuAction())
        self.menuModules_help.addAction(self.menuKinematics_help.menuAction())
        self.menuModules_help.addAction(self.menuEngineering_and_Drafting_help.menuAction())
        self.menuModules_help.addAction(self.menuAdditional_Calculators_help.menuAction())
        self.menuGeneral_Analysis_help.addAction(self.actionUnit_Converter_help)
        self.menuGeneral_Analysis_help.addAction(self.actionMoments_of_Inertia_help)
        self.menuGeneral_Analysis_help.addAction(self.actionVectors_help)
        self.menuGeneral_Analysis_help.addAction(self.actionFriction_and_Force_help)
        self.menuGeneral_Analysis_help.addAction(self.actionFasteners_help)
        self.menuGeneral_Analysis_help.addAction(self.actionMaterial_Properties_help)
        self.menuGeneral_Analysis_help.addAction(self.actionCM_and_CG_help)
        self.menuBeams_and_Loads_help.addAction(self.menuGeneral_Beam_Analysis.menuAction())
        self.menuBeams_and_Loads_help.addAction(self.menuCombined_Loadings_help.menuAction())
        self.menuGeneral_Beam_Analysis.addAction(self.actionTrusses_help)
        self.menuGeneral_Beam_Analysis.addAction(self.actionBeamsMoments_of_Inertia_help)
        self.menuGeneral_Beam_Analysis.addAction(self.actionShear_and_Moment_help)
        self.menuGeneral_Beam_Analysis.addAction(self.actionIndeterminate_Axial_Structures_help)
        self.menuGeneral_Beam_Analysis.addAction(self.actionFlexure_help)
        self.menuGeneral_Beam_Analysis.addAction(self.actionBeam_Deformation_help)
        self.menuGeneral_Beam_Analysis.addAction(self.actionAxial_Beam_Deformation_help)
        self.menuGeneral_Beam_Analysis.addAction(self.actionTorsional_Beam_Deformation_help)
        self.menuGeneral_Beam_Analysis.addAction(self.actionSupported_Beams_help)
        self.menuGeneral_Beam_Analysis.addAction(self.actionMohr_s_Circle_help)
        self.menuCombined_Loadings_help.addAction(self.menuEccentric_Loadings_help.menuAction())
        self.menuCombined_Loadings_help.addAction(self.menuShear_Force_and_Bending_Moment_help.menuAction())
        self.menuCombined_Loadings_help.addAction(self.menuAxial_Torsional_and_Bending_Stresses_help.menuAction())
        self.menuEccentric_Loadings_help.addAction(self.actionC_Clamp_help)
        self.menuEccentric_Loadings_help.addAction(self.actionCompression_Link_help)
        self.menuEccentric_Loadings_help.addAction(self.actionTension_Link_help)
        self.menuEccentric_Loadings_help.addAction(self.actionPost_help)
        self.menuShear_Force_and_Bending_Moment_help.addAction(self.actionPost_and_Beam_help)
        self.menuAxial_Torsional_and_Bending_Stresses_help.addAction(self.actionSolid_shaft_and_Pipe_help)
        self.menuKinematics_help.addAction(self.actionKinematic_Diagraming_help)
        self.menuKinematics_help.addAction(self.actionVector_and_Motion_Analysis_help)
        self.menuEngineering_and_Drafting_help.addAction(self.actionGDT_Checker_help)
        self.menuEngineering_and_Drafting_help.addAction(self.actionVirtual_Condition_Calculator_help)
        self.menuEngineering_and_Drafting_help.addAction(self.actionLimits_and_Fits_help)
        self.menuEngineering_and_Drafting_help.addAction(self.actionGDTFasteners_help)
        self.menuEngineering_and_Drafting_help.addAction(self.actionPaper_Gauging_help)
        self.menuEngineering_and_Drafting_help.addAction(self.actionTolerance_Finder_help)
        self.menuEngineering_and_Drafting_help.addAction(self.actionDiameter_Deviation_help)
        self.menuAdditional_Calculators_help.addAction(self.actionTorsion_help)
        self.menuAdditional_Calculators_help.addAction(self.actionPressure_help)
        self.menuAdditional_Calculators_help.addAction(self.actionMohr_s_Circle_2)
        self.menu_Modules.addAction(self.menu_General_Analysis.menuAction())
        self.menu_Modules.addAction(self.menu_Beams_and_Loads.menuAction())
        self.menu_Modules.addAction(self.menu_Kinematics.menuAction())
        self.menu_Modules.addAction(self.menu_Egineering_and_Drafting.menuAction())
        self.menu_Modules.addAction(self.menu_Additional_Calculators.menuAction())
        self.menu_General_Analysis.addAction(self.actionUnit_Converter)
        self.menu_General_Analysis.addAction(self.actionMoments_of_Inertia)
        self.menu_General_Analysis.addAction(self.actionVectors)
        self.menu_General_Analysis.addAction(self.actionFriction_and_Force)
        self.menu_General_Analysis.addAction(self.actionFasteners)
        self.menu_General_Analysis.addAction(self.actionMaterial_Properties)
        self.menu_General_Analysis.addAction(self.actionCM_and_CG)
        self.menu_Beams_and_Loads.addAction(self.menu_Generic_Beam_Analysis.menuAction())
        self.menu_Beams_and_Loads.addAction(self.menuCombined_Loadings.menuAction())
        self.menu_Generic_Beam_Analysis.addAction(self.actionTrusses)
        self.menu_Generic_Beam_Analysis.addAction(self.actionBeamsMoments_of_Inertia)
        self.menu_Generic_Beam_Analysis.addAction(self.actionShear_and_Moment)
        self.menu_Generic_Beam_Analysis.addAction(self.actionIndeterminate_Axial_Structures)
        self.menu_Generic_Beam_Analysis.addAction(self.actionFlexure)
        self.menu_Generic_Beam_Analysis.addAction(self.actionBeam_Deformation)
        self.menu_Generic_Beam_Analysis.addAction(self.actionAxial_Beam_Deformation)
        self.menu_Generic_Beam_Analysis.addAction(self.actionTorsional_Beam_Deformation)
        self.menu_Generic_Beam_Analysis.addAction(self.actionSupported_Beams)
        self.menu_Generic_Beam_Analysis.addAction(self.actionMohr_s_Circle)
        self.menuCombined_Loadings.addAction(self.menuEccentric_Loadings.menuAction())
        self.menuCombined_Loadings.addAction(self.menuShear_Force_and_Bending_Moment.menuAction())
        self.menuCombined_Loadings.addAction(self.menuAxial_Torsional_and_Bending_Stresses.menuAction())
        self.menuEccentric_Loadings.addAction(self.actionC_Clamp)
        self.menuEccentric_Loadings.addAction(self.actionCompression_Link)
        self.menuEccentric_Loadings.addAction(self.actionTension_Link)
        self.menuEccentric_Loadings.addAction(self.actionPost)
        self.menuShear_Force_and_Bending_Moment.addAction(self.actionPost_and_Beam)
        self.menuAxial_Torsional_and_Bending_Stresses.addAction(self.actionSolid_Shaft_and_Pipe)
        self.menu_Kinematics.addAction(self.actionKinematic_Diagraming)
        self.menu_Kinematics.addAction(self.actionVector_Analysis)
        self.menu_Egineering_and_Drafting.addAction(self.actionGDT_Checker)
        self.menu_Egineering_and_Drafting.addAction(self.actionVirtual_Condition_Calculator)
        self.menu_Egineering_and_Drafting.addAction(self.actionLimits_and_Fits)
        self.menu_Egineering_and_Drafting.addAction(self.actionGDTFasteners)
        self.menu_Egineering_and_Drafting.addAction(self.actionPaper_Gauging)
        self.menu_Egineering_and_Drafting.addAction(self.actionTolerance_Finder)
        self.menu_Egineering_and_Drafting.addAction(self.actionDiameter_Deviation)
        self.menu_Additional_Calculators.addAction(self.actionTorsion)
        self.menu_Additional_Calculators.addAction(self.actionPressure)
        self.menu_Additional_Calculators.addAction(self.actionAddMohr_s_Circle)

        self.retranslateUi(MOIBasiccomp)

        QMetaObject.connectSlotsByName(MOIBasiccomp)
    # setupUi

    def retranslateUi(self, MOIBasiccomp):
        MOIBasiccomp.setWindowTitle(QCoreApplication.translate("MOIBasiccomp", u"MainWindow", None))
        self.actionUnit_Converter.setText(QCoreApplication.translate("MOIBasiccomp", u"Unit Converter", None))
        self.actionMoments_of_Inertia.setText(QCoreApplication.translate("MOIBasiccomp", u"Moments of Inertia", None))
        self.actionVectors.setText(QCoreApplication.translate("MOIBasiccomp", u"Vectors", None))
        self.actionFriction_and_Force.setText(QCoreApplication.translate("MOIBasiccomp", u"Friction and Force", None))
        self.actionFasteners.setText(QCoreApplication.translate("MOIBasiccomp", u"Fasteners", None))
        self.actionMaterial_Properties.setText(QCoreApplication.translate("MOIBasiccomp", u"Material Properties", None))
        self.actionCM_and_CG.setText(QCoreApplication.translate("MOIBasiccomp", u"CM and CG", None))
        self.actionTrusses.setText(QCoreApplication.translate("MOIBasiccomp", u"Trusses", None))
        self.actionBeamsMoments_of_Inertia.setText(QCoreApplication.translate("MOIBasiccomp", u"Moments of Inertia", None))
        self.actionShear_and_Moment.setText(QCoreApplication.translate("MOIBasiccomp", u"Shear and Moment", None))
        self.actionIndeterminate_Axial_Structures.setText(QCoreApplication.translate("MOIBasiccomp", u"Indeterminate Axial Structures", None))
        self.actionFlexure.setText(QCoreApplication.translate("MOIBasiccomp", u"Flexure", None))
        self.actionBeam_Deformation.setText(QCoreApplication.translate("MOIBasiccomp", u"Beam Deformation", None))
        self.actionAxial_Beam_Deformation.setText(QCoreApplication.translate("MOIBasiccomp", u"Axial Beam Deformation", None))
        self.actionTorsional_Beam_Deformation.setText(QCoreApplication.translate("MOIBasiccomp", u"Torsional Beam Deformation", None))
        self.actionSupported_Beams.setText(QCoreApplication.translate("MOIBasiccomp", u"Supported Beams", None))
        self.actionMohr_s_Circle.setText(QCoreApplication.translate("MOIBasiccomp", u"Mohr's Circle", None))
        self.actionC_Clamp.setText(QCoreApplication.translate("MOIBasiccomp", u"C-Clamp", None))
        self.actionCompression_Link.setText(QCoreApplication.translate("MOIBasiccomp", u"Compression Link", None))
        self.actionTension_Link.setText(QCoreApplication.translate("MOIBasiccomp", u"Tension Link", None))
        self.actionPost.setText(QCoreApplication.translate("MOIBasiccomp", u"Post", None))
        self.actionPost_and_Beam.setText(QCoreApplication.translate("MOIBasiccomp", u"Post and Beam", None))
        self.actionKinematic_Diagraming.setText(QCoreApplication.translate("MOIBasiccomp", u"Kinematic Diagraming", None))
        self.actionVector_Analysis.setText(QCoreApplication.translate("MOIBasiccomp", u"Vector Analysis", None))
        self.actionGDT_Checker.setText(QCoreApplication.translate("MOIBasiccomp", u"GDT Checker", None))
        self.actionVirtual_Condition_Calculator.setText(QCoreApplication.translate("MOIBasiccomp", u"Virtual Condition Calculator", None))
        self.actionLimits_and_Fits.setText(QCoreApplication.translate("MOIBasiccomp", u"Limits and Fits", None))
        self.actionGDTFasteners.setText(QCoreApplication.translate("MOIBasiccomp", u"Fasteners", None))
        self.actionPaper_Gauging.setText(QCoreApplication.translate("MOIBasiccomp", u"Paper Gauging", None))
        self.actionTolerance_Finder.setText(QCoreApplication.translate("MOIBasiccomp", u"Tolerance Finder", None))
        self.actionDiameter_Deviation.setText(QCoreApplication.translate("MOIBasiccomp", u"Diameter Deviation", None))
        self.actionTorsion.setText(QCoreApplication.translate("MOIBasiccomp", u"Torsion", None))
        self.actionPressure.setText(QCoreApplication.translate("MOIBasiccomp", u"Pressure", None))
        self.actionAddMohr_s_Circle.setText(QCoreApplication.translate("MOIBasiccomp", u"Mohr's Circle", None))
        self.actionModule_List.setText(QCoreApplication.translate("MOIBasiccomp", u"Module List", None))
        self.actionQuit.setText(QCoreApplication.translate("MOIBasiccomp", u"Quit", None))
        self.actionNotepad.setText(QCoreApplication.translate("MOIBasiccomp", u"Notepad", None))
        self.actionCalculator.setText(QCoreApplication.translate("MOIBasiccomp", u"Calculator", None))
        self.actionScreenshot.setText(QCoreApplication.translate("MOIBasiccomp", u"Screenshot", None))
        self.actionPerfer_SI_units.setText(QCoreApplication.translate("MOIBasiccomp", u"Edit Saftey Factor", None))
        self.actionPerfer_Metric_Units.setText(QCoreApplication.translate("MOIBasiccomp", u"Theme", None))
        self.actionMaterials_list.setText(QCoreApplication.translate("MOIBasiccomp", u"Materials List", None))
        self.actionCross_Sectional_Beams_and_Shapes_Lists.setText(QCoreApplication.translate("MOIBasiccomp", u"Beams and Shapes Lists", None))
        self.actionAbout.setText(QCoreApplication.translate("MOIBasiccomp", u"About", None))
        self.actionUnit_Converter_help.setText(QCoreApplication.translate("MOIBasiccomp", u"Unit Converter", None))
        self.actionMoments_of_Inertia_help.setText(QCoreApplication.translate("MOIBasiccomp", u"Moments of Inertia", None))
        self.actionVectors_help.setText(QCoreApplication.translate("MOIBasiccomp", u"Vectors", None))
        self.actionFriction_and_Force_help.setText(QCoreApplication.translate("MOIBasiccomp", u"Friction and Force", None))
        self.actionFasteners_help.setText(QCoreApplication.translate("MOIBasiccomp", u"Fasteners", None))
        self.actionMaterial_Properties_help.setText(QCoreApplication.translate("MOIBasiccomp", u"Material Properties", None))
        self.actionCM_and_CG_help.setText(QCoreApplication.translate("MOIBasiccomp", u"CM and CG", None))
        self.actionTrusses_help.setText(QCoreApplication.translate("MOIBasiccomp", u"Trusses", None))
        self.actionBeamsMoments_of_Inertia_help.setText(QCoreApplication.translate("MOIBasiccomp", u"Moments of Inertia", None))
        self.actionShear_and_Moment_help.setText(QCoreApplication.translate("MOIBasiccomp", u"Shear and Moment", None))
        self.actionIndeterminate_Axial_Structures_help.setText(QCoreApplication.translate("MOIBasiccomp", u"Indeterminate Axial Structures", None))
        self.actionFlexure_help.setText(QCoreApplication.translate("MOIBasiccomp", u"Flexure", None))
        self.actionBeam_Deformation_help.setText(QCoreApplication.translate("MOIBasiccomp", u"Beam Deformation", None))
        self.actionAxial_Beam_Deformation_help.setText(QCoreApplication.translate("MOIBasiccomp", u"Axial Beam Deformation", None))
        self.actionTorsional_Beam_Deformation_help.setText(QCoreApplication.translate("MOIBasiccomp", u"Torsional Beam Deformation", None))
        self.actionSupported_Beams_help.setText(QCoreApplication.translate("MOIBasiccomp", u"Supported Beams", None))
        self.actionMohr_s_Circle_help.setText(QCoreApplication.translate("MOIBasiccomp", u"Mohr's Circle", None))
        self.actionC_Clamp_help.setText(QCoreApplication.translate("MOIBasiccomp", u"C-Clamp", None))
        self.actionCompression_Link_help.setText(QCoreApplication.translate("MOIBasiccomp", u"Compression Link", None))
        self.actionTension_Link_help.setText(QCoreApplication.translate("MOIBasiccomp", u"Tension Link", None))
        self.actionPost_help.setText(QCoreApplication.translate("MOIBasiccomp", u"Post", None))
        self.actionPost_and_Beam_help.setText(QCoreApplication.translate("MOIBasiccomp", u"Post and Beam", None))
        self.actionSolid_shaft_and_Pipe_help.setText(QCoreApplication.translate("MOIBasiccomp", u"Solid Shaft and Pipe", None))
        self.actionKinematic_Diagraming_help.setText(QCoreApplication.translate("MOIBasiccomp", u"Kinematic Diagraming", None))
        self.actionVector_and_Motion_Analysis_help.setText(QCoreApplication.translate("MOIBasiccomp", u"Vector and Motion Analysis", None))
        self.actionGDT_Checker_help.setText(QCoreApplication.translate("MOIBasiccomp", u"GDT Checker", None))
        self.actionVirtual_Condition_Calculator_help.setText(QCoreApplication.translate("MOIBasiccomp", u"Virtual Condition Calculator", None))
        self.actionLimits_and_Fits_help.setText(QCoreApplication.translate("MOIBasiccomp", u"Limits and Fits", None))
        self.actionGDTFasteners_help.setText(QCoreApplication.translate("MOIBasiccomp", u"Fasteners", None))
        self.actionPaper_Gauging_help.setText(QCoreApplication.translate("MOIBasiccomp", u"Paper Gauging", None))
        self.actionTolerance_Finder_help.setText(QCoreApplication.translate("MOIBasiccomp", u"Tolerance Finder", None))
        self.actionDiameter_Deviation_help.setText(QCoreApplication.translate("MOIBasiccomp", u"Diameter Deviation", None))
        self.actionTorsion_help.setText(QCoreApplication.translate("MOIBasiccomp", u"Torsion", None))
        self.actionPressure_help.setText(QCoreApplication.translate("MOIBasiccomp", u"Pressure", None))
        self.actionTheme.setText(QCoreApplication.translate("MOIBasiccomp", u"Theme", None))
        self.actionSaftey_Factors.setText(QCoreApplication.translate("MOIBasiccomp", u"Saftey Factors", None))
        self.actionSolid_Shaft_and_Pipe.setText(QCoreApplication.translate("MOIBasiccomp", u"Solid Shaft and Pipe", None))
        self.actionMohr_s_Circle_2.setText(QCoreApplication.translate("MOIBasiccomp", u"Mohr's Circle", None))
        self.actionFit_Classes.setText(QCoreApplication.translate("MOIBasiccomp", u"Fit Classes", None))
        self.actionQuit_All.setText(QCoreApplication.translate("MOIBasiccomp", u"Quit All", None))
        self.actionBack_to_Shape_Selector.setText(QCoreApplication.translate("MOIBasiccomp", u"Back to Shape Selector", None))
        self.pushButton.setText(QCoreApplication.translate("MOIBasiccomp", u"Mohr's Circle", None))
        self.computeMOI.setText(QCoreApplication.translate("MOIBasiccomp", u"Compute", None))
        self.groupBox.setTitle(QCoreApplication.translate("MOIBasiccomp", u"Axis", None))
        self.xyaxis_2.setText(QCoreApplication.translate("MOIBasiccomp", u"X - Y", None))
        self.yzaxis_2.setText(QCoreApplication.translate("MOIBasiccomp", u"Y - Z ", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MOIBasiccomp", u"Units", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("MOIBasiccomp", u"Rotate", None))
        self.rotate0deg.setText(QCoreApplication.translate("MOIBasiccomp", u"0 ", None))
        self.rotate90deg.setText(QCoreApplication.translate("MOIBasiccomp", u"90", None))
        self.rotate180deg.setText(QCoreApplication.translate("MOIBasiccomp", u"180", None))
        self.rotate270deg.setText(QCoreApplication.translate("MOIBasiccomp", u"270", None))
        self.rotate.setText(QCoreApplication.translate("MOIBasiccomp", u"Rotate", None))
        self.groupBox_5.setTitle(QCoreApplication.translate("MOIBasiccomp", u"Output", None))
        self.plasticmodvar.setText(QCoreApplication.translate("MOIBasiccomp", u"Zz", None))
        self.plasticmodunits.setText("")
        self.plastictotopunits.setText("")
        self.plastictotopvar.setText(QCoreApplication.translate("MOIBasiccomp", u"yp (top)", None))
        self.plastictobottomunits.setText("")
        self.plasticbottomvariable.setText(QCoreApplication.translate("MOIBasiccomp", u"yp (bot)", None))
        self.polarMOIunits.setText("")
        self.productofinertiaunits.setText("")
        self.axisprops.setItemText(0, QCoreApplication.translate("MOIBasiccomp", u"Z Axis Properties", None))
        self.axisprops.setItemText(1, QCoreApplication.translate("MOIBasiccomp", u"Y Axis Properties", None))

        self.minMOIunits.setText("")
        self.axisangleunits.setText("")
        self.maxMOIunits.setText("")
        self.axisangledirec.setText(QCoreApplication.translate("MOIBasiccomp", u"Counterclockwise", None))
        self.polarMOIlabel.setText(QCoreApplication.translate("MOIBasiccomp", u"Polar Moment of Inertia", None))
        self.productofinertialabel.setText(QCoreApplication.translate("MOIBasiccomp", u"Product of Inertia", None))
        self.maxMOIlabel.setText(QCoreApplication.translate("MOIBasiccomp", u"Maximum Moment of Inertia", None))
        self.minMOIlabel.setText(QCoreApplication.translate("MOIBasiccomp", u"Minimum Moment of Inertia", None))
        self.axisanglelabel.setText(QCoreApplication.translate("MOIBasiccomp", u"Angle From Z Axis to Imax Axis", None))
        self.plasticmodlabel.setText(QCoreApplication.translate("MOIBasiccomp", u"Plastic Modulus", None))
        self.shapefactorlabel.setText(QCoreApplication.translate("MOIBasiccomp", u"Shape Factor", None))
        self.plasticlabel.setText(QCoreApplication.translate("MOIBasiccomp", u"From Bottom to Plastic n.a", None))
        self.plastictotoplabel.setText(QCoreApplication.translate("MOIBasiccomp", u"From Plastic n.a to Top", None))
        self.MOIlabel_2.setText(QCoreApplication.translate("MOIBasiccomp", u"Moment of Inertia", None))
        self.sectionmodlabel.setText(QCoreApplication.translate("MOIBasiccomp", u"Section Modulus", None))
        self.sectionmodbottomlabel.setText(QCoreApplication.translate("MOIBasiccomp", u"Section Modulus (Bottom)", None))
        self.sectionmodtoplabel.setText(QCoreApplication.translate("MOIBasiccomp", u"Section Modulus (Top)", None))
        self.radofgyrationlabel.setText(QCoreApplication.translate("MOIBasiccomp", u"Radius of Gyration", None))
        self.elasticmoduluslabel.setText(QCoreApplication.translate("MOIBasiccomp", u"Elastic Modulus", None))
        self.bottomtocentroidlabel.setText(QCoreApplication.translate("MOIBasiccomp", u"Distance from Bottom to Centroid ", None))
        self.toptocentroidlabel.setText(QCoreApplication.translate("MOIBasiccomp", u"Distance from Centroid to Top", None))
        self.arealabel.setText(QCoreApplication.translate("MOIBasiccomp", u"Area", None))
        self.elasticmodvar.setText(QCoreApplication.translate("MOIBasiccomp", u"E", None))
        self.bottomtocentroidvar.setText(QCoreApplication.translate("MOIBasiccomp", u"y (bot)", None))
        self.toptocentroidvar.setText(QCoreApplication.translate("MOIBasiccomp", u"y (top)", None))
        self.areavar.setText(QCoreApplication.translate("MOIBasiccomp", u"A", None))
        self.MOIlabel.setText(QCoreApplication.translate("MOIBasiccomp", u"Iz", None))
        self.sectionmodvar.setText(QCoreApplication.translate("MOIBasiccomp", u"Sz", None))
        self.sectionmodbottomvar.setText(QCoreApplication.translate("MOIBasiccomp", u"S (bot)", None))
        self.sectionmodtopvar.setText(QCoreApplication.translate("MOIBasiccomp", u"S (top)", None))
        self.radofgyrationvar.setText(QCoreApplication.translate("MOIBasiccomp", u"rz", None))
        self.sectionmodbottomunits.setText("")
        self.sectionmodtopunits.setText("")
        self.radofgyrationunits.setText("")
        self.polarMOIvar.setText(QCoreApplication.translate("MOIBasiccomp", u"J", None))
        self.productofinertiavar.setText(QCoreApplication.translate("MOIBasiccomp", u"Iyz", None))
        self.maxMOIvar.setText(QCoreApplication.translate("MOIBasiccomp", u"Imax", None))
        self.minMOIvar.setText(QCoreApplication.translate("MOIBasiccomp", u"Imin", None))
        self.axisanglevar.setText(QCoreApplication.translate("MOIBasiccomp", u"	\u03b2", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("MOIBasiccomp", u"Elastic Modulus", None))
        self.label_5.setText(QCoreApplication.translate("MOIBasiccomp", u"Material", None))
        self.label_10.setText(QCoreApplication.translate("MOIBasiccomp", u"Assign area to this material\n"
"by Left clicking on the area", None))
        self.label_9.setText(QCoreApplication.translate("MOIBasiccomp", u"Assign area to this material\n"
"by Right clicking on the area", None))
        self.compositeXsec.setText(QCoreApplication.translate("MOIBasiccomp", u"Composite Cross Section", None))
        self.label_11.setText(QCoreApplication.translate("MOIBasiccomp", u"Elastic Modulus Units", None))
        self.label_8.setText(QCoreApplication.translate("MOIBasiccomp", u"Material B", None))
        self.label_7.setText(QCoreApplication.translate("MOIBasiccomp", u"Material A", None))
        self.label_6.setText(QCoreApplication.translate("MOIBasiccomp", u"Elastic Modulus", None))
        self.menu_File.setTitle(QCoreApplication.translate("MOIBasiccomp", u"&File", None))
        self.menu_Settings.setTitle(QCoreApplication.translate("MOIBasiccomp", u"Settings", None))
        self.menu_Utilites.setTitle(QCoreApplication.translate("MOIBasiccomp", u"&Utilites", None))
        self.menuTables.setTitle(QCoreApplication.translate("MOIBasiccomp", u"Tables", None))
        self.menu_Help.setTitle(QCoreApplication.translate("MOIBasiccomp", u"&Help", None))
        self.menuModules_help.setTitle(QCoreApplication.translate("MOIBasiccomp", u"Modules", None))
        self.menuGeneral_Analysis_help.setTitle(QCoreApplication.translate("MOIBasiccomp", u"General Analysis", None))
        self.menuBeams_and_Loads_help.setTitle(QCoreApplication.translate("MOIBasiccomp", u"Beams and Loads", None))
        self.menuGeneral_Beam_Analysis.setTitle(QCoreApplication.translate("MOIBasiccomp", u"General Beam Analysis", None))
        self.menuCombined_Loadings_help.setTitle(QCoreApplication.translate("MOIBasiccomp", u"Combined Loadings", None))
        self.menuEccentric_Loadings_help.setTitle(QCoreApplication.translate("MOIBasiccomp", u"Eccentric Loadings", None))
        self.menuShear_Force_and_Bending_Moment_help.setTitle(QCoreApplication.translate("MOIBasiccomp", u"Shear Force and Bending Moment", None))
        self.menuAxial_Torsional_and_Bending_Stresses_help.setTitle(QCoreApplication.translate("MOIBasiccomp", u"Axial, Torsional, and Bending Stresses", None))
        self.menuKinematics_help.setTitle(QCoreApplication.translate("MOIBasiccomp", u"Kinematics", None))
        self.menuEngineering_and_Drafting_help.setTitle(QCoreApplication.translate("MOIBasiccomp", u"Engineering and Drafting", None))
        self.menuAdditional_Calculators_help.setTitle(QCoreApplication.translate("MOIBasiccomp", u"Additional Calculators", None))
        self.menu_Modules.setTitle(QCoreApplication.translate("MOIBasiccomp", u"&Modules", None))
        self.menu_General_Analysis.setTitle(QCoreApplication.translate("MOIBasiccomp", u"General Analysis", None))
        self.menu_Beams_and_Loads.setTitle(QCoreApplication.translate("MOIBasiccomp", u"Beams and Loads", None))
        self.menu_Generic_Beam_Analysis.setTitle(QCoreApplication.translate("MOIBasiccomp", u"Generic Beam Analysis", None))
        self.menuCombined_Loadings.setTitle(QCoreApplication.translate("MOIBasiccomp", u"Combined Loadings", None))
        self.menuEccentric_Loadings.setTitle(QCoreApplication.translate("MOIBasiccomp", u"Eccentric Loadings", None))
        self.menuShear_Force_and_Bending_Moment.setTitle(QCoreApplication.translate("MOIBasiccomp", u"Shear Force and Bending Moment", None))
        self.menuAxial_Torsional_and_Bending_Stresses.setTitle(QCoreApplication.translate("MOIBasiccomp", u"Axial, Torsional, and Bending Stresses", None))
        self.menu_Kinematics.setTitle(QCoreApplication.translate("MOIBasiccomp", u"Kinematics", None))
        self.menu_Egineering_and_Drafting.setTitle(QCoreApplication.translate("MOIBasiccomp", u"Egineering and Drafting", None))
        self.menu_Additional_Calculators.setTitle(QCoreApplication.translate("MOIBasiccomp", u"Additional Calculators", None))
    # retranslateUi

